/*----------------------------------------------------------------------------*/
/**
* @file		BMX_Driver.c
* @brief	Bus Matrixモジュールに関するドライバ関数
* @date		24/07/16
* @details	
* @note		
*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*インクルードファイル*/
/*----------------------------------------------------------------------------*/
#include <xc.h>
#include "BoardSupportPackage.h"
#include "init_fix.h"
#include "typedef.h"
#include "bmx_user.h"
/*----------------------------------------------------------------------------*/
/*定数定義*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*変数定義*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*プロトタイプ宣言*/
/*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*/
/*
* @fn			vdg_BMX_Set_Register()
* @brief        クロックの設定をします
* @param
* @return
* @detail
*/
/*----------------------------------------------------------------------------*/
void vdg_BMX_Set_Register(void)
{
	
	/*-----------------------------------------------------------------------*/
	/* BMXINITPRレジスタ */
	/*-----------------------------------------------------------------------*/
		BMXINITPR = 
			( BMX_USER_BMXINITPR_DMAPR << _BMXINITPR_DMAPR_POSITION ) |
			( BMX_USER_BMXINITPR_CRYPTPR << _BMXINITPR_CRYPTPR_POSITION ) |
			( BMX_USER_BMXINITPR_CAN1PR << _BMXINITPR_CAN1PR_POSITION ) |
			( BMX_USER_BMXINITPR_CAN2PR << _BMXINITPR_CAN2PR_POSITION ) |
			( BMX_USER_BMXINITPR_NVMPR << _BMXINITPR_NVMPR_POSITION ) ;
		#ifdef DEF_BITNAME
			BMXINITPRbits.DMAPR = BMX_USER_BMXINITPR_DMAPR;
			BMXINITPRbits.CRYPTPR = BMX_USER_BMXINITPR_CRYPTPR;
			BMXINITPRbits.CAN1PR = BMX_USER_BMXINITPR_CAN1PR;
			BMXINITPRbits.CAN2PR = BMX_USER_BMXINITPR_CAN2PR;
			BMXINITPRbits.NVMPR = BMX_USER_BMXINITPR_NVMPR;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* BMXIRAMLレジスタ */
	/*-----------------------------------------------------------------------*/
		BMXIRAML = BMX_USER_BMXIRAML;
	/*-----------------------------------------------------------------------*/
	/* BMXIRAMHレジスタ */
	/*-----------------------------------------------------------------------*/
		BMXIRAMH = BMX_USER_BMXIRAMH;
	/*-----------------------------------------------------------------------*/
	/* BMXXDATERRレジスタ */
	/*-----------------------------------------------------------------------*/
		BMXXDATERR = 
			( BMX_USER_BMXXDATERR_BADTGTRERR << _BMXXDATERR_BADTGTRERR_POSITION ) |
			( BMX_USER_BMXXDATERR_ADDRERR << _BMXXDATERR_ADDRERR_POSITION ) |
			( BMX_USER_BMXXDATERR_IRAMRDERR << _BMXXDATERR_IRAMRDERR_POSITION ) |
			( BMX_USER_BMXXDATERR_PGSPCRERR << _BMXXDATERR_PGSPCRERR_POSITION ) |
			( BMX_USER_BMXXDATERR_SFRRERR << _BMXXDATERR_SFRRERR_POSITION ) |
			( BMX_USER_BMXXDATERR_XRAMRERR << _BMXXDATERR_XRAMRERR_POSITION ) |
			( BMX_USER_BMXXDATERR_YRAMRERR << _BMXXDATERR_YRAMRERR_POSITION ) |
			( BMX_USER_BMXXDATERR_CRYPTRERR << _BMXXDATERR_CRYPTRERR_POSITION ) |
			( BMX_USER_BMXXDATERR_DBGRERR << _BMXXDATERR_DBGRERR_POSITION ) |
			( BMX_USER_BMXXDATERR_BADTGTWERR << _BMXXDATERR_BADTGTWERR_POSITION ) |
			( BMX_USER_BMXXDATERR_ADDWERR << _BMXXDATERR_ADDWERR_POSITION ) |
			( BMX_USER_BMXXDATERR_IRAMWRERR << _BMXXDATERR_IRAMWRERR_POSITION ) |
			( BMX_USER_BMXXDATERR_PGSPCWERR << _BMXXDATERR_PGSPCWERR_POSITION ) |
			( BMX_USER_BMXXDATERR_SFRWERR << _BMXXDATERR_SFRWERR_POSITION ) |
			( BMX_USER_BMXXDATERR_XRAMWERR << _BMXXDATERR_XRAMWERR_POSITION ) |
			( BMX_USER_BMXXDATERR_YRAMWERR << _BMXXDATERR_YRAMWERR_POSITION ) |
			( BMX_USER_BMXXDATERR_CRYPTWERR << _BMXXDATERR_CRYPTWERR_POSITION ) |
			( BMX_USER_BMXXDATERR_DBGWERR << _BMXXDATERR_DBGWERR_POSITION ) ;
		#ifdef DEF_BITNAME
			BMXXDATERRbits.BADTGTRERR = BMX_USER_BMXXDATERR_BADTGTRERR;
			BMXXDATERRbits.ADDRERR = BMX_USER_BMXXDATERR_ADDRERR;
			BMXXDATERRbits.IRAMRDERR = BMX_USER_BMXXDATERR_IRAMRDERR;
			BMXXDATERRbits.PGSPCRERR = BMX_USER_BMXXDATERR_PGSPCRERR;
			BMXXDATERRbits.SFRRERR = BMX_USER_BMXXDATERR_SFRRERR;
			BMXXDATERRbits.XRAMRERR = BMX_USER_BMXXDATERR_XRAMRERR;
			BMXXDATERRbits.YRAMRERR = BMX_USER_BMXXDATERR_YRAMRERR;
			BMXXDATERRbits.CRYPTRERR = BMX_USER_BMXXDATERR_CRYPTRERR;
			BMXXDATERRbits.DBGRERR = BMX_USER_BMXXDATERR_DBGRERR;
			BMXXDATERRbits.BADTGTWERR = BMX_USER_BMXXDATERR_BADTGTWERR;
			BMXXDATERRbits.ADDWERR = BMX_USER_BMXXDATERR_ADDWERR;
			BMXXDATERRbits.IRAMWRERR = BMX_USER_BMXXDATERR_IRAMWRERR;
			BMXXDATERRbits.PGSPCWERR = BMX_USER_BMXXDATERR_PGSPCWERR;
			BMXXDATERRbits.SFRWERR = BMX_USER_BMXXDATERR_SFRWERR;
			BMXXDATERRbits.XRAMWERR = BMX_USER_BMXXDATERR_XRAMWERR;
			BMXXDATERRbits.YRAMWERR = BMX_USER_BMXXDATERR_YRAMWERR;
			BMXXDATERRbits.CRYPTWERR = BMX_USER_BMXXDATERR_CRYPTWERR;
			BMXXDATERRbits.DBGWERR = BMX_USER_BMXXDATERR_DBGWERR;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* BMXYDATERRレジスタ */
	/*-----------------------------------------------------------------------*/
		BMXYDATERR = 
			( BMX_USER_BMXYDATERR_BADTGTRERR << _BMXYDATERR_BADTGTRERR_POSITION ) |
			( BMX_USER_BMXYDATERR_ADDRERR << _BMXYDATERR_ADDRERR_POSITION ) |
			( BMX_USER_BMXYDATERR_IRAMRDERR << _BMXYDATERR_IRAMRDERR_POSITION ) |
			( BMX_USER_BMXYDATERR_PGSPCRERR << _BMXYDATERR_PGSPCRERR_POSITION ) |
			( BMX_USER_BMXYDATERR_SFRRERR << _BMXYDATERR_SFRRERR_POSITION ) |
			( BMX_USER_BMXYDATERR_XRAMRERR << _BMXYDATERR_XRAMRERR_POSITION ) |
			( BMX_USER_BMXYDATERR_YRAMRERR << _BMXYDATERR_YRAMRERR_POSITION ) |
			( BMX_USER_BMXYDATERR_CRYPTRERR << _BMXYDATERR_CRYPTRERR_POSITION ) |
			( BMX_USER_BMXYDATERR_DBGRERR << _BMXYDATERR_DBGRERR_POSITION ) |
			( BMX_USER_BMXYDATERR_BADTGTWERR << _BMXYDATERR_BADTGTWERR_POSITION ) |
			( BMX_USER_BMXYDATERR_ADDWERR << _BMXYDATERR_ADDWERR_POSITION ) |
			( BMX_USER_BMXYDATERR_IRAMWRERR << _BMXYDATERR_IRAMWRERR_POSITION ) |
			( BMX_USER_BMXYDATERR_PGSPCWERR << _BMXYDATERR_PGSPCWERR_POSITION ) |
			( BMX_USER_BMXYDATERR_SFRWERR << _BMXYDATERR_SFRWERR_POSITION ) |
			( BMX_USER_BMXYDATERR_XRAMWERR << _BMXYDATERR_XRAMWERR_POSITION ) |
			( BMX_USER_BMXYDATERR_YRAMWERR << _BMXYDATERR_YRAMWERR_POSITION ) |
			( BMX_USER_BMXYDATERR_CRYPTWERR << _BMXYDATERR_CRYPTWERR_POSITION ) |
			( BMX_USER_BMXYDATERR_DBGWERR << _BMXYDATERR_DBGWERR_POSITION ) ;
		#ifdef DEF_BITNAME
			BMXYDATERRbits.BADTGTRERR = BMX_USER_BMXYDATERR_BADTGTRERR;
			BMXYDATERRbits.ADDRERR = BMX_USER_BMXYDATERR_ADDRERR;
			BMXYDATERRbits.IRAMRDERR = BMX_USER_BMXYDATERR_IRAMRDERR;
			BMXYDATERRbits.PGSPCRERR = BMX_USER_BMXYDATERR_PGSPCRERR;
			BMXYDATERRbits.SFRRERR = BMX_USER_BMXYDATERR_SFRRERR;
			BMXYDATERRbits.XRAMRERR = BMX_USER_BMXYDATERR_XRAMRERR;
			BMXYDATERRbits.YRAMRERR = BMX_USER_BMXYDATERR_YRAMRERR;
			BMXYDATERRbits.CRYPTRERR = BMX_USER_BMXYDATERR_CRYPTRERR;
			BMXYDATERRbits.DBGRERR = BMX_USER_BMXYDATERR_DBGRERR;
			BMXYDATERRbits.BADTGTWERR = BMX_USER_BMXYDATERR_BADTGTWERR;
			BMXYDATERRbits.ADDWERR = BMX_USER_BMXYDATERR_ADDWERR;
			BMXYDATERRbits.IRAMWRERR = BMX_USER_BMXYDATERR_IRAMWRERR;
			BMXYDATERRbits.PGSPCWERR = BMX_USER_BMXYDATERR_PGSPCWERR;
			BMXYDATERRbits.SFRWERR = BMX_USER_BMXYDATERR_SFRWERR;
			BMXYDATERRbits.XRAMWERR = BMX_USER_BMXYDATERR_XRAMWERR;
			BMXYDATERRbits.YRAMWERR = BMX_USER_BMXYDATERR_YRAMWERR;
			BMXYDATERRbits.CRYPTWERR = BMX_USER_BMXYDATERR_CRYPTWERR;
			BMXYDATERRbits.DBGWERR = BMX_USER_BMXYDATERR_DBGWERR;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* BMXDMAERRレジスタ */
	/*-----------------------------------------------------------------------*/
		BMXDMAERR = 
			( BMX_USER_BMXDMAERR_BADTGTRERR << _BMXDMAERR_BADTGTRERR_POSITION ) |
			( BMX_USER_BMXDMAERR_ADDRERR << _BMXDMAERR_ADDRERR_POSITION ) |
			( BMX_USER_BMXDMAERR_IRAMRDERR << _BMXDMAERR_IRAMRDERR_POSITION ) |
			( BMX_USER_BMXDMAERR_PGSPCRERR << _BMXDMAERR_PGSPCRERR_POSITION ) |
			( BMX_USER_BMXDMAERR_SFRRERR << _BMXDMAERR_SFRRERR_POSITION ) |
			( BMX_USER_BMXDMAERR_XRAMRERR << _BMXDMAERR_XRAMRERR_POSITION ) |
			( BMX_USER_BMXDMAERR_YRAMRERR << _BMXDMAERR_YRAMRERR_POSITION ) |
			( BMX_USER_BMXDMAERR_CRYPTRERR << _BMXDMAERR_CRYPTRERR_POSITION ) |
			( BMX_USER_BMXDMAERR_DBGRERR << _BMXDMAERR_DBGRERR_POSITION ) |
			( BMX_USER_BMXDMAERR_BADTGTWERR << _BMXDMAERR_BADTGTWERR_POSITION ) |
			( BMX_USER_BMXDMAERR_ADDWERR << _BMXDMAERR_ADDWERR_POSITION ) |
			( BMX_USER_BMXDMAERR_IRAMWRERR << _BMXDMAERR_IRAMWRERR_POSITION ) |
			( BMX_USER_BMXDMAERR_PGSPCWERR << _BMXDMAERR_PGSPCWERR_POSITION ) |
			( BMX_USER_BMXDMAERR_SFRWERR << _BMXDMAERR_SFRWERR_POSITION ) |
			( BMX_USER_BMXDMAERR_XRAMWERR << _BMXDMAERR_XRAMWERR_POSITION ) |
			( BMX_USER_BMXDMAERR_YRAMWERR << _BMXDMAERR_YRAMWERR_POSITION ) |
			( BMX_USER_BMXDMAERR_CRYPTWERR << _BMXDMAERR_CRYPTWERR_POSITION ) |
			( BMX_USER_BMXDMAERR_DBGWERR << _BMXDMAERR_DBGWERR_POSITION ) ;
		#ifdef DEF_BITNAME
			BMXDMAERRbits.BADTGTRERR = BMX_USER_BMXDMAERR_BADTGTRERR;
			BMXDMAERRbits.ADDRERR = BMX_USER_BMXDMAERR_ADDRERR;
			BMXDMAERRbits.IRAMRDERR = BMX_USER_BMXDMAERR_IRAMRDERR;
			BMXDMAERRbits.PGSPCRERR = BMX_USER_BMXDMAERR_PGSPCRERR;
			BMXDMAERRbits.SFRRERR = BMX_USER_BMXDMAERR_SFRRERR;
			BMXDMAERRbits.XRAMRERR = BMX_USER_BMXDMAERR_XRAMRERR;
			BMXDMAERRbits.YRAMRERR = BMX_USER_BMXDMAERR_YRAMRERR;
			BMXDMAERRbits.CRYPTRERR = BMX_USER_BMXDMAERR_CRYPTRERR;
			BMXDMAERRbits.DBGRERR = BMX_USER_BMXDMAERR_DBGRERR;
			BMXDMAERRbits.BADTGTWERR = BMX_USER_BMXDMAERR_BADTGTWERR;
			BMXDMAERRbits.ADDWERR = BMX_USER_BMXDMAERR_ADDWERR;
			BMXDMAERRbits.IRAMWRERR = BMX_USER_BMXDMAERR_IRAMWRERR;
			BMXDMAERRbits.PGSPCWERR = BMX_USER_BMXDMAERR_PGSPCWERR;
			BMXDMAERRbits.SFRWERR = BMX_USER_BMXDMAERR_SFRWERR;
			BMXDMAERRbits.XRAMWERR = BMX_USER_BMXDMAERR_XRAMWERR;
			BMXDMAERRbits.YRAMWERR = BMX_USER_BMXDMAERR_YRAMWERR;
			BMXDMAERRbits.CRYPTWERR = BMX_USER_BMXDMAERR_CRYPTWERR;
			BMXDMAERRbits.DBGWERR = BMX_USER_BMXDMAERR_DBGWERR;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* BMXCPUERRレジスタ */
	/*-----------------------------------------------------------------------*/
		BMXCPUERR = 
			( BMX_USER_BMXCPUERR_BADTGTRERR << _BMXCPUERR_BADTGTRERR_POSITION ) |
			( BMX_USER_BMXCPUERR_ADDRERR << _BMXCPUERR_ADDRERR_POSITION ) |
			( BMX_USER_BMXCPUERR_IRAMRDERR << _BMXCPUERR_IRAMRDERR_POSITION ) |
			( BMX_USER_BMXCPUERR_PGSPCRERR << _BMXCPUERR_PGSPCRERR_POSITION ) |
			( BMX_USER_BMXCPUERR_SFRRERR << _BMXCPUERR_SFRRERR_POSITION ) |
			( BMX_USER_BMXCPUERR_XRAMRERR << _BMXCPUERR_XRAMRERR_POSITION ) |
			( BMX_USER_BMXCPUERR_YRAMRERR << _BMXCPUERR_YRAMRERR_POSITION ) |
			( BMX_USER_BMXCPUERR_CRYPTRERR << _BMXCPUERR_CRYPTRERR_POSITION ) |
			( BMX_USER_BMXCPUERR_DBGRERR << _BMXCPUERR_DBGRERR_POSITION ) |
			( BMX_USER_BMXCPUERR_BADTGTWERR << _BMXCPUERR_BADTGTWERR_POSITION ) |
			( BMX_USER_BMXCPUERR_ADDWERR << _BMXCPUERR_ADDWERR_POSITION ) |
			( BMX_USER_BMXCPUERR_IRAMWRERR << _BMXCPUERR_IRAMWRERR_POSITION ) |
			( BMX_USER_BMXCPUERR_PGSPCWERR << _BMXCPUERR_PGSPCWERR_POSITION ) |
			( BMX_USER_BMXCPUERR_SFRWERR << _BMXCPUERR_SFRWERR_POSITION ) |
			( BMX_USER_BMXCPUERR_XRAMWERR << _BMXCPUERR_XRAMWERR_POSITION ) |
			( BMX_USER_BMXCPUERR_YRAMWERR << _BMXCPUERR_YRAMWERR_POSITION ) |
			( BMX_USER_BMXCPUERR_CRYPTWERR << _BMXCPUERR_CRYPTWERR_POSITION ) |
			( BMX_USER_BMXCPUERR_DBGWERR << _BMXCPUERR_DBGWERR_POSITION ) ;
		#ifdef DEF_BITNAME
			BMXCPUERRbits.BADTGTRERR = BMX_USER_BMXCPUERR_BADTGTRERR;
			BMXCPUERRbits.ADDRERR = BMX_USER_BMXCPUERR_ADDRERR;
			BMXCPUERRbits.IRAMRDERR = BMX_USER_BMXCPUERR_IRAMRDERR;
			BMXCPUERRbits.PGSPCRERR = BMX_USER_BMXCPUERR_PGSPCRERR;
			BMXCPUERRbits.SFRRERR = BMX_USER_BMXCPUERR_SFRRERR;
			BMXCPUERRbits.XRAMRERR = BMX_USER_BMXCPUERR_XRAMRERR;
			BMXCPUERRbits.YRAMRERR = BMX_USER_BMXCPUERR_YRAMRERR;
			BMXCPUERRbits.CRYPTRERR = BMX_USER_BMXCPUERR_CRYPTRERR;
			BMXCPUERRbits.DBGRERR = BMX_USER_BMXCPUERR_DBGRERR;
			BMXCPUERRbits.BADTGTWERR = BMX_USER_BMXCPUERR_BADTGTWERR;
			BMXCPUERRbits.ADDWERR = BMX_USER_BMXCPUERR_ADDWERR;
			BMXCPUERRbits.IRAMWRERR = BMX_USER_BMXCPUERR_IRAMWRERR;
			BMXCPUERRbits.PGSPCWERR = BMX_USER_BMXCPUERR_PGSPCWERR;
			BMXCPUERRbits.SFRWERR = BMX_USER_BMXCPUERR_SFRWERR;
			BMXCPUERRbits.XRAMWERR = BMX_USER_BMXCPUERR_XRAMWERR;
			BMXCPUERRbits.YRAMWERR = BMX_USER_BMXCPUERR_YRAMWERR;
			BMXCPUERRbits.CRYPTWERR = BMX_USER_BMXCPUERR_CRYPTWERR;
			BMXCPUERRbits.DBGWERR = BMX_USER_BMXCPUERR_DBGWERR;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* BMXCRYPTERRレジスタ */
	/*-----------------------------------------------------------------------*/
		BMXCRYPTERR = 
			( BMX_USER_BMXCRYPTERR_BADTGTRERR << _BMXCRYPTERR_BADTGTRERR_POSITION ) |
			( BMX_USER_BMXCRYPTERR_ADDRERR << _BMXCRYPTERR_ADDRERR_POSITION ) |
			( BMX_USER_BMXCRYPTERR_IRAMRDERR << _BMXCRYPTERR_IRAMRDERR_POSITION ) |
			( BMX_USER_BMXCRYPTERR_PGSPCRERR << _BMXCRYPTERR_PGSPCRERR_POSITION ) |
			( BMX_USER_BMXCRYPTERR_SFRRERR << _BMXCRYPTERR_SFRRERR_POSITION ) |
			( BMX_USER_BMXCRYPTERR_XRAMRERR << _BMXCRYPTERR_XRAMRERR_POSITION ) |
			( BMX_USER_BMXCRYPTERR_YRAMRERR << _BMXCRYPTERR_YRAMRERR_POSITION ) |
			( BMX_USER_BMXCRYPTERR_CRYPTRERR << _BMXCRYPTERR_CRYPTRERR_POSITION ) |
			( BMX_USER_BMXCRYPTERR_DBGRERR << _BMXCRYPTERR_DBGRERR_POSITION ) |
			( BMX_USER_BMXCRYPTERR_BADTGTWERR << _BMXCRYPTERR_BADTGTWERR_POSITION ) |
			( BMX_USER_BMXCRYPTERR_ADDWERR << _BMXCRYPTERR_ADDWERR_POSITION ) |
			( BMX_USER_BMXCRYPTERR_IRAMWRERR << _BMXCRYPTERR_IRAMWRERR_POSITION ) |
			( BMX_USER_BMXCRYPTERR_PGSPCWERR << _BMXCRYPTERR_PGSPCWERR_POSITION ) |
			( BMX_USER_BMXCRYPTERR_SFRWERR << _BMXCRYPTERR_SFRWERR_POSITION ) |
			( BMX_USER_BMXCRYPTERR_XRAMWERR << _BMXCRYPTERR_XRAMWERR_POSITION ) |
			( BMX_USER_BMXCRYPTERR_YRAMWERR << _BMXCRYPTERR_YRAMWERR_POSITION ) |
			( BMX_USER_BMXCRYPTERR_CRYPTWERR << _BMXCRYPTERR_CRYPTWERR_POSITION ) |
			( BMX_USER_BMXCRYPTERR_DBGWERR << _BMXCRYPTERR_DBGWERR_POSITION ) ;
		#ifdef DEF_BITNAME
			BMXCRYPTERRbits.BADTGTRERR = BMX_USER_BMXCRYPTERR_BADTGTRERR;
			BMXCRYPTERRbits.ADDRERR = BMX_USER_BMXCRYPTERR_ADDRERR;
			BMXCRYPTERRbits.IRAMRDERR = BMX_USER_BMXCRYPTERR_IRAMRDERR;
			BMXCRYPTERRbits.PGSPCRERR = BMX_USER_BMXCRYPTERR_PGSPCRERR;
			BMXCRYPTERRbits.SFRRERR = BMX_USER_BMXCRYPTERR_SFRRERR;
			BMXCRYPTERRbits.XRAMRERR = BMX_USER_BMXCRYPTERR_XRAMRERR;
			BMXCRYPTERRbits.YRAMRERR = BMX_USER_BMXCRYPTERR_YRAMRERR;
			BMXCRYPTERRbits.CRYPTRERR = BMX_USER_BMXCRYPTERR_CRYPTRERR;
			BMXCRYPTERRbits.DBGRERR = BMX_USER_BMXCRYPTERR_DBGRERR;
			BMXCRYPTERRbits.BADTGTWERR = BMX_USER_BMXCRYPTERR_BADTGTWERR;
			BMXCRYPTERRbits.ADDWERR = BMX_USER_BMXCRYPTERR_ADDWERR;
			BMXCRYPTERRbits.IRAMWRERR = BMX_USER_BMXCRYPTERR_IRAMWRERR;
			BMXCRYPTERRbits.PGSPCWERR = BMX_USER_BMXCRYPTERR_PGSPCWERR;
			BMXCRYPTERRbits.SFRWERR = BMX_USER_BMXCRYPTERR_SFRWERR;
			BMXCRYPTERRbits.XRAMWERR = BMX_USER_BMXCRYPTERR_XRAMWERR;
			BMXCRYPTERRbits.YRAMWERR = BMX_USER_BMXCRYPTERR_YRAMWERR;
			BMXCRYPTERRbits.CRYPTWERR = BMX_USER_BMXCRYPTERR_CRYPTWERR;
			BMXCRYPTERRbits.DBGWERR = BMX_USER_BMXCRYPTERR_DBGWERR;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* BMXCAN1ERRレジスタ */
	/*-----------------------------------------------------------------------*/
		BMXCAN1ERR = 
			( BMX_USER_BMXCAN1ERR_BADTGTRERR << _BMXCAN1ERR_BADTGTRERR_POSITION ) |
			( BMX_USER_BMXCAN1ERR_ADDRERR << _BMXCAN1ERR_ADDRERR_POSITION ) |
			( BMX_USER_BMXCAN1ERR_IRAMRDERR << _BMXCAN1ERR_IRAMRDERR_POSITION ) |
			( BMX_USER_BMXCAN1ERR_PGSPCRERR << _BMXCAN1ERR_PGSPCRERR_POSITION ) |
			( BMX_USER_BMXCAN1ERR_SFRRERR << _BMXCAN1ERR_SFRRERR_POSITION ) |
			( BMX_USER_BMXCAN1ERR_XRAMRERR << _BMXCAN1ERR_XRAMRERR_POSITION ) |
			( BMX_USER_BMXCAN1ERR_YRAMRERR << _BMXCAN1ERR_YRAMRERR_POSITION ) |
			( BMX_USER_BMXCAN1ERR_CRYPTRERR << _BMXCAN1ERR_CRYPTRERR_POSITION ) |
			( BMX_USER_BMXCAN1ERR_DBGRERR << _BMXCAN1ERR_DBGRERR_POSITION ) |
			( BMX_USER_BMXCAN1ERR_BADTGTWERR << _BMXCAN1ERR_BADTGTWERR_POSITION ) |
			( BMX_USER_BMXCAN1ERR_ADDWERR << _BMXCAN1ERR_ADDWERR_POSITION ) |
			( BMX_USER_BMXCAN1ERR_IRAMWRERR << _BMXCAN1ERR_IRAMWRERR_POSITION ) |
			( BMX_USER_BMXCAN1ERR_PGSPCWERR << _BMXCAN1ERR_PGSPCWERR_POSITION ) |
			( BMX_USER_BMXCAN1ERR_SFRWERR << _BMXCAN1ERR_SFRWERR_POSITION ) |
			( BMX_USER_BMXCAN1ERR_XRAMWERR << _BMXCAN1ERR_XRAMWERR_POSITION ) |
			( BMX_USER_BMXCAN1ERR_YRAMWERR << _BMXCAN1ERR_YRAMWERR_POSITION ) |
			( BMX_USER_BMXCAN1ERR_CRYPTWERR << _BMXCAN1ERR_CRYPTWERR_POSITION ) |
			( BMX_USER_BMXCAN1ERR_DBGWERR << _BMXCAN1ERR_DBGWERR_POSITION ) ;
		#ifdef DEF_BITNAME
			BMXCAN1ERRbits.BADTGTRERR = BMX_USER_BMXCAN1ERR_BADTGTRERR;
			BMXCAN1ERRbits.ADDRERR = BMX_USER_BMXCAN1ERR_ADDRERR;
			BMXCAN1ERRbits.IRAMRDERR = BMX_USER_BMXCAN1ERR_IRAMRDERR;
			BMXCAN1ERRbits.PGSPCRERR = BMX_USER_BMXCAN1ERR_PGSPCRERR;
			BMXCAN1ERRbits.SFRRERR = BMX_USER_BMXCAN1ERR_SFRRERR;
			BMXCAN1ERRbits.XRAMRERR = BMX_USER_BMXCAN1ERR_XRAMRERR;
			BMXCAN1ERRbits.YRAMRERR = BMX_USER_BMXCAN1ERR_YRAMRERR;
			BMXCAN1ERRbits.CRYPTRERR = BMX_USER_BMXCAN1ERR_CRYPTRERR;
			BMXCAN1ERRbits.DBGRERR = BMX_USER_BMXCAN1ERR_DBGRERR;
			BMXCAN1ERRbits.BADTGTWERR = BMX_USER_BMXCAN1ERR_BADTGTWERR;
			BMXCAN1ERRbits.ADDWERR = BMX_USER_BMXCAN1ERR_ADDWERR;
			BMXCAN1ERRbits.IRAMWRERR = BMX_USER_BMXCAN1ERR_IRAMWRERR;
			BMXCAN1ERRbits.PGSPCWERR = BMX_USER_BMXCAN1ERR_PGSPCWERR;
			BMXCAN1ERRbits.SFRWERR = BMX_USER_BMXCAN1ERR_SFRWERR;
			BMXCAN1ERRbits.XRAMWERR = BMX_USER_BMXCAN1ERR_XRAMWERR;
			BMXCAN1ERRbits.YRAMWERR = BMX_USER_BMXCAN1ERR_YRAMWERR;
			BMXCAN1ERRbits.CRYPTWERR = BMX_USER_BMXCAN1ERR_CRYPTWERR;
			BMXCAN1ERRbits.DBGWERR = BMX_USER_BMXCAN1ERR_DBGWERR;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* BMXCAN2ERRレジスタ */
	/*-----------------------------------------------------------------------*/
		BMXCAN2ERR = 
			( BMX_USER_BMXCAN2ERR_BADTGTRERR << _BMXCAN2ERR_BADTGTRERR_POSITION ) |
			( BMX_USER_BMXCAN2ERR_ADDRERR << _BMXCAN2ERR_ADDRERR_POSITION ) |
			( BMX_USER_BMXCAN2ERR_IRAMRDERR << _BMXCAN2ERR_IRAMRDERR_POSITION ) |
			( BMX_USER_BMXCAN2ERR_PGSPCRERR << _BMXCAN2ERR_PGSPCRERR_POSITION ) |
			( BMX_USER_BMXCAN2ERR_SFRRERR << _BMXCAN2ERR_SFRRERR_POSITION ) |
			( BMX_USER_BMXCAN2ERR_XRAMRERR << _BMXCAN2ERR_XRAMRERR_POSITION ) |
			( BMX_USER_BMXCAN2ERR_YRAMRERR << _BMXCAN2ERR_YRAMRERR_POSITION ) |
			( BMX_USER_BMXCAN2ERR_CRYPTRERR << _BMXCAN2ERR_CRYPTRERR_POSITION ) |
			( BMX_USER_BMXCAN2ERR_DBGRERR << _BMXCAN2ERR_DBGRERR_POSITION ) |
			( BMX_USER_BMXCAN2ERR_BADTGTWERR << _BMXCAN2ERR_BADTGTWERR_POSITION ) |
			( BMX_USER_BMXCAN2ERR_ADDWERR << _BMXCAN2ERR_ADDWERR_POSITION ) |
			( BMX_USER_BMXCAN2ERR_IRAMWRERR << _BMXCAN2ERR_IRAMWRERR_POSITION ) |
			( BMX_USER_BMXCAN2ERR_PGSPCWERR << _BMXCAN2ERR_PGSPCWERR_POSITION ) |
			( BMX_USER_BMXCAN2ERR_SFRWERR << _BMXCAN2ERR_SFRWERR_POSITION ) |
			( BMX_USER_BMXCAN2ERR_XRAMWERR << _BMXCAN2ERR_XRAMWERR_POSITION ) |
			( BMX_USER_BMXCAN2ERR_YRAMWERR << _BMXCAN2ERR_YRAMWERR_POSITION ) |
			( BMX_USER_BMXCAN2ERR_CRYPTWERR << _BMXCAN2ERR_CRYPTWERR_POSITION ) |
			( BMX_USER_BMXCAN2ERR_DBGWERR << _BMXCAN2ERR_DBGWERR_POSITION ) ;
		#ifdef DEF_BITNAME
			BMXCAN2ERRbits.BADTGTRERR = BMX_USER_BMXCAN2ERR_BADTGTRERR;
			BMXCAN2ERRbits.ADDRERR = BMX_USER_BMXCAN2ERR_ADDRERR;
			BMXCAN2ERRbits.IRAMRDERR = BMX_USER_BMXCAN2ERR_IRAMRDERR;
			BMXCAN2ERRbits.PGSPCRERR = BMX_USER_BMXCAN2ERR_PGSPCRERR;
			BMXCAN2ERRbits.SFRRERR = BMX_USER_BMXCAN2ERR_SFRRERR;
			BMXCAN2ERRbits.XRAMRERR = BMX_USER_BMXCAN2ERR_XRAMRERR;
			BMXCAN2ERRbits.YRAMRERR = BMX_USER_BMXCAN2ERR_YRAMRERR;
			BMXCAN2ERRbits.CRYPTRERR = BMX_USER_BMXCAN2ERR_CRYPTRERR;
			BMXCAN2ERRbits.DBGRERR = BMX_USER_BMXCAN2ERR_DBGRERR;
			BMXCAN2ERRbits.BADTGTWERR = BMX_USER_BMXCAN2ERR_BADTGTWERR;
			BMXCAN2ERRbits.ADDWERR = BMX_USER_BMXCAN2ERR_ADDWERR;
			BMXCAN2ERRbits.IRAMWRERR = BMX_USER_BMXCAN2ERR_IRAMWRERR;
			BMXCAN2ERRbits.PGSPCWERR = BMX_USER_BMXCAN2ERR_PGSPCWERR;
			BMXCAN2ERRbits.SFRWERR = BMX_USER_BMXCAN2ERR_SFRWERR;
			BMXCAN2ERRbits.XRAMWERR = BMX_USER_BMXCAN2ERR_XRAMWERR;
			BMXCAN2ERRbits.YRAMWERR = BMX_USER_BMXCAN2ERR_YRAMWERR;
			BMXCAN2ERRbits.CRYPTWERR = BMX_USER_BMXCAN2ERR_CRYPTWERR;
			BMXCAN2ERRbits.DBGWERR = BMX_USER_BMXCAN2ERR_DBGWERR;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* BMXNVMERRレジスタ */
	/*-----------------------------------------------------------------------*/
		BMXNVMERR = 
			( BMX_USER_BMXNVMERR_BADTGTRERR << _BMXNVMERR_BADTGTRERR_POSITION ) |
			( BMX_USER_BMXNVMERR_ADDRERR << _BMXNVMERR_ADDRERR_POSITION ) |
			( BMX_USER_BMXNVMERR_IRAMRDERR << _BMXNVMERR_IRAMRDERR_POSITION ) |
			( BMX_USER_BMXNVMERR_PGSPCRERR << _BMXNVMERR_PGSPCRERR_POSITION ) |
			( BMX_USER_BMXNVMERR_SFRRERR << _BMXNVMERR_SFRRERR_POSITION ) |
			( BMX_USER_BMXNVMERR_XRAMRERR << _BMXNVMERR_XRAMRERR_POSITION ) |
			( BMX_USER_BMXNVMERR_YRAMRERR << _BMXNVMERR_YRAMRERR_POSITION ) |
			( BMX_USER_BMXNVMERR_CRYPTRERR << _BMXNVMERR_CRYPTRERR_POSITION ) |
			( BMX_USER_BMXNVMERR_DBGRERR << _BMXNVMERR_DBGRERR_POSITION ) |
			( BMX_USER_BMXNVMERR_BADTGTWERR << _BMXNVMERR_BADTGTWERR_POSITION ) |
			( BMX_USER_BMXNVMERR_ADDWERR << _BMXNVMERR_ADDWERR_POSITION ) |
			( BMX_USER_BMXNVMERR_IRAMWRERR << _BMXNVMERR_IRAMWRERR_POSITION ) |
			( BMX_USER_BMXNVMERR_PGSPCWERR << _BMXNVMERR_PGSPCWERR_POSITION ) |
			( BMX_USER_BMXNVMERR_SFRWERR << _BMXNVMERR_SFRWERR_POSITION ) |
			( BMX_USER_BMXNVMERR_XRAMWERR << _BMXNVMERR_XRAMWERR_POSITION ) |
			( BMX_USER_BMXNVMERR_YRAMWERR << _BMXNVMERR_YRAMWERR_POSITION ) |
			( BMX_USER_BMXNVMERR_CRYPTWERR << _BMXNVMERR_CRYPTWERR_POSITION ) |
			( BMX_USER_BMXNVMERR_DBGWERR << _BMXNVMERR_DBGWERR_POSITION ) ;
		#ifdef DEF_BITNAME
			BMXNVMERRbits.BADTGTRERR = BMX_USER_BMXNVMERR_BADTGTRERR;
			BMXNVMERRbits.ADDRERR = BMX_USER_BMXNVMERR_ADDRERR;
			BMXNVMERRbits.IRAMRDERR = BMX_USER_BMXNVMERR_IRAMRDERR;
			BMXNVMERRbits.PGSPCRERR = BMX_USER_BMXNVMERR_PGSPCRERR;
			BMXNVMERRbits.SFRRERR = BMX_USER_BMXNVMERR_SFRRERR;
			BMXNVMERRbits.XRAMRERR = BMX_USER_BMXNVMERR_XRAMRERR;
			BMXNVMERRbits.YRAMRERR = BMX_USER_BMXNVMERR_YRAMRERR;
			BMXNVMERRbits.CRYPTRERR = BMX_USER_BMXNVMERR_CRYPTRERR;
			BMXNVMERRbits.DBGRERR = BMX_USER_BMXNVMERR_DBGRERR;
			BMXNVMERRbits.BADTGTWERR = BMX_USER_BMXNVMERR_BADTGTWERR;
			BMXNVMERRbits.ADDWERR = BMX_USER_BMXNVMERR_ADDWERR;
			BMXNVMERRbits.IRAMWRERR = BMX_USER_BMXNVMERR_IRAMWRERR;
			BMXNVMERRbits.PGSPCWERR = BMX_USER_BMXNVMERR_PGSPCWERR;
			BMXNVMERRbits.SFRWERR = BMX_USER_BMXNVMERR_SFRWERR;
			BMXNVMERRbits.XRAMWERR = BMX_USER_BMXNVMERR_XRAMWERR;
			BMXNVMERRbits.YRAMWERR = BMX_USER_BMXNVMERR_YRAMWERR;
			BMXNVMERRbits.CRYPTWERR = BMX_USER_BMXNVMERR_CRYPTWERR;
			BMXNVMERRbits.DBGWERR = BMX_USER_BMXNVMERR_DBGWERR;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* BMXICDERRレジスタ */
	/*-----------------------------------------------------------------------*/
		BMXICDERR = 
			( BMX_USER_BMXICDERR_BADTGTRERR << _BMXICDERR_BADTGTRERR_POSITION ) |
			( BMX_USER_BMXICDERR_ADDRERR << _BMXICDERR_ADDRERR_POSITION ) |
			( BMX_USER_BMXICDERR_IRAMRDERR << _BMXICDERR_IRAMRDERR_POSITION ) |
			( BMX_USER_BMXICDERR_PGSPCRERR << _BMXICDERR_PGSPCRERR_POSITION ) |
			( BMX_USER_BMXICDERR_SFRRERR << _BMXICDERR_SFRRERR_POSITION ) |
			( BMX_USER_BMXICDERR_XRAMRERR << _BMXICDERR_XRAMRERR_POSITION ) |
			( BMX_USER_BMXICDERR_YRAMRERR << _BMXICDERR_YRAMRERR_POSITION ) |
			( BMX_USER_BMXICDERR_CRYPTRERR << _BMXICDERR_CRYPTRERR_POSITION ) |
			( BMX_USER_BMXICDERR_DBGRERR << _BMXICDERR_DBGRERR_POSITION ) |
			( BMX_USER_BMXICDERR_BADTGTWERR << _BMXICDERR_BADTGTWERR_POSITION ) |
			( BMX_USER_BMXICDERR_ADDWERR << _BMXICDERR_ADDWERR_POSITION ) |
			( BMX_USER_BMXICDERR_IRAMWRERR << _BMXICDERR_IRAMWRERR_POSITION ) |
			( BMX_USER_BMXICDERR_PGSPCWERR << _BMXICDERR_PGSPCWERR_POSITION ) |
			( BMX_USER_BMXICDERR_SFRWERR << _BMXICDERR_SFRWERR_POSITION ) |
			( BMX_USER_BMXICDERR_XRAMWERR << _BMXICDERR_XRAMWERR_POSITION ) |
			( BMX_USER_BMXICDERR_YRAMWERR << _BMXICDERR_YRAMWERR_POSITION ) |
			( BMX_USER_BMXICDERR_CRYPTWERR << _BMXICDERR_CRYPTWERR_POSITION ) |
			( BMX_USER_BMXICDERR_DBGWERR << _BMXICDERR_DBGWERR_POSITION ) ;
		#ifdef DEF_BITNAME
			BMXICDERRbits.BADTGTRERR = BMX_USER_BMXICDERR_BADTGTRERR;
			BMXICDERRbits.ADDRERR = BMX_USER_BMXICDERR_ADDRERR;
			BMXICDERRbits.IRAMRDERR = BMX_USER_BMXICDERR_IRAMRDERR;
			BMXICDERRbits.PGSPCRERR = BMX_USER_BMXICDERR_PGSPCRERR;
			BMXICDERRbits.SFRRERR = BMX_USER_BMXICDERR_SFRRERR;
			BMXICDERRbits.XRAMRERR = BMX_USER_BMXICDERR_XRAMRERR;
			BMXICDERRbits.YRAMRERR = BMX_USER_BMXICDERR_YRAMRERR;
			BMXICDERRbits.CRYPTRERR = BMX_USER_BMXICDERR_CRYPTRERR;
			BMXICDERRbits.DBGRERR = BMX_USER_BMXICDERR_DBGRERR;
			BMXICDERRbits.BADTGTWERR = BMX_USER_BMXICDERR_BADTGTWERR;
			BMXICDERRbits.ADDWERR = BMX_USER_BMXICDERR_ADDWERR;
			BMXICDERRbits.IRAMWRERR = BMX_USER_BMXICDERR_IRAMWRERR;
			BMXICDERRbits.PGSPCWERR = BMX_USER_BMXICDERR_PGSPCWERR;
			BMXICDERRbits.SFRWERR = BMX_USER_BMXICDERR_SFRWERR;
			BMXICDERRbits.XRAMWERR = BMX_USER_BMXICDERR_XRAMWERR;
			BMXICDERRbits.YRAMWERR = BMX_USER_BMXICDERR_YRAMWERR;
			BMXICDERRbits.CRYPTWERR = BMX_USER_BMXICDERR_CRYPTWERR;
			BMXICDERRbits.DBGWERR = BMX_USER_BMXICDERR_DBGWERR;
		#endif 
}