/*----------------------------------------------------------------------------*/
/**
* @file		CLC_Driver.c
* @brief	CLCモジュールに関するドライバ関数
* @date		24/07/16
* @details	
* @note		
*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*インクルードファイル*/
/*----------------------------------------------------------------------------*/
#include <xc.h>
#include "BoardSupportPackage.h"
#include "init_fix.h"
#include "typedef.h"
#include "clc_driver.h"
#include "clc_user.h"
/*----------------------------------------------------------------------------*/
/*定数定義*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*変数定義*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*プロトタイプ宣言*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_CLC1_Set_Register(void)
* @brief     CLC1レジスタを初期化します
* @param
* @return
* @detail
*/
/*----------------------------------------------------------------------------*/
void vdg_CLC1_Set_Register(void)
{
#if ( PMD_CLC1MD == PMD_MODULE_ENABLE )
  
/*-----------------------------------------------------------------------*/
	/* CLC1CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC1CON = 
			( CLC_USER_CLC1CON_MODE << _CLC1CON_MODE_POSITION ) |
			( CLC_USER_CLC1CON_LCPOL << _CLC1CON_LCPOL_POSITION ) |
			( CLC_USER_CLC1CON_LCOUT << _CLC1CON_LCOUT_POSITION ) |
			( CLC_USER_CLC1CON_LCOE << _CLC1CON_LCOE_POSITION ) |
			( CLC_USER_CLC1CON_INTN << _CLC1CON_INTN_POSITION ) |
			( CLC_USER_CLC1CON_INTP << _CLC1CON_INTP_POSITION ) |
			( CLC_USER_CLC1CON_ON << _CLC1CON_ON_POSITION ) |
			( CLC_USER_CLC1CON_G1POL << _CLC1CON_G1POL_POSITION ) |
			( CLC_USER_CLC1CON_G2POL << _CLC1CON_G2POL_POSITION ) |
			( CLC_USER_CLC1CON_G3POL << _CLC1CON_G3POL_POSITION ) |
			( CLC_USER_CLC1CON_G4POL << _CLC1CON_G4POL_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC1CONbits.MODE = CLC_USER_CLC1CON_MODE;
			CLC1CONbits.LCPOL = CLC_USER_CLC1CON_LCPOL;
			CLC1CONbits.LCOUT = CLC_USER_CLC1CON_LCOUT;
			CLC1CONbits.LCOE = CLC_USER_CLC1CON_LCOE;
			CLC1CONbits.INTN = CLC_USER_CLC1CON_INTN;
			CLC1CONbits.INTP = CLC_USER_CLC1CON_INTP;
			CLC1CONbits.ON = CLC_USER_CLC1CON_ON;
			CLC1CONbits.G1POL = CLC_USER_CLC1CON_G1POL;
			CLC1CONbits.G2POL = CLC_USER_CLC1CON_G2POL;
			CLC1CONbits.G3POL = CLC_USER_CLC1CON_G3POL;
			CLC1CONbits.G4POL = CLC_USER_CLC1CON_G4POL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC1SELレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC1SEL = 
			( CLC_USER_CLC1SEL_DS1 << _CLC1SEL_DS1_POSITION ) |
			( CLC_USER_CLC1SEL_DS2 << _CLC1SEL_DS2_POSITION ) |
			( CLC_USER_CLC1SEL_DS3 << _CLC1SEL_DS3_POSITION ) |
			( CLC_USER_CLC1SEL_DS4 << _CLC1SEL_DS4_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC1SELbits.DS1 = CLC_USER_CLC1SEL_DS1;
			CLC1SELbits.DS2 = CLC_USER_CLC1SEL_DS2;
			CLC1SELbits.DS3 = CLC_USER_CLC1SEL_DS3;
			CLC1SELbits.DS4 = CLC_USER_CLC1SEL_DS4;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC1GLSレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC1GLS = 
			( CLC_USER_CLC1GLS_G1D1N << _CLC1GLS_G1D1N_POSITION ) |
			( CLC_USER_CLC1GLS_G1D1T << _CLC1GLS_G1D1T_POSITION ) |
			( CLC_USER_CLC1GLS_G1D2N << _CLC1GLS_G1D2N_POSITION ) |
			( CLC_USER_CLC1GLS_G1D2T << _CLC1GLS_G1D2T_POSITION ) |
			( CLC_USER_CLC1GLS_G1D3N << _CLC1GLS_G1D3N_POSITION ) |
			( CLC_USER_CLC1GLS_G1D3T << _CLC1GLS_G1D3T_POSITION ) |
			( CLC_USER_CLC1GLS_G1D4N << _CLC1GLS_G1D4N_POSITION ) |
			( CLC_USER_CLC1GLS_G1D4T << _CLC1GLS_G1D4T_POSITION ) |
			( CLC_USER_CLC1GLS_G2D1N << _CLC1GLS_G2D1N_POSITION ) |
			( CLC_USER_CLC1GLS_G2D1T << _CLC1GLS_G2D1T_POSITION ) |
			( CLC_USER_CLC1GLS_G2D2N << _CLC1GLS_G2D2N_POSITION ) |
			( CLC_USER_CLC1GLS_G2D2T << _CLC1GLS_G2D2T_POSITION ) |
			( CLC_USER_CLC1GLS_G2D3N << _CLC1GLS_G2D3N_POSITION ) |
			( CLC_USER_CLC1GLS_G2D3T << _CLC1GLS_G2D3T_POSITION ) |
			( CLC_USER_CLC1GLS_G2D4N << _CLC1GLS_G2D4N_POSITION ) |
			( CLC_USER_CLC1GLS_G2D4T << _CLC1GLS_G2D4T_POSITION ) |
			( CLC_USER_CLC1GLS_G3D1N << _CLC1GLS_G3D1N_POSITION ) |
			( CLC_USER_CLC1GLS_G3D1T << _CLC1GLS_G3D1T_POSITION ) |
			( CLC_USER_CLC1GLS_G3D2N << _CLC1GLS_G3D2N_POSITION ) |
			( CLC_USER_CLC1GLS_G3D2T << _CLC1GLS_G3D2T_POSITION ) |
			( CLC_USER_CLC1GLS_G3D3N << _CLC1GLS_G3D3N_POSITION ) |
			( CLC_USER_CLC1GLS_G3D3T << _CLC1GLS_G3D3T_POSITION ) |
			( CLC_USER_CLC1GLS_G3D4N << _CLC1GLS_G3D4N_POSITION ) |
			( CLC_USER_CLC1GLS_G3D4T << _CLC1GLS_G3D4T_POSITION ) |
			( CLC_USER_CLC1GLS_G4D1N << _CLC1GLS_G4D1N_POSITION ) |
			( CLC_USER_CLC1GLS_G4D1T << _CLC1GLS_G4D1T_POSITION ) |
			( CLC_USER_CLC1GLS_G4D2N << _CLC1GLS_G4D2N_POSITION ) |
			( CLC_USER_CLC1GLS_G4D2T << _CLC1GLS_G4D2T_POSITION ) |
			( CLC_USER_CLC1GLS_G4D3N << _CLC1GLS_G4D3N_POSITION ) |
			( CLC_USER_CLC1GLS_G4D3T << _CLC1GLS_G4D3T_POSITION ) |
			( CLC_USER_CLC1GLS_G4D4N << _CLC1GLS_G4D4N_POSITION ) |
			( CLC_USER_CLC1GLS_G4D4T << _CLC1GLS_G4D4T_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC1GLSbits.G1D1N = CLC_USER_CLC1GLS_G1D1N;
			CLC1GLSbits.G1D1T = CLC_USER_CLC1GLS_G1D1T;
			CLC1GLSbits.G1D2N = CLC_USER_CLC1GLS_G1D2N;
			CLC1GLSbits.G1D2T = CLC_USER_CLC1GLS_G1D2T;
			CLC1GLSbits.G1D3N = CLC_USER_CLC1GLS_G1D3N;
			CLC1GLSbits.G1D3T = CLC_USER_CLC1GLS_G1D3T;
			CLC1GLSbits.G1D4N = CLC_USER_CLC1GLS_G1D4N;
			CLC1GLSbits.G1D4T = CLC_USER_CLC1GLS_G1D4T;
			CLC1GLSbits.G2D1N = CLC_USER_CLC1GLS_G2D1N;
			CLC1GLSbits.G2D1T = CLC_USER_CLC1GLS_G2D1T;
			CLC1GLSbits.G2D2N = CLC_USER_CLC1GLS_G2D2N;
			CLC1GLSbits.G2D2T = CLC_USER_CLC1GLS_G2D2T;
			CLC1GLSbits.G2D3N = CLC_USER_CLC1GLS_G2D3N;
			CLC1GLSbits.G2D3T = CLC_USER_CLC1GLS_G2D3T;
			CLC1GLSbits.G2D4N = CLC_USER_CLC1GLS_G2D4N;
			CLC1GLSbits.G2D4T = CLC_USER_CLC1GLS_G2D4T;
			CLC1GLSbits.G3D1N = CLC_USER_CLC1GLS_G3D1N;
			CLC1GLSbits.G3D1T = CLC_USER_CLC1GLS_G3D1T;
			CLC1GLSbits.G3D2N = CLC_USER_CLC1GLS_G3D2N;
			CLC1GLSbits.G3D2T = CLC_USER_CLC1GLS_G3D2T;
			CLC1GLSbits.G3D3N = CLC_USER_CLC1GLS_G3D3N;
			CLC1GLSbits.G3D3T = CLC_USER_CLC1GLS_G3D3T;
			CLC1GLSbits.G3D4N = CLC_USER_CLC1GLS_G3D4N;
			CLC1GLSbits.G3D4T = CLC_USER_CLC1GLS_G3D4T;
			CLC1GLSbits.G4D1N = CLC_USER_CLC1GLS_G4D1N;
			CLC1GLSbits.G4D1T = CLC_USER_CLC1GLS_G4D1T;
			CLC1GLSbits.G4D2N = CLC_USER_CLC1GLS_G4D2N;
			CLC1GLSbits.G4D2T = CLC_USER_CLC1GLS_G4D2T;
			CLC1GLSbits.G4D3N = CLC_USER_CLC1GLS_G4D3N;
			CLC1GLSbits.G4D3T = CLC_USER_CLC1GLS_G4D3T;
			CLC1GLSbits.G4D4N = CLC_USER_CLC1GLS_G4D4N;
			CLC1GLSbits.G4D4T = CLC_USER_CLC1GLS_G4D4T;
		#endif 

			
		CLC1CONbits.ON = CLC_USER_CLC1CON_ON;
#endif 
}
/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_CLC2_Set_Register(void)
* @brief     CLC2レジスタを初期化します
* @param
* @return
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_CLC2_Set_Register(void)
{
#if ( PMD_CLC2MD == PMD_MODULE_ENABLE )
	/*-----------------------------------------------------------------------*/
	/* CLC2CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC2CON = 
			( CLC_USER_CLC2CON_MODE << _CLC2CON_MODE_POSITION ) |
			( CLC_USER_CLC2CON_LCPOL << _CLC2CON_LCPOL_POSITION ) |
			( CLC_USER_CLC2CON_LCOUT << _CLC2CON_LCOUT_POSITION ) |
			( CLC_USER_CLC2CON_LCOE << _CLC2CON_LCOE_POSITION ) |
			( CLC_USER_CLC2CON_INTN << _CLC2CON_INTN_POSITION ) |
			( CLC_USER_CLC2CON_INTP << _CLC2CON_INTP_POSITION ) |
			( CLC_USER_CLC2CON_ON << _CLC2CON_ON_POSITION ) |
			( CLC_USER_CLC2CON_G1POL << _CLC2CON_G1POL_POSITION ) |
			( CLC_USER_CLC2CON_G2POL << _CLC2CON_G2POL_POSITION ) |
			( CLC_USER_CLC2CON_G3POL << _CLC2CON_G3POL_POSITION ) |
			( CLC_USER_CLC2CON_G4POL << _CLC2CON_G4POL_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC2CONbits.MODE = CLC_USER_CLC2CON_MODE;
			CLC2CONbits.LCPOL = CLC_USER_CLC2CON_LCPOL;
			CLC2CONbits.LCOUT = CLC_USER_CLC2CON_LCOUT;
			CLC2CONbits.LCOE = CLC_USER_CLC2CON_LCOE;
			CLC2CONbits.INTN = CLC_USER_CLC2CON_INTN;
			CLC2CONbits.INTP = CLC_USER_CLC2CON_INTP;
			CLC2CONbits.ON = CLC_USER_CLC2CON_ON;
			CLC2CONbits.G1POL = CLC_USER_CLC2CON_G1POL;
			CLC2CONbits.G2POL = CLC_USER_CLC2CON_G2POL;
			CLC2CONbits.G3POL = CLC_USER_CLC2CON_G3POL;
			CLC2CONbits.G4POL = CLC_USER_CLC2CON_G4POL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC2SELレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC2SEL = 
			( CLC_USER_CLC2SEL_DS1 << _CLC2SEL_DS1_POSITION ) |
			( CLC_USER_CLC2SEL_DS2 << _CLC2SEL_DS2_POSITION ) |
			( CLC_USER_CLC2SEL_DS3 << _CLC2SEL_DS3_POSITION ) |
			( CLC_USER_CLC2SEL_DS4 << _CLC2SEL_DS4_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC2SELbits.DS1 = CLC_USER_CLC2SEL_DS1;
			CLC2SELbits.DS2 = CLC_USER_CLC2SEL_DS2;
			CLC2SELbits.DS3 = CLC_USER_CLC2SEL_DS3;
			CLC2SELbits.DS4 = CLC_USER_CLC2SEL_DS4;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC2GLSレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC2GLS = 
			( CLC_USER_CLC2GLS_G1D1N << _CLC2GLS_G1D1N_POSITION ) |
			( CLC_USER_CLC2GLS_G1D1T << _CLC2GLS_G1D1T_POSITION ) |
			( CLC_USER_CLC2GLS_G1D2N << _CLC2GLS_G1D2N_POSITION ) |
			( CLC_USER_CLC2GLS_G1D2T << _CLC2GLS_G1D2T_POSITION ) |
			( CLC_USER_CLC2GLS_G1D3N << _CLC2GLS_G1D3N_POSITION ) |
			( CLC_USER_CLC2GLS_G1D3T << _CLC2GLS_G1D3T_POSITION ) |
			( CLC_USER_CLC2GLS_G1D4N << _CLC2GLS_G1D4N_POSITION ) |
			( CLC_USER_CLC2GLS_G1D4T << _CLC2GLS_G1D4T_POSITION ) |
			( CLC_USER_CLC2GLS_G2D1N << _CLC2GLS_G2D1N_POSITION ) |
			( CLC_USER_CLC2GLS_G2D1T << _CLC2GLS_G2D1T_POSITION ) |
			( CLC_USER_CLC2GLS_G2D2N << _CLC2GLS_G2D2N_POSITION ) |
			( CLC_USER_CLC2GLS_G2D2T << _CLC2GLS_G2D2T_POSITION ) |
			( CLC_USER_CLC2GLS_G2D3N << _CLC2GLS_G2D3N_POSITION ) |
			( CLC_USER_CLC2GLS_G2D3T << _CLC2GLS_G2D3T_POSITION ) |
			( CLC_USER_CLC2GLS_G2D4N << _CLC2GLS_G2D4N_POSITION ) |
			( CLC_USER_CLC2GLS_G2D4T << _CLC2GLS_G2D4T_POSITION ) |
			( CLC_USER_CLC2GLS_G3D1N << _CLC2GLS_G3D1N_POSITION ) |
			( CLC_USER_CLC2GLS_G3D1T << _CLC2GLS_G3D1T_POSITION ) |
			( CLC_USER_CLC2GLS_G3D2N << _CLC2GLS_G3D2N_POSITION ) |
			( CLC_USER_CLC2GLS_G3D2T << _CLC2GLS_G3D2T_POSITION ) |
			( CLC_USER_CLC2GLS_G3D3N << _CLC2GLS_G3D3N_POSITION ) |
			( CLC_USER_CLC2GLS_G3D3T << _CLC2GLS_G3D3T_POSITION ) |
			( CLC_USER_CLC2GLS_G3D4N << _CLC2GLS_G3D4N_POSITION ) |
			( CLC_USER_CLC2GLS_G3D4T << _CLC2GLS_G3D4T_POSITION ) |
			( CLC_USER_CLC2GLS_G4D1N << _CLC2GLS_G4D1N_POSITION ) |
			( CLC_USER_CLC2GLS_G4D1T << _CLC2GLS_G4D1T_POSITION ) |
			( CLC_USER_CLC2GLS_G4D2N << _CLC2GLS_G4D2N_POSITION ) |
			( CLC_USER_CLC2GLS_G4D2T << _CLC2GLS_G4D2T_POSITION ) |
			( CLC_USER_CLC2GLS_G4D3N << _CLC2GLS_G4D3N_POSITION ) |
			( CLC_USER_CLC2GLS_G4D3T << _CLC2GLS_G4D3T_POSITION ) |
			( CLC_USER_CLC2GLS_G4D4N << _CLC2GLS_G4D4N_POSITION ) |
			( CLC_USER_CLC2GLS_G4D4T << _CLC2GLS_G4D4T_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC2GLSbits.G1D1N = CLC_USER_CLC2GLS_G1D1N;
			CLC2GLSbits.G1D1T = CLC_USER_CLC2GLS_G1D1T;
			CLC2GLSbits.G1D2N = CLC_USER_CLC2GLS_G1D2N;
			CLC2GLSbits.G1D2T = CLC_USER_CLC2GLS_G1D2T;
			CLC2GLSbits.G1D3N = CLC_USER_CLC2GLS_G1D3N;
			CLC2GLSbits.G1D3T = CLC_USER_CLC2GLS_G1D3T;
			CLC2GLSbits.G1D4N = CLC_USER_CLC2GLS_G1D4N;
			CLC2GLSbits.G1D4T = CLC_USER_CLC2GLS_G1D4T;
			CLC2GLSbits.G2D1N = CLC_USER_CLC2GLS_G2D1N;
			CLC2GLSbits.G2D1T = CLC_USER_CLC2GLS_G2D1T;
			CLC2GLSbits.G2D2N = CLC_USER_CLC2GLS_G2D2N;
			CLC2GLSbits.G2D2T = CLC_USER_CLC2GLS_G2D2T;
			CLC2GLSbits.G2D3N = CLC_USER_CLC2GLS_G2D3N;
			CLC2GLSbits.G2D3T = CLC_USER_CLC2GLS_G2D3T;
			CLC2GLSbits.G2D4N = CLC_USER_CLC2GLS_G2D4N;
			CLC2GLSbits.G2D4T = CLC_USER_CLC2GLS_G2D4T;
			CLC2GLSbits.G3D1N = CLC_USER_CLC2GLS_G3D1N;
			CLC2GLSbits.G3D1T = CLC_USER_CLC2GLS_G3D1T;
			CLC2GLSbits.G3D2N = CLC_USER_CLC2GLS_G3D2N;
			CLC2GLSbits.G3D2T = CLC_USER_CLC2GLS_G3D2T;
			CLC2GLSbits.G3D3N = CLC_USER_CLC2GLS_G3D3N;
			CLC2GLSbits.G3D3T = CLC_USER_CLC2GLS_G3D3T;
			CLC2GLSbits.G3D4N = CLC_USER_CLC2GLS_G3D4N;
			CLC2GLSbits.G3D4T = CLC_USER_CLC2GLS_G3D4T;
			CLC2GLSbits.G4D1N = CLC_USER_CLC2GLS_G4D1N;
			CLC2GLSbits.G4D1T = CLC_USER_CLC2GLS_G4D1T;
			CLC2GLSbits.G4D2N = CLC_USER_CLC2GLS_G4D2N;
			CLC2GLSbits.G4D2T = CLC_USER_CLC2GLS_G4D2T;
			CLC2GLSbits.G4D3N = CLC_USER_CLC2GLS_G4D3N;
			CLC2GLSbits.G4D3T = CLC_USER_CLC2GLS_G4D3T;
			CLC2GLSbits.G4D4N = CLC_USER_CLC2GLS_G4D4N;
			CLC2GLSbits.G4D4T = CLC_USER_CLC2GLS_G4D4T;
		#endif 
			
		CLC2CONbits.ON = CLC_USER_CLC2CON_ON;
#endif
}
/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_CLC3_Set_Register(void)
* @brief        CLC3レジスタを初期化します 
* @param
* @return
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_CLC3_Set_Register(void)
{
#if ( PMD_CLC3MD == PMD_MODULE_ENABLE )
    /*-----------------------------------------------------------------------*/
	/* CLC3CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC3CON = 
			( CLC_USER_CLC3CON_MODE << _CLC3CON_MODE_POSITION ) |
			( CLC_USER_CLC3CON_LCPOL << _CLC3CON_LCPOL_POSITION ) |
			( CLC_USER_CLC3CON_LCOUT << _CLC3CON_LCOUT_POSITION ) |
			( CLC_USER_CLC3CON_LCOE << _CLC3CON_LCOE_POSITION ) |
			( CLC_USER_CLC3CON_INTN << _CLC3CON_INTN_POSITION ) |
			( CLC_USER_CLC3CON_INTP << _CLC3CON_INTP_POSITION ) |
			( CLC_USER_CLC3CON_ON << _CLC3CON_ON_POSITION ) |
			( CLC_USER_CLC3CON_G1POL << _CLC3CON_G1POL_POSITION ) |
			( CLC_USER_CLC3CON_G2POL << _CLC3CON_G2POL_POSITION ) |
			( CLC_USER_CLC3CON_G3POL << _CLC3CON_G3POL_POSITION ) |
			( CLC_USER_CLC3CON_G4POL << _CLC3CON_G4POL_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC3CONbits.MODE = CLC_USER_CLC3CON_MODE;
			CLC3CONbits.LCPOL = CLC_USER_CLC3CON_LCPOL;
			CLC3CONbits.LCOUT = CLC_USER_CLC3CON_LCOUT;
			CLC3CONbits.LCOE = CLC_USER_CLC3CON_LCOE;
			CLC3CONbits.INTN = CLC_USER_CLC3CON_INTN;
			CLC3CONbits.INTP = CLC_USER_CLC3CON_INTP;
			CLC3CONbits.ON = CLC_USER_CLC3CON_ON;
			CLC3CONbits.G1POL = CLC_USER_CLC3CON_G1POL;
			CLC3CONbits.G2POL = CLC_USER_CLC3CON_G2POL;
			CLC3CONbits.G3POL = CLC_USER_CLC3CON_G3POL;
			CLC3CONbits.G4POL = CLC_USER_CLC3CON_G4POL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC3SELレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC3SEL = 
			( CLC_USER_CLC3SEL_DS1 << _CLC3SEL_DS1_POSITION ) |
			( CLC_USER_CLC3SEL_DS2 << _CLC3SEL_DS2_POSITION ) |
			( CLC_USER_CLC3SEL_DS3 << _CLC3SEL_DS3_POSITION ) |
			( CLC_USER_CLC3SEL_DS4 << _CLC3SEL_DS4_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC3SELbits.DS1 = CLC_USER_CLC3SEL_DS1;
			CLC3SELbits.DS2 = CLC_USER_CLC3SEL_DS2;
			CLC3SELbits.DS3 = CLC_USER_CLC3SEL_DS3;
			CLC3SELbits.DS4 = CLC_USER_CLC3SEL_DS4;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC3GLSレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC3GLS = 
			( CLC_USER_CLC3GLS_G1D1N << _CLC3GLS_G1D1N_POSITION ) |
			( CLC_USER_CLC3GLS_G1D1T << _CLC3GLS_G1D1T_POSITION ) |
			( CLC_USER_CLC3GLS_G1D2N << _CLC3GLS_G1D2N_POSITION ) |
			( CLC_USER_CLC3GLS_G1D2T << _CLC3GLS_G1D2T_POSITION ) |
			( CLC_USER_CLC3GLS_G1D3N << _CLC3GLS_G1D3N_POSITION ) |
			( CLC_USER_CLC3GLS_G1D3T << _CLC3GLS_G1D3T_POSITION ) |
			( CLC_USER_CLC3GLS_G1D4N << _CLC3GLS_G1D4N_POSITION ) |
			( CLC_USER_CLC3GLS_G1D4T << _CLC3GLS_G1D4T_POSITION ) |
			( CLC_USER_CLC3GLS_G2D1N << _CLC3GLS_G2D1N_POSITION ) |
			( CLC_USER_CLC3GLS_G2D1T << _CLC3GLS_G2D1T_POSITION ) |
			( CLC_USER_CLC3GLS_G2D2N << _CLC3GLS_G2D2N_POSITION ) |
			( CLC_USER_CLC3GLS_G2D2T << _CLC3GLS_G2D2T_POSITION ) |
			( CLC_USER_CLC3GLS_G2D3N << _CLC3GLS_G2D3N_POSITION ) |
			( CLC_USER_CLC3GLS_G2D3T << _CLC3GLS_G2D3T_POSITION ) |
			( CLC_USER_CLC3GLS_G2D4N << _CLC3GLS_G2D4N_POSITION ) |
			( CLC_USER_CLC3GLS_G2D4T << _CLC3GLS_G2D4T_POSITION ) |
			( CLC_USER_CLC3GLS_G3D1N << _CLC3GLS_G3D1N_POSITION ) |
			( CLC_USER_CLC3GLS_G3D1T << _CLC3GLS_G3D1T_POSITION ) |
			( CLC_USER_CLC3GLS_G3D2N << _CLC3GLS_G3D2N_POSITION ) |
			( CLC_USER_CLC3GLS_G3D2T << _CLC3GLS_G3D2T_POSITION ) |
			( CLC_USER_CLC3GLS_G3D3N << _CLC3GLS_G3D3N_POSITION ) |
			( CLC_USER_CLC3GLS_G3D3T << _CLC3GLS_G3D3T_POSITION ) |
			( CLC_USER_CLC3GLS_G3D4N << _CLC3GLS_G3D4N_POSITION ) |
			( CLC_USER_CLC3GLS_G3D4T << _CLC3GLS_G3D4T_POSITION ) |
			( CLC_USER_CLC3GLS_G4D1N << _CLC3GLS_G4D1N_POSITION ) |
			( CLC_USER_CLC3GLS_G4D1T << _CLC3GLS_G4D1T_POSITION ) |
			( CLC_USER_CLC3GLS_G4D2N << _CLC3GLS_G4D2N_POSITION ) |
			( CLC_USER_CLC3GLS_G4D2T << _CLC3GLS_G4D2T_POSITION ) |
			( CLC_USER_CLC3GLS_G4D3N << _CLC3GLS_G4D3N_POSITION ) |
			( CLC_USER_CLC3GLS_G4D3T << _CLC3GLS_G4D3T_POSITION ) |
			( CLC_USER_CLC3GLS_G4D4N << _CLC3GLS_G4D4N_POSITION ) |
			( CLC_USER_CLC3GLS_G4D4T << _CLC3GLS_G4D4T_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC3GLSbits.G1D1N = CLC_USER_CLC3GLS_G1D1N;
			CLC3GLSbits.G1D1T = CLC_USER_CLC3GLS_G1D1T;
			CLC3GLSbits.G1D2N = CLC_USER_CLC3GLS_G1D2N;
			CLC3GLSbits.G1D2T = CLC_USER_CLC3GLS_G1D2T;
			CLC3GLSbits.G1D3N = CLC_USER_CLC3GLS_G1D3N;
			CLC3GLSbits.G1D3T = CLC_USER_CLC3GLS_G1D3T;
			CLC3GLSbits.G1D4N = CLC_USER_CLC3GLS_G1D4N;
			CLC3GLSbits.G1D4T = CLC_USER_CLC3GLS_G1D4T;
			CLC3GLSbits.G2D1N = CLC_USER_CLC3GLS_G2D1N;
			CLC3GLSbits.G2D1T = CLC_USER_CLC3GLS_G2D1T;
			CLC3GLSbits.G2D2N = CLC_USER_CLC3GLS_G2D2N;
			CLC3GLSbits.G2D2T = CLC_USER_CLC3GLS_G2D2T;
			CLC3GLSbits.G2D3N = CLC_USER_CLC3GLS_G2D3N;
			CLC3GLSbits.G2D3T = CLC_USER_CLC3GLS_G2D3T;
			CLC3GLSbits.G2D4N = CLC_USER_CLC3GLS_G2D4N;
			CLC3GLSbits.G2D4T = CLC_USER_CLC3GLS_G2D4T;
			CLC3GLSbits.G3D1N = CLC_USER_CLC3GLS_G3D1N;
			CLC3GLSbits.G3D1T = CLC_USER_CLC3GLS_G3D1T;
			CLC3GLSbits.G3D2N = CLC_USER_CLC3GLS_G3D2N;
			CLC3GLSbits.G3D2T = CLC_USER_CLC3GLS_G3D2T;
			CLC3GLSbits.G3D3N = CLC_USER_CLC3GLS_G3D3N;
			CLC3GLSbits.G3D3T = CLC_USER_CLC3GLS_G3D3T;
			CLC3GLSbits.G3D4N = CLC_USER_CLC3GLS_G3D4N;
			CLC3GLSbits.G3D4T = CLC_USER_CLC3GLS_G3D4T;
			CLC3GLSbits.G4D1N = CLC_USER_CLC3GLS_G4D1N;
			CLC3GLSbits.G4D1T = CLC_USER_CLC3GLS_G4D1T;
			CLC3GLSbits.G4D2N = CLC_USER_CLC3GLS_G4D2N;
			CLC3GLSbits.G4D2T = CLC_USER_CLC3GLS_G4D2T;
			CLC3GLSbits.G4D3N = CLC_USER_CLC3GLS_G4D3N;
			CLC3GLSbits.G4D3T = CLC_USER_CLC3GLS_G4D3T;
			CLC3GLSbits.G4D4N = CLC_USER_CLC3GLS_G4D4N;
			CLC3GLSbits.G4D4T = CLC_USER_CLC3GLS_G4D4T;
		#endif 
			
		CLC3CONbits.ON = CLC_USER_CLC3CON_ON;
#endif
}
/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_CLC4_Set_Register(void)
* @brief     CLC4レジスタを初期化します
* @param
* @return
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_CLC4_Set_Register(void)
{
#if ( PMD_CLC4MD == PMD_MODULE_ENABLE )
    /*-----------------------------------------------------------------------*/
	/* CLC4CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC4CON = 
			( CLC_USER_CLC4CON_MODE << _CLC4CON_MODE_POSITION ) |
			( CLC_USER_CLC4CON_LCPOL << _CLC4CON_LCPOL_POSITION ) |
			( CLC_USER_CLC4CON_LCOUT << _CLC4CON_LCOUT_POSITION ) |
			( CLC_USER_CLC4CON_LCOE << _CLC4CON_LCOE_POSITION ) |
			( CLC_USER_CLC4CON_INTN << _CLC4CON_INTN_POSITION ) |
			( CLC_USER_CLC4CON_INTP << _CLC4CON_INTP_POSITION ) |
			( CLC_USER_CLC4CON_ON << _CLC4CON_ON_POSITION ) |
			( CLC_USER_CLC4CON_G1POL << _CLC4CON_G1POL_POSITION ) |
			( CLC_USER_CLC4CON_G2POL << _CLC4CON_G2POL_POSITION ) |
			( CLC_USER_CLC4CON_G3POL << _CLC4CON_G3POL_POSITION ) |
			( CLC_USER_CLC4CON_G4POL << _CLC4CON_G4POL_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC4CONbits.MODE = CLC_USER_CLC4CON_MODE;
			CLC4CONbits.LCPOL = CLC_USER_CLC4CON_LCPOL;
			CLC4CONbits.LCOUT = CLC_USER_CLC4CON_LCOUT;
			CLC4CONbits.LCOE = CLC_USER_CLC4CON_LCOE;
			CLC4CONbits.INTN = CLC_USER_CLC4CON_INTN;
			CLC4CONbits.INTP = CLC_USER_CLC4CON_INTP;
			CLC4CONbits.ON = CLC_USER_CLC4CON_ON;
			CLC4CONbits.G1POL = CLC_USER_CLC4CON_G1POL;
			CLC4CONbits.G2POL = CLC_USER_CLC4CON_G2POL;
			CLC4CONbits.G3POL = CLC_USER_CLC4CON_G3POL;
			CLC4CONbits.G4POL = CLC_USER_CLC4CON_G4POL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC4SELレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC4SEL = 
			( CLC_USER_CLC4SEL_DS1 << _CLC4SEL_DS1_POSITION ) |
			( CLC_USER_CLC4SEL_DS2 << _CLC4SEL_DS2_POSITION ) |
			( CLC_USER_CLC4SEL_DS3 << _CLC4SEL_DS3_POSITION ) |
			( CLC_USER_CLC4SEL_DS4 << _CLC4SEL_DS4_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC4SELbits.DS1 = CLC_USER_CLC4SEL_DS1;
			CLC4SELbits.DS2 = CLC_USER_CLC4SEL_DS2;
			CLC4SELbits.DS3 = CLC_USER_CLC4SEL_DS3;
			CLC4SELbits.DS4 = CLC_USER_CLC4SEL_DS4;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC4GLSレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC4GLS = 
			( CLC_USER_CLC4GLS_G1D1N << _CLC4GLS_G1D1N_POSITION ) |
			( CLC_USER_CLC4GLS_G1D1T << _CLC4GLS_G1D1T_POSITION ) |
			( CLC_USER_CLC4GLS_G1D2N << _CLC4GLS_G1D2N_POSITION ) |
			( CLC_USER_CLC4GLS_G1D2T << _CLC4GLS_G1D2T_POSITION ) |
			( CLC_USER_CLC4GLS_G1D3N << _CLC4GLS_G1D3N_POSITION ) |
			( CLC_USER_CLC4GLS_G1D3T << _CLC4GLS_G1D3T_POSITION ) |
			( CLC_USER_CLC4GLS_G1D4N << _CLC4GLS_G1D4N_POSITION ) |
			( CLC_USER_CLC4GLS_G1D4T << _CLC4GLS_G1D4T_POSITION ) |
			( CLC_USER_CLC4GLS_G2D1N << _CLC4GLS_G2D1N_POSITION ) |
			( CLC_USER_CLC4GLS_G2D1T << _CLC4GLS_G2D1T_POSITION ) |
			( CLC_USER_CLC4GLS_G2D2N << _CLC4GLS_G2D2N_POSITION ) |
			( CLC_USER_CLC4GLS_G2D2T << _CLC4GLS_G2D2T_POSITION ) |
			( CLC_USER_CLC4GLS_G2D3N << _CLC4GLS_G2D3N_POSITION ) |
			( CLC_USER_CLC4GLS_G2D3T << _CLC4GLS_G2D3T_POSITION ) |
			( CLC_USER_CLC4GLS_G2D4N << _CLC4GLS_G2D4N_POSITION ) |
			( CLC_USER_CLC4GLS_G2D4T << _CLC4GLS_G2D4T_POSITION ) |
			( CLC_USER_CLC4GLS_G3D1N << _CLC4GLS_G3D1N_POSITION ) |
			( CLC_USER_CLC4GLS_G3D1T << _CLC4GLS_G3D1T_POSITION ) |
			( CLC_USER_CLC4GLS_G3D2N << _CLC4GLS_G3D2N_POSITION ) |
			( CLC_USER_CLC4GLS_G3D2T << _CLC4GLS_G3D2T_POSITION ) |
			( CLC_USER_CLC4GLS_G3D3N << _CLC4GLS_G3D3N_POSITION ) |
			( CLC_USER_CLC4GLS_G3D3T << _CLC4GLS_G3D3T_POSITION ) |
			( CLC_USER_CLC4GLS_G3D4N << _CLC4GLS_G3D4N_POSITION ) |
			( CLC_USER_CLC4GLS_G3D4T << _CLC4GLS_G3D4T_POSITION ) |
			( CLC_USER_CLC4GLS_G4D1N << _CLC4GLS_G4D1N_POSITION ) |
			( CLC_USER_CLC4GLS_G4D1T << _CLC4GLS_G4D1T_POSITION ) |
			( CLC_USER_CLC4GLS_G4D2N << _CLC4GLS_G4D2N_POSITION ) |
			( CLC_USER_CLC4GLS_G4D2T << _CLC4GLS_G4D2T_POSITION ) |
			( CLC_USER_CLC4GLS_G4D3N << _CLC4GLS_G4D3N_POSITION ) |
			( CLC_USER_CLC4GLS_G4D3T << _CLC4GLS_G4D3T_POSITION ) |
			( CLC_USER_CLC4GLS_G4D4N << _CLC4GLS_G4D4N_POSITION ) |
			( CLC_USER_CLC4GLS_G4D4T << _CLC4GLS_G4D4T_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC4GLSbits.G1D1N = CLC_USER_CLC4GLS_G1D1N;
			CLC4GLSbits.G1D1T = CLC_USER_CLC4GLS_G1D1T;
			CLC4GLSbits.G1D2N = CLC_USER_CLC4GLS_G1D2N;
			CLC4GLSbits.G1D2T = CLC_USER_CLC4GLS_G1D2T;
			CLC4GLSbits.G1D3N = CLC_USER_CLC4GLS_G1D3N;
			CLC4GLSbits.G1D3T = CLC_USER_CLC4GLS_G1D3T;
			CLC4GLSbits.G1D4N = CLC_USER_CLC4GLS_G1D4N;
			CLC4GLSbits.G1D4T = CLC_USER_CLC4GLS_G1D4T;
			CLC4GLSbits.G2D1N = CLC_USER_CLC4GLS_G2D1N;
			CLC4GLSbits.G2D1T = CLC_USER_CLC4GLS_G2D1T;
			CLC4GLSbits.G2D2N = CLC_USER_CLC4GLS_G2D2N;
			CLC4GLSbits.G2D2T = CLC_USER_CLC4GLS_G2D2T;
			CLC4GLSbits.G2D3N = CLC_USER_CLC4GLS_G2D3N;
			CLC4GLSbits.G2D3T = CLC_USER_CLC4GLS_G2D3T;
			CLC4GLSbits.G2D4N = CLC_USER_CLC4GLS_G2D4N;
			CLC4GLSbits.G2D4T = CLC_USER_CLC4GLS_G2D4T;
			CLC4GLSbits.G3D1N = CLC_USER_CLC4GLS_G3D1N;
			CLC4GLSbits.G3D1T = CLC_USER_CLC4GLS_G3D1T;
			CLC4GLSbits.G3D2N = CLC_USER_CLC4GLS_G3D2N;
			CLC4GLSbits.G3D2T = CLC_USER_CLC4GLS_G3D2T;
			CLC4GLSbits.G3D3N = CLC_USER_CLC4GLS_G3D3N;
			CLC4GLSbits.G3D3T = CLC_USER_CLC4GLS_G3D3T;
			CLC4GLSbits.G3D4N = CLC_USER_CLC4GLS_G3D4N;
			CLC4GLSbits.G3D4T = CLC_USER_CLC4GLS_G3D4T;
			CLC4GLSbits.G4D1N = CLC_USER_CLC4GLS_G4D1N;
			CLC4GLSbits.G4D1T = CLC_USER_CLC4GLS_G4D1T;
			CLC4GLSbits.G4D2N = CLC_USER_CLC4GLS_G4D2N;
			CLC4GLSbits.G4D2T = CLC_USER_CLC4GLS_G4D2T;
			CLC4GLSbits.G4D3N = CLC_USER_CLC4GLS_G4D3N;
			CLC4GLSbits.G4D3T = CLC_USER_CLC4GLS_G4D3T;
			CLC4GLSbits.G4D4N = CLC_USER_CLC4GLS_G4D4N;
			CLC4GLSbits.G4D4T = CLC_USER_CLC4GLS_G4D4T;
		#endif 
			
		CLC4CONbits.ON = CLC_USER_CLC4CON_ON;
#endif
}

/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_CLC5_Set_Register(void)
* @brief     CLC5レジスタを初期化します
* @param
* @return
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_CLC5_Set_Register(void)
{
#if ( PMD_CLC5MD == PMD_MODULE_ENABLE )
    
	/*-----------------------------------------------------------------------*/
	/* CLC5CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC5CON = 
			( CLC_USER_CLC5CON_MODE << _CLC5CON_MODE_POSITION ) |
			( CLC_USER_CLC5CON_LCPOL << _CLC5CON_LCPOL_POSITION ) |
			( CLC_USER_CLC5CON_LCOUT << _CLC5CON_LCOUT_POSITION ) |
			( CLC_USER_CLC5CON_LCOE << _CLC5CON_LCOE_POSITION ) |
			( CLC_USER_CLC5CON_INTN << _CLC5CON_INTN_POSITION ) |
			( CLC_USER_CLC5CON_INTP << _CLC5CON_INTP_POSITION ) |
			( CLC_USER_CLC5CON_ON << _CLC5CON_ON_POSITION ) |
			( CLC_USER_CLC5CON_G1POL << _CLC5CON_G1POL_POSITION ) |
			( CLC_USER_CLC5CON_G2POL << _CLC5CON_G2POL_POSITION ) |
			( CLC_USER_CLC5CON_G3POL << _CLC5CON_G3POL_POSITION ) |
			( CLC_USER_CLC5CON_G4POL << _CLC5CON_G4POL_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC5CONbits.MODE = CLC_USER_CLC5CON_MODE;
			CLC5CONbits.LCPOL = CLC_USER_CLC5CON_LCPOL;
			CLC5CONbits.LCOUT = CLC_USER_CLC5CON_LCOUT;
			CLC5CONbits.LCOE = CLC_USER_CLC5CON_LCOE;
			CLC5CONbits.INTN = CLC_USER_CLC5CON_INTN;
			CLC5CONbits.INTP = CLC_USER_CLC5CON_INTP;
			CLC5CONbits.ON = CLC_USER_CLC5CON_ON;
			CLC5CONbits.G1POL = CLC_USER_CLC5CON_G1POL;
			CLC5CONbits.G2POL = CLC_USER_CLC5CON_G2POL;
			CLC5CONbits.G3POL = CLC_USER_CLC5CON_G3POL;
			CLC5CONbits.G4POL = CLC_USER_CLC5CON_G4POL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC5SELレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC5SEL = 
			( CLC_USER_CLC5SEL_DS1 << _CLC5SEL_DS1_POSITION ) |
			( CLC_USER_CLC5SEL_DS2 << _CLC5SEL_DS2_POSITION ) |
			( CLC_USER_CLC5SEL_DS3 << _CLC5SEL_DS3_POSITION ) |
			( CLC_USER_CLC5SEL_DS4 << _CLC5SEL_DS4_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC5SELbits.DS1 = CLC_USER_CLC5SEL_DS1;
			CLC5SELbits.DS2 = CLC_USER_CLC5SEL_DS2;
			CLC5SELbits.DS3 = CLC_USER_CLC5SEL_DS3;
			CLC5SELbits.DS4 = CLC_USER_CLC5SEL_DS4;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC5GLSレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC5GLS = 
			( CLC_USER_CLC5GLS_G1D1N << _CLC5GLS_G1D1N_POSITION ) |
			( CLC_USER_CLC5GLS_G1D1T << _CLC5GLS_G1D1T_POSITION ) |
			( CLC_USER_CLC5GLS_G1D2N << _CLC5GLS_G1D2N_POSITION ) |
			( CLC_USER_CLC5GLS_G1D2T << _CLC5GLS_G1D2T_POSITION ) |
			( CLC_USER_CLC5GLS_G1D3N << _CLC5GLS_G1D3N_POSITION ) |
			( CLC_USER_CLC5GLS_G1D3T << _CLC5GLS_G1D3T_POSITION ) |
			( CLC_USER_CLC5GLS_G1D4N << _CLC5GLS_G1D4N_POSITION ) |
			( CLC_USER_CLC5GLS_G1D4T << _CLC5GLS_G1D4T_POSITION ) |
			( CLC_USER_CLC5GLS_G2D1N << _CLC5GLS_G2D1N_POSITION ) |
			( CLC_USER_CLC5GLS_G2D1T << _CLC5GLS_G2D1T_POSITION ) |
			( CLC_USER_CLC5GLS_G2D2N << _CLC5GLS_G2D2N_POSITION ) |
			( CLC_USER_CLC5GLS_G2D2T << _CLC5GLS_G2D2T_POSITION ) |
			( CLC_USER_CLC5GLS_G2D3N << _CLC5GLS_G2D3N_POSITION ) |
			( CLC_USER_CLC5GLS_G2D3T << _CLC5GLS_G2D3T_POSITION ) |
			( CLC_USER_CLC5GLS_G2D4N << _CLC5GLS_G2D4N_POSITION ) |
			( CLC_USER_CLC5GLS_G2D4T << _CLC5GLS_G2D4T_POSITION ) |
			( CLC_USER_CLC5GLS_G3D1N << _CLC5GLS_G3D1N_POSITION ) |
			( CLC_USER_CLC5GLS_G3D1T << _CLC5GLS_G3D1T_POSITION ) |
			( CLC_USER_CLC5GLS_G3D2N << _CLC5GLS_G3D2N_POSITION ) |
			( CLC_USER_CLC5GLS_G3D2T << _CLC5GLS_G3D2T_POSITION ) |
			( CLC_USER_CLC5GLS_G3D3N << _CLC5GLS_G3D3N_POSITION ) |
			( CLC_USER_CLC5GLS_G3D3T << _CLC5GLS_G3D3T_POSITION ) |
			( CLC_USER_CLC5GLS_G3D4N << _CLC5GLS_G3D4N_POSITION ) |
			( CLC_USER_CLC5GLS_G3D4T << _CLC5GLS_G3D4T_POSITION ) |
			( CLC_USER_CLC5GLS_G4D1N << _CLC5GLS_G4D1N_POSITION ) |
			( CLC_USER_CLC5GLS_G4D1T << _CLC5GLS_G4D1T_POSITION ) |
			( CLC_USER_CLC5GLS_G4D2N << _CLC5GLS_G4D2N_POSITION ) |
			( CLC_USER_CLC5GLS_G4D2T << _CLC5GLS_G4D2T_POSITION ) |
			( CLC_USER_CLC5GLS_G4D3N << _CLC5GLS_G4D3N_POSITION ) |
			( CLC_USER_CLC5GLS_G4D3T << _CLC5GLS_G4D3T_POSITION ) |
			( CLC_USER_CLC5GLS_G4D4N << _CLC5GLS_G4D4N_POSITION ) |
			( CLC_USER_CLC5GLS_G4D4T << _CLC5GLS_G4D4T_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC5GLSbits.G1D1N = CLC_USER_CLC5GLS_G1D1N;
			CLC5GLSbits.G1D1T = CLC_USER_CLC5GLS_G1D1T;
			CLC5GLSbits.G1D2N = CLC_USER_CLC5GLS_G1D2N;
			CLC5GLSbits.G1D2T = CLC_USER_CLC5GLS_G1D2T;
			CLC5GLSbits.G1D3N = CLC_USER_CLC5GLS_G1D3N;
			CLC5GLSbits.G1D3T = CLC_USER_CLC5GLS_G1D3T;
			CLC5GLSbits.G1D4N = CLC_USER_CLC5GLS_G1D4N;
			CLC5GLSbits.G1D4T = CLC_USER_CLC5GLS_G1D4T;
			CLC5GLSbits.G2D1N = CLC_USER_CLC5GLS_G2D1N;
			CLC5GLSbits.G2D1T = CLC_USER_CLC5GLS_G2D1T;
			CLC5GLSbits.G2D2N = CLC_USER_CLC5GLS_G2D2N;
			CLC5GLSbits.G2D2T = CLC_USER_CLC5GLS_G2D2T;
			CLC5GLSbits.G2D3N = CLC_USER_CLC5GLS_G2D3N;
			CLC5GLSbits.G2D3T = CLC_USER_CLC5GLS_G2D3T;
			CLC5GLSbits.G2D4N = CLC_USER_CLC5GLS_G2D4N;
			CLC5GLSbits.G2D4T = CLC_USER_CLC5GLS_G2D4T;
			CLC5GLSbits.G3D1N = CLC_USER_CLC5GLS_G3D1N;
			CLC5GLSbits.G3D1T = CLC_USER_CLC5GLS_G3D1T;
			CLC5GLSbits.G3D2N = CLC_USER_CLC5GLS_G3D2N;
			CLC5GLSbits.G3D2T = CLC_USER_CLC5GLS_G3D2T;
			CLC5GLSbits.G3D3N = CLC_USER_CLC5GLS_G3D3N;
			CLC5GLSbits.G3D3T = CLC_USER_CLC5GLS_G3D3T;
			CLC5GLSbits.G3D4N = CLC_USER_CLC5GLS_G3D4N;
			CLC5GLSbits.G3D4T = CLC_USER_CLC5GLS_G3D4T;
			CLC5GLSbits.G4D1N = CLC_USER_CLC5GLS_G4D1N;
			CLC5GLSbits.G4D1T = CLC_USER_CLC5GLS_G4D1T;
			CLC5GLSbits.G4D2N = CLC_USER_CLC5GLS_G4D2N;
			CLC5GLSbits.G4D2T = CLC_USER_CLC5GLS_G4D2T;
			CLC5GLSbits.G4D3N = CLC_USER_CLC5GLS_G4D3N;
			CLC5GLSbits.G4D3T = CLC_USER_CLC5GLS_G4D3T;
			CLC5GLSbits.G4D4N = CLC_USER_CLC5GLS_G4D4N;
			CLC5GLSbits.G4D4T = CLC_USER_CLC5GLS_G4D4T;
		#endif 
			
		CLC5CONbits.ON = CLC_USER_CLC5CON_ON;
#endif
}

/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_CLC6_Set_Register(void)
* @brief     CLC6レジスタを初期化します
* @param
* @return
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_CLC6_Set_Register(void)
{
#if ( PMD_CLC6MD == PMD_MODULE_ENABLE )
    /*-----------------------------------------------------------------------*/
	/* CLC6CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC6CON = 
			( CLC_USER_CLC6CON_MODE << _CLC6CON_MODE_POSITION ) |
			( CLC_USER_CLC6CON_LCPOL << _CLC6CON_LCPOL_POSITION ) |
			( CLC_USER_CLC6CON_LCOUT << _CLC6CON_LCOUT_POSITION ) |
			( CLC_USER_CLC6CON_LCOE << _CLC6CON_LCOE_POSITION ) |
			( CLC_USER_CLC6CON_INTN << _CLC6CON_INTN_POSITION ) |
			( CLC_USER_CLC6CON_INTP << _CLC6CON_INTP_POSITION ) |
			( CLC_USER_CLC6CON_ON << _CLC6CON_ON_POSITION ) |
			( CLC_USER_CLC6CON_G1POL << _CLC6CON_G1POL_POSITION ) |
			( CLC_USER_CLC6CON_G2POL << _CLC6CON_G2POL_POSITION ) |
			( CLC_USER_CLC6CON_G3POL << _CLC6CON_G3POL_POSITION ) |
			( CLC_USER_CLC6CON_G4POL << _CLC6CON_G4POL_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC6CONbits.MODE = CLC_USER_CLC6CON_MODE;
			CLC6CONbits.LCPOL = CLC_USER_CLC6CON_LCPOL;
			CLC6CONbits.LCOUT = CLC_USER_CLC6CON_LCOUT;
			CLC6CONbits.LCOE = CLC_USER_CLC6CON_LCOE;
			CLC6CONbits.INTN = CLC_USER_CLC6CON_INTN;
			CLC6CONbits.INTP = CLC_USER_CLC6CON_INTP;
			CLC6CONbits.ON = CLC_USER_CLC6CON_ON;
			CLC6CONbits.G1POL = CLC_USER_CLC6CON_G1POL;
			CLC6CONbits.G2POL = CLC_USER_CLC6CON_G2POL;
			CLC6CONbits.G3POL = CLC_USER_CLC6CON_G3POL;
			CLC6CONbits.G4POL = CLC_USER_CLC6CON_G4POL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC6SELレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC6SEL = 
			( CLC_USER_CLC6SEL_DS1 << _CLC6SEL_DS1_POSITION ) |
			( CLC_USER_CLC6SEL_DS2 << _CLC6SEL_DS2_POSITION ) |
			( CLC_USER_CLC6SEL_DS3 << _CLC6SEL_DS3_POSITION ) |
			( CLC_USER_CLC6SEL_DS4 << _CLC6SEL_DS4_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC6SELbits.DS1 = CLC_USER_CLC6SEL_DS1;
			CLC6SELbits.DS2 = CLC_USER_CLC6SEL_DS2;
			CLC6SELbits.DS3 = CLC_USER_CLC6SEL_DS3;
			CLC6SELbits.DS4 = CLC_USER_CLC6SEL_DS4;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC6GLSレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC6GLS = 
			( CLC_USER_CLC6GLS_G1D1N << _CLC6GLS_G1D1N_POSITION ) |
			( CLC_USER_CLC6GLS_G1D1T << _CLC6GLS_G1D1T_POSITION ) |
			( CLC_USER_CLC6GLS_G1D2N << _CLC6GLS_G1D2N_POSITION ) |
			( CLC_USER_CLC6GLS_G1D2T << _CLC6GLS_G1D2T_POSITION ) |
			( CLC_USER_CLC6GLS_G1D3N << _CLC6GLS_G1D3N_POSITION ) |
			( CLC_USER_CLC6GLS_G1D3T << _CLC6GLS_G1D3T_POSITION ) |
			( CLC_USER_CLC6GLS_G1D4N << _CLC6GLS_G1D4N_POSITION ) |
			( CLC_USER_CLC6GLS_G1D4T << _CLC6GLS_G1D4T_POSITION ) |
			( CLC_USER_CLC6GLS_G2D1N << _CLC6GLS_G2D1N_POSITION ) |
			( CLC_USER_CLC6GLS_G2D1T << _CLC6GLS_G2D1T_POSITION ) |
			( CLC_USER_CLC6GLS_G2D2N << _CLC6GLS_G2D2N_POSITION ) |
			( CLC_USER_CLC6GLS_G2D2T << _CLC6GLS_G2D2T_POSITION ) |
			( CLC_USER_CLC6GLS_G2D3N << _CLC6GLS_G2D3N_POSITION ) |
			( CLC_USER_CLC6GLS_G2D3T << _CLC6GLS_G2D3T_POSITION ) |
			( CLC_USER_CLC6GLS_G2D4N << _CLC6GLS_G2D4N_POSITION ) |
			( CLC_USER_CLC6GLS_G2D4T << _CLC6GLS_G2D4T_POSITION ) |
			( CLC_USER_CLC6GLS_G3D1N << _CLC6GLS_G3D1N_POSITION ) |
			( CLC_USER_CLC6GLS_G3D1T << _CLC6GLS_G3D1T_POSITION ) |
			( CLC_USER_CLC6GLS_G3D2N << _CLC6GLS_G3D2N_POSITION ) |
			( CLC_USER_CLC6GLS_G3D2T << _CLC6GLS_G3D2T_POSITION ) |
			( CLC_USER_CLC6GLS_G3D3N << _CLC6GLS_G3D3N_POSITION ) |
			( CLC_USER_CLC6GLS_G3D3T << _CLC6GLS_G3D3T_POSITION ) |
			( CLC_USER_CLC6GLS_G3D4N << _CLC6GLS_G3D4N_POSITION ) |
			( CLC_USER_CLC6GLS_G3D4T << _CLC6GLS_G3D4T_POSITION ) |
			( CLC_USER_CLC6GLS_G4D1N << _CLC6GLS_G4D1N_POSITION ) |
			( CLC_USER_CLC6GLS_G4D1T << _CLC6GLS_G4D1T_POSITION ) |
			( CLC_USER_CLC6GLS_G4D2N << _CLC6GLS_G4D2N_POSITION ) |
			( CLC_USER_CLC6GLS_G4D2T << _CLC6GLS_G4D2T_POSITION ) |
			( CLC_USER_CLC6GLS_G4D3N << _CLC6GLS_G4D3N_POSITION ) |
			( CLC_USER_CLC6GLS_G4D3T << _CLC6GLS_G4D3T_POSITION ) |
			( CLC_USER_CLC6GLS_G4D4N << _CLC6GLS_G4D4N_POSITION ) |
			( CLC_USER_CLC6GLS_G4D4T << _CLC6GLS_G4D4T_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC6GLSbits.G1D1N = CLC_USER_CLC6GLS_G1D1N;
			CLC6GLSbits.G1D1T = CLC_USER_CLC6GLS_G1D1T;
			CLC6GLSbits.G1D2N = CLC_USER_CLC6GLS_G1D2N;
			CLC6GLSbits.G1D2T = CLC_USER_CLC6GLS_G1D2T;
			CLC6GLSbits.G1D3N = CLC_USER_CLC6GLS_G1D3N;
			CLC6GLSbits.G1D3T = CLC_USER_CLC6GLS_G1D3T;
			CLC6GLSbits.G1D4N = CLC_USER_CLC6GLS_G1D4N;
			CLC6GLSbits.G1D4T = CLC_USER_CLC6GLS_G1D4T;
			CLC6GLSbits.G2D1N = CLC_USER_CLC6GLS_G2D1N;
			CLC6GLSbits.G2D1T = CLC_USER_CLC6GLS_G2D1T;
			CLC6GLSbits.G2D2N = CLC_USER_CLC6GLS_G2D2N;
			CLC6GLSbits.G2D2T = CLC_USER_CLC6GLS_G2D2T;
			CLC6GLSbits.G2D3N = CLC_USER_CLC6GLS_G2D3N;
			CLC6GLSbits.G2D3T = CLC_USER_CLC6GLS_G2D3T;
			CLC6GLSbits.G2D4N = CLC_USER_CLC6GLS_G2D4N;
			CLC6GLSbits.G2D4T = CLC_USER_CLC6GLS_G2D4T;
			CLC6GLSbits.G3D1N = CLC_USER_CLC6GLS_G3D1N;
			CLC6GLSbits.G3D1T = CLC_USER_CLC6GLS_G3D1T;
			CLC6GLSbits.G3D2N = CLC_USER_CLC6GLS_G3D2N;
			CLC6GLSbits.G3D2T = CLC_USER_CLC6GLS_G3D2T;
			CLC6GLSbits.G3D3N = CLC_USER_CLC6GLS_G3D3N;
			CLC6GLSbits.G3D3T = CLC_USER_CLC6GLS_G3D3T;
			CLC6GLSbits.G3D4N = CLC_USER_CLC6GLS_G3D4N;
			CLC6GLSbits.G3D4T = CLC_USER_CLC6GLS_G3D4T;
			CLC6GLSbits.G4D1N = CLC_USER_CLC6GLS_G4D1N;
			CLC6GLSbits.G4D1T = CLC_USER_CLC6GLS_G4D1T;
			CLC6GLSbits.G4D2N = CLC_USER_CLC6GLS_G4D2N;
			CLC6GLSbits.G4D2T = CLC_USER_CLC6GLS_G4D2T;
			CLC6GLSbits.G4D3N = CLC_USER_CLC6GLS_G4D3N;
			CLC6GLSbits.G4D3T = CLC_USER_CLC6GLS_G4D3T;
			CLC6GLSbits.G4D4N = CLC_USER_CLC6GLS_G4D4N;
			CLC6GLSbits.G4D4T = CLC_USER_CLC6GLS_G4D4T;
		#endif 
			
		CLC6CONbits.ON = CLC_USER_CLC6CON_ON;
#endif
}

/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_CLC7_Set_Register(void)
* @brief     CLC7レジスタを初期化します
* @param
* @return
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_CLC7_Set_Register(void)
{
#if ( PMD_CLC7MD == PMD_MODULE_ENABLE )
   	/*-----------------------------------------------------------------------*/
	/* CLC7CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC7CON = 
			( CLC_USER_CLC7CON_MODE << _CLC7CON_MODE_POSITION ) |
			( CLC_USER_CLC7CON_LCPOL << _CLC7CON_LCPOL_POSITION ) |
			( CLC_USER_CLC7CON_LCOUT << _CLC7CON_LCOUT_POSITION ) |
			( CLC_USER_CLC7CON_LCOE << _CLC7CON_LCOE_POSITION ) |
			( CLC_USER_CLC7CON_INTN << _CLC7CON_INTN_POSITION ) |
			( CLC_USER_CLC7CON_INTP << _CLC7CON_INTP_POSITION ) |
			( CLC_USER_CLC7CON_ON << _CLC7CON_ON_POSITION ) |
			( CLC_USER_CLC7CON_G1POL << _CLC7CON_G1POL_POSITION ) |
			( CLC_USER_CLC7CON_G2POL << _CLC7CON_G2POL_POSITION ) |
			( CLC_USER_CLC7CON_G3POL << _CLC7CON_G3POL_POSITION ) |
			( CLC_USER_CLC7CON_G4POL << _CLC7CON_G4POL_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC7CONbits.MODE = CLC_USER_CLC7CON_MODE;
			CLC7CONbits.LCPOL = CLC_USER_CLC7CON_LCPOL;
			CLC7CONbits.LCOUT = CLC_USER_CLC7CON_LCOUT;
			CLC7CONbits.LCOE = CLC_USER_CLC7CON_LCOE;
			CLC7CONbits.INTN = CLC_USER_CLC7CON_INTN;
			CLC7CONbits.INTP = CLC_USER_CLC7CON_INTP;
			CLC7CONbits.ON = CLC_USER_CLC7CON_ON;
			CLC7CONbits.G1POL = CLC_USER_CLC7CON_G1POL;
			CLC7CONbits.G2POL = CLC_USER_CLC7CON_G2POL;
			CLC7CONbits.G3POL = CLC_USER_CLC7CON_G3POL;
			CLC7CONbits.G4POL = CLC_USER_CLC7CON_G4POL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC7SELレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC7SEL = 
			( CLC_USER_CLC7SEL_DS1 << _CLC7SEL_DS1_POSITION ) |
			( CLC_USER_CLC7SEL_DS2 << _CLC7SEL_DS2_POSITION ) |
			( CLC_USER_CLC7SEL_DS3 << _CLC7SEL_DS3_POSITION ) |
			( CLC_USER_CLC7SEL_DS4 << _CLC7SEL_DS4_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC7SELbits.DS1 = CLC_USER_CLC7SEL_DS1;
			CLC7SELbits.DS2 = CLC_USER_CLC7SEL_DS2;
			CLC7SELbits.DS3 = CLC_USER_CLC7SEL_DS3;
			CLC7SELbits.DS4 = CLC_USER_CLC7SEL_DS4;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC7GLSレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC7GLS = 
			( CLC_USER_CLC7GLS_G1D1N << _CLC7GLS_G1D1N_POSITION ) |
			( CLC_USER_CLC7GLS_G1D1T << _CLC7GLS_G1D1T_POSITION ) |
			( CLC_USER_CLC7GLS_G1D2N << _CLC7GLS_G1D2N_POSITION ) |
			( CLC_USER_CLC7GLS_G1D2T << _CLC7GLS_G1D2T_POSITION ) |
			( CLC_USER_CLC7GLS_G1D3N << _CLC7GLS_G1D3N_POSITION ) |
			( CLC_USER_CLC7GLS_G1D3T << _CLC7GLS_G1D3T_POSITION ) |
			( CLC_USER_CLC7GLS_G1D4N << _CLC7GLS_G1D4N_POSITION ) |
			( CLC_USER_CLC7GLS_G1D4T << _CLC7GLS_G1D4T_POSITION ) |
			( CLC_USER_CLC7GLS_G2D1N << _CLC7GLS_G2D1N_POSITION ) |
			( CLC_USER_CLC7GLS_G2D1T << _CLC7GLS_G2D1T_POSITION ) |
			( CLC_USER_CLC7GLS_G2D2N << _CLC7GLS_G2D2N_POSITION ) |
			( CLC_USER_CLC7GLS_G2D2T << _CLC7GLS_G2D2T_POSITION ) |
			( CLC_USER_CLC7GLS_G2D3N << _CLC7GLS_G2D3N_POSITION ) |
			( CLC_USER_CLC7GLS_G2D3T << _CLC7GLS_G2D3T_POSITION ) |
			( CLC_USER_CLC7GLS_G2D4N << _CLC7GLS_G2D4N_POSITION ) |
			( CLC_USER_CLC7GLS_G2D4T << _CLC7GLS_G2D4T_POSITION ) |
			( CLC_USER_CLC7GLS_G3D1N << _CLC7GLS_G3D1N_POSITION ) |
			( CLC_USER_CLC7GLS_G3D1T << _CLC7GLS_G3D1T_POSITION ) |
			( CLC_USER_CLC7GLS_G3D2N << _CLC7GLS_G3D2N_POSITION ) |
			( CLC_USER_CLC7GLS_G3D2T << _CLC7GLS_G3D2T_POSITION ) |
			( CLC_USER_CLC7GLS_G3D3N << _CLC7GLS_G3D3N_POSITION ) |
			( CLC_USER_CLC7GLS_G3D3T << _CLC7GLS_G3D3T_POSITION ) |
			( CLC_USER_CLC7GLS_G3D4N << _CLC7GLS_G3D4N_POSITION ) |
			( CLC_USER_CLC7GLS_G3D4T << _CLC7GLS_G3D4T_POSITION ) |
			( CLC_USER_CLC7GLS_G4D1N << _CLC7GLS_G4D1N_POSITION ) |
			( CLC_USER_CLC7GLS_G4D1T << _CLC7GLS_G4D1T_POSITION ) |
			( CLC_USER_CLC7GLS_G4D2N << _CLC7GLS_G4D2N_POSITION ) |
			( CLC_USER_CLC7GLS_G4D2T << _CLC7GLS_G4D2T_POSITION ) |
			( CLC_USER_CLC7GLS_G4D3N << _CLC7GLS_G4D3N_POSITION ) |
			( CLC_USER_CLC7GLS_G4D3T << _CLC7GLS_G4D3T_POSITION ) |
			( CLC_USER_CLC7GLS_G4D4N << _CLC7GLS_G4D4N_POSITION ) |
			( CLC_USER_CLC7GLS_G4D4T << _CLC7GLS_G4D4T_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC7GLSbits.G1D1N = CLC_USER_CLC7GLS_G1D1N;
			CLC7GLSbits.G1D1T = CLC_USER_CLC7GLS_G1D1T;
			CLC7GLSbits.G1D2N = CLC_USER_CLC7GLS_G1D2N;
			CLC7GLSbits.G1D2T = CLC_USER_CLC7GLS_G1D2T;
			CLC7GLSbits.G1D3N = CLC_USER_CLC7GLS_G1D3N;
			CLC7GLSbits.G1D3T = CLC_USER_CLC7GLS_G1D3T;
			CLC7GLSbits.G1D4N = CLC_USER_CLC7GLS_G1D4N;
			CLC7GLSbits.G1D4T = CLC_USER_CLC7GLS_G1D4T;
			CLC7GLSbits.G2D1N = CLC_USER_CLC7GLS_G2D1N;
			CLC7GLSbits.G2D1T = CLC_USER_CLC7GLS_G2D1T;
			CLC7GLSbits.G2D2N = CLC_USER_CLC7GLS_G2D2N;
			CLC7GLSbits.G2D2T = CLC_USER_CLC7GLS_G2D2T;
			CLC7GLSbits.G2D3N = CLC_USER_CLC7GLS_G2D3N;
			CLC7GLSbits.G2D3T = CLC_USER_CLC7GLS_G2D3T;
			CLC7GLSbits.G2D4N = CLC_USER_CLC7GLS_G2D4N;
			CLC7GLSbits.G2D4T = CLC_USER_CLC7GLS_G2D4T;
			CLC7GLSbits.G3D1N = CLC_USER_CLC7GLS_G3D1N;
			CLC7GLSbits.G3D1T = CLC_USER_CLC7GLS_G3D1T;
			CLC7GLSbits.G3D2N = CLC_USER_CLC7GLS_G3D2N;
			CLC7GLSbits.G3D2T = CLC_USER_CLC7GLS_G3D2T;
			CLC7GLSbits.G3D3N = CLC_USER_CLC7GLS_G3D3N;
			CLC7GLSbits.G3D3T = CLC_USER_CLC7GLS_G3D3T;
			CLC7GLSbits.G3D4N = CLC_USER_CLC7GLS_G3D4N;
			CLC7GLSbits.G3D4T = CLC_USER_CLC7GLS_G3D4T;
			CLC7GLSbits.G4D1N = CLC_USER_CLC7GLS_G4D1N;
			CLC7GLSbits.G4D1T = CLC_USER_CLC7GLS_G4D1T;
			CLC7GLSbits.G4D2N = CLC_USER_CLC7GLS_G4D2N;
			CLC7GLSbits.G4D2T = CLC_USER_CLC7GLS_G4D2T;
			CLC7GLSbits.G4D3N = CLC_USER_CLC7GLS_G4D3N;
			CLC7GLSbits.G4D3T = CLC_USER_CLC7GLS_G4D3T;
			CLC7GLSbits.G4D4N = CLC_USER_CLC7GLS_G4D4N;
			CLC7GLSbits.G4D4T = CLC_USER_CLC7GLS_G4D4T;
		#endif 
			
		CLC7CONbits.ON = CLC_USER_CLC7CON_ON;
#endif
}

/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_CLC8_Set_Register(void)
* @brief     CLC8レジスタを初期化します
* @param
* @return
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_CLC8_Set_Register(void)
{
#if ( PMD_CLC8MD == PMD_MODULE_ENABLE )
    /*-----------------------------------------------------------------------*/
	/* CLC8CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC8CON = 
			( CLC_USER_CLC8CON_MODE << _CLC8CON_MODE_POSITION ) |
			( CLC_USER_CLC8CON_LCPOL << _CLC8CON_LCPOL_POSITION ) |
			( CLC_USER_CLC8CON_LCOUT << _CLC8CON_LCOUT_POSITION ) |
			( CLC_USER_CLC8CON_LCOE << _CLC8CON_LCOE_POSITION ) |
			( CLC_USER_CLC8CON_INTN << _CLC8CON_INTN_POSITION ) |
			( CLC_USER_CLC8CON_INTP << _CLC8CON_INTP_POSITION ) |
			( CLC_USER_CLC8CON_ON << _CLC8CON_ON_POSITION ) |
			( CLC_USER_CLC8CON_G1POL << _CLC8CON_G1POL_POSITION ) |
			( CLC_USER_CLC8CON_G2POL << _CLC8CON_G2POL_POSITION ) |
			( CLC_USER_CLC8CON_G3POL << _CLC8CON_G3POL_POSITION ) |
			( CLC_USER_CLC8CON_G4POL << _CLC8CON_G4POL_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC8CONbits.MODE = CLC_USER_CLC8CON_MODE;
			CLC8CONbits.LCPOL = CLC_USER_CLC8CON_LCPOL;
			CLC8CONbits.LCOUT = CLC_USER_CLC8CON_LCOUT;
			CLC8CONbits.LCOE = CLC_USER_CLC8CON_LCOE;
			CLC8CONbits.INTN = CLC_USER_CLC8CON_INTN;
			CLC8CONbits.INTP = CLC_USER_CLC8CON_INTP;
			CLC8CONbits.ON = CLC_USER_CLC8CON_ON;
			CLC8CONbits.G1POL = CLC_USER_CLC8CON_G1POL;
			CLC8CONbits.G2POL = CLC_USER_CLC8CON_G2POL;
			CLC8CONbits.G3POL = CLC_USER_CLC8CON_G3POL;
			CLC8CONbits.G4POL = CLC_USER_CLC8CON_G4POL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC8SELレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC8SEL = 
			( CLC_USER_CLC8SEL_DS1 << _CLC8SEL_DS1_POSITION ) |
			( CLC_USER_CLC8SEL_DS2 << _CLC8SEL_DS2_POSITION ) |
			( CLC_USER_CLC8SEL_DS3 << _CLC8SEL_DS3_POSITION ) |
			( CLC_USER_CLC8SEL_DS4 << _CLC8SEL_DS4_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC8SELbits.DS1 = CLC_USER_CLC8SEL_DS1;
			CLC8SELbits.DS2 = CLC_USER_CLC8SEL_DS2;
			CLC8SELbits.DS3 = CLC_USER_CLC8SEL_DS3;
			CLC8SELbits.DS4 = CLC_USER_CLC8SEL_DS4;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC8GLSレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC8GLS = 
			( CLC_USER_CLC8GLS_G1D1N << _CLC8GLS_G1D1N_POSITION ) |
			( CLC_USER_CLC8GLS_G1D1T << _CLC8GLS_G1D1T_POSITION ) |
			( CLC_USER_CLC8GLS_G1D2N << _CLC8GLS_G1D2N_POSITION ) |
			( CLC_USER_CLC8GLS_G1D2T << _CLC8GLS_G1D2T_POSITION ) |
			( CLC_USER_CLC8GLS_G1D3N << _CLC8GLS_G1D3N_POSITION ) |
			( CLC_USER_CLC8GLS_G1D3T << _CLC8GLS_G1D3T_POSITION ) |
			( CLC_USER_CLC8GLS_G1D4N << _CLC8GLS_G1D4N_POSITION ) |
			( CLC_USER_CLC8GLS_G1D4T << _CLC8GLS_G1D4T_POSITION ) |
			( CLC_USER_CLC8GLS_G2D1N << _CLC8GLS_G2D1N_POSITION ) |
			( CLC_USER_CLC8GLS_G2D1T << _CLC8GLS_G2D1T_POSITION ) |
			( CLC_USER_CLC8GLS_G2D2N << _CLC8GLS_G2D2N_POSITION ) |
			( CLC_USER_CLC8GLS_G2D2T << _CLC8GLS_G2D2T_POSITION ) |
			( CLC_USER_CLC8GLS_G2D3N << _CLC8GLS_G2D3N_POSITION ) |
			( CLC_USER_CLC8GLS_G2D3T << _CLC8GLS_G2D3T_POSITION ) |
			( CLC_USER_CLC8GLS_G2D4N << _CLC8GLS_G2D4N_POSITION ) |
			( CLC_USER_CLC8GLS_G2D4T << _CLC8GLS_G2D4T_POSITION ) |
			( CLC_USER_CLC8GLS_G3D1N << _CLC8GLS_G3D1N_POSITION ) |
			( CLC_USER_CLC8GLS_G3D1T << _CLC8GLS_G3D1T_POSITION ) |
			( CLC_USER_CLC8GLS_G3D2N << _CLC8GLS_G3D2N_POSITION ) |
			( CLC_USER_CLC8GLS_G3D2T << _CLC8GLS_G3D2T_POSITION ) |
			( CLC_USER_CLC8GLS_G3D3N << _CLC8GLS_G3D3N_POSITION ) |
			( CLC_USER_CLC8GLS_G3D3T << _CLC8GLS_G3D3T_POSITION ) |
			( CLC_USER_CLC8GLS_G3D4N << _CLC8GLS_G3D4N_POSITION ) |
			( CLC_USER_CLC8GLS_G3D4T << _CLC8GLS_G3D4T_POSITION ) |
			( CLC_USER_CLC8GLS_G4D1N << _CLC8GLS_G4D1N_POSITION ) |
			( CLC_USER_CLC8GLS_G4D1T << _CLC8GLS_G4D1T_POSITION ) |
			( CLC_USER_CLC8GLS_G4D2N << _CLC8GLS_G4D2N_POSITION ) |
			( CLC_USER_CLC8GLS_G4D2T << _CLC8GLS_G4D2T_POSITION ) |
			( CLC_USER_CLC8GLS_G4D3N << _CLC8GLS_G4D3N_POSITION ) |
			( CLC_USER_CLC8GLS_G4D3T << _CLC8GLS_G4D3T_POSITION ) |
			( CLC_USER_CLC8GLS_G4D4N << _CLC8GLS_G4D4N_POSITION ) |
			( CLC_USER_CLC8GLS_G4D4T << _CLC8GLS_G4D4T_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC8GLSbits.G1D1N = CLC_USER_CLC8GLS_G1D1N;
			CLC8GLSbits.G1D1T = CLC_USER_CLC8GLS_G1D1T;
			CLC8GLSbits.G1D2N = CLC_USER_CLC8GLS_G1D2N;
			CLC8GLSbits.G1D2T = CLC_USER_CLC8GLS_G1D2T;
			CLC8GLSbits.G1D3N = CLC_USER_CLC8GLS_G1D3N;
			CLC8GLSbits.G1D3T = CLC_USER_CLC8GLS_G1D3T;
			CLC8GLSbits.G1D4N = CLC_USER_CLC8GLS_G1D4N;
			CLC8GLSbits.G1D4T = CLC_USER_CLC8GLS_G1D4T;
			CLC8GLSbits.G2D1N = CLC_USER_CLC8GLS_G2D1N;
			CLC8GLSbits.G2D1T = CLC_USER_CLC8GLS_G2D1T;
			CLC8GLSbits.G2D2N = CLC_USER_CLC8GLS_G2D2N;
			CLC8GLSbits.G2D2T = CLC_USER_CLC8GLS_G2D2T;
			CLC8GLSbits.G2D3N = CLC_USER_CLC8GLS_G2D3N;
			CLC8GLSbits.G2D3T = CLC_USER_CLC8GLS_G2D3T;
			CLC8GLSbits.G2D4N = CLC_USER_CLC8GLS_G2D4N;
			CLC8GLSbits.G2D4T = CLC_USER_CLC8GLS_G2D4T;
			CLC8GLSbits.G3D1N = CLC_USER_CLC8GLS_G3D1N;
			CLC8GLSbits.G3D1T = CLC_USER_CLC8GLS_G3D1T;
			CLC8GLSbits.G3D2N = CLC_USER_CLC8GLS_G3D2N;
			CLC8GLSbits.G3D2T = CLC_USER_CLC8GLS_G3D2T;
			CLC8GLSbits.G3D3N = CLC_USER_CLC8GLS_G3D3N;
			CLC8GLSbits.G3D3T = CLC_USER_CLC8GLS_G3D3T;
			CLC8GLSbits.G3D4N = CLC_USER_CLC8GLS_G3D4N;
			CLC8GLSbits.G3D4T = CLC_USER_CLC8GLS_G3D4T;
			CLC8GLSbits.G4D1N = CLC_USER_CLC8GLS_G4D1N;
			CLC8GLSbits.G4D1T = CLC_USER_CLC8GLS_G4D1T;
			CLC8GLSbits.G4D2N = CLC_USER_CLC8GLS_G4D2N;
			CLC8GLSbits.G4D2T = CLC_USER_CLC8GLS_G4D2T;
			CLC8GLSbits.G4D3N = CLC_USER_CLC8GLS_G4D3N;
			CLC8GLSbits.G4D3T = CLC_USER_CLC8GLS_G4D3T;
			CLC8GLSbits.G4D4N = CLC_USER_CLC8GLS_G4D4N;
			CLC8GLSbits.G4D4T = CLC_USER_CLC8GLS_G4D4T;
		#endif 
			
		CLC8CONbits.ON = CLC_USER_CLC8CON_ON;
#endif
}

/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_CLC9_Set_Register(void)
* @brief     CLC9レジスタを初期化します
* @param
* @return
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_CLC9_Set_Register(void)
{
#if ( PMD_CLC9MD == PMD_MODULE_ENABLE )
    /*-----------------------------------------------------------------------*/
	/* CLC9CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC9CON = 
			( CLC_USER_CLC9CON_MODE << _CLC9CON_MODE_POSITION ) |
			( CLC_USER_CLC9CON_LCPOL << _CLC9CON_LCPOL_POSITION ) |
			( CLC_USER_CLC9CON_LCOUT << _CLC9CON_LCOUT_POSITION ) |
			( CLC_USER_CLC9CON_LCOE << _CLC9CON_LCOE_POSITION ) |
			( CLC_USER_CLC9CON_INTN << _CLC9CON_INTN_POSITION ) |
			( CLC_USER_CLC9CON_INTP << _CLC9CON_INTP_POSITION ) |
			( CLC_USER_CLC9CON_ON << _CLC9CON_ON_POSITION ) |
			( CLC_USER_CLC9CON_G1POL << _CLC9CON_G1POL_POSITION ) |
			( CLC_USER_CLC9CON_G2POL << _CLC9CON_G2POL_POSITION ) |
			( CLC_USER_CLC9CON_G3POL << _CLC9CON_G3POL_POSITION ) |
			( CLC_USER_CLC9CON_G4POL << _CLC9CON_G4POL_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC9CONbits.MODE = CLC_USER_CLC9CON_MODE;
			CLC9CONbits.LCPOL = CLC_USER_CLC9CON_LCPOL;
			CLC9CONbits.LCOUT = CLC_USER_CLC9CON_LCOUT;
			CLC9CONbits.LCOE = CLC_USER_CLC9CON_LCOE;
			CLC9CONbits.INTN = CLC_USER_CLC9CON_INTN;
			CLC9CONbits.INTP = CLC_USER_CLC9CON_INTP;
			CLC9CONbits.ON = CLC_USER_CLC9CON_ON;
			CLC9CONbits.G1POL = CLC_USER_CLC9CON_G1POL;
			CLC9CONbits.G2POL = CLC_USER_CLC9CON_G2POL;
			CLC9CONbits.G3POL = CLC_USER_CLC9CON_G3POL;
			CLC9CONbits.G4POL = CLC_USER_CLC9CON_G4POL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC9SELレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC9SEL = 
			( CLC_USER_CLC9SEL_DS1 << _CLC9SEL_DS1_POSITION ) |
			( CLC_USER_CLC9SEL_DS2 << _CLC9SEL_DS2_POSITION ) |
			( CLC_USER_CLC9SEL_DS3 << _CLC9SEL_DS3_POSITION ) |
			( CLC_USER_CLC9SEL_DS4 << _CLC9SEL_DS4_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC9SELbits.DS1 = CLC_USER_CLC9SEL_DS1;
			CLC9SELbits.DS2 = CLC_USER_CLC9SEL_DS2;
			CLC9SELbits.DS3 = CLC_USER_CLC9SEL_DS3;
			CLC9SELbits.DS4 = CLC_USER_CLC9SEL_DS4;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC9GLSレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC9GLS = 
			( CLC_USER_CLC9GLS_G1D1N << _CLC9GLS_G1D1N_POSITION ) |
			( CLC_USER_CLC9GLS_G1D1T << _CLC9GLS_G1D1T_POSITION ) |
			( CLC_USER_CLC9GLS_G1D2N << _CLC9GLS_G1D2N_POSITION ) |
			( CLC_USER_CLC9GLS_G1D2T << _CLC9GLS_G1D2T_POSITION ) |
			( CLC_USER_CLC9GLS_G1D3N << _CLC9GLS_G1D3N_POSITION ) |
			( CLC_USER_CLC9GLS_G1D3T << _CLC9GLS_G1D3T_POSITION ) |
			( CLC_USER_CLC9GLS_G1D4N << _CLC9GLS_G1D4N_POSITION ) |
			( CLC_USER_CLC9GLS_G1D4T << _CLC9GLS_G1D4T_POSITION ) |
			( CLC_USER_CLC9GLS_G2D1N << _CLC9GLS_G2D1N_POSITION ) |
			( CLC_USER_CLC9GLS_G2D1T << _CLC9GLS_G2D1T_POSITION ) |
			( CLC_USER_CLC9GLS_G2D2N << _CLC9GLS_G2D2N_POSITION ) |
			( CLC_USER_CLC9GLS_G2D2T << _CLC9GLS_G2D2T_POSITION ) |
			( CLC_USER_CLC9GLS_G2D3N << _CLC9GLS_G2D3N_POSITION ) |
			( CLC_USER_CLC9GLS_G2D3T << _CLC9GLS_G2D3T_POSITION ) |
			( CLC_USER_CLC9GLS_G2D4N << _CLC9GLS_G2D4N_POSITION ) |
			( CLC_USER_CLC9GLS_G2D4T << _CLC9GLS_G2D4T_POSITION ) |
			( CLC_USER_CLC9GLS_G3D1N << _CLC9GLS_G3D1N_POSITION ) |
			( CLC_USER_CLC9GLS_G3D1T << _CLC9GLS_G3D1T_POSITION ) |
			( CLC_USER_CLC9GLS_G3D2N << _CLC9GLS_G3D2N_POSITION ) |
			( CLC_USER_CLC9GLS_G3D2T << _CLC9GLS_G3D2T_POSITION ) |
			( CLC_USER_CLC9GLS_G3D3N << _CLC9GLS_G3D3N_POSITION ) |
			( CLC_USER_CLC9GLS_G3D3T << _CLC9GLS_G3D3T_POSITION ) |
			( CLC_USER_CLC9GLS_G3D4N << _CLC9GLS_G3D4N_POSITION ) |
			( CLC_USER_CLC9GLS_G3D4T << _CLC9GLS_G3D4T_POSITION ) |
			( CLC_USER_CLC9GLS_G4D1N << _CLC9GLS_G4D1N_POSITION ) |
			( CLC_USER_CLC9GLS_G4D1T << _CLC9GLS_G4D1T_POSITION ) |
			( CLC_USER_CLC9GLS_G4D2N << _CLC9GLS_G4D2N_POSITION ) |
			( CLC_USER_CLC9GLS_G4D2T << _CLC9GLS_G4D2T_POSITION ) |
			( CLC_USER_CLC9GLS_G4D3N << _CLC9GLS_G4D3N_POSITION ) |
			( CLC_USER_CLC9GLS_G4D3T << _CLC9GLS_G4D3T_POSITION ) |
			( CLC_USER_CLC9GLS_G4D4N << _CLC9GLS_G4D4N_POSITION ) |
			( CLC_USER_CLC9GLS_G4D4T << _CLC9GLS_G4D4T_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC9GLSbits.G1D1N = CLC_USER_CLC9GLS_G1D1N;
			CLC9GLSbits.G1D1T = CLC_USER_CLC9GLS_G1D1T;
			CLC9GLSbits.G1D2N = CLC_USER_CLC9GLS_G1D2N;
			CLC9GLSbits.G1D2T = CLC_USER_CLC9GLS_G1D2T;
			CLC9GLSbits.G1D3N = CLC_USER_CLC9GLS_G1D3N;
			CLC9GLSbits.G1D3T = CLC_USER_CLC9GLS_G1D3T;
			CLC9GLSbits.G1D4N = CLC_USER_CLC9GLS_G1D4N;
			CLC9GLSbits.G1D4T = CLC_USER_CLC9GLS_G1D4T;
			CLC9GLSbits.G2D1N = CLC_USER_CLC9GLS_G2D1N;
			CLC9GLSbits.G2D1T = CLC_USER_CLC9GLS_G2D1T;
			CLC9GLSbits.G2D2N = CLC_USER_CLC9GLS_G2D2N;
			CLC9GLSbits.G2D2T = CLC_USER_CLC9GLS_G2D2T;
			CLC9GLSbits.G2D3N = CLC_USER_CLC9GLS_G2D3N;
			CLC9GLSbits.G2D3T = CLC_USER_CLC9GLS_G2D3T;
			CLC9GLSbits.G2D4N = CLC_USER_CLC9GLS_G2D4N;
			CLC9GLSbits.G2D4T = CLC_USER_CLC9GLS_G2D4T;
			CLC9GLSbits.G3D1N = CLC_USER_CLC9GLS_G3D1N;
			CLC9GLSbits.G3D1T = CLC_USER_CLC9GLS_G3D1T;
			CLC9GLSbits.G3D2N = CLC_USER_CLC9GLS_G3D2N;
			CLC9GLSbits.G3D2T = CLC_USER_CLC9GLS_G3D2T;
			CLC9GLSbits.G3D3N = CLC_USER_CLC9GLS_G3D3N;
			CLC9GLSbits.G3D3T = CLC_USER_CLC9GLS_G3D3T;
			CLC9GLSbits.G3D4N = CLC_USER_CLC9GLS_G3D4N;
			CLC9GLSbits.G3D4T = CLC_USER_CLC9GLS_G3D4T;
			CLC9GLSbits.G4D1N = CLC_USER_CLC9GLS_G4D1N;
			CLC9GLSbits.G4D1T = CLC_USER_CLC9GLS_G4D1T;
			CLC9GLSbits.G4D2N = CLC_USER_CLC9GLS_G4D2N;
			CLC9GLSbits.G4D2T = CLC_USER_CLC9GLS_G4D2T;
			CLC9GLSbits.G4D3N = CLC_USER_CLC9GLS_G4D3N;
			CLC9GLSbits.G4D3T = CLC_USER_CLC9GLS_G4D3T;
			CLC9GLSbits.G4D4N = CLC_USER_CLC9GLS_G4D4N;
			CLC9GLSbits.G4D4T = CLC_USER_CLC9GLS_G4D4T;
		#endif 
			
		CLC9CONbits.ON = CLC_USER_CLC9CON_ON;
#endif
}

/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_CLC10_Set_Register(void)
* @brief     CLC10レジスタを初期化します
* @param
* @return
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_CLC10_Set_Register(void)
{
#if ( PMD_CLC10MD == PMD_MODULE_ENABLE )
    /*-----------------------------------------------------------------------*/
	/* CLC10CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC10CON = 
			( CLC_USER_CLC10CON_MODE << _CLC10CON_MODE_POSITION ) |
			( CLC_USER_CLC10CON_LCPOL << _CLC10CON_LCPOL_POSITION ) |
			( CLC_USER_CLC10CON_LCOUT << _CLC10CON_LCOUT_POSITION ) |
			( CLC_USER_CLC10CON_LCOE << _CLC10CON_LCOE_POSITION ) |
			( CLC_USER_CLC10CON_INTN << _CLC10CON_INTN_POSITION ) |
			( CLC_USER_CLC10CON_INTP << _CLC10CON_INTP_POSITION ) |
			( CLC_USER_CLC10CON_ON << _CLC10CON_ON_POSITION ) |
			( CLC_USER_CLC10CON_G1POL << _CLC10CON_G1POL_POSITION ) |
			( CLC_USER_CLC10CON_G2POL << _CLC10CON_G2POL_POSITION ) |
			( CLC_USER_CLC10CON_G3POL << _CLC10CON_G3POL_POSITION ) |
			( CLC_USER_CLC10CON_G4POL << _CLC10CON_G4POL_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC10CONbits.MODE = CLC_USER_CLC10CON_MODE;
			CLC10CONbits.LCPOL = CLC_USER_CLC10CON_LCPOL;
			CLC10CONbits.LCOUT = CLC_USER_CLC10CON_LCOUT;
			CLC10CONbits.LCOE = CLC_USER_CLC10CON_LCOE;
			CLC10CONbits.INTN = CLC_USER_CLC10CON_INTN;
			CLC10CONbits.INTP = CLC_USER_CLC10CON_INTP;
			CLC10CONbits.ON = CLC_USER_CLC10CON_ON;
			CLC10CONbits.G1POL = CLC_USER_CLC10CON_G1POL;
			CLC10CONbits.G2POL = CLC_USER_CLC10CON_G2POL;
			CLC10CONbits.G3POL = CLC_USER_CLC10CON_G3POL;
			CLC10CONbits.G4POL = CLC_USER_CLC10CON_G4POL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC10SELレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC10SEL = 
			( CLC_USER_CLC10SEL_DS1 << _CLC10SEL_DS1_POSITION ) |
			( CLC_USER_CLC10SEL_DS2 << _CLC10SEL_DS2_POSITION ) |
			( CLC_USER_CLC10SEL_DS3 << _CLC10SEL_DS3_POSITION ) |
			( CLC_USER_CLC10SEL_DS4 << _CLC10SEL_DS4_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC10SELbits.DS1 = CLC_USER_CLC10SEL_DS1;
			CLC10SELbits.DS2 = CLC_USER_CLC10SEL_DS2;
			CLC10SELbits.DS3 = CLC_USER_CLC10SEL_DS3;
			CLC10SELbits.DS4 = CLC_USER_CLC10SEL_DS4;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLC10GLSレジスタ */
	/*-----------------------------------------------------------------------*/
		CLC10GLS = 
			( CLC_USER_CLC10GLS_G1D1N << _CLC10GLS_G1D1N_POSITION ) |
			( CLC_USER_CLC10GLS_G1D1T << _CLC10GLS_G1D1T_POSITION ) |
			( CLC_USER_CLC10GLS_G1D2N << _CLC10GLS_G1D2N_POSITION ) |
			( CLC_USER_CLC10GLS_G1D2T << _CLC10GLS_G1D2T_POSITION ) |
			( CLC_USER_CLC10GLS_G1D3N << _CLC10GLS_G1D3N_POSITION ) |
			( CLC_USER_CLC10GLS_G1D3T << _CLC10GLS_G1D3T_POSITION ) |
			( CLC_USER_CLC10GLS_G1D4N << _CLC10GLS_G1D4N_POSITION ) |
			( CLC_USER_CLC10GLS_G1D4T << _CLC10GLS_G1D4T_POSITION ) |
			( CLC_USER_CLC10GLS_G2D1N << _CLC10GLS_G2D1N_POSITION ) |
			( CLC_USER_CLC10GLS_G2D1T << _CLC10GLS_G2D1T_POSITION ) |
			( CLC_USER_CLC10GLS_G2D2N << _CLC10GLS_G2D2N_POSITION ) |
			( CLC_USER_CLC10GLS_G2D2T << _CLC10GLS_G2D2T_POSITION ) |
			( CLC_USER_CLC10GLS_G2D3N << _CLC10GLS_G2D3N_POSITION ) |
			( CLC_USER_CLC10GLS_G2D3T << _CLC10GLS_G2D3T_POSITION ) |
			( CLC_USER_CLC10GLS_G2D4N << _CLC10GLS_G2D4N_POSITION ) |
			( CLC_USER_CLC10GLS_G2D4T << _CLC10GLS_G2D4T_POSITION ) |
			( CLC_USER_CLC10GLS_G3D1N << _CLC10GLS_G3D1N_POSITION ) |
			( CLC_USER_CLC10GLS_G3D1T << _CLC10GLS_G3D1T_POSITION ) |
			( CLC_USER_CLC10GLS_G3D2N << _CLC10GLS_G3D2N_POSITION ) |
			( CLC_USER_CLC10GLS_G3D2T << _CLC10GLS_G3D2T_POSITION ) |
			( CLC_USER_CLC10GLS_G3D3N << _CLC10GLS_G3D3N_POSITION ) |
			( CLC_USER_CLC10GLS_G3D3T << _CLC10GLS_G3D3T_POSITION ) |
			( CLC_USER_CLC10GLS_G3D4N << _CLC10GLS_G3D4N_POSITION ) |
			( CLC_USER_CLC10GLS_G3D4T << _CLC10GLS_G3D4T_POSITION ) |
			( CLC_USER_CLC10GLS_G4D1N << _CLC10GLS_G4D1N_POSITION ) |
			( CLC_USER_CLC10GLS_G4D1T << _CLC10GLS_G4D1T_POSITION ) |
			( CLC_USER_CLC10GLS_G4D2N << _CLC10GLS_G4D2N_POSITION ) |
			( CLC_USER_CLC10GLS_G4D2T << _CLC10GLS_G4D2T_POSITION ) |
			( CLC_USER_CLC10GLS_G4D3N << _CLC10GLS_G4D3N_POSITION ) |
			( CLC_USER_CLC10GLS_G4D3T << _CLC10GLS_G4D3T_POSITION ) |
			( CLC_USER_CLC10GLS_G4D4N << _CLC10GLS_G4D4N_POSITION ) |
			( CLC_USER_CLC10GLS_G4D4T << _CLC10GLS_G4D4T_POSITION ) ;
		#ifdef DEF_BITNAME
			CLC10GLSbits.G1D1N = CLC_USER_CLC10GLS_G1D1N;
			CLC10GLSbits.G1D1T = CLC_USER_CLC10GLS_G1D1T;
			CLC10GLSbits.G1D2N = CLC_USER_CLC10GLS_G1D2N;
			CLC10GLSbits.G1D2T = CLC_USER_CLC10GLS_G1D2T;
			CLC10GLSbits.G1D3N = CLC_USER_CLC10GLS_G1D3N;
			CLC10GLSbits.G1D3T = CLC_USER_CLC10GLS_G1D3T;
			CLC10GLSbits.G1D4N = CLC_USER_CLC10GLS_G1D4N;
			CLC10GLSbits.G1D4T = CLC_USER_CLC10GLS_G1D4T;
			CLC10GLSbits.G2D1N = CLC_USER_CLC10GLS_G2D1N;
			CLC10GLSbits.G2D1T = CLC_USER_CLC10GLS_G2D1T;
			CLC10GLSbits.G2D2N = CLC_USER_CLC10GLS_G2D2N;
			CLC10GLSbits.G2D2T = CLC_USER_CLC10GLS_G2D2T;
			CLC10GLSbits.G2D3N = CLC_USER_CLC10GLS_G2D3N;
			CLC10GLSbits.G2D3T = CLC_USER_CLC10GLS_G2D3T;
			CLC10GLSbits.G2D4N = CLC_USER_CLC10GLS_G2D4N;
			CLC10GLSbits.G2D4T = CLC_USER_CLC10GLS_G2D4T;
			CLC10GLSbits.G3D1N = CLC_USER_CLC10GLS_G3D1N;
			CLC10GLSbits.G3D1T = CLC_USER_CLC10GLS_G3D1T;
			CLC10GLSbits.G3D2N = CLC_USER_CLC10GLS_G3D2N;
			CLC10GLSbits.G3D2T = CLC_USER_CLC10GLS_G3D2T;
			CLC10GLSbits.G3D3N = CLC_USER_CLC10GLS_G3D3N;
			CLC10GLSbits.G3D3T = CLC_USER_CLC10GLS_G3D3T;
			CLC10GLSbits.G3D4N = CLC_USER_CLC10GLS_G3D4N;
			CLC10GLSbits.G3D4T = CLC_USER_CLC10GLS_G3D4T;
			CLC10GLSbits.G4D1N = CLC_USER_CLC10GLS_G4D1N;
			CLC10GLSbits.G4D1T = CLC_USER_CLC10GLS_G4D1T;
			CLC10GLSbits.G4D2N = CLC_USER_CLC10GLS_G4D2N;
			CLC10GLSbits.G4D2T = CLC_USER_CLC10GLS_G4D2T;
			CLC10GLSbits.G4D3N = CLC_USER_CLC10GLS_G4D3N;
			CLC10GLSbits.G4D3T = CLC_USER_CLC10GLS_G4D3T;
			CLC10GLSbits.G4D4N = CLC_USER_CLC10GLS_G4D4N;
			CLC10GLSbits.G4D4T = CLC_USER_CLC10GLS_G4D4T;
		#endif 
			
		CLC10CONbits.ON = CLC_USER_CLC10CON_ON;
#endif
}
/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_CLC_Set_Register(void)
* @brief     全てのCLCレジスタを初期化します
* @param
* @return
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_CLC_Set_Register(void)
{
#if ( PMD_CLC1MD == PMD_MODULE_ENABLE )
    vdg_CLC1_Set_Register();
#endif
#if ( PMD_CLC2MD == PMD_MODULE_ENABLE )
    vdg_CLC2_Set_Register();
#endif
#if ( PMD_CLC3MD == PMD_MODULE_ENABLE )
    vdg_CLC3_Set_Register();
#endif
#if ( PMD_CLC4MD == PMD_MODULE_ENABLE )
    vdg_CLC4_Set_Register();
#endif
	
#if ( PMD_CLC5MD == PMD_MODULE_ENABLE )
    vdg_CLC5_Set_Register();
#endif
#if ( PMD_CLC6MD == PMD_MODULE_ENABLE )
    vdg_CLC6_Set_Register();
#endif
#if ( PMD_CLC7MD == PMD_MODULE_ENABLE )
    vdg_CLC7_Set_Register();
#endif
#if ( PMD_CLC8MD == PMD_MODULE_ENABLE )
    vdg_CLC8_Set_Register();
#endif
#if ( PMD_CLC9MD == PMD_MODULE_ENABLE )
    vdg_CLC9_Set_Register();
#endif
#if ( PMD_CLC10MD == PMD_MODULE_ENABLE )
    vdg_CLC10_Set_Register();
#endif
}