/*----------------------------------------------------------------------------*/
/**
* @file		Clock_Driver.c
* @brief	Clockモジュールに関するドライバ関数
* @date		24/07/16
* @details	
* @note		
*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*インクルードファイル*/
/*----------------------------------------------------------------------------*/
#include <xc.h>
#include "BoardSupportPackage.h"
#include "init_fix.h"
#include "typedef.h"
#include "clock_user.h"
/*----------------------------------------------------------------------------*/
/*定数定義*/
/*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*/
/*変数定義*/
/*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*/
/*プロトタイプ宣言*/
/*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_Clock_Init_Register(void)
* @brief     クロックの設定をします
* @param
* @return
* @detail
*/
/*----------------------------------------------------------------------------*/
void vdg_Clock_Init_Register(void)
{
#if 0
	/*-----------------------------------------------------------------------*/
	/* OSCCTRLレジスタ */
	/*-----------------------------------------------------------------------*/
		OSCCTRL = 
			( CLOCK_USER_OSCCTRL_FRCEN << _OSCCTRL_FRCEN_POSITION ) |
			( CLOCK_USER_OSCCTRL_BFRCEN << _OSCCTRL_BFRCEN_POSITION ) |
			( CLOCK_USER_OSCCTRL_POSCEN << _OSCCTRL_POSCEN_POSITION ) |
			( CLOCK_USER_OSCCTRL_SOSCEN << _OSCCTRL_SOSCEN_POSITION ) |
			( CLOCK_USER_OSCCTRL_AOSCEN << _OSCCTRL_AOSCEN_POSITION ) |
			( CLOCK_USER_OSCCTRL_LFRCEN << _OSCCTRL_LFRCEN_POSITION ) |
			( CLOCK_USER_OSCCTRL_PLL1EN << _OSCCTRL_PLL1EN_POSITION ) |
			( CLOCK_USER_OSCCTRL_PLL2EN << _OSCCTRL_PLL2EN_POSITION ) |
			( CLOCK_USER_OSCCTRL_FRCRDY << _OSCCTRL_FRCRDY_POSITION ) |
			( CLOCK_USER_OSCCTRL_BFRCRDY << _OSCCTRL_BFRCRDY_POSITION ) |
			( CLOCK_USER_OSCCTRL_POSCRDY << _OSCCTRL_POSCRDY_POSITION ) |
			( CLOCK_USER_OSCCTRL_SOSCRDY << _OSCCTRL_SOSCRDY_POSITION ) |
			( CLOCK_USER_OSCCTRL_AOSCRDY << _OSCCTRL_AOSCRDY_POSITION ) |
			( CLOCK_USER_OSCCTRL_LPRCRDY << _OSCCTRL_LPRCRDY_POSITION ) |
			( CLOCK_USER_OSCCTRL_PLL1RDY << _OSCCTRL_PLL1RDY_POSITION ) |
			( CLOCK_USER_OSCCTRL_PLL2RDY << _OSCCTRL_PLL2RDY_POSITION ) |
			( CLOCK_USER_OSCCTRL_CLKLOCK << _OSCCTRL_CLKLOCK_POSITION ) |
			( CLOCK_USER_OSCCTRL_DIAGLOCK << _OSCCTRL_DIAGLOCK_POSITION ) ;
		#ifdef DEF_BITNAME
			OSCCTRLbits.FRCEN = CLOCK_USER_OSCCTRL_FRCEN;
			OSCCTRLbits.BFRCEN = CLOCK_USER_OSCCTRL_BFRCEN;
			OSCCTRLbits.POSCEN = CLOCK_USER_OSCCTRL_POSCEN;
			OSCCTRLbits.SOSCEN = CLOCK_USER_OSCCTRL_SOSCEN;
			OSCCTRLbits.AOSCEN = CLOCK_USER_OSCCTRL_AOSCEN;
			OSCCTRLbits.LFRCEN = CLOCK_USER_OSCCTRL_LFRCEN;
			OSCCTRLbits.PLL1EN = CLOCK_USER_OSCCTRL_PLL1EN;
			OSCCTRLbits.PLL2EN = CLOCK_USER_OSCCTRL_PLL2EN;
			OSCCTRLbits.FRCRDY = CLOCK_USER_OSCCTRL_FRCRDY;
			OSCCTRLbits.BFRCRDY = CLOCK_USER_OSCCTRL_BFRCRDY;
			OSCCTRLbits.POSCRDY = CLOCK_USER_OSCCTRL_POSCRDY;
			OSCCTRLbits.SOSCRDY = CLOCK_USER_OSCCTRL_SOSCRDY;
			OSCCTRLbits.AOSCRDY = CLOCK_USER_OSCCTRL_AOSCRDY;
			OSCCTRLbits.LPRCRDY = CLOCK_USER_OSCCTRL_LPRCRDY;
			OSCCTRLbits.PLL1RDY = CLOCK_USER_OSCCTRL_PLL1RDY;
			OSCCTRLbits.PLL2RDY = CLOCK_USER_OSCCTRL_PLL2RDY;
			OSCCTRLbits.CLKLOCK = CLOCK_USER_OSCCTRL_CLKLOCK;
			OSCCTRLbits.DIAGLOCK = CLOCK_USER_OSCCTRL_DIAGLOCK;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* OSCCFGレジスタ */
	/*-----------------------------------------------------------------------*/
		OSCCFG = 
			( CLOCK_USER_OSCCFG_POSCMD << _OSCCFG_POSCMD_POSITION ) |
			( CLOCK_USER_OSCCFG_GAIN << _OSCCFG_GAIN_POSITION ) |
			( CLOCK_USER_OSCCFG_KICKSTART << _OSCCFG_KICKSTART_POSITION ) |
			( CLOCK_USER_OSCCFG_POSCIOFNC << _OSCCFG_POSCIOFNC_POSITION ) |
			( CLOCK_USER_OSCCFG_AOSCMD << _OSCCFG_AOSCMD_POSITION ) |
			( CLOCK_USER_OSCCFG_AOSCIOFNC << _OSCCFG_AOSCIOFNC_POSITION ) |
			( CLOCK_USER_OSCCFG_FRCLPWR << _OSCCFG_FRCLPWR_POSITION ) ;
		#ifdef DEF_BITNAME
			OSCCFGbits.POSCMD = CLOCK_USER_OSCCFG_POSCMD;
			OSCCFGbits.GAIN = CLOCK_USER_OSCCFG_GAIN;
			OSCCFGbits.KICKSTART = CLOCK_USER_OSCCFG_KICKSTART;
			OSCCFGbits.POSCIOFNC = CLOCK_USER_OSCCFG_POSCIOFNC;
			OSCCFGbits.AOSCMD = CLOCK_USER_OSCCFG_AOSCMD;
			OSCCFGbits.AOSCIOFNC = CLOCK_USER_OSCCFG_AOSCIOFNC;
			OSCCFGbits.FRCLPWR = CLOCK_USER_OSCCFG_FRCLPWR;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLKFAILレジスタ */
	/*-----------------------------------------------------------------------*/
		CLKFAIL = 
			( CLOCK_USER_CLKFAIL_CLKFAIL1 << _CLKFAIL_CLKFAIL1_POSITION ) |
			( CLOCK_USER_CLKFAIL_CLKFAIL2 << _CLKFAIL_CLKFAIL2_POSITION ) |
			( CLOCK_USER_CLKFAIL_CLKFAIL3 << _CLKFAIL_CLKFAIL3_POSITION ) |
			( CLOCK_USER_CLKFAIL_CLKFAIL4 << _CLKFAIL_CLKFAIL4_POSITION ) |
			( CLOCK_USER_CLKFAIL_CLKFAIL5 << _CLKFAIL_CLKFAIL5_POSITION ) |
			( CLOCK_USER_CLKFAIL_CLKFAIL6 << _CLKFAIL_CLKFAIL6_POSITION ) |
			( CLOCK_USER_CLKFAIL_CLKFAIL7 << _CLKFAIL_CLKFAIL7_POSITION ) |
			( CLOCK_USER_CLKFAIL_CLKFAIL8 << _CLKFAIL_CLKFAIL8_POSITION ) |
			( CLOCK_USER_CLKFAIL_CLKFAIL9 << _CLKFAIL_CLKFAIL9_POSITION ) |
			( CLOCK_USER_CLKFAIL_CLKFAIL10 << _CLKFAIL_CLKFAIL10_POSITION ) |
			( CLOCK_USER_CLKFAIL_CLKFAIL11 << _CLKFAIL_CLKFAIL11_POSITION ) |
			( CLOCK_USER_CLKFAIL_CLKFAIL12 << _CLKFAIL_CLKFAIL12_POSITION ) |
			( CLOCK_USER_CLKFAIL_CLKFAIL13 << _CLKFAIL_CLKFAIL13_POSITION ) |
			( CLOCK_USER_CLKFAIL_CLKFAIL14 << _CLKFAIL_CLKFAIL14_POSITION ) |
			( CLOCK_USER_CLKFAIL_PLL1FAIL << _CLKFAIL_PLL1FAIL_POSITION ) |
			( CLOCK_USER_CLKFAIL_PLL2FAIL << _CLKFAIL_PLL2FAIL_POSITION ) |
			( CLOCK_USER_CLKFAIL_SCSMCH << _CLKFAIL_SCSMCH_POSITION ) ;
		#ifdef DEF_BITNAME
			CLKFAILbits.CLKFAIL1 = CLOCK_USER_CLKFAIL_CLKFAIL1;
			CLKFAILbits.CLKFAIL2 = CLOCK_USER_CLKFAIL_CLKFAIL2;
			CLKFAILbits.CLKFAIL3 = CLOCK_USER_CLKFAIL_CLKFAIL3;
			CLKFAILbits.CLKFAIL4 = CLOCK_USER_CLKFAIL_CLKFAIL4;
			CLKFAILbits.CLKFAIL5 = CLOCK_USER_CLKFAIL_CLKFAIL5;
			CLKFAILbits.CLKFAIL6 = CLOCK_USER_CLKFAIL_CLKFAIL6;
			CLKFAILbits.CLKFAIL7 = CLOCK_USER_CLKFAIL_CLKFAIL7;
			CLKFAILbits.CLKFAIL8 = CLOCK_USER_CLKFAIL_CLKFAIL8;
			CLKFAILbits.CLKFAIL9 = CLOCK_USER_CLKFAIL_CLKFAIL9;
			CLKFAILbits.CLKFAIL10 = CLOCK_USER_CLKFAIL_CLKFAIL10;
			CLKFAILbits.CLKFAIL11 = CLOCK_USER_CLKFAIL_CLKFAIL11;
			CLKFAILbits.CLKFAIL12 = CLOCK_USER_CLKFAIL_CLKFAIL12;
			CLKFAILbits.CLKFAIL13 = CLOCK_USER_CLKFAIL_CLKFAIL13;
			CLKFAILbits.CLKFAIL14 = CLOCK_USER_CLKFAIL_CLKFAIL14;
			CLKFAILbits.PLL1FAIL = CLOCK_USER_CLKFAIL_PLL1FAIL;
			CLKFAILbits.PLL2FAIL = CLOCK_USER_CLKFAIL_PLL2FAIL;
			CLKFAILbits.SCSMCH = CLOCK_USER_CLKFAIL_SCSMCH;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SCSFAILレジスタ */
	/*-----------------------------------------------------------------------*/
		SCSFAIL = 
			( CLOCK_USER_SCSFAIL_CLKSCS1 << _SCSFAIL_CLKSCS1_POSITION ) |
			( CLOCK_USER_SCSFAIL_CLKSCS2 << _SCSFAIL_CLKSCS2_POSITION ) |
			( CLOCK_USER_SCSFAIL_CLKSCS3 << _SCSFAIL_CLKSCS3_POSITION ) |
			( CLOCK_USER_SCSFAIL_CLKSCS4 << _SCSFAIL_CLKSCS4_POSITION ) |
			( CLOCK_USER_SCSFAIL_CLKSCS5 << _SCSFAIL_CLKSCS5_POSITION ) |
			( CLOCK_USER_SCSFAIL_CLKSCS6 << _SCSFAIL_CLKSCS6_POSITION ) |
			( CLOCK_USER_SCSFAIL_CLKSCS7 << _SCSFAIL_CLKSCS7_POSITION ) |
			( CLOCK_USER_SCSFAIL_CLKSCS8 << _SCSFAIL_CLKSCS8_POSITION ) |
			( CLOCK_USER_SCSFAIL_CLKSCS9 << _SCSFAIL_CLKSCS9_POSITION ) |
			( CLOCK_USER_SCSFAIL_CLKSCS10 << _SCSFAIL_CLKSCS10_POSITION ) |
			( CLOCK_USER_SCSFAIL_CLKSCS11 << _SCSFAIL_CLKSCS11_POSITION ) |
			( CLOCK_USER_SCSFAIL_CLKSCS12 << _SCSFAIL_CLKSCS12_POSITION ) |
			( CLOCK_USER_SCSFAIL_CLKSCS13 << _SCSFAIL_CLKSCS13_POSITION ) |
			( CLOCK_USER_SCSFAIL_CLKSCS14 << _SCSFAIL_CLKSCS14_POSITION ) |
			( CLOCK_USER_SCSFAIL_PLL1SCS << _SCSFAIL_PLL1SCS_POSITION ) |
			( CLOCK_USER_SCSFAIL_PLL2SCS << _SCSFAIL_PLL2SCS_POSITION ) ;
		#ifdef DEF_BITNAME
			SCSFAILbits.CLKSCS1 = CLOCK_USER_SCSFAIL_CLKSCS1;
			SCSFAILbits.CLKSCS2 = CLOCK_USER_SCSFAIL_CLKSCS2;
			SCSFAILbits.CLKSCS3 = CLOCK_USER_SCSFAIL_CLKSCS3;
			SCSFAILbits.CLKSCS4 = CLOCK_USER_SCSFAIL_CLKSCS4;
			SCSFAILbits.CLKSCS5 = CLOCK_USER_SCSFAIL_CLKSCS5;
			SCSFAILbits.CLKSCS6 = CLOCK_USER_SCSFAIL_CLKSCS6;
			SCSFAILbits.CLKSCS7 = CLOCK_USER_SCSFAIL_CLKSCS7;
			SCSFAILbits.CLKSCS8 = CLOCK_USER_SCSFAIL_CLKSCS8;
			SCSFAILbits.CLKSCS9 = CLOCK_USER_SCSFAIL_CLKSCS9;
			SCSFAILbits.CLKSCS10 = CLOCK_USER_SCSFAIL_CLKSCS10;
			SCSFAILbits.CLKSCS11 = CLOCK_USER_SCSFAIL_CLKSCS11;
			SCSFAILbits.CLKSCS12 = CLOCK_USER_SCSFAIL_CLKSCS12;
			SCSFAILbits.CLKSCS13 = CLOCK_USER_SCSFAIL_CLKSCS13;
			SCSFAILbits.CLKSCS14 = CLOCK_USER_SCSFAIL_CLKSCS14;
			SCSFAILbits.PLL1SCS = CLOCK_USER_SCSFAIL_PLL1SCS;
			SCSFAILbits.PLL2SCS = CLOCK_USER_SCSFAIL_PLL2SCS;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK1CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK1CON = 
			( CLOCK_USER_CLK1CON_COSC << _CLK1CON_COSC_POSITION ) |
			( CLOCK_USER_CLK1CON_SLEEPDLY << _CLK1CON_SLEEPDLY_POSITION ) |
			( CLOCK_USER_CLK1CON_NOSC << _CLK1CON_NOSC_POSITION ) |
			( CLOCK_USER_CLK1CON_OE << _CLK1CON_OE_POSITION ) |
			( CLOCK_USER_CLK1CON_SIDL << _CLK1CON_SIDL_POSITION ) |
			( CLOCK_USER_CLK1CON_ON << _CLK1CON_ON_POSITION ) |
			( CLOCK_USER_CLK1CON_BOSC << _CLK1CON_BOSC_POSITION ) |
			( CLOCK_USER_CLK1CON_FSCMEN << _CLK1CON_FSCMEN_POSITION ) |
			( CLOCK_USER_CLK1CON_DIVSWEN << _CLK1CON_DIVSWEN_POSITION ) |
			( CLOCK_USER_CLK1CON_OSWEN << _CLK1CON_OSWEN_POSITION ) |
			( CLOCK_USER_CLK1CON_EXTCFSEL << _CLK1CON_EXTCFSEL_POSITION ) |
			( CLOCK_USER_CLK1CON_EXTCFEN << _CLK1CON_EXTCFEN_POSITION ) |
			( CLOCK_USER_CLK1CON_RIS << _CLK1CON_RIS_POSITION ) |
			( CLOCK_USER_CLK1CON_CLKRDY << _CLK1CON_CLKRDY_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK1CONbits.COSC = CLOCK_USER_CLK1CON_COSC;
			CLK1CONbits.SLEEPDLY = CLOCK_USER_CLK1CON_SLEEPDLY;
			CLK1CONbits.NOSC = CLOCK_USER_CLK1CON_NOSC;
			CLK1CONbits.OE = CLOCK_USER_CLK1CON_OE;
			CLK1CONbits.SIDL = CLOCK_USER_CLK1CON_SIDL;
			CLK1CONbits.ON = CLOCK_USER_CLK1CON_ON;
			CLK1CONbits.BOSC = CLOCK_USER_CLK1CON_BOSC;
			CLK1CONbits.FSCMEN = CLOCK_USER_CLK1CON_FSCMEN;
			CLK1CONbits.DIVSWEN = CLOCK_USER_CLK1CON_DIVSWEN;
			CLK1CONbits.OSWEN = CLOCK_USER_CLK1CON_OSWEN;
			CLK1CONbits.EXTCFSEL = CLOCK_USER_CLK1CON_EXTCFSEL;
			CLK1CONbits.EXTCFEN = CLOCK_USER_CLK1CON_EXTCFEN;
			CLK1CONbits.RIS = CLOCK_USER_CLK1CON_RIS;
			CLK1CONbits.CLKRDY = CLOCK_USER_CLK1CON_CLKRDY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK1DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK1DIV = 
			( CLOCK_USER_CLK1DIV_FRACDIV << _CLK1DIV_FRACDIV_POSITION ) |
			( CLOCK_USER_CLK1DIV_INTDIV << _CLK1DIV_INTDIV_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK1DIVbits.FRACDIV = CLOCK_USER_CLK1DIV_FRACDIV;
			CLK1DIVbits.INTDIV = CLOCK_USER_CLK1DIV_INTDIV;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK2CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK2CON = 
			( CLOCK_USER_CLK2CON_COSC << _CLK2CON_COSC_POSITION ) |
			( CLOCK_USER_CLK2CON_SLEEPDLY << _CLK2CON_SLEEPDLY_POSITION ) |
			( CLOCK_USER_CLK2CON_NOSC << _CLK2CON_NOSC_POSITION ) |
			( CLOCK_USER_CLK2CON_OE << _CLK2CON_OE_POSITION ) |
			( CLOCK_USER_CLK2CON_SIDL << _CLK2CON_SIDL_POSITION ) |
			( CLOCK_USER_CLK2CON_ON << _CLK2CON_ON_POSITION ) |
			( CLOCK_USER_CLK2CON_BOSC << _CLK2CON_BOSC_POSITION ) |
			( CLOCK_USER_CLK2CON_FSCMEN << _CLK2CON_FSCMEN_POSITION ) |
			( CLOCK_USER_CLK2CON_DIVSWEN << _CLK2CON_DIVSWEN_POSITION ) |
			( CLOCK_USER_CLK2CON_OSWEN << _CLK2CON_OSWEN_POSITION ) |
			( CLOCK_USER_CLK2CON_EXTCFSEL << _CLK2CON_EXTCFSEL_POSITION ) |
			( CLOCK_USER_CLK2CON_EXTCFEN << _CLK2CON_EXTCFEN_POSITION ) |
			( CLOCK_USER_CLK2CON_RIS << _CLK2CON_RIS_POSITION ) |
			( CLOCK_USER_CLK2CON_CLKRDY << _CLK2CON_CLKRDY_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK2CONbits.COSC = CLOCK_USER_CLK2CON_COSC;
			CLK2CONbits.SLEEPDLY = CLOCK_USER_CLK2CON_SLEEPDLY;
			CLK2CONbits.NOSC = CLOCK_USER_CLK2CON_NOSC;
			CLK2CONbits.OE = CLOCK_USER_CLK2CON_OE;
			CLK2CONbits.SIDL = CLOCK_USER_CLK2CON_SIDL;
			CLK2CONbits.ON = CLOCK_USER_CLK2CON_ON;
			CLK2CONbits.BOSC = CLOCK_USER_CLK2CON_BOSC;
			CLK2CONbits.FSCMEN = CLOCK_USER_CLK2CON_FSCMEN;
			CLK2CONbits.DIVSWEN = CLOCK_USER_CLK2CON_DIVSWEN;
			CLK2CONbits.OSWEN = CLOCK_USER_CLK2CON_OSWEN;
			CLK2CONbits.EXTCFSEL = CLOCK_USER_CLK2CON_EXTCFSEL;
			CLK2CONbits.EXTCFEN = CLOCK_USER_CLK2CON_EXTCFEN;
			CLK2CONbits.RIS = CLOCK_USER_CLK2CON_RIS;
			CLK2CONbits.CLKRDY = CLOCK_USER_CLK2CON_CLKRDY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK2DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK2DIV = 
			( CLOCK_USER_CLK2DIV_FRACDIV << _CLK2DIV_FRACDIV_POSITION ) |
			( CLOCK_USER_CLK2DIV_INTDIV << _CLK2DIV_INTDIV_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK2DIVbits.FRACDIV = CLOCK_USER_CLK2DIV_FRACDIV;
			CLK2DIVbits.INTDIV = CLOCK_USER_CLK2DIV_INTDIV;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK3CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK3CON = 
			( CLOCK_USER_CLK3CON_COSC << _CLK3CON_COSC_POSITION ) |
			( CLOCK_USER_CLK3CON_SLEEPDLY << _CLK3CON_SLEEPDLY_POSITION ) |
			( CLOCK_USER_CLK3CON_NOSC << _CLK3CON_NOSC_POSITION ) |
			( CLOCK_USER_CLK3CON_OE << _CLK3CON_OE_POSITION ) |
			( CLOCK_USER_CLK3CON_SIDL << _CLK3CON_SIDL_POSITION ) |
			( CLOCK_USER_CLK3CON_ON << _CLK3CON_ON_POSITION ) |
			( CLOCK_USER_CLK3CON_BOSC << _CLK3CON_BOSC_POSITION ) |
			( CLOCK_USER_CLK3CON_FSCMEN << _CLK3CON_FSCMEN_POSITION ) |
			( CLOCK_USER_CLK3CON_DIVSWEN << _CLK3CON_DIVSWEN_POSITION ) |
			( CLOCK_USER_CLK3CON_OSWEN << _CLK3CON_OSWEN_POSITION ) |
			( CLOCK_USER_CLK3CON_EXTCFSEL << _CLK3CON_EXTCFSEL_POSITION ) |
			( CLOCK_USER_CLK3CON_EXTCFEN << _CLK3CON_EXTCFEN_POSITION ) |
			( CLOCK_USER_CLK3CON_RIS << _CLK3CON_RIS_POSITION ) |
			( CLOCK_USER_CLK3CON_CLKRDY << _CLK3CON_CLKRDY_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK3CONbits.COSC = CLOCK_USER_CLK3CON_COSC;
			CLK3CONbits.SLEEPDLY = CLOCK_USER_CLK3CON_SLEEPDLY;
			CLK3CONbits.NOSC = CLOCK_USER_CLK3CON_NOSC;
			CLK3CONbits.OE = CLOCK_USER_CLK3CON_OE;
			CLK3CONbits.SIDL = CLOCK_USER_CLK3CON_SIDL;
			CLK3CONbits.ON = CLOCK_USER_CLK3CON_ON;
			CLK3CONbits.BOSC = CLOCK_USER_CLK3CON_BOSC;
			CLK3CONbits.FSCMEN = CLOCK_USER_CLK3CON_FSCMEN;
			CLK3CONbits.DIVSWEN = CLOCK_USER_CLK3CON_DIVSWEN;
			CLK3CONbits.OSWEN = CLOCK_USER_CLK3CON_OSWEN;
			CLK3CONbits.EXTCFSEL = CLOCK_USER_CLK3CON_EXTCFSEL;
			CLK3CONbits.EXTCFEN = CLOCK_USER_CLK3CON_EXTCFEN;
			CLK3CONbits.RIS = CLOCK_USER_CLK3CON_RIS;
			CLK3CONbits.CLKRDY = CLOCK_USER_CLK3CON_CLKRDY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK3DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK3DIV = 
			( CLOCK_USER_CLK3DIV_FRACDIV << _CLK3DIV_FRACDIV_POSITION ) |
			( CLOCK_USER_CLK3DIV_INTDIV << _CLK3DIV_INTDIV_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK3DIVbits.FRACDIV = CLOCK_USER_CLK3DIV_FRACDIV;
			CLK3DIVbits.INTDIV = CLOCK_USER_CLK3DIV_INTDIV;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK4CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK4CON = 
			( CLOCK_USER_CLK4CON_COSC << _CLK4CON_COSC_POSITION ) |
			( CLOCK_USER_CLK4CON_SLEEPDLY << _CLK4CON_SLEEPDLY_POSITION ) |
			( CLOCK_USER_CLK4CON_NOSC << _CLK4CON_NOSC_POSITION ) |
			( CLOCK_USER_CLK4CON_OE << _CLK4CON_OE_POSITION ) |
			( CLOCK_USER_CLK4CON_SIDL << _CLK4CON_SIDL_POSITION ) |
			( CLOCK_USER_CLK4CON_ON << _CLK4CON_ON_POSITION ) |
			( CLOCK_USER_CLK4CON_BOSC << _CLK4CON_BOSC_POSITION ) |
			( CLOCK_USER_CLK4CON_FSCMEN << _CLK4CON_FSCMEN_POSITION ) |
			( CLOCK_USER_CLK4CON_DIVSWEN << _CLK4CON_DIVSWEN_POSITION ) |
			( CLOCK_USER_CLK4CON_OSWEN << _CLK4CON_OSWEN_POSITION ) |
			( CLOCK_USER_CLK4CON_EXTCFSEL << _CLK4CON_EXTCFSEL_POSITION ) |
			( CLOCK_USER_CLK4CON_EXTCFEN << _CLK4CON_EXTCFEN_POSITION ) |
			( CLOCK_USER_CLK4CON_RIS << _CLK4CON_RIS_POSITION ) |
			( CLOCK_USER_CLK4CON_CLKRDY << _CLK4CON_CLKRDY_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK4CONbits.COSC = CLOCK_USER_CLK4CON_COSC;
			CLK4CONbits.SLEEPDLY = CLOCK_USER_CLK4CON_SLEEPDLY;
			CLK4CONbits.NOSC = CLOCK_USER_CLK4CON_NOSC;
			CLK4CONbits.OE = CLOCK_USER_CLK4CON_OE;
			CLK4CONbits.SIDL = CLOCK_USER_CLK4CON_SIDL;
			CLK4CONbits.ON = CLOCK_USER_CLK4CON_ON;
			CLK4CONbits.BOSC = CLOCK_USER_CLK4CON_BOSC;
			CLK4CONbits.FSCMEN = CLOCK_USER_CLK4CON_FSCMEN;
			CLK4CONbits.DIVSWEN = CLOCK_USER_CLK4CON_DIVSWEN;
			CLK4CONbits.OSWEN = CLOCK_USER_CLK4CON_OSWEN;
			CLK4CONbits.EXTCFSEL = CLOCK_USER_CLK4CON_EXTCFSEL;
			CLK4CONbits.EXTCFEN = CLOCK_USER_CLK4CON_EXTCFEN;
			CLK4CONbits.RIS = CLOCK_USER_CLK4CON_RIS;
			CLK4CONbits.CLKRDY = CLOCK_USER_CLK4CON_CLKRDY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK4DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK4DIV = 
			( CLOCK_USER_CLK4DIV_FRACDIV << _CLK4DIV_FRACDIV_POSITION ) |
			( CLOCK_USER_CLK4DIV_INTDIV << _CLK4DIV_INTDIV_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK4DIVbits.FRACDIV = CLOCK_USER_CLK4DIV_FRACDIV;
			CLK4DIVbits.INTDIV = CLOCK_USER_CLK4DIV_INTDIV;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK5CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK5CON = 
			( CLOCK_USER_CLK5CON_COSC << _CLK5CON_COSC_POSITION ) |
			( CLOCK_USER_CLK5CON_SLEEPDLY << _CLK5CON_SLEEPDLY_POSITION ) |
			( CLOCK_USER_CLK5CON_NOSC << _CLK5CON_NOSC_POSITION ) |
			( CLOCK_USER_CLK5CON_OE << _CLK5CON_OE_POSITION ) |
			( CLOCK_USER_CLK5CON_SIDL << _CLK5CON_SIDL_POSITION ) |
			( CLOCK_USER_CLK5CON_ON << _CLK5CON_ON_POSITION ) |
			( CLOCK_USER_CLK5CON_BOSC << _CLK5CON_BOSC_POSITION ) |
			( CLOCK_USER_CLK5CON_FSCMEN << _CLK5CON_FSCMEN_POSITION ) |
			( CLOCK_USER_CLK5CON_DIVSWEN << _CLK5CON_DIVSWEN_POSITION ) |
			( CLOCK_USER_CLK5CON_OSWEN << _CLK5CON_OSWEN_POSITION ) |
			( CLOCK_USER_CLK5CON_EXTCFSEL << _CLK5CON_EXTCFSEL_POSITION ) |
			( CLOCK_USER_CLK5CON_EXTCFEN << _CLK5CON_EXTCFEN_POSITION ) |
			( CLOCK_USER_CLK5CON_RIS << _CLK5CON_RIS_POSITION ) |
			( CLOCK_USER_CLK5CON_CLKRDY << _CLK5CON_CLKRDY_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK5CONbits.COSC = CLOCK_USER_CLK5CON_COSC;
			CLK5CONbits.SLEEPDLY = CLOCK_USER_CLK5CON_SLEEPDLY;
			CLK5CONbits.NOSC = CLOCK_USER_CLK5CON_NOSC;
			CLK5CONbits.OE = CLOCK_USER_CLK5CON_OE;
			CLK5CONbits.SIDL = CLOCK_USER_CLK5CON_SIDL;
			CLK5CONbits.ON = CLOCK_USER_CLK5CON_ON;
			CLK5CONbits.BOSC = CLOCK_USER_CLK5CON_BOSC;
			CLK5CONbits.FSCMEN = CLOCK_USER_CLK5CON_FSCMEN;
			CLK5CONbits.DIVSWEN = CLOCK_USER_CLK5CON_DIVSWEN;
			CLK5CONbits.OSWEN = CLOCK_USER_CLK5CON_OSWEN;
			CLK5CONbits.EXTCFSEL = CLOCK_USER_CLK5CON_EXTCFSEL;
			CLK5CONbits.EXTCFEN = CLOCK_USER_CLK5CON_EXTCFEN;
			CLK5CONbits.RIS = CLOCK_USER_CLK5CON_RIS;
			CLK5CONbits.CLKRDY = CLOCK_USER_CLK5CON_CLKRDY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK5DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK5DIV = 
			( CLOCK_USER_CLK5DIV_FRACDIV << _CLK5DIV_FRACDIV_POSITION ) |
			( CLOCK_USER_CLK5DIV_INTDIV << _CLK5DIV_INTDIV_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK5DIVbits.FRACDIV = CLOCK_USER_CLK5DIV_FRACDIV;
			CLK5DIVbits.INTDIV = CLOCK_USER_CLK5DIV_INTDIV;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK6CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK6CON = 
			( CLOCK_USER_CLK6CON_COSC << _CLK6CON_COSC_POSITION ) |
			( CLOCK_USER_CLK6CON_SLEEPDLY << _CLK6CON_SLEEPDLY_POSITION ) |
			( CLOCK_USER_CLK6CON_NOSC << _CLK6CON_NOSC_POSITION ) |
			( CLOCK_USER_CLK6CON_OE << _CLK6CON_OE_POSITION ) |
			( CLOCK_USER_CLK6CON_SIDL << _CLK6CON_SIDL_POSITION ) |
			( CLOCK_USER_CLK6CON_ON << _CLK6CON_ON_POSITION ) |
			( CLOCK_USER_CLK6CON_BOSC << _CLK6CON_BOSC_POSITION ) |
			( CLOCK_USER_CLK6CON_FSCMEN << _CLK6CON_FSCMEN_POSITION ) |
			( CLOCK_USER_CLK6CON_DIVSWEN << _CLK6CON_DIVSWEN_POSITION ) |
			( CLOCK_USER_CLK6CON_OSWEN << _CLK6CON_OSWEN_POSITION ) |
			( CLOCK_USER_CLK6CON_EXTCFSEL << _CLK6CON_EXTCFSEL_POSITION ) |
			( CLOCK_USER_CLK6CON_EXTCFEN << _CLK6CON_EXTCFEN_POSITION ) |
			( CLOCK_USER_CLK6CON_RIS << _CLK6CON_RIS_POSITION ) |
			( CLOCK_USER_CLK6CON_CLKRDY << _CLK6CON_CLKRDY_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK6CONbits.COSC = CLOCK_USER_CLK6CON_COSC;
			CLK6CONbits.SLEEPDLY = CLOCK_USER_CLK6CON_SLEEPDLY;
			CLK6CONbits.NOSC = CLOCK_USER_CLK6CON_NOSC;
			CLK6CONbits.OE = CLOCK_USER_CLK6CON_OE;
			CLK6CONbits.SIDL = CLOCK_USER_CLK6CON_SIDL;
			CLK6CONbits.ON = CLOCK_USER_CLK6CON_ON;
			CLK6CONbits.BOSC = CLOCK_USER_CLK6CON_BOSC;
			CLK6CONbits.FSCMEN = CLOCK_USER_CLK6CON_FSCMEN;
			CLK6CONbits.DIVSWEN = CLOCK_USER_CLK6CON_DIVSWEN;
			CLK6CONbits.OSWEN = CLOCK_USER_CLK6CON_OSWEN;
			CLK6CONbits.EXTCFSEL = CLOCK_USER_CLK6CON_EXTCFSEL;
			CLK6CONbits.EXTCFEN = CLOCK_USER_CLK6CON_EXTCFEN;
			CLK6CONbits.RIS = CLOCK_USER_CLK6CON_RIS;
			CLK6CONbits.CLKRDY = CLOCK_USER_CLK6CON_CLKRDY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK6DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK6DIV = 
			( CLOCK_USER_CLK6DIV_FRACDIV << _CLK6DIV_FRACDIV_POSITION ) |
			( CLOCK_USER_CLK6DIV_INTDIV << _CLK6DIV_INTDIV_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK6DIVbits.FRACDIV = CLOCK_USER_CLK6DIV_FRACDIV;
			CLK6DIVbits.INTDIV = CLOCK_USER_CLK6DIV_INTDIV;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK7CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK7CON = 
			( CLOCK_USER_CLK7CON_COSC << _CLK7CON_COSC_POSITION ) |
			( CLOCK_USER_CLK7CON_SLEEPDLY << _CLK7CON_SLEEPDLY_POSITION ) |
			( CLOCK_USER_CLK7CON_NOSC << _CLK7CON_NOSC_POSITION ) |
			( CLOCK_USER_CLK7CON_OE << _CLK7CON_OE_POSITION ) |
			( CLOCK_USER_CLK7CON_SIDL << _CLK7CON_SIDL_POSITION ) |
			( CLOCK_USER_CLK7CON_ON << _CLK7CON_ON_POSITION ) |
			( CLOCK_USER_CLK7CON_BOSC << _CLK7CON_BOSC_POSITION ) |
			( CLOCK_USER_CLK7CON_FSCMEN << _CLK7CON_FSCMEN_POSITION ) |
			( CLOCK_USER_CLK7CON_DIVSWEN << _CLK7CON_DIVSWEN_POSITION ) |
			( CLOCK_USER_CLK7CON_OSWEN << _CLK7CON_OSWEN_POSITION ) |
			( CLOCK_USER_CLK7CON_EXTCFSEL << _CLK7CON_EXTCFSEL_POSITION ) |
			( CLOCK_USER_CLK7CON_EXTCFEN << _CLK7CON_EXTCFEN_POSITION ) |
			( CLOCK_USER_CLK7CON_RIS << _CLK7CON_RIS_POSITION ) |
			( CLOCK_USER_CLK7CON_CLKRDY << _CLK7CON_CLKRDY_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK7CONbits.COSC = CLOCK_USER_CLK7CON_COSC;
			CLK7CONbits.SLEEPDLY = CLOCK_USER_CLK7CON_SLEEPDLY;
			CLK7CONbits.NOSC = CLOCK_USER_CLK7CON_NOSC;
			CLK7CONbits.OE = CLOCK_USER_CLK7CON_OE;
			CLK7CONbits.SIDL = CLOCK_USER_CLK7CON_SIDL;
			CLK7CONbits.ON = CLOCK_USER_CLK7CON_ON;
			CLK7CONbits.BOSC = CLOCK_USER_CLK7CON_BOSC;
			CLK7CONbits.FSCMEN = CLOCK_USER_CLK7CON_FSCMEN;
			CLK7CONbits.DIVSWEN = CLOCK_USER_CLK7CON_DIVSWEN;
			CLK7CONbits.OSWEN = CLOCK_USER_CLK7CON_OSWEN;
			CLK7CONbits.EXTCFSEL = CLOCK_USER_CLK7CON_EXTCFSEL;
			CLK7CONbits.EXTCFEN = CLOCK_USER_CLK7CON_EXTCFEN;
			CLK7CONbits.RIS = CLOCK_USER_CLK7CON_RIS;
			CLK7CONbits.CLKRDY = CLOCK_USER_CLK7CON_CLKRDY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK7DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK7DIV = 
			( CLOCK_USER_CLK7DIV_FRACDIV << _CLK7DIV_FRACDIV_POSITION ) |
			( CLOCK_USER_CLK7DIV_INTDIV << _CLK7DIV_INTDIV_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK7DIVbits.FRACDIV = CLOCK_USER_CLK7DIV_FRACDIV;
			CLK7DIVbits.INTDIV = CLOCK_USER_CLK7DIV_INTDIV;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK8CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK8CON = 
			( CLOCK_USER_CLK8CON_COSC << _CLK8CON_COSC_POSITION ) |
			( CLOCK_USER_CLK8CON_SLEEPDLY << _CLK8CON_SLEEPDLY_POSITION ) |
			( CLOCK_USER_CLK8CON_NOSC << _CLK8CON_NOSC_POSITION ) |
			( CLOCK_USER_CLK8CON_OE << _CLK8CON_OE_POSITION ) |
			( CLOCK_USER_CLK8CON_SIDL << _CLK8CON_SIDL_POSITION ) |
			( CLOCK_USER_CLK8CON_ON << _CLK8CON_ON_POSITION ) |
			( CLOCK_USER_CLK8CON_BOSC << _CLK8CON_BOSC_POSITION ) |
			( CLOCK_USER_CLK8CON_FSCMEN << _CLK8CON_FSCMEN_POSITION ) |
			( CLOCK_USER_CLK8CON_DIVSWEN << _CLK8CON_DIVSWEN_POSITION ) |
			( CLOCK_USER_CLK8CON_OSWEN << _CLK8CON_OSWEN_POSITION ) |
			( CLOCK_USER_CLK8CON_EXTCFSEL << _CLK8CON_EXTCFSEL_POSITION ) |
			( CLOCK_USER_CLK8CON_EXTCFEN << _CLK8CON_EXTCFEN_POSITION ) |
			( CLOCK_USER_CLK8CON_RIS << _CLK8CON_RIS_POSITION ) |
			( CLOCK_USER_CLK8CON_CLKRDY << _CLK8CON_CLKRDY_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK8CONbits.COSC = CLOCK_USER_CLK8CON_COSC;
			CLK8CONbits.SLEEPDLY = CLOCK_USER_CLK8CON_SLEEPDLY;
			CLK8CONbits.NOSC = CLOCK_USER_CLK8CON_NOSC;
			CLK8CONbits.OE = CLOCK_USER_CLK8CON_OE;
			CLK8CONbits.SIDL = CLOCK_USER_CLK8CON_SIDL;
			CLK8CONbits.ON = CLOCK_USER_CLK8CON_ON;
			CLK8CONbits.BOSC = CLOCK_USER_CLK8CON_BOSC;
			CLK8CONbits.FSCMEN = CLOCK_USER_CLK8CON_FSCMEN;
			CLK8CONbits.DIVSWEN = CLOCK_USER_CLK8CON_DIVSWEN;
			CLK8CONbits.OSWEN = CLOCK_USER_CLK8CON_OSWEN;
			CLK8CONbits.EXTCFSEL = CLOCK_USER_CLK8CON_EXTCFSEL;
			CLK8CONbits.EXTCFEN = CLOCK_USER_CLK8CON_EXTCFEN;
			CLK8CONbits.RIS = CLOCK_USER_CLK8CON_RIS;
			CLK8CONbits.CLKRDY = CLOCK_USER_CLK8CON_CLKRDY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK8DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK8DIV = 
			( CLOCK_USER_CLK8DIV_FRACDIV << _CLK8DIV_FRACDIV_POSITION ) |
			( CLOCK_USER_CLK8DIV_INTDIV << _CLK8DIV_INTDIV_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK8DIVbits.FRACDIV = CLOCK_USER_CLK8DIV_FRACDIV;
			CLK8DIVbits.INTDIV = CLOCK_USER_CLK8DIV_INTDIV;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK9CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK9CON = 
			( CLOCK_USER_CLK9CON_COSC << _CLK9CON_COSC_POSITION ) |
			( CLOCK_USER_CLK9CON_SLEEPDLY << _CLK9CON_SLEEPDLY_POSITION ) |
			( CLOCK_USER_CLK9CON_NOSC << _CLK9CON_NOSC_POSITION ) |
			( CLOCK_USER_CLK9CON_OE << _CLK9CON_OE_POSITION ) |
			( CLOCK_USER_CLK9CON_SIDL << _CLK9CON_SIDL_POSITION ) |
			( CLOCK_USER_CLK9CON_ON << _CLK9CON_ON_POSITION ) |
			( CLOCK_USER_CLK9CON_BOSC << _CLK9CON_BOSC_POSITION ) |
			( CLOCK_USER_CLK9CON_FSCMEN << _CLK9CON_FSCMEN_POSITION ) |
			( CLOCK_USER_CLK9CON_DIVSWEN << _CLK9CON_DIVSWEN_POSITION ) |
			( CLOCK_USER_CLK9CON_OSWEN << _CLK9CON_OSWEN_POSITION ) |
			( CLOCK_USER_CLK9CON_EXTCFSEL << _CLK9CON_EXTCFSEL_POSITION ) |
			( CLOCK_USER_CLK9CON_EXTCFEN << _CLK9CON_EXTCFEN_POSITION ) |
			( CLOCK_USER_CLK9CON_RIS << _CLK9CON_RIS_POSITION ) |
			( CLOCK_USER_CLK9CON_CLKRDY << _CLK9CON_CLKRDY_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK9CONbits.COSC = CLOCK_USER_CLK9CON_COSC;
			CLK9CONbits.SLEEPDLY = CLOCK_USER_CLK9CON_SLEEPDLY;
			CLK9CONbits.NOSC = CLOCK_USER_CLK9CON_NOSC;
			CLK9CONbits.OE = CLOCK_USER_CLK9CON_OE;
			CLK9CONbits.SIDL = CLOCK_USER_CLK9CON_SIDL;
			CLK9CONbits.ON = CLOCK_USER_CLK9CON_ON;
			CLK9CONbits.BOSC = CLOCK_USER_CLK9CON_BOSC;
			CLK9CONbits.FSCMEN = CLOCK_USER_CLK9CON_FSCMEN;
			CLK9CONbits.DIVSWEN = CLOCK_USER_CLK9CON_DIVSWEN;
			CLK9CONbits.OSWEN = CLOCK_USER_CLK9CON_OSWEN;
			CLK9CONbits.EXTCFSEL = CLOCK_USER_CLK9CON_EXTCFSEL;
			CLK9CONbits.EXTCFEN = CLOCK_USER_CLK9CON_EXTCFEN;
			CLK9CONbits.RIS = CLOCK_USER_CLK9CON_RIS;
			CLK9CONbits.CLKRDY = CLOCK_USER_CLK9CON_CLKRDY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK9DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK9DIV = 
			( CLOCK_USER_CLK9DIV_FRACDIV << _CLK9DIV_FRACDIV_POSITION ) |
			( CLOCK_USER_CLK9DIV_INTDIV << _CLK9DIV_INTDIV_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK9DIVbits.FRACDIV = CLOCK_USER_CLK9DIV_FRACDIV;
			CLK9DIVbits.INTDIV = CLOCK_USER_CLK9DIV_INTDIV;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK10CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK10CON = 
			( CLOCK_USER_CLK10CON_COSC << _CLK10CON_COSC_POSITION ) |
			( CLOCK_USER_CLK10CON_SLEEPDLY << _CLK10CON_SLEEPDLY_POSITION ) |
			( CLOCK_USER_CLK10CON_NOSC << _CLK10CON_NOSC_POSITION ) |
			( CLOCK_USER_CLK10CON_OE << _CLK10CON_OE_POSITION ) |
			( CLOCK_USER_CLK10CON_SIDL << _CLK10CON_SIDL_POSITION ) |
			( CLOCK_USER_CLK10CON_ON << _CLK10CON_ON_POSITION ) |
			( CLOCK_USER_CLK10CON_BOSC << _CLK10CON_BOSC_POSITION ) |
			( CLOCK_USER_CLK10CON_FSCMEN << _CLK10CON_FSCMEN_POSITION ) |
			( CLOCK_USER_CLK10CON_DIVSWEN << _CLK10CON_DIVSWEN_POSITION ) |
			( CLOCK_USER_CLK10CON_OSWEN << _CLK10CON_OSWEN_POSITION ) |
			( CLOCK_USER_CLK10CON_EXTCFSEL << _CLK10CON_EXTCFSEL_POSITION ) |
			( CLOCK_USER_CLK10CON_EXTCFEN << _CLK10CON_EXTCFEN_POSITION ) |
			( CLOCK_USER_CLK10CON_RIS << _CLK10CON_RIS_POSITION ) |
			( CLOCK_USER_CLK10CON_CLKRDY << _CLK10CON_CLKRDY_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK10CONbits.COSC = CLOCK_USER_CLK10CON_COSC;
			CLK10CONbits.SLEEPDLY = CLOCK_USER_CLK10CON_SLEEPDLY;
			CLK10CONbits.NOSC = CLOCK_USER_CLK10CON_NOSC;
			CLK10CONbits.OE = CLOCK_USER_CLK10CON_OE;
			CLK10CONbits.SIDL = CLOCK_USER_CLK10CON_SIDL;
			CLK10CONbits.ON = CLOCK_USER_CLK10CON_ON;
			CLK10CONbits.BOSC = CLOCK_USER_CLK10CON_BOSC;
			CLK10CONbits.FSCMEN = CLOCK_USER_CLK10CON_FSCMEN;
			CLK10CONbits.DIVSWEN = CLOCK_USER_CLK10CON_DIVSWEN;
			CLK10CONbits.OSWEN = CLOCK_USER_CLK10CON_OSWEN;
			CLK10CONbits.EXTCFSEL = CLOCK_USER_CLK10CON_EXTCFSEL;
			CLK10CONbits.EXTCFEN = CLOCK_USER_CLK10CON_EXTCFEN;
			CLK10CONbits.RIS = CLOCK_USER_CLK10CON_RIS;
			CLK10CONbits.CLKRDY = CLOCK_USER_CLK10CON_CLKRDY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK10DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK10DIV = 
			( CLOCK_USER_CLK10DIV_FRACDIV << _CLK10DIV_FRACDIV_POSITION ) |
			( CLOCK_USER_CLK10DIV_INTDIV << _CLK10DIV_INTDIV_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK10DIVbits.FRACDIV = CLOCK_USER_CLK10DIV_FRACDIV;
			CLK10DIVbits.INTDIV = CLOCK_USER_CLK10DIV_INTDIV;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK11CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK11CON = 
			( CLOCK_USER_CLK11CON_COSC << _CLK11CON_COSC_POSITION ) |
			( CLOCK_USER_CLK11CON_SLEEPDLY << _CLK11CON_SLEEPDLY_POSITION ) |
			( CLOCK_USER_CLK11CON_NOSC << _CLK11CON_NOSC_POSITION ) |
			( CLOCK_USER_CLK11CON_OE << _CLK11CON_OE_POSITION ) |
			( CLOCK_USER_CLK11CON_SIDL << _CLK11CON_SIDL_POSITION ) |
			( CLOCK_USER_CLK11CON_ON << _CLK11CON_ON_POSITION ) |
			( CLOCK_USER_CLK11CON_BOSC << _CLK11CON_BOSC_POSITION ) |
			( CLOCK_USER_CLK11CON_FSCMEN << _CLK11CON_FSCMEN_POSITION ) |
			( CLOCK_USER_CLK11CON_DIVSWEN << _CLK11CON_DIVSWEN_POSITION ) |
			( CLOCK_USER_CLK11CON_OSWEN << _CLK11CON_OSWEN_POSITION ) |
			( CLOCK_USER_CLK11CON_EXTCFSEL << _CLK11CON_EXTCFSEL_POSITION ) |
			( CLOCK_USER_CLK11CON_EXTCFEN << _CLK11CON_EXTCFEN_POSITION ) |
			( CLOCK_USER_CLK11CON_RIS << _CLK11CON_RIS_POSITION ) |
			( CLOCK_USER_CLK11CON_CLKRDY << _CLK11CON_CLKRDY_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK11CONbits.COSC = CLOCK_USER_CLK11CON_COSC;
			CLK11CONbits.SLEEPDLY = CLOCK_USER_CLK11CON_SLEEPDLY;
			CLK11CONbits.NOSC = CLOCK_USER_CLK11CON_NOSC;
			CLK11CONbits.OE = CLOCK_USER_CLK11CON_OE;
			CLK11CONbits.SIDL = CLOCK_USER_CLK11CON_SIDL;
			CLK11CONbits.ON = CLOCK_USER_CLK11CON_ON;
			CLK11CONbits.BOSC = CLOCK_USER_CLK11CON_BOSC;
			CLK11CONbits.FSCMEN = CLOCK_USER_CLK11CON_FSCMEN;
			CLK11CONbits.DIVSWEN = CLOCK_USER_CLK11CON_DIVSWEN;
			CLK11CONbits.OSWEN = CLOCK_USER_CLK11CON_OSWEN;
			CLK11CONbits.EXTCFSEL = CLOCK_USER_CLK11CON_EXTCFSEL;
			CLK11CONbits.EXTCFEN = CLOCK_USER_CLK11CON_EXTCFEN;
			CLK11CONbits.RIS = CLOCK_USER_CLK11CON_RIS;
			CLK11CONbits.CLKRDY = CLOCK_USER_CLK11CON_CLKRDY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK11DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK11DIV = 
			( CLOCK_USER_CLK11DIV_FRACDIV << _CLK11DIV_FRACDIV_POSITION ) |
			( CLOCK_USER_CLK11DIV_INTDIV << _CLK11DIV_INTDIV_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK11DIVbits.FRACDIV = CLOCK_USER_CLK11DIV_FRACDIV;
			CLK11DIVbits.INTDIV = CLOCK_USER_CLK11DIV_INTDIV;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK12CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK12CON = 
			( CLOCK_USER_CLK12CON_COSC << _CLK12CON_COSC_POSITION ) |
			( CLOCK_USER_CLK12CON_SLEEPDLY << _CLK12CON_SLEEPDLY_POSITION ) |
			( CLOCK_USER_CLK12CON_NOSC << _CLK12CON_NOSC_POSITION ) |
			( CLOCK_USER_CLK12CON_OE << _CLK12CON_OE_POSITION ) |
			( CLOCK_USER_CLK12CON_SIDL << _CLK12CON_SIDL_POSITION ) |
			( CLOCK_USER_CLK12CON_ON << _CLK12CON_ON_POSITION ) |
			( CLOCK_USER_CLK12CON_BOSC << _CLK12CON_BOSC_POSITION ) |
			( CLOCK_USER_CLK12CON_FSCMEN << _CLK12CON_FSCMEN_POSITION ) |
			( CLOCK_USER_CLK12CON_DIVSWEN << _CLK12CON_DIVSWEN_POSITION ) |
			( CLOCK_USER_CLK12CON_OSWEN << _CLK12CON_OSWEN_POSITION ) |
			( CLOCK_USER_CLK12CON_EXTCFSEL << _CLK12CON_EXTCFSEL_POSITION ) |
			( CLOCK_USER_CLK12CON_EXTCFEN << _CLK12CON_EXTCFEN_POSITION ) |
			( CLOCK_USER_CLK12CON_RIS << _CLK12CON_RIS_POSITION ) |
			( CLOCK_USER_CLK12CON_CLKRDY << _CLK12CON_CLKRDY_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK12CONbits.COSC = CLOCK_USER_CLK12CON_COSC;
			CLK12CONbits.SLEEPDLY = CLOCK_USER_CLK12CON_SLEEPDLY;
			CLK12CONbits.NOSC = CLOCK_USER_CLK12CON_NOSC;
			CLK12CONbits.OE = CLOCK_USER_CLK12CON_OE;
			CLK12CONbits.SIDL = CLOCK_USER_CLK12CON_SIDL;
			CLK12CONbits.ON = CLOCK_USER_CLK12CON_ON;
			CLK12CONbits.BOSC = CLOCK_USER_CLK12CON_BOSC;
			CLK12CONbits.FSCMEN = CLOCK_USER_CLK12CON_FSCMEN;
			CLK12CONbits.DIVSWEN = CLOCK_USER_CLK12CON_DIVSWEN;
			CLK12CONbits.OSWEN = CLOCK_USER_CLK12CON_OSWEN;
			CLK12CONbits.EXTCFSEL = CLOCK_USER_CLK12CON_EXTCFSEL;
			CLK12CONbits.EXTCFEN = CLOCK_USER_CLK12CON_EXTCFEN;
			CLK12CONbits.RIS = CLOCK_USER_CLK12CON_RIS;
			CLK12CONbits.CLKRDY = CLOCK_USER_CLK12CON_CLKRDY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK12DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK12DIV = 
			( CLOCK_USER_CLK12DIV_FRACDIV << _CLK12DIV_FRACDIV_POSITION ) |
			( CLOCK_USER_CLK12DIV_INTDIV << _CLK12DIV_INTDIV_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK12DIVbits.FRACDIV = CLOCK_USER_CLK12DIV_FRACDIV;
			CLK12DIVbits.INTDIV = CLOCK_USER_CLK12DIV_INTDIV;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK13CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK13CON = 
			( CLOCK_USER_CLK13CON_COSC << _CLK13CON_COSC_POSITION ) |
			( CLOCK_USER_CLK13CON_SLEEPDLY << _CLK13CON_SLEEPDLY_POSITION ) |
			( CLOCK_USER_CLK13CON_NOSC << _CLK13CON_NOSC_POSITION ) |
			( CLOCK_USER_CLK13CON_OE << _CLK13CON_OE_POSITION ) |
			( CLOCK_USER_CLK13CON_SIDL << _CLK13CON_SIDL_POSITION ) |
			( CLOCK_USER_CLK13CON_ON << _CLK13CON_ON_POSITION ) |
			( CLOCK_USER_CLK13CON_BOSC << _CLK13CON_BOSC_POSITION ) |
			( CLOCK_USER_CLK13CON_FSCMEN << _CLK13CON_FSCMEN_POSITION ) |
			( CLOCK_USER_CLK13CON_DIVSWEN << _CLK13CON_DIVSWEN_POSITION ) |
			( CLOCK_USER_CLK13CON_OSWEN << _CLK13CON_OSWEN_POSITION ) |
			( CLOCK_USER_CLK13CON_EXTCFSEL << _CLK13CON_EXTCFSEL_POSITION ) |
			( CLOCK_USER_CLK13CON_EXTCFEN << _CLK13CON_EXTCFEN_POSITION ) |
			( CLOCK_USER_CLK13CON_RIS << _CLK13CON_RIS_POSITION ) |
			( CLOCK_USER_CLK13CON_CLKRDY << _CLK13CON_CLKRDY_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK13CONbits.COSC = CLOCK_USER_CLK13CON_COSC;
			CLK13CONbits.SLEEPDLY = CLOCK_USER_CLK13CON_SLEEPDLY;
			CLK13CONbits.NOSC = CLOCK_USER_CLK13CON_NOSC;
			CLK13CONbits.OE = CLOCK_USER_CLK13CON_OE;
			CLK13CONbits.SIDL = CLOCK_USER_CLK13CON_SIDL;
			CLK13CONbits.ON = CLOCK_USER_CLK13CON_ON;
			CLK13CONbits.BOSC = CLOCK_USER_CLK13CON_BOSC;
			CLK13CONbits.FSCMEN = CLOCK_USER_CLK13CON_FSCMEN;
			CLK13CONbits.DIVSWEN = CLOCK_USER_CLK13CON_DIVSWEN;
			CLK13CONbits.OSWEN = CLOCK_USER_CLK13CON_OSWEN;
			CLK13CONbits.EXTCFSEL = CLOCK_USER_CLK13CON_EXTCFSEL;
			CLK13CONbits.EXTCFEN = CLOCK_USER_CLK13CON_EXTCFEN;
			CLK13CONbits.RIS = CLOCK_USER_CLK13CON_RIS;
			CLK13CONbits.CLKRDY = CLOCK_USER_CLK13CON_CLKRDY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK13DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK13DIV = 
			( CLOCK_USER_CLK13DIV_FRACDIV << _CLK13DIV_FRACDIV_POSITION ) |
			( CLOCK_USER_CLK13DIV_INTDIV << _CLK13DIV_INTDIV_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK13DIVbits.FRACDIV = CLOCK_USER_CLK13DIV_FRACDIV;
			CLK13DIVbits.INTDIV = CLOCK_USER_CLK13DIV_INTDIV;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK14CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK14CON = 
			( CLOCK_USER_CLK14CON_COSC << _CLK14CON_COSC_POSITION ) |
			( CLOCK_USER_CLK14CON_SLEEPDLY << _CLK14CON_SLEEPDLY_POSITION ) |
			( CLOCK_USER_CLK14CON_NOSC << _CLK14CON_NOSC_POSITION ) |
			( CLOCK_USER_CLK14CON_OE << _CLK14CON_OE_POSITION ) |
			( CLOCK_USER_CLK14CON_SIDL << _CLK14CON_SIDL_POSITION ) |
			( CLOCK_USER_CLK14CON_ON << _CLK14CON_ON_POSITION ) |
			( CLOCK_USER_CLK14CON_BOSC << _CLK14CON_BOSC_POSITION ) |
			( CLOCK_USER_CLK14CON_FSCMEN << _CLK14CON_FSCMEN_POSITION ) |
			( CLOCK_USER_CLK14CON_DIVSWEN << _CLK14CON_DIVSWEN_POSITION ) |
			( CLOCK_USER_CLK14CON_OSWEN << _CLK14CON_OSWEN_POSITION ) |
			( CLOCK_USER_CLK14CON_EXTCFSEL << _CLK14CON_EXTCFSEL_POSITION ) |
			( CLOCK_USER_CLK14CON_EXTCFEN << _CLK14CON_EXTCFEN_POSITION ) |
			( CLOCK_USER_CLK14CON_RIS << _CLK14CON_RIS_POSITION ) |
			( CLOCK_USER_CLK14CON_CLKRDY << _CLK14CON_CLKRDY_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK14CONbits.COSC = CLOCK_USER_CLK14CON_COSC;
			CLK14CONbits.SLEEPDLY = CLOCK_USER_CLK14CON_SLEEPDLY;
			CLK14CONbits.NOSC = CLOCK_USER_CLK14CON_NOSC;
			CLK14CONbits.OE = CLOCK_USER_CLK14CON_OE;
			CLK14CONbits.SIDL = CLOCK_USER_CLK14CON_SIDL;
			CLK14CONbits.ON = CLOCK_USER_CLK14CON_ON;
			CLK14CONbits.BOSC = CLOCK_USER_CLK14CON_BOSC;
			CLK14CONbits.FSCMEN = CLOCK_USER_CLK14CON_FSCMEN;
			CLK14CONbits.DIVSWEN = CLOCK_USER_CLK14CON_DIVSWEN;
			CLK14CONbits.OSWEN = CLOCK_USER_CLK14CON_OSWEN;
			CLK14CONbits.EXTCFSEL = CLOCK_USER_CLK14CON_EXTCFSEL;
			CLK14CONbits.EXTCFEN = CLOCK_USER_CLK14CON_EXTCFEN;
			CLK14CONbits.RIS = CLOCK_USER_CLK14CON_RIS;
			CLK14CONbits.CLKRDY = CLOCK_USER_CLK14CON_CLKRDY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CLK14DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		CLK14DIV = 
			( CLOCK_USER_CLK14DIV_FRACDIV << _CLK14DIV_FRACDIV_POSITION ) |
			( CLOCK_USER_CLK14DIV_INTDIV << _CLK14DIV_INTDIV_POSITION ) ;
		#ifdef DEF_BITNAME
			CLK14DIVbits.FRACDIV = CLOCK_USER_CLK14DIV_FRACDIV;
			CLK14DIVbits.INTDIV = CLOCK_USER_CLK14DIV_INTDIV;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PLL1CONレジスタ */
	/*-----------------------------------------------------------------------*/
		PLL1CON = 
			( CLOCK_USER_PLL1CON_COSC << _PLL1CON_COSC_POSITION ) |
			( CLOCK_USER_PLL1CON_NOSC << _PLL1CON_NOSC_POSITION ) |
			( CLOCK_USER_PLL1CON_OE << _PLL1CON_OE_POSITION ) |
			( CLOCK_USER_PLL1CON_SIDL << _PLL1CON_SIDL_POSITION ) |
			( CLOCK_USER_PLL1CON_ON << _PLL1CON_ON_POSITION ) |
			( CLOCK_USER_PLL1CON_BOSC << _PLL1CON_BOSC_POSITION ) |
			( CLOCK_USER_PLL1CON_FSCMEN << _PLL1CON_FSCMEN_POSITION ) |
			( CLOCK_USER_PLL1CON_DIVSWEN << _PLL1CON_DIVSWEN_POSITION ) |
			( CLOCK_USER_PLL1CON_OSWEN << _PLL1CON_OSWEN_POSITION ) |
			( CLOCK_USER_PLL1CON_EXTCFSEL << _PLL1CON_EXTCFSEL_POSITION ) |
			( CLOCK_USER_PLL1CON_EXTCFEN << _PLL1CON_EXTCFEN_POSITION ) |
			( CLOCK_USER_PLL1CON_FOUTSWEN << _PLL1CON_FOUTSWEN_POSITION ) |
			( CLOCK_USER_PLL1CON_RIS << _PLL1CON_RIS_POSITION ) |
			( CLOCK_USER_PLL1CON_PLLSWEN << _PLL1CON_PLLSWEN_POSITION ) |
			( CLOCK_USER_PLL1CON_CLKRDY << _PLL1CON_CLKRDY_POSITION ) ;
		#ifdef DEF_BITNAME
			PLL1CONbits.COSC = CLOCK_USER_PLL1CON_COSC;
			PLL1CONbits.NOSC = CLOCK_USER_PLL1CON_NOSC;
			PLL1CONbits.OE = CLOCK_USER_PLL1CON_OE;
			PLL1CONbits.SIDL = CLOCK_USER_PLL1CON_SIDL;
			PLL1CONbits.ON = CLOCK_USER_PLL1CON_ON;
			PLL1CONbits.BOSC = CLOCK_USER_PLL1CON_BOSC;
			PLL1CONbits.FSCMEN = CLOCK_USER_PLL1CON_FSCMEN;
			PLL1CONbits.DIVSWEN = CLOCK_USER_PLL1CON_DIVSWEN;
			PLL1CONbits.OSWEN = CLOCK_USER_PLL1CON_OSWEN;
			PLL1CONbits.EXTCFSEL = CLOCK_USER_PLL1CON_EXTCFSEL;
			PLL1CONbits.EXTCFEN = CLOCK_USER_PLL1CON_EXTCFEN;
			PLL1CONbits.FOUTSWEN = CLOCK_USER_PLL1CON_FOUTSWEN;
			PLL1CONbits.RIS = CLOCK_USER_PLL1CON_RIS;
			PLL1CONbits.PLLSWEN = CLOCK_USER_PLL1CON_PLLSWEN;
			PLL1CONbits.CLKRDY = CLOCK_USER_PLL1CON_CLKRDY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PLL1DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		PLL1DIV = 
			( CLOCK_USER_PLL1DIV_POSTDIV2 << _PLL1DIV_POSTDIV2_POSITION ) |
			( CLOCK_USER_PLL1DIV_POSTDIV1 << _PLL1DIV_POSTDIV1_POSITION ) |
			( CLOCK_USER_PLL1DIV_PLLFBDIV << _PLL1DIV_PLLFBDIV_POSITION ) |
			( CLOCK_USER_PLL1DIV_PLLPRE << _PLL1DIV_PLLPRE_POSITION ) ;
		#ifdef DEF_BITNAME
			PLL1DIVbits.POSTDIV2 = CLOCK_USER_PLL1DIV_POSTDIV2;
			PLL1DIVbits.POSTDIV1 = CLOCK_USER_PLL1DIV_POSTDIV1;
			PLL1DIVbits.PLLFBDIV = CLOCK_USER_PLL1DIV_PLLFBDIV;
			PLL1DIVbits.PLLPRE = CLOCK_USER_PLL1DIV_PLLPRE;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* VCO1DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		VCO1DIV = 
			( CLOCK_USER_VCO1DIV_INTDIV << _VCO1DIV_INTDIV_POSITION ) ;
		#ifdef DEF_BITNAME
			VCO1DIVbits.INTDIV = CLOCK_USER_VCO1DIV_INTDIV;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PLL2CONレジスタ */
	/*-----------------------------------------------------------------------*/
		PLL2CON = 
			( CLOCK_USER_PLL2CON_COSC << _PLL2CON_COSC_POSITION ) |
			( CLOCK_USER_PLL2CON_NOSC << _PLL2CON_NOSC_POSITION ) |
			( CLOCK_USER_PLL2CON_OE << _PLL2CON_OE_POSITION ) |
			( CLOCK_USER_PLL2CON_SIDL << _PLL2CON_SIDL_POSITION ) |
			( CLOCK_USER_PLL2CON_ON << _PLL2CON_ON_POSITION ) |
			( CLOCK_USER_PLL2CON_BOSC << _PLL2CON_BOSC_POSITION ) |
			( CLOCK_USER_PLL2CON_FSCMEN << _PLL2CON_FSCMEN_POSITION ) |
			( CLOCK_USER_PLL2CON_DIVSWEN << _PLL2CON_DIVSWEN_POSITION ) |
			( CLOCK_USER_PLL2CON_OSWEN << _PLL2CON_OSWEN_POSITION ) |
			( CLOCK_USER_PLL2CON_EXTCFSEL << _PLL2CON_EXTCFSEL_POSITION ) |
			( CLOCK_USER_PLL2CON_EXTCFEN << _PLL2CON_EXTCFEN_POSITION ) |
			( CLOCK_USER_PLL2CON_FOUTSWEN << _PLL2CON_FOUTSWEN_POSITION ) |
			( CLOCK_USER_PLL2CON_RIS << _PLL2CON_RIS_POSITION ) |
			( CLOCK_USER_PLL2CON_PLLSWEN << _PLL2CON_PLLSWEN_POSITION ) |
			( CLOCK_USER_PLL2CON_CLKRDY << _PLL2CON_CLKRDY_POSITION ) ;
		#ifdef DEF_BITNAME
			PLL2CONbits.COSC = CLOCK_USER_PLL2CON_COSC;
			PLL2CONbits.NOSC = CLOCK_USER_PLL2CON_NOSC;
			PLL2CONbits.OE = CLOCK_USER_PLL2CON_OE;
			PLL2CONbits.SIDL = CLOCK_USER_PLL2CON_SIDL;
			PLL2CONbits.ON = CLOCK_USER_PLL2CON_ON;
			PLL2CONbits.BOSC = CLOCK_USER_PLL2CON_BOSC;
			PLL2CONbits.FSCMEN = CLOCK_USER_PLL2CON_FSCMEN;
			PLL2CONbits.DIVSWEN = CLOCK_USER_PLL2CON_DIVSWEN;
			PLL2CONbits.OSWEN = CLOCK_USER_PLL2CON_OSWEN;
			PLL2CONbits.EXTCFSEL = CLOCK_USER_PLL2CON_EXTCFSEL;
			PLL2CONbits.EXTCFEN = CLOCK_USER_PLL2CON_EXTCFEN;
			PLL2CONbits.FOUTSWEN = CLOCK_USER_PLL2CON_FOUTSWEN;
			PLL2CONbits.RIS = CLOCK_USER_PLL2CON_RIS;
			PLL2CONbits.PLLSWEN = CLOCK_USER_PLL2CON_PLLSWEN;
			PLL2CONbits.CLKRDY = CLOCK_USER_PLL2CON_CLKRDY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PLL2DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		PLL2DIV = 
			( CLOCK_USER_PLL2DIV_POSTDIV2 << _PLL2DIV_POSTDIV2_POSITION ) |
			( CLOCK_USER_PLL2DIV_POSTDIV1 << _PLL2DIV_POSTDIV1_POSITION ) |
			( CLOCK_USER_PLL2DIV_PLLFBDIV << _PLL2DIV_PLLFBDIV_POSITION ) |
			( CLOCK_USER_PLL2DIV_PLLPRE << _PLL2DIV_PLLPRE_POSITION ) ;
		#ifdef DEF_BITNAME
			PLL2DIVbits.POSTDIV2 = CLOCK_USER_PLL2DIV_POSTDIV2;
			PLL2DIVbits.POSTDIV1 = CLOCK_USER_PLL2DIV_POSTDIV1;
			PLL2DIVbits.PLLFBDIV = CLOCK_USER_PLL2DIV_PLLFBDIV;
			PLL2DIVbits.PLLPRE = CLOCK_USER_PLL2DIV_PLLPRE;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* VCO2DIVレジスタ */
	/*-----------------------------------------------------------------------*/
		VCO2DIV = 
			( CLOCK_USER_VCO2DIV_INTDIV << _VCO2DIV_INTDIV_POSITION ) ;
		#ifdef DEF_BITNAME
			VCO2DIVbits.INTDIV = CLOCK_USER_VCO2DIV_INTDIV;
		#endif 

	

	/*-----------------------------------------------------------------------*/
	/* CLKDIAGレジスタ */
	/*-----------------------------------------------------------------------*/
		CLKDIAG = 
			( CLOCK_USER_CLKDIAG_STOPGEN1 << _CLKDIAG_STOPGEN1_POSITION ) |
			( CLOCK_USER_CLKDIAG_STOPGEN2 << _CLKDIAG_STOPGEN2_POSITION ) |
			( CLOCK_USER_CLKDIAG_STOPGEN3 << _CLKDIAG_STOPGEN3_POSITION ) |
			( CLOCK_USER_CLKDIAG_STOPGEN4 << _CLKDIAG_STOPGEN4_POSITION ) |
			( CLOCK_USER_CLKDIAG_STOPGEN5 << _CLKDIAG_STOPGEN5_POSITION ) |
			( CLOCK_USER_CLKDIAG_STOPGEN6 << _CLKDIAG_STOPGEN6_POSITION ) |
			( CLOCK_USER_CLKDIAG_STOPGEN7 << _CLKDIAG_STOPGEN7_POSITION ) |
			( CLOCK_USER_CLKDIAG_STOPGEN8 << _CLKDIAG_STOPGEN8_POSITION ) |
			( CLOCK_USER_CLKDIAG_STOPGEN9 << _CLKDIAG_STOPGEN9_POSITION ) |
			( CLOCK_USER_CLKDIAG_STOPGEN10 << _CLKDIAG_STOPGEN10_POSITION ) |
			( CLOCK_USER_CLKDIAG_STOPGEN11 << _CLKDIAG_STOPGEN11_POSITION ) |
			( CLOCK_USER_CLKDIAG_STOPGEN12 << _CLKDIAG_STOPGEN12_POSITION ) |
			( CLOCK_USER_CLKDIAG_STOPGEN13 << _CLKDIAG_STOPGEN13_POSITION ) |
			( CLOCK_USER_CLKDIAG_STOPGEN14 << _CLKDIAG_STOPGEN14_POSITION ) |
			( CLOCK_USER_CLKDIAG_SCSFLTDATA << _CLKDIAG_SCSFLTDATA_POSITION ) |
			( CLOCK_USER_CLKDIAG_GENSEL << _CLKDIAG_GENSEL_POSITION ) |
			( CLOCK_USER_CLKDIAG_STOPPLL1 << _CLKDIAG_STOPPLL1_POSITION ) |
			( CLOCK_USER_CLKDIAG_STOPPLL2 << _CLKDIAG_STOPPLL2_POSITION ) |
			( CLOCK_USER_CLKDIAG_FLTIJEN << _CLKDIAG_FLTIJEN_POSITION ) ;
		#ifdef DEF_BITNAME
			CLKDIAGbits.STOPGEN1 = CLOCK_USER_CLKDIAG_STOPGEN1;
			CLKDIAGbits.STOPGEN2 = CLOCK_USER_CLKDIAG_STOPGEN2;
			CLKDIAGbits.STOPGEN3 = CLOCK_USER_CLKDIAG_STOPGEN3;
			CLKDIAGbits.STOPGEN4 = CLOCK_USER_CLKDIAG_STOPGEN4;
			CLKDIAGbits.STOPGEN5 = CLOCK_USER_CLKDIAG_STOPGEN5;
			CLKDIAGbits.STOPGEN6 = CLOCK_USER_CLKDIAG_STOPGEN6;
			CLKDIAGbits.STOPGEN7 = CLOCK_USER_CLKDIAG_STOPGEN7;
			CLKDIAGbits.STOPGEN8 = CLOCK_USER_CLKDIAG_STOPGEN8;
			CLKDIAGbits.STOPGEN9 = CLOCK_USER_CLKDIAG_STOPGEN9;
			CLKDIAGbits.STOPGEN10 = CLOCK_USER_CLKDIAG_STOPGEN10;
			CLKDIAGbits.STOPGEN11 = CLOCK_USER_CLKDIAG_STOPGEN11;
			CLKDIAGbits.STOPGEN12 = CLOCK_USER_CLKDIAG_STOPGEN12;
			CLKDIAGbits.STOPGEN13 = CLOCK_USER_CLKDIAG_STOPGEN13;
			CLKDIAGbits.STOPGEN14 = CLOCK_USER_CLKDIAG_STOPGEN14;
			CLKDIAGbits.SCSFLTDATA = CLOCK_USER_CLKDIAG_SCSFLTDATA;
			CLKDIAGbits.GENSEL = CLOCK_USER_CLKDIAG_GENSEL;
			CLKDIAGbits.STOPPLL1 = CLOCK_USER_CLKDIAG_STOPPLL1;
			CLKDIAGbits.STOPPLL2 = CLOCK_USER_CLKDIAG_STOPPLL2;
			CLKDIAGbits.FLTIJEN = CLOCK_USER_CLKDIAG_FLTIJEN;
		#endif 
#endif
			
	/*-----------------------------------------------------------------------*/
	/* クロックの設定 */
	/*-----------------------------------------------------------------------*/	
	  
	//システムクロックソース                            :  PLL1 Out出力
	//システム/ジェネレータ 1 の周波数 (Fosc)            :  200 MHz
	//クロックジェネレータ 2 の周波数                     : 8 MHz
	//クロックジェネレータ 3 の周波数                     : 8 MHz
	//クロックジェネレータ 5 の周波数                     : 400 MHz
	//クロックジェネレータ 6 の周波数                     : 200 MHz
	//クロックジェネレータ 7 の周波数                     : 400 MHz
	//クロックジェネレータ 8 の周波数                     : 200 MHz
	//クロックジェネレータ 9 の周波数                     : 4 MHz
	//クロックジェネレータ 10 の周波数                    : 400 MHz
	//クロックジェネレータ 12 の周波数                    : 200 MHz
	//クロックジェネレータ 13 の周波数                    : 200 MHz
	//PLL 1 の周波数                                    : 400 MHz
	//PLL 1 VCO 出力周波数                              : 800 MHz
	/*-----------------------------------------------------------------------*/
	/* プライマリオシレータの設定と有効化 */
	/*-----------------------------------------------------------------------*/	
		// プライマリオシレータの選択		
		OSCCFGbits.POSCMD = 0x2u;
		OSCCFGbits.POSCIOFNC = 0u;
		OSCCTRLbits.POSCEN = 1U;
		while(OSCCTRLbits.POSCRDY == 0U){};
		
	/*-----------------------------------------------------------------------*/
	/* PLL1の設定と有効化 */
	/*-----------------------------------------------------------------------*/	
		// NOSC プライマリオシレータ; OE 有効; SIDL 無効; ON 有効; BOSC シリアルテストモードクロック (PGC); FSCMEN 無効; DIVSWEN 無効; OSWEN 無効; EXTCFSEL 無効; EXTCFEN 無効; FOUTSWEN 無効; RIS 無効; PLLSWEN 無効; 
		PLL1CON = 0x9300UL;
		// POSTDIV2 1x 分周; POSTDIV1 4x 分周; PLLFBDIV 200; PLLPRE 1; 
		PLL1DIV = 0x100C821UL;
		// PLL 入力およびフィードバック分周の更新を有効化
		PLL1CONbits.PLLSWEN = 1U;
		while (PLL1CONbits.PLLSWEN == 1){};
		PLL1CONbits.FOUTSWEN = 1U;
		while (PLL1CONbits.FOUTSWEN == 1U){};
		// クロックスイッチングを有効化
		PLL1CONbits.OSWEN = 1U; 
		// スイッチング待ち
		while(PLL1CONbits.OSWEN == 1U){}; 
		// クロックが準備完了するのを待つ
		while(OSCCTRLbits.PLL1RDY == 0U){};    
    
		// VCO 分周器の設定
		// INTDIV 1; 
		VCO1DIV = 0x10000UL;
		// PLL VCO 分周器を有効化
		PLL1CONbits.DIVSWEN = 1U; 
		// セットアップ完了待ち
		while(PLL1CONbits.DIVSWEN == 1U){}; 
	/*-----------------------------------------------------------------------*/
	/* クロックジェネレータ1の設定と有効化 */
	/*-----------------------------------------------------------------------*/	
		// NOSC PLL1 Out 出力; OE 有効; SIDL 無効; ON 有効; BOSC FRC オシレータ; FSCMEN 無効; DIVSWEN 無効; OSWEN 無効; EXTCFSEL 外部クロック故障検出モジュール #1; EXTCFEN 無効; RIS 無効; 
		CLK1CON = 0x19500UL;
		// FRACDIV 0; INTDIV 1; 
		CLK1DIV = 0x10000UL;
		// 分周ファクターを有効化
		CLK1CONbits.DIVSWEN = 1U; 
		// 分周ファクターの更新を待つ
		while(CLK1CONbits.DIVSWEN == 1U){};
		// クロックスイッチングを有効化
		CLK1CONbits.OSWEN = 1U; 
		// クロックスイッチング完了待ち
		while(CLK1CONbits.OSWEN == 1U){};
		
	/*-----------------------------------------------------------------------*/
	/* クロックジェネレータ2の設定と有効化 */
	/*-----------------------------------------------------------------------*/	
		// NOSC FRC オシレータ; OE 有効; SIDL 無効; ON 有効; BOSC シリアルテストモードクロック (PGC); FSCMEN 無効; DIVSWEN 無効; OSWEN 無効; EXTCFSEL 外部クロック故障検出モジュール #1; EXTCFEN 無効; RIS 無効; 
		CLK2CON = 0x9101UL;
		// クロックスイッチングを有効化
		CLK2CONbits.OSWEN = 1U; 
		// クロックスイッチング完了待ち
		while(CLK2CONbits.OSWEN == 1U){};
		
	/*-----------------------------------------------------------------------*/
	/* クロックジェネレータ3の設定と有効化 */
	/*-----------------------------------------------------------------------*/	
		// NOSC バックアップ FRC オシレータ; OE 有効; SIDL 無効; ON 有効; BOSC シリアルテストモードクロック (PGC); FSCMEN 無効; DIVSWEN 無効; OSWEN 無効; EXTCFSEL 外部クロック故障検出モジュール #1; EXTCFEN 無効; RIS 無効; 
		CLK3CON = 0x9202UL;
		// クロックスイッチングを有効化
		CLK3CONbits.OSWEN = 1U; 
		// クロックスイッチング完了待ち
		while(CLK3CONbits.OSWEN == 1U){};

		
	/*-----------------------------------------------------------------------*/
	/* クロックジェネレータ5の設定と有効化 */
	/*-----------------------------------------------------------------------*/	
		// NOSC PLL1 VCO 分周出力; OE 有効; SIDL 無効; ON 有効; BOSC シリアルテストモードクロック (PGC); FSCMEN 無効; DIVSWEN 無効; OSWEN 無効; EXTCFSEL 外部クロック故障検出モジュール #1; EXTCFEN 無効; RIS 無効; 
		CLK5CON = 0x9700UL;
		// FRACDIV 0; INTDIV 1; 
		CLK5DIV = 0x10000UL;
		// 分周ファクターを有効化
		CLK5CONbits.DIVSWEN = 1U; 
		// 分周ファクターの更新を待つ
		while(CLK5CONbits.DIVSWEN == 1U){};
		// クロックスイッチングを有効化
		CLK5CONbits.OSWEN = 1U; 
		// クロックスイッチング完了待ち
		while(CLK5CONbits.OSWEN == 1U){};

	/*-----------------------------------------------------------------------*/
	/* クロックジェネレータ6の設定と有効化 */
	/*-----------------------------------------------------------------------*/	
		// NOSC PLL1 VCO 分周出力; OE 有効; SIDL 無効; ON 有効; BOSC シリアルテストモードクロック (PGC); FSCMEN 無効; DIVSWEN 無効; OSWEN 無効; EXTCFSEL 外部クロック故障検出モジュール #1; EXTCFEN 無効; RIS 無効; 
		CLK6CON = 0x9700UL;
		// FRACDIV 0; INTDIV 2; 
		CLK6DIV = 0x20000UL;
		// 分周ファクターを有効化
		CLK6CONbits.DIVSWEN = 1U; 
		// 分周ファクターの更新を待つ
		while(CLK6CONbits.DIVSWEN == 1U){};
		// クロックスイッチングを有効化
		CLK6CONbits.OSWEN = 1U; 
		// クロックスイッチング完了待ち
		while(CLK6CONbits.OSWEN == 1U){};

	/*-----------------------------------------------------------------------*/
	/* クロックジェネレータ7の設定と有効化 */
	/*-----------------------------------------------------------------------*/	
		// NOSC PLL1 Out 出力; OE 有効; SIDL 無効; ON 有効; BOSC シリアルテストモードクロック (PGC); FSCMEN 無効; DIVSWEN 無効; OSWEN 無効; EXTCFSEL 外部クロック故障検出モジュール #1; EXTCFEN 無効; RIS 無効; 
		CLK7CON = 0x9500UL;
		// FRACDIV 0x0; INTDIV 0x0; 
		CLK7DIV = 0x0UL;
		// クロックスイッチングを有効化
		CLK7CONbits.OSWEN = 1U; 
		// クロックスイッチング完了待ち
		while(CLK7CONbits.OSWEN == 1U){};

	/*-----------------------------------------------------------------------*/
	/* クロックジェネレータ8の設定と有効化 */
	/*-----------------------------------------------------------------------*/	
		// NOSC PLL1 Out 出力; OE 有効; SIDL 無効; ON 有効; BOSC シリアルテストモードクロック (PGC); FSCMEN 無効; DIVSWEN 無効; OSWEN 無効; EXTCFSEL 外部クロック故障検出モジュール #1; EXTCFEN 無効; RIS 無効; 
		CLK8CON = 0x9500UL;
		// FRACDIV 0; INTDIV 1; 
		CLK8DIV = 0x10000UL;
		// 分周ファクターを有効化
		CLK8CONbits.DIVSWEN = 1U; 
		// 分周ファクターの更新を待つ
		while(CLK8CONbits.DIVSWEN == 1U){};
		// クロックスイッチングを有効化
		CLK8CONbits.OSWEN = 1U; 
		// クロックスイッチング完了待ち
		while(CLK8CONbits.OSWEN == 1U){};

	/*-----------------------------------------------------------------------*/
	/* クロックジェネレータ9の設定と有効化 */
	/*-----------------------------------------------------------------------*/	
		// NOSC PLL1 Out 出力; OE 有効; SIDL 無効; ON 有効; BOSC シリアルテストモードクロック (PGC); FSCMEN 無効; DIVSWEN 無効; OSWEN 無効; EXTCFSEL 外部クロック故障検出モジュール #1; EXTCFEN 無効; RIS 無効; 
		CLK9CON = 0x9500UL;
		// FRACDIV 0; INTDIV 50; 
		CLK9DIV = 0x320000UL;
		// 分周ファクターを有効化
		CLK9CONbits.DIVSWEN = 1U; 
		// 分周ファクターの更新を待つ
		while(CLK9CONbits.DIVSWEN == 1U){};
		// クロックスイッチングを有効化
		CLK9CONbits.OSWEN = 1U; 
		// クロックスイッチング完了待ち
		while(CLK9CONbits.OSWEN == 1U){};
		
	/*-----------------------------------------------------------------------*/
	/* クロックジェネレータ10の設定と有効化 */
	/*-----------------------------------------------------------------------*/	
		// NOSC PLL1 VCO 分周出力; OE 有効; SIDL 無効; ON 有効; BOSC シリアルテストモードクロック (PGC); FSCMEN 無効; DIVSWEN 無効; OSWEN 無効; EXTCFSEL 外部クロック故障検出モジュール #1; EXTCFEN 無効; RIS 無効; 
		CLK10CON = 0x9700UL;
		// FRACDIV 0; INTDIV 1; 
		CLK10DIV = 0x10000UL;
		// 分周ファクターを有効化
		CLK10CONbits.DIVSWEN = 1U; 
		// 分周ファクターの更新を待つ
		while(CLK10CONbits.DIVSWEN == 1U){};
		// クロックスイッチングを有効化
		CLK10CONbits.OSWEN = 1U; 
		// クロックスイッチング完了待ち
		while(CLK10CONbits.OSWEN == 1U){};
		
	/*-----------------------------------------------------------------------*/
	/* クロックジェネレータ12の設定と有効化 */
	/*-----------------------------------------------------------------------*/	
		// NOSC PLL1 Out 出力; OE 有効; SIDL 無効; ON 有効; BOSC シリアルテストモードクロック (PGC); FSCMEN 無効; DIVSWEN 無効; OSWEN 無効; EXTCFSEL 外部クロック故障検出モジュール #1; EXTCFEN 無効; RIS 無効; 
		CLK12CON = 0x9500UL;
		// FRACDIV 0; INTDIV 1; 
		CLK12DIV = 0x10000UL;
		// 分周ファクターを有効化
		CLK12CONbits.DIVSWEN = 1U; 
		// 分周ファクターの更新を待つ
		while(CLK12CONbits.DIVSWEN == 1U){};
		// クロックスイッチングを有効化
		CLK12CONbits.OSWEN = 1U; 
		// クロックスイッチング完了待ち
		while(CLK12CONbits.OSWEN == 1U){};
		
	/*-----------------------------------------------------------------------*/
	/* クロックジェネレータ13の設定と有効化 */
	/*-----------------------------------------------------------------------*/	
		// NOSC PLL1 Out 出力; OE 有効; SIDL 無効; ON 有効; BOSC シリアルテストモードクロック (PGC); FSCMEN 無効; DIVSWEN 無効; OSWEN 無効; EXTCFSEL 外部クロック故障検出モジュール #1; EXTCFEN 無効; RIS 無効; 
		CLK13CON = 0x9500UL;
		// FRACDIV 0; INTDIV 1; 
		CLK13DIV = 0x10000UL;
		// 分周ファクターを有効化
		CLK13CONbits.DIVSWEN = 1U; 
		// 分周ファクターの更新を待つ
		while(CLK13CONbits.DIVSWEN == 1U){};
		// クロックスイッチングを有効化
		CLK13CONbits.OSWEN = 1U; 
		// クロックスイッチング完了待ち
		while(CLK13CONbits.OSWEN == 1U){};

	
	/*-----------------------------------------------------------------------*/
	/* FRCTUNレジスタ */
	/*-----------------------------------------------------------------------*/
		FRCTUN = CLOCK_USER_FRCTUN;

	/*-----------------------------------------------------------------------*/
	/* BFRCTUNレジスタ */
	/*-----------------------------------------------------------------------*/
		BFRCTUN = CLOCK_USER_BFRCTUN;

}

/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_CM1_Set_Register(void)
* @brief     CM1レジスタを初期化します
* @param
* @return
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_CM1_Set_Register(void)
{
	/*-----------------------------------------------------------------------*/
	/* CM1CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CM1CON = 
			( CLOCK_USER_CM1CON_WIDTH << _CM1CON_WIDTH_POSITION ) |
			( CLOCK_USER_CM1CON_FLTINJ << _CM1CON_FLTINJ_POSITION ) |
			( CLOCK_USER_CM1CON_CNTDIV << _CM1CON_CNTDIV_POSITION ) |
			( CLOCK_USER_CM1CON_SLPEN << _CM1CON_SLPEN_POSITION ) |
			( CLOCK_USER_CM1CON_SIDL << _CM1CON_SIDL_POSITION ) |
			( CLOCK_USER_CM1CON_ON << _CM1CON_ON_POSITION ) ;
		#ifdef DEF_BITNAME
			CM1CONbits.WIDTH = CLOCK_USER_CM1CON_WIDTH;
			CM1CONbits.FLTINJ = CLOCK_USER_CM1CON_FLTINJ;
			CM1CONbits.CNTDIV = CLOCK_USER_CM1CON_CNTDIV;
			CM1CONbits.SLPEN = CLOCK_USER_CM1CON_SLPEN;
			CM1CONbits.SIDL = CLOCK_USER_CM1CON_SIDL;
			CM1CONbits.ON = CLOCK_USER_CM1CON_ON;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CM1STATレジスタ */
	/*-----------------------------------------------------------------------*/
		CM1STAT = 
			( CLOCK_USER_CM1STAT_BUFV << _CM1STAT_BUFV_POSITION ) |
			( CLOCK_USER_CM1STAT_SATD << _CM1STAT_SATD_POSITION ) |
			( CLOCK_USER_CM1STAT_TRIG << _CM1STAT_TRIG_POSITION ) |
			( CLOCK_USER_CM1STAT_LFT << _CM1STAT_LFT_POSITION ) |
			( CLOCK_USER_CM1STAT_HFT << _CM1STAT_HFT_POSITION ) |
			( CLOCK_USER_CM1STAT_LWT << _CM1STAT_LWT_POSITION ) |
			( CLOCK_USER_CM1STAT_HWT << _CM1STAT_HWT_POSITION ) ;
		#ifdef DEF_BITNAME
			CM1STATbits.BUFV = CLOCK_USER_CM1STAT_BUFV;
			CM1STATbits.SATD = CLOCK_USER_CM1STAT_SATD;
			CM1STATbits.TRIG = CLOCK_USER_CM1STAT_TRIG;
			CM1STATbits.LFT = CLOCK_USER_CM1STAT_LFT;
			CM1STATbits.HFT = CLOCK_USER_CM1STAT_HFT;
			CM1STATbits.LWT = CLOCK_USER_CM1STAT_LWT;
			CM1STATbits.HWT = CLOCK_USER_CM1STAT_HWT;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CM1WINPRレジスタ */
	/*-----------------------------------------------------------------------*/
		CM1WINPR = CLOCK_USER_CM1WINPR;
	/*-----------------------------------------------------------------------*/
	/* CM1SELレジスタ */
	/*-----------------------------------------------------------------------*/
		CM1SEL = 
			( CLOCK_USER_CM1SEL_WINSEL << _CM1SEL_WINSEL_POSITION ) |
			( CLOCK_USER_CM1SEL_CNTSEL << _CM1SEL_CNTSEL_POSITION ) ;
		#ifdef DEF_BITNAME
			CM1SELbits.WINSEL = CLOCK_USER_CM1SEL_WINSEL;
			CM1SELbits.CNTSEL = CLOCK_USER_CM1SEL_CNTSEL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CM1BUFレジスタ */
	/*-----------------------------------------------------------------------*/
		CM1BUF = CLOCK_USER_CM1BUF;
	/*-----------------------------------------------------------------------*/
	/* CM1SATレジスタ */
	/*-----------------------------------------------------------------------*/
		CM1SAT = CLOCK_USER_CM1SAT;
	/*-----------------------------------------------------------------------*/
	/* CM1HFAILレジスタ */
	/*-----------------------------------------------------------------------*/
		CM1HFAIL = CLOCK_USER_CM1HFAIL;
	/*-----------------------------------------------------------------------*/
	/* CM1LFAILレジスタ */
	/*-----------------------------------------------------------------------*/
		CM1LFAIL = CLOCK_USER_CM1LFAIL;
	/*-----------------------------------------------------------------------*/
	/* CM1HWARNレジスタ */
	/*-----------------------------------------------------------------------*/
		CM1HWARN = CLOCK_USER_CM1HWARN;
	/*-----------------------------------------------------------------------*/
	/* CM1LWARNレジスタ */
	/*-----------------------------------------------------------------------*/
		CM1LWARN = CLOCK_USER_CM1LWARN;
}
/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_CM2_Set_Register(void)
* @brief     CM2レジスタを初期化します
* @param
* @return
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_CM2_Set_Register(void)
{
	/*-----------------------------------------------------------------------*/
	/* CM2CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CM2CON = 
			( CLOCK_USER_CM2CON_WIDTH << _CM2CON_WIDTH_POSITION ) |
			( CLOCK_USER_CM2CON_FLTINJ << _CM2CON_FLTINJ_POSITION ) |
			( CLOCK_USER_CM2CON_CNTDIV << _CM2CON_CNTDIV_POSITION ) |
			( CLOCK_USER_CM2CON_SLPEN << _CM2CON_SLPEN_POSITION ) |
			( CLOCK_USER_CM2CON_SIDL << _CM2CON_SIDL_POSITION ) |
			( CLOCK_USER_CM2CON_ON << _CM2CON_ON_POSITION ) ;
		#ifdef DEF_BITNAME
			CM2CONbits.WIDTH = CLOCK_USER_CM2CON_WIDTH;
			CM2CONbits.FLTINJ = CLOCK_USER_CM2CON_FLTINJ;
			CM2CONbits.CNTDIV = CLOCK_USER_CM2CON_CNTDIV;
			CM2CONbits.SLPEN = CLOCK_USER_CM2CON_SLPEN;
			CM2CONbits.SIDL = CLOCK_USER_CM2CON_SIDL;
			CM2CONbits.ON = CLOCK_USER_CM2CON_ON;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CM2STATレジスタ */
	/*-----------------------------------------------------------------------*/
		CM2STAT = 
			( CLOCK_USER_CM2STAT_BUFV << _CM2STAT_BUFV_POSITION ) |
			( CLOCK_USER_CM2STAT_SATD << _CM2STAT_SATD_POSITION ) |
			( CLOCK_USER_CM2STAT_TRIG << _CM2STAT_TRIG_POSITION ) |
			( CLOCK_USER_CM2STAT_LFT << _CM2STAT_LFT_POSITION ) |
			( CLOCK_USER_CM2STAT_HFT << _CM2STAT_HFT_POSITION ) |
			( CLOCK_USER_CM2STAT_LWT << _CM2STAT_LWT_POSITION ) |
			( CLOCK_USER_CM2STAT_HWT << _CM2STAT_HWT_POSITION ) ;
		#ifdef DEF_BITNAME
			CM2STATbits.BUFV = CLOCK_USER_CM2STAT_BUFV;
			CM2STATbits.SATD = CLOCK_USER_CM2STAT_SATD;
			CM2STATbits.TRIG = CLOCK_USER_CM2STAT_TRIG;
			CM2STATbits.LFT = CLOCK_USER_CM2STAT_LFT;
			CM2STATbits.HFT = CLOCK_USER_CM2STAT_HFT;
			CM2STATbits.LWT = CLOCK_USER_CM2STAT_LWT;
			CM2STATbits.HWT = CLOCK_USER_CM2STAT_HWT;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CM2WINPRレジスタ */
	/*-----------------------------------------------------------------------*/
		CM2WINPR = CLOCK_USER_CM2WINPR;
	/*-----------------------------------------------------------------------*/
	/* CM2SELレジスタ */
	/*-----------------------------------------------------------------------*/
		CM2SEL = 
			( CLOCK_USER_CM2SEL_WINSEL << _CM2SEL_WINSEL_POSITION ) |
			( CLOCK_USER_CM2SEL_CNTSEL << _CM2SEL_CNTSEL_POSITION ) ;
		#ifdef DEF_BITNAME
			CM2SELbits.WINSEL = CLOCK_USER_CM2SEL_WINSEL;
			CM2SELbits.CNTSEL = CLOCK_USER_CM2SEL_CNTSEL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CM2BUFレジスタ */
	/*-----------------------------------------------------------------------*/
		CM2BUF = CLOCK_USER_CM2BUF;
	/*-----------------------------------------------------------------------*/
	/* CM2SATレジスタ */
	/*-----------------------------------------------------------------------*/
		CM2SAT = CLOCK_USER_CM2SAT;
	/*-----------------------------------------------------------------------*/
	/* CM2HFAILレジスタ */
	/*-----------------------------------------------------------------------*/
		CM2HFAIL = CLOCK_USER_CM2HFAIL;
	/*-----------------------------------------------------------------------*/
	/* CM2LFAILレジスタ */
	/*-----------------------------------------------------------------------*/
		CM2LFAIL = CLOCK_USER_CM2LFAIL;
	/*-----------------------------------------------------------------------*/
	/* CM2HWARNレジスタ */
	/*-----------------------------------------------------------------------*/
		CM2HWARN = CLOCK_USER_CM2HWARN;
	/*-----------------------------------------------------------------------*/
	/* CM2LWARNレジスタ */
	/*-----------------------------------------------------------------------*/
		CM2LWARN = CLOCK_USER_CM2LWARN;
}
/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_CM3_Set_Register(void)
* @brief     CM3レジスタを初期化します
* @param
* @return
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_CM3_Set_Register(void)
{
	/*-----------------------------------------------------------------------*/
	/* CM3CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CM3CON = 
			( CLOCK_USER_CM3CON_WIDTH << _CM3CON_WIDTH_POSITION ) |
			( CLOCK_USER_CM3CON_FLTINJ << _CM3CON_FLTINJ_POSITION ) |
			( CLOCK_USER_CM3CON_CNTDIV << _CM3CON_CNTDIV_POSITION ) |
			( CLOCK_USER_CM3CON_SLPEN << _CM3CON_SLPEN_POSITION ) |
			( CLOCK_USER_CM3CON_SIDL << _CM3CON_SIDL_POSITION ) |
			( CLOCK_USER_CM3CON_ON << _CM3CON_ON_POSITION ) ;
		#ifdef DEF_BITNAME
			CM3CONbits.WIDTH = CLOCK_USER_CM3CON_WIDTH;
			CM3CONbits.FLTINJ = CLOCK_USER_CM3CON_FLTINJ;
			CM3CONbits.CNTDIV = CLOCK_USER_CM3CON_CNTDIV;
			CM3CONbits.SLPEN = CLOCK_USER_CM3CON_SLPEN;
			CM3CONbits.SIDL = CLOCK_USER_CM3CON_SIDL;
			CM3CONbits.ON = CLOCK_USER_CM3CON_ON;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CM3STATレジスタ */
	/*-----------------------------------------------------------------------*/
		CM3STAT = 
			( CLOCK_USER_CM3STAT_BUFV << _CM3STAT_BUFV_POSITION ) |
			( CLOCK_USER_CM3STAT_SATD << _CM3STAT_SATD_POSITION ) |
			( CLOCK_USER_CM3STAT_TRIG << _CM3STAT_TRIG_POSITION ) |
			( CLOCK_USER_CM3STAT_LFT << _CM3STAT_LFT_POSITION ) |
			( CLOCK_USER_CM3STAT_HFT << _CM3STAT_HFT_POSITION ) |
			( CLOCK_USER_CM3STAT_LWT << _CM3STAT_LWT_POSITION ) |
			( CLOCK_USER_CM3STAT_HWT << _CM3STAT_HWT_POSITION ) ;
		#ifdef DEF_BITNAME
			CM3STATbits.BUFV = CLOCK_USER_CM3STAT_BUFV;
			CM3STATbits.SATD = CLOCK_USER_CM3STAT_SATD;
			CM3STATbits.TRIG = CLOCK_USER_CM3STAT_TRIG;
			CM3STATbits.LFT = CLOCK_USER_CM3STAT_LFT;
			CM3STATbits.HFT = CLOCK_USER_CM3STAT_HFT;
			CM3STATbits.LWT = CLOCK_USER_CM3STAT_LWT;
			CM3STATbits.HWT = CLOCK_USER_CM3STAT_HWT;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CM3WINPRレジスタ */
	/*-----------------------------------------------------------------------*/
		CM3WINPR = CLOCK_USER_CM3WINPR;
	/*-----------------------------------------------------------------------*/
	/* CM3SELレジスタ */
	/*-----------------------------------------------------------------------*/
		CM3SEL = 
			( CLOCK_USER_CM3SEL_WINSEL << _CM3SEL_WINSEL_POSITION ) |
			( CLOCK_USER_CM3SEL_CNTSEL << _CM3SEL_CNTSEL_POSITION ) ;
		#ifdef DEF_BITNAME
			CM3SELbits.WINSEL = CLOCK_USER_CM3SEL_WINSEL;
			CM3SELbits.CNTSEL = CLOCK_USER_CM3SEL_CNTSEL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CM3BUFレジスタ */
	/*-----------------------------------------------------------------------*/
		CM3BUF = CLOCK_USER_CM3BUF;
	/*-----------------------------------------------------------------------*/
	/* CM3SATレジスタ */
	/*-----------------------------------------------------------------------*/
		CM3SAT = CLOCK_USER_CM3SAT;
	/*-----------------------------------------------------------------------*/
	/* CM3HFAILレジスタ */
	/*-----------------------------------------------------------------------*/
		CM3HFAIL = CLOCK_USER_CM3HFAIL;
	/*-----------------------------------------------------------------------*/
	/* CM3LFAILレジスタ */
	/*-----------------------------------------------------------------------*/
		CM3LFAIL = CLOCK_USER_CM3LFAIL;
	/*-----------------------------------------------------------------------*/
	/* CM3HWARNレジスタ */
	/*-----------------------------------------------------------------------*/
		CM3HWARN = CLOCK_USER_CM3HWARN;
	/*-----------------------------------------------------------------------*/
	/* CM3LWARNレジスタ */
	/*-----------------------------------------------------------------------*/
		CM3LWARN = CLOCK_USER_CM3LWARN;
}
/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_CM4_Set_Register(void)
* @brief     CM4レジスタを初期化します
* @param
* @return
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_CM4_Set_Register(void)
{
	/*-----------------------------------------------------------------------*/
	/* CM4CONレジスタ */
	/*-----------------------------------------------------------------------*/
		CM4CON = 
			( CLOCK_USER_CM4CON_WIDTH << _CM4CON_WIDTH_POSITION ) |
			( CLOCK_USER_CM4CON_FLTINJ << _CM4CON_FLTINJ_POSITION ) |
			( CLOCK_USER_CM4CON_CNTDIV << _CM4CON_CNTDIV_POSITION ) |
			( CLOCK_USER_CM4CON_SLPEN << _CM4CON_SLPEN_POSITION ) |
			( CLOCK_USER_CM4CON_SIDL << _CM4CON_SIDL_POSITION ) |
			( CLOCK_USER_CM4CON_ON << _CM4CON_ON_POSITION ) ;
		#ifdef DEF_BITNAME
			CM4CONbits.WIDTH = CLOCK_USER_CM4CON_WIDTH;
			CM4CONbits.FLTINJ = CLOCK_USER_CM4CON_FLTINJ;
			CM4CONbits.CNTDIV = CLOCK_USER_CM4CON_CNTDIV;
			CM4CONbits.SLPEN = CLOCK_USER_CM4CON_SLPEN;
			CM4CONbits.SIDL = CLOCK_USER_CM4CON_SIDL;
			CM4CONbits.ON = CLOCK_USER_CM4CON_ON;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CM4STATレジスタ */
	/*-----------------------------------------------------------------------*/
		CM4STAT = 
			( CLOCK_USER_CM4STAT_BUFV << _CM4STAT_BUFV_POSITION ) |
			( CLOCK_USER_CM4STAT_SATD << _CM4STAT_SATD_POSITION ) |
			( CLOCK_USER_CM4STAT_TRIG << _CM4STAT_TRIG_POSITION ) |
			( CLOCK_USER_CM4STAT_LFT << _CM4STAT_LFT_POSITION ) |
			( CLOCK_USER_CM4STAT_HFT << _CM4STAT_HFT_POSITION ) |
			( CLOCK_USER_CM4STAT_LWT << _CM4STAT_LWT_POSITION ) |
			( CLOCK_USER_CM4STAT_HWT << _CM4STAT_HWT_POSITION ) ;
		#ifdef DEF_BITNAME
			CM4STATbits.BUFV = CLOCK_USER_CM4STAT_BUFV;
			CM4STATbits.SATD = CLOCK_USER_CM4STAT_SATD;
			CM4STATbits.TRIG = CLOCK_USER_CM4STAT_TRIG;
			CM4STATbits.LFT = CLOCK_USER_CM4STAT_LFT;
			CM4STATbits.HFT = CLOCK_USER_CM4STAT_HFT;
			CM4STATbits.LWT = CLOCK_USER_CM4STAT_LWT;
			CM4STATbits.HWT = CLOCK_USER_CM4STAT_HWT;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CM4WINPRレジスタ */
	/*-----------------------------------------------------------------------*/
		CM4WINPR = CLOCK_USER_CM4WINPR;
	/*-----------------------------------------------------------------------*/
	/* CM4SELレジスタ */
	/*-----------------------------------------------------------------------*/
		CM4SEL = 
			( CLOCK_USER_CM4SEL_WINSEL << _CM4SEL_WINSEL_POSITION ) |
			( CLOCK_USER_CM4SEL_CNTSEL << _CM4SEL_CNTSEL_POSITION ) ;
		#ifdef DEF_BITNAME
			CM4SELbits.WINSEL = CLOCK_USER_CM4SEL_WINSEL;
			CM4SELbits.CNTSEL = CLOCK_USER_CM4SEL_CNTSEL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* CM4BUFレジスタ */
	/*-----------------------------------------------------------------------*/
		CM4BUF = CLOCK_USER_CM4BUF;
	/*-----------------------------------------------------------------------*/
	/* CM4SATレジスタ */
	/*-----------------------------------------------------------------------*/
		CM4SAT = CLOCK_USER_CM4SAT;
	/*-----------------------------------------------------------------------*/
	/* CM4HFAILレジスタ */
	/*-----------------------------------------------------------------------*/
		CM4HFAIL = CLOCK_USER_CM4HFAIL;
	/*-----------------------------------------------------------------------*/
	/* CM4LFAILレジスタ */
	/*-----------------------------------------------------------------------*/
		CM4LFAIL = CLOCK_USER_CM4LFAIL;
	/*-----------------------------------------------------------------------*/
	/* CM4HWARNレジスタ */
	/*-----------------------------------------------------------------------*/
		CM4HWARN = CLOCK_USER_CM4HWARN;
	/*-----------------------------------------------------------------------*/
	/* CM4LWARNレジスタ */
	/*-----------------------------------------------------------------------*/
		CM4LWARN = CLOCK_USER_CM4LWARN;
}


/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_Clock_Set_Register(void)
* @brief     _Clockレジスタ全てを初期化します
* @param
* @return
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_Clock_Set_Register(void)
{
	vdg_Clock_Init_Register();
	vdg_CM1_Set_Register();
	vdg_CM2_Set_Register();
	vdg_CM3_Set_Register();
	vdg_CM4_Set_Register();
}