/*----------------------------------------------------------------------------*/
/**
 * @file	ITC_Driver.c
 * @brief	ITCモジュールに関するドライバ関数
 * @details 
 */
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*インクルードファイル*/
/*----------------------------------------------------------------------------*/
#include <xc.h>
#include "BoardSupportPackage.h"
#include "init_fix.h"
#include "typedef.h"
#include "itc_user.h"
/*----------------------------------------------------------------------------*/
/*定数定義*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*変数定義*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*プロトタイプ宣言*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_ITC_Set_Register(void) 
* @brief     ITCレジスタを初期化します 
* @param
* @return
* @detail 
 */
/*----------------------------------------------------------------------------*/
void vdg_ITC_Set_Register(void)
{
#if ( PMD_ITCMD == PMD_MODULE_ENABLE )
	/*-----------------------------------------------------------------------*/
	/* ITCCON1レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCCON1 = 
			( ITC_USER_ITCCON1_SIGN << _ITCCON1_SIGN_POSITION ) |
			( ITC_USER_ITCCON1_CVDEN << _ITCCON1_CVDEN_POSITION ) |
			( ITC_USER_ITCCON1_ON << _ITCCON1_ON_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCCON1bits.SIGN = ITC_USER_ITCCON1_SIGN;
			ITCCON1bits.CVDEN = ITC_USER_ITCCON1_CVDEN;
			ITCCON1bits.ON = ITC_USER_ITCCON1_ON;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCCON2レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCCON2 = 
			( ITC_USER_ITCCON2_TRGEN0 << _ITCCON2_TRGEN0_POSITION ) |
			( ITC_USER_ITCCON2_TRGEN1 << _ITCCON2_TRGEN1_POSITION ) |
			( ITC_USER_ITCCON2_TRGEN2 << _ITCCON2_TRGEN2_POSITION ) |
			( ITC_USER_ITCCON2_TMRPR << _ITCCON2_TMRPR_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCCON2bits.TRGEN0 = ITC_USER_ITCCON2_TRGEN0;
			ITCCON2bits.TRGEN1 = ITC_USER_ITCCON2_TRGEN1;
			ITCCON2bits.TRGEN2 = ITC_USER_ITCCON2_TRGEN2;
			ITCCON2bits.TMRPR = ITC_USER_ITCCON2_TMRPR;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCSTATレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCSTAT = 
			( ITC_USER_ITCSTAT_INT0 << _ITCSTAT_INT0_POSITION ) |
			( ITC_USER_ITCSTAT_INT1 << _ITCSTAT_INT1_POSITION ) |
			( ITC_USER_ITCSTAT_INT2 << _ITCSTAT_INT2_POSITION ) |
			( ITC_USER_ITCSTAT_DRDY << _ITCSTAT_DRDY_POSITION ) |
			( ITC_USER_ITCSTAT_TSTEN << _ITCSTAT_TSTEN_POSITION ) |
			( ITC_USER_ITCSTAT_TSTDATA << _ITCSTAT_TSTDATA_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCSTATbits.INT0 = ITC_USER_ITCSTAT_INT0;
			ITCSTATbits.INT1 = ITC_USER_ITCSTAT_INT1;
			ITCSTATbits.INT2 = ITC_USER_ITCSTAT_INT2;
			ITCSTATbits.DRDY = ITC_USER_ITCSTAT_DRDY;
			ITCSTATbits.TSTEN = ITC_USER_ITCSTAT_TSTEN;
			ITCSTATbits.TSTDATA = ITC_USER_ITCSTAT_TSTDATA;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCTXAレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCTXA = 
			( ITC_USER_ITCTXA_TXA0 << _ITCTXA_TXA0_POSITION ) |
			( ITC_USER_ITCTXA_TXA1 << _ITCTXA_TXA1_POSITION ) |
			( ITC_USER_ITCTXA_TXA2 << _ITCTXA_TXA2_POSITION ) |
			( ITC_USER_ITCTXA_TXA3 << _ITCTXA_TXA3_POSITION ) |
			( ITC_USER_ITCTXA_TXA4 << _ITCTXA_TXA4_POSITION ) |
			( ITC_USER_ITCTXA_TXA5 << _ITCTXA_TXA5_POSITION ) |
			( ITC_USER_ITCTXA_TXA6 << _ITCTXA_TXA6_POSITION ) |
			( ITC_USER_ITCTXA_TXA7 << _ITCTXA_TXA7_POSITION ) |
			( ITC_USER_ITCTXA_TXA8 << _ITCTXA_TXA8_POSITION ) |
			( ITC_USER_ITCTXA_TXA9 << _ITCTXA_TXA9_POSITION ) |
			( ITC_USER_ITCTXA_TXA10 << _ITCTXA_TXA10_POSITION ) |
			( ITC_USER_ITCTXA_TXA11 << _ITCTXA_TXA11_POSITION ) |
			( ITC_USER_ITCTXA_TXA12 << _ITCTXA_TXA12_POSITION ) |
			( ITC_USER_ITCTXA_TXA13 << _ITCTXA_TXA13_POSITION ) |
			( ITC_USER_ITCTXA_TXA14 << _ITCTXA_TXA14_POSITION ) |
			( ITC_USER_ITCTXA_TXA15 << _ITCTXA_TXA15_POSITION ) |
			( ITC_USER_ITCTXA_TXA16 << _ITCTXA_TXA16_POSITION ) |
			( ITC_USER_ITCTXA_TXA17 << _ITCTXA_TXA17_POSITION ) |
			( ITC_USER_ITCTXA_TXA18 << _ITCTXA_TXA18_POSITION ) |
			( ITC_USER_ITCTXA_TXA19 << _ITCTXA_TXA19_POSITION ) |
			( ITC_USER_ITCTXA_TXA20 << _ITCTXA_TXA20_POSITION ) |
			( ITC_USER_ITCTXA_TXA21 << _ITCTXA_TXA21_POSITION ) |
			( ITC_USER_ITCTXA_TXA22 << _ITCTXA_TXA22_POSITION ) |
			( ITC_USER_ITCTXA_TXA23 << _ITCTXA_TXA23_POSITION ) |
			( ITC_USER_ITCTXA_TXA24 << _ITCTXA_TXA24_POSITION ) |
			( ITC_USER_ITCTXA_TXA25 << _ITCTXA_TXA25_POSITION ) |
			( ITC_USER_ITCTXA_TXA26 << _ITCTXA_TXA26_POSITION ) |
			( ITC_USER_ITCTXA_TXA27 << _ITCTXA_TXA27_POSITION ) |
			( ITC_USER_ITCTXA_TXA28 << _ITCTXA_TXA28_POSITION ) |
			( ITC_USER_ITCTXA_TXA29 << _ITCTXA_TXA29_POSITION ) |
			( ITC_USER_ITCTXA_TXA30 << _ITCTXA_TXA30_POSITION ) |
			( ITC_USER_ITCTXA_TXA31 << _ITCTXA_TXA31_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCTXAbits.TXA0 = ITC_USER_ITCTXA_TXA0;
			ITCTXAbits.TXA1 = ITC_USER_ITCTXA_TXA1;
			ITCTXAbits.TXA2 = ITC_USER_ITCTXA_TXA2;
			ITCTXAbits.TXA3 = ITC_USER_ITCTXA_TXA3;
			ITCTXAbits.TXA4 = ITC_USER_ITCTXA_TXA4;
			ITCTXAbits.TXA5 = ITC_USER_ITCTXA_TXA5;
			ITCTXAbits.TXA6 = ITC_USER_ITCTXA_TXA6;
			ITCTXAbits.TXA7 = ITC_USER_ITCTXA_TXA7;
			ITCTXAbits.TXA8 = ITC_USER_ITCTXA_TXA8;
			ITCTXAbits.TXA9 = ITC_USER_ITCTXA_TXA9;
			ITCTXAbits.TXA10 = ITC_USER_ITCTXA_TXA10;
			ITCTXAbits.TXA11 = ITC_USER_ITCTXA_TXA11;
			ITCTXAbits.TXA12 = ITC_USER_ITCTXA_TXA12;
			ITCTXAbits.TXA13 = ITC_USER_ITCTXA_TXA13;
			ITCTXAbits.TXA14 = ITC_USER_ITCTXA_TXA14;
			ITCTXAbits.TXA15 = ITC_USER_ITCTXA_TXA15;
			ITCTXAbits.TXA16 = ITC_USER_ITCTXA_TXA16;
			ITCTXAbits.TXA17 = ITC_USER_ITCTXA_TXA17;
			ITCTXAbits.TXA18 = ITC_USER_ITCTXA_TXA18;
			ITCTXAbits.TXA19 = ITC_USER_ITCTXA_TXA19;
			ITCTXAbits.TXA20 = ITC_USER_ITCTXA_TXA20;
			ITCTXAbits.TXA21 = ITC_USER_ITCTXA_TXA21;
			ITCTXAbits.TXA22 = ITC_USER_ITCTXA_TXA22;
			ITCTXAbits.TXA23 = ITC_USER_ITCTXA_TXA23;
			ITCTXAbits.TXA24 = ITC_USER_ITCTXA_TXA24;
			ITCTXAbits.TXA25 = ITC_USER_ITCTXA_TXA25;
			ITCTXAbits.TXA26 = ITC_USER_ITCTXA_TXA26;
			ITCTXAbits.TXA27 = ITC_USER_ITCTXA_TXA27;
			ITCTXAbits.TXA28 = ITC_USER_ITCTXA_TXA28;
			ITCTXAbits.TXA29 = ITC_USER_ITCTXA_TXA29;
			ITCTXAbits.TXA30 = ITC_USER_ITCTXA_TXA30;
			ITCTXAbits.TXA31 = ITC_USER_ITCTXA_TXA31;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCTXBレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCTXB = 
			( ITC_USER_ITCTXB_TXB0 << _ITCTXB_TXB0_POSITION ) |
			( ITC_USER_ITCTXB_TXB1 << _ITCTXB_TXB1_POSITION ) |
			( ITC_USER_ITCTXB_TXB2 << _ITCTXB_TXB2_POSITION ) |
			( ITC_USER_ITCTXB_TXB3 << _ITCTXB_TXB3_POSITION ) |
			( ITC_USER_ITCTXB_TXB4 << _ITCTXB_TXB4_POSITION ) |
			( ITC_USER_ITCTXB_TXB5 << _ITCTXB_TXB5_POSITION ) |
			( ITC_USER_ITCTXB_TXB6 << _ITCTXB_TXB6_POSITION ) |
			( ITC_USER_ITCTXB_TXB7 << _ITCTXB_TXB7_POSITION ) |
			( ITC_USER_ITCTXB_TXB8 << _ITCTXB_TXB8_POSITION ) |
			( ITC_USER_ITCTXB_TXB9 << _ITCTXB_TXB9_POSITION ) |
			( ITC_USER_ITCTXB_TXB10 << _ITCTXB_TXB10_POSITION ) |
			( ITC_USER_ITCTXB_TXB11 << _ITCTXB_TXB11_POSITION ) |
			( ITC_USER_ITCTXB_TXB12 << _ITCTXB_TXB12_POSITION ) |
			( ITC_USER_ITCTXB_TXB13 << _ITCTXB_TXB13_POSITION ) |
			( ITC_USER_ITCTXB_TXB14 << _ITCTXB_TXB14_POSITION ) |
			( ITC_USER_ITCTXB_TXB15 << _ITCTXB_TXB15_POSITION ) |
			( ITC_USER_ITCTXB_TXB16 << _ITCTXB_TXB16_POSITION ) |
			( ITC_USER_ITCTXB_TXB17 << _ITCTXB_TXB17_POSITION ) |
			( ITC_USER_ITCTXB_TXB18 << _ITCTXB_TXB18_POSITION ) |
			( ITC_USER_ITCTXB_TXB19 << _ITCTXB_TXB19_POSITION ) |
			( ITC_USER_ITCTXB_TXB20 << _ITCTXB_TXB20_POSITION ) |
			( ITC_USER_ITCTXB_TXB21 << _ITCTXB_TXB21_POSITION ) |
			( ITC_USER_ITCTXB_TXB22 << _ITCTXB_TXB22_POSITION ) |
			( ITC_USER_ITCTXB_TXB23 << _ITCTXB_TXB23_POSITION ) |
			( ITC_USER_ITCTXB_TXB24 << _ITCTXB_TXB24_POSITION ) |
			( ITC_USER_ITCTXB_TXB25 << _ITCTXB_TXB25_POSITION ) |
			( ITC_USER_ITCTXB_TXB26 << _ITCTXB_TXB26_POSITION ) |
			( ITC_USER_ITCTXB_TXB27 << _ITCTXB_TXB27_POSITION ) |
			( ITC_USER_ITCTXB_TXB28 << _ITCTXB_TXB28_POSITION ) |
			( ITC_USER_ITCTXB_TXB29 << _ITCTXB_TXB29_POSITION ) |
			( ITC_USER_ITCTXB_TXB30 << _ITCTXB_TXB30_POSITION ) |
			( ITC_USER_ITCTXB_TXB31 << _ITCTXB_TXB31_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCTXBbits.TXB0 = ITC_USER_ITCTXB_TXB0;
			ITCTXBbits.TXB1 = ITC_USER_ITCTXB_TXB1;
			ITCTXBbits.TXB2 = ITC_USER_ITCTXB_TXB2;
			ITCTXBbits.TXB3 = ITC_USER_ITCTXB_TXB3;
			ITCTXBbits.TXB4 = ITC_USER_ITCTXB_TXB4;
			ITCTXBbits.TXB5 = ITC_USER_ITCTXB_TXB5;
			ITCTXBbits.TXB6 = ITC_USER_ITCTXB_TXB6;
			ITCTXBbits.TXB7 = ITC_USER_ITCTXB_TXB7;
			ITCTXBbits.TXB8 = ITC_USER_ITCTXB_TXB8;
			ITCTXBbits.TXB9 = ITC_USER_ITCTXB_TXB9;
			ITCTXBbits.TXB10 = ITC_USER_ITCTXB_TXB10;
			ITCTXBbits.TXB11 = ITC_USER_ITCTXB_TXB11;
			ITCTXBbits.TXB12 = ITC_USER_ITCTXB_TXB12;
			ITCTXBbits.TXB13 = ITC_USER_ITCTXB_TXB13;
			ITCTXBbits.TXB14 = ITC_USER_ITCTXB_TXB14;
			ITCTXBbits.TXB15 = ITC_USER_ITCTXB_TXB15;
			ITCTXBbits.TXB16 = ITC_USER_ITCTXB_TXB16;
			ITCTXBbits.TXB17 = ITC_USER_ITCTXB_TXB17;
			ITCTXBbits.TXB18 = ITC_USER_ITCTXB_TXB18;
			ITCTXBbits.TXB19 = ITC_USER_ITCTXB_TXB19;
			ITCTXBbits.TXB20 = ITC_USER_ITCTXB_TXB20;
			ITCTXBbits.TXB21 = ITC_USER_ITCTXB_TXB21;
			ITCTXBbits.TXB22 = ITC_USER_ITCTXB_TXB22;
			ITCTXBbits.TXB23 = ITC_USER_ITCTXB_TXB23;
			ITCTXBbits.TXB24 = ITC_USER_ITCTXB_TXB24;
			ITCTXBbits.TXB25 = ITC_USER_ITCTXB_TXB25;
			ITCTXBbits.TXB26 = ITC_USER_ITCTXB_TXB26;
			ITCTXBbits.TXB27 = ITC_USER_ITCTXB_TXB27;
			ITCTXBbits.TXB28 = ITC_USER_ITCTXB_TXB28;
			ITCTXBbits.TXB29 = ITC_USER_ITCTXB_TXB29;
			ITCTXBbits.TXB30 = ITC_USER_ITCTXB_TXB30;
			ITCTXBbits.TXB31 = ITC_USER_ITCTXB_TXB31;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCTXCレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCTXC = 
			( ITC_USER_ITCTXC_TXC0 << _ITCTXC_TXC0_POSITION ) |
			( ITC_USER_ITCTXC_TXC1 << _ITCTXC_TXC1_POSITION ) |
			( ITC_USER_ITCTXC_TXC2 << _ITCTXC_TXC2_POSITION ) |
			( ITC_USER_ITCTXC_TXC3 << _ITCTXC_TXC3_POSITION ) |
			( ITC_USER_ITCTXC_TXC4 << _ITCTXC_TXC4_POSITION ) |
			( ITC_USER_ITCTXC_TXC5 << _ITCTXC_TXC5_POSITION ) |
			( ITC_USER_ITCTXC_TXC6 << _ITCTXC_TXC6_POSITION ) |
			( ITC_USER_ITCTXC_TXC7 << _ITCTXC_TXC7_POSITION ) |
			( ITC_USER_ITCTXC_TXC8 << _ITCTXC_TXC8_POSITION ) |
			( ITC_USER_ITCTXC_TXC9 << _ITCTXC_TXC9_POSITION ) |
			( ITC_USER_ITCTXC_TXC10 << _ITCTXC_TXC10_POSITION ) |
			( ITC_USER_ITCTXC_TXC11 << _ITCTXC_TXC11_POSITION ) |
			( ITC_USER_ITCTXC_TXC12 << _ITCTXC_TXC12_POSITION ) |
			( ITC_USER_ITCTXC_TXC13 << _ITCTXC_TXC13_POSITION ) |
			( ITC_USER_ITCTXC_TXC14 << _ITCTXC_TXC14_POSITION ) |
			( ITC_USER_ITCTXC_TXC15 << _ITCTXC_TXC15_POSITION ) |
			( ITC_USER_ITCTXC_TXC16 << _ITCTXC_TXC16_POSITION ) |
			( ITC_USER_ITCTXC_TXC17 << _ITCTXC_TXC17_POSITION ) |
			( ITC_USER_ITCTXC_TXC18 << _ITCTXC_TXC18_POSITION ) |
			( ITC_USER_ITCTXC_TXC19 << _ITCTXC_TXC19_POSITION ) |
			( ITC_USER_ITCTXC_TXC20 << _ITCTXC_TXC20_POSITION ) |
			( ITC_USER_ITCTXC_TXC21 << _ITCTXC_TXC21_POSITION ) |
			( ITC_USER_ITCTXC_TXC22 << _ITCTXC_TXC22_POSITION ) |
			( ITC_USER_ITCTXC_TXC23 << _ITCTXC_TXC23_POSITION ) |
			( ITC_USER_ITCTXC_TXC24 << _ITCTXC_TXC24_POSITION ) |
			( ITC_USER_ITCTXC_TXC25 << _ITCTXC_TXC25_POSITION ) |
			( ITC_USER_ITCTXC_TXC26 << _ITCTXC_TXC26_POSITION ) |
			( ITC_USER_ITCTXC_TXC27 << _ITCTXC_TXC27_POSITION ) |
			( ITC_USER_ITCTXC_TXC28 << _ITCTXC_TXC28_POSITION ) |
			( ITC_USER_ITCTXC_TXC29 << _ITCTXC_TXC29_POSITION ) |
			( ITC_USER_ITCTXC_TXC30 << _ITCTXC_TXC30_POSITION ) |
			( ITC_USER_ITCTXC_TXC31 << _ITCTXC_TXC31_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCTXCbits.TXC0 = ITC_USER_ITCTXC_TXC0;
			ITCTXCbits.TXC1 = ITC_USER_ITCTXC_TXC1;
			ITCTXCbits.TXC2 = ITC_USER_ITCTXC_TXC2;
			ITCTXCbits.TXC3 = ITC_USER_ITCTXC_TXC3;
			ITCTXCbits.TXC4 = ITC_USER_ITCTXC_TXC4;
			ITCTXCbits.TXC5 = ITC_USER_ITCTXC_TXC5;
			ITCTXCbits.TXC6 = ITC_USER_ITCTXC_TXC6;
			ITCTXCbits.TXC7 = ITC_USER_ITCTXC_TXC7;
			ITCTXCbits.TXC8 = ITC_USER_ITCTXC_TXC8;
			ITCTXCbits.TXC9 = ITC_USER_ITCTXC_TXC9;
			ITCTXCbits.TXC10 = ITC_USER_ITCTXC_TXC10;
			ITCTXCbits.TXC11 = ITC_USER_ITCTXC_TXC11;
			ITCTXCbits.TXC12 = ITC_USER_ITCTXC_TXC12;
			ITCTXCbits.TXC13 = ITC_USER_ITCTXC_TXC13;
			ITCTXCbits.TXC14 = ITC_USER_ITCTXC_TXC14;
			ITCTXCbits.TXC15 = ITC_USER_ITCTXC_TXC15;
			ITCTXCbits.TXC16 = ITC_USER_ITCTXC_TXC16;
			ITCTXCbits.TXC17 = ITC_USER_ITCTXC_TXC17;
			ITCTXCbits.TXC18 = ITC_USER_ITCTXC_TXC18;
			ITCTXCbits.TXC19 = ITC_USER_ITCTXC_TXC19;
			ITCTXCbits.TXC20 = ITC_USER_ITCTXC_TXC20;
			ITCTXCbits.TXC21 = ITC_USER_ITCTXC_TXC21;
			ITCTXCbits.TXC22 = ITC_USER_ITCTXC_TXC22;
			ITCTXCbits.TXC23 = ITC_USER_ITCTXC_TXC23;
			ITCTXCbits.TXC24 = ITC_USER_ITCTXC_TXC24;
			ITCTXCbits.TXC25 = ITC_USER_ITCTXC_TXC25;
			ITCTXCbits.TXC26 = ITC_USER_ITCTXC_TXC26;
			ITCTXCbits.TXC27 = ITC_USER_ITCTXC_TXC27;
			ITCTXCbits.TXC28 = ITC_USER_ITCTXC_TXC28;
			ITCTXCbits.TXC29 = ITC_USER_ITCTXC_TXC29;
			ITCTXCbits.TXC30 = ITC_USER_ITCTXC_TXC30;
			ITCTXCbits.TXC31 = ITC_USER_ITCTXC_TXC31;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ADHITレジスタ */
	/*-----------------------------------------------------------------------*/
		ADHIT = 
			( ITC_USER_ADHIT_HIT0 << _ADHIT_HIT0_POSITION ) |
			( ITC_USER_ADHIT_HIT1 << _ADHIT_HIT1_POSITION ) |
			( ITC_USER_ADHIT_HIT2 << _ADHIT_HIT2_POSITION ) |
			( ITC_USER_ADHIT_HIT3 << _ADHIT_HIT3_POSITION ) |
			( ITC_USER_ADHIT_HIT4 << _ADHIT_HIT4_POSITION ) |
			( ITC_USER_ADHIT_HIT5 << _ADHIT_HIT5_POSITION ) |
			( ITC_USER_ADHIT_HIT6 << _ADHIT_HIT6_POSITION ) |
			( ITC_USER_ADHIT_HIT7 << _ADHIT_HIT7_POSITION ) |
			( ITC_USER_ADHIT_HIT8 << _ADHIT_HIT8_POSITION ) |
			( ITC_USER_ADHIT_HIT9 << _ADHIT_HIT9_POSITION ) |
			( ITC_USER_ADHIT_HIT10 << _ADHIT_HIT10_POSITION ) |
			( ITC_USER_ADHIT_HIT11 << _ADHIT_HIT11_POSITION ) |
			( ITC_USER_ADHIT_HIT12 << _ADHIT_HIT12_POSITION ) |
			( ITC_USER_ADHIT_HIT13 << _ADHIT_HIT13_POSITION ) |
			( ITC_USER_ADHIT_HIT14 << _ADHIT_HIT14_POSITION ) |
			( ITC_USER_ADHIT_HIT15 << _ADHIT_HIT15_POSITION ) |
			( ITC_USER_ADHIT_HIT16 << _ADHIT_HIT16_POSITION ) |
			( ITC_USER_ADHIT_HIT17 << _ADHIT_HIT17_POSITION ) |
			( ITC_USER_ADHIT_HIT18 << _ADHIT_HIT18_POSITION ) |
			( ITC_USER_ADHIT_HIT19 << _ADHIT_HIT19_POSITION ) |
			( ITC_USER_ADHIT_HIT20 << _ADHIT_HIT20_POSITION ) |
			( ITC_USER_ADHIT_HIT21 << _ADHIT_HIT21_POSITION ) |
			( ITC_USER_ADHIT_HIT22 << _ADHIT_HIT22_POSITION ) |
			( ITC_USER_ADHIT_HIT23 << _ADHIT_HIT23_POSITION ) |
			( ITC_USER_ADHIT_HIT24 << _ADHIT_HIT24_POSITION ) |
			( ITC_USER_ADHIT_HIT25 << _ADHIT_HIT25_POSITION ) |
			( ITC_USER_ADHIT_HIT26 << _ADHIT_HIT26_POSITION ) |
			( ITC_USER_ADHIT_HIT27 << _ADHIT_HIT27_POSITION ) |
			( ITC_USER_ADHIT_HIT28 << _ADHIT_HIT28_POSITION ) |
			( ITC_USER_ADHIT_HIT29 << _ADHIT_HIT29_POSITION ) |
			( ITC_USER_ADHIT_HIT30 << _ADHIT_HIT30_POSITION ) |
			( ITC_USER_ADHIT_HIT31 << _ADHIT_HIT31_POSITION ) ;
		#ifdef DEF_BITNAME
			ADHITbits.HIT0 = ITC_USER_ADHIT_HIT0;
			ADHITbits.HIT1 = ITC_USER_ADHIT_HIT1;
			ADHITbits.HIT2 = ITC_USER_ADHIT_HIT2;
			ADHITbits.HIT3 = ITC_USER_ADHIT_HIT3;
			ADHITbits.HIT4 = ITC_USER_ADHIT_HIT4;
			ADHITbits.HIT5 = ITC_USER_ADHIT_HIT5;
			ADHITbits.HIT6 = ITC_USER_ADHIT_HIT6;
			ADHITbits.HIT7 = ITC_USER_ADHIT_HIT7;
			ADHITbits.HIT8 = ITC_USER_ADHIT_HIT8;
			ADHITbits.HIT9 = ITC_USER_ADHIT_HIT9;
			ADHITbits.HIT10 = ITC_USER_ADHIT_HIT10;
			ADHITbits.HIT11 = ITC_USER_ADHIT_HIT11;
			ADHITbits.HIT12 = ITC_USER_ADHIT_HIT12;
			ADHITbits.HIT13 = ITC_USER_ADHIT_HIT13;
			ADHITbits.HIT14 = ITC_USER_ADHIT_HIT14;
			ADHITbits.HIT15 = ITC_USER_ADHIT_HIT15;
			ADHITbits.HIT16 = ITC_USER_ADHIT_HIT16;
			ADHITbits.HIT17 = ITC_USER_ADHIT_HIT17;
			ADHITbits.HIT18 = ITC_USER_ADHIT_HIT18;
			ADHITbits.HIT19 = ITC_USER_ADHIT_HIT19;
			ADHITbits.HIT20 = ITC_USER_ADHIT_HIT20;
			ADHITbits.HIT21 = ITC_USER_ADHIT_HIT21;
			ADHITbits.HIT22 = ITC_USER_ADHIT_HIT22;
			ADHITbits.HIT23 = ITC_USER_ADHIT_HIT23;
			ADHITbits.HIT24 = ITC_USER_ADHIT_HIT24;
			ADHITbits.HIT25 = ITC_USER_ADHIT_HIT25;
			ADHITbits.HIT26 = ITC_USER_ADHIT_HIT26;
			ADHITbits.HIT27 = ITC_USER_ADHIT_HIT27;
			ADHITbits.HIT28 = ITC_USER_ADHIT_HIT28;
			ADHITbits.HIT29 = ITC_USER_ADHIT_HIT29;
			ADHITbits.HIT30 = ITC_USER_ADHIT_HIT30;
			ADHITbits.HIT31 = ITC_USER_ADHIT_HIT31;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCLS0CONレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS0CON = 
			( ITC_USER_ITCLS0CON_RECCNT << _ITCLS0CON_RECCNT_POSITION ) |
			( ITC_USER_ITCLS0CON_SSRC << _ITCLS0CON_SSRC_POSITION ) |
			( ITC_USER_ITCLS0CON_TRGCLR << _ITCLS0CON_TRGCLR_POSITION ) |
			( ITC_USER_ITCLS0CON_SAMP << _ITCLS0CON_SAMP_POSITION ) |
			( ITC_USER_ITCLS0CON_TRGEN << _ITCLS0CON_TRGEN_POSITION ) |
			( ITC_USER_ITCLS0CON_SAMC << _ITCLS0CON_SAMC_POSITION ) |
			( ITC_USER_ITCLS0CON_MULCHEN << _ITCLS0CON_MULCHEN_POSITION ) |
			( ITC_USER_ITCLS0CON_DMAEN << _ITCLS0CON_DMAEN_POSITION ) |
			( ITC_USER_ITCLS0CON_CM << _ITCLS0CON_CM_POSITION ) |
			( ITC_USER_ITCLS0CON_WM << _ITCLS0CON_WM_POSITION ) |
			( ITC_USER_ITCLS0CON_MODE << _ITCLS0CON_MODE_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCLS0CONbits.RECCNT = ITC_USER_ITCLS0CON_RECCNT;
			ITCLS0CONbits.SSRC = ITC_USER_ITCLS0CON_SSRC;
			ITCLS0CONbits.TRGCLR = ITC_USER_ITCLS0CON_TRGCLR;
			ITCLS0CONbits.SAMP = ITC_USER_ITCLS0CON_SAMP;
			ITCLS0CONbits.TRGEN = ITC_USER_ITCLS0CON_TRGEN;
			ITCLS0CONbits.SAMC = ITC_USER_ITCLS0CON_SAMC;
			ITCLS0CONbits.MULCHEN = ITC_USER_ITCLS0CON_MULCHEN;
			ITCLS0CONbits.DMAEN = ITC_USER_ITCLS0CON_DMAEN;
			ITCLS0CONbits.CM = ITC_USER_ITCLS0CON_CM;
			ITCLS0CONbits.WM = ITC_USER_ITCLS0CON_WM;
			ITCLS0CONbits.MODE = ITC_USER_ITCLS0CON_MODE;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCLS0STATレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS0STAT = 
			( ITC_USER_ITCLS0STAT_NEXT << _ITCLS0STAT_NEXT_POSITION ) |
			( ITC_USER_ITCLS0STAT_INT << _ITCLS0STAT_INT_POSITION ) |
			( ITC_USER_ITCLS0STAT_BUSY << _ITCLS0STAT_BUSY_POSITION ) |
			( ITC_USER_ITCLS0STAT_TACT << _ITCLS0STAT_TACT_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCLS0STATbits.NEXT = ITC_USER_ITCLS0STAT_NEXT;
			ITCLS0STATbits.INT = ITC_USER_ITCLS0STAT_INT;
			ITCLS0STATbits.BUSY = ITC_USER_ITCLS0STAT_BUSY;
			ITCLS0STATbits.TACT = ITC_USER_ITCLS0STAT_TACT;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCLS0CMPHIレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS0CMPHI = ITC_USER_ITCLS0CMPHI;
	/*-----------------------------------------------------------------------*/
	/* ITCLS0CMPLOレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS0CMPLO = ITC_USER_ITCLS0CMPLO;
	/*-----------------------------------------------------------------------*/
	/* ITCLS0MULレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS0MUL = 
			( ITC_USER_ITCLS0MUL_MUL0 << _ITCLS0MUL_MUL0_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL1 << _ITCLS0MUL_MUL1_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL2 << _ITCLS0MUL_MUL2_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL3 << _ITCLS0MUL_MUL3_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL4 << _ITCLS0MUL_MUL4_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL5 << _ITCLS0MUL_MUL5_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL6 << _ITCLS0MUL_MUL6_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL7 << _ITCLS0MUL_MUL7_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL8 << _ITCLS0MUL_MUL8_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL9 << _ITCLS0MUL_MUL9_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL10 << _ITCLS0MUL_MUL10_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL11 << _ITCLS0MUL_MUL11_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL12 << _ITCLS0MUL_MUL12_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL13 << _ITCLS0MUL_MUL13_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL14 << _ITCLS0MUL_MUL14_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL15 << _ITCLS0MUL_MUL15_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL16 << _ITCLS0MUL_MUL16_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL17 << _ITCLS0MUL_MUL17_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL18 << _ITCLS0MUL_MUL18_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL19 << _ITCLS0MUL_MUL19_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL20 << _ITCLS0MUL_MUL20_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL21 << _ITCLS0MUL_MUL21_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL22 << _ITCLS0MUL_MUL22_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL23 << _ITCLS0MUL_MUL23_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL24 << _ITCLS0MUL_MUL24_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL25 << _ITCLS0MUL_MUL25_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL26 << _ITCLS0MUL_MUL26_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL27 << _ITCLS0MUL_MUL27_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL28 << _ITCLS0MUL_MUL28_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL29 << _ITCLS0MUL_MUL29_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL30 << _ITCLS0MUL_MUL30_POSITION ) |
			( ITC_USER_ITCLS0MUL_MUL31 << _ITCLS0MUL_MUL31_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCLS0MULbits.MUL0 = ITC_USER_ITCLS0MUL_MUL0;
			ITCLS0MULbits.MUL1 = ITC_USER_ITCLS0MUL_MUL1;
			ITCLS0MULbits.MUL2 = ITC_USER_ITCLS0MUL_MUL2;
			ITCLS0MULbits.MUL3 = ITC_USER_ITCLS0MUL_MUL3;
			ITCLS0MULbits.MUL4 = ITC_USER_ITCLS0MUL_MUL4;
			ITCLS0MULbits.MUL5 = ITC_USER_ITCLS0MUL_MUL5;
			ITCLS0MULbits.MUL6 = ITC_USER_ITCLS0MUL_MUL6;
			ITCLS0MULbits.MUL7 = ITC_USER_ITCLS0MUL_MUL7;
			ITCLS0MULbits.MUL8 = ITC_USER_ITCLS0MUL_MUL8;
			ITCLS0MULbits.MUL9 = ITC_USER_ITCLS0MUL_MUL9;
			ITCLS0MULbits.MUL10 = ITC_USER_ITCLS0MUL_MUL10;
			ITCLS0MULbits.MUL11 = ITC_USER_ITCLS0MUL_MUL11;
			ITCLS0MULbits.MUL12 = ITC_USER_ITCLS0MUL_MUL12;
			ITCLS0MULbits.MUL13 = ITC_USER_ITCLS0MUL_MUL13;
			ITCLS0MULbits.MUL14 = ITC_USER_ITCLS0MUL_MUL14;
			ITCLS0MULbits.MUL15 = ITC_USER_ITCLS0MUL_MUL15;
			ITCLS0MULbits.MUL16 = ITC_USER_ITCLS0MUL_MUL16;
			ITCLS0MULbits.MUL17 = ITC_USER_ITCLS0MUL_MUL17;
			ITCLS0MULbits.MUL18 = ITC_USER_ITCLS0MUL_MUL18;
			ITCLS0MULbits.MUL19 = ITC_USER_ITCLS0MUL_MUL19;
			ITCLS0MULbits.MUL20 = ITC_USER_ITCLS0MUL_MUL20;
			ITCLS0MULbits.MUL21 = ITC_USER_ITCLS0MUL_MUL21;
			ITCLS0MULbits.MUL22 = ITC_USER_ITCLS0MUL_MUL22;
			ITCLS0MULbits.MUL23 = ITC_USER_ITCLS0MUL_MUL23;
			ITCLS0MULbits.MUL24 = ITC_USER_ITCLS0MUL_MUL24;
			ITCLS0MULbits.MUL25 = ITC_USER_ITCLS0MUL_MUL25;
			ITCLS0MULbits.MUL26 = ITC_USER_ITCLS0MUL_MUL26;
			ITCLS0MULbits.MUL27 = ITC_USER_ITCLS0MUL_MUL27;
			ITCLS0MULbits.MUL28 = ITC_USER_ITCLS0MUL_MUL28;
			ITCLS0MULbits.MUL29 = ITC_USER_ITCLS0MUL_MUL29;
			ITCLS0MULbits.MUL30 = ITC_USER_ITCLS0MUL_MUL30;
			ITCLS0MULbits.MUL31 = ITC_USER_ITCLS0MUL_MUL31;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCLS0SEQレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS0SEQ = 
			( ITC_USER_ITCLS0SEQ_ACCCNT << _ITCLS0SEQ_ACCCNT_POSITION ) |
			( ITC_USER_ITCLS0SEQ_ACCEN << _ITCLS0SEQ_ACCEN_POSITION ) |
			( ITC_USER_ITCLS0SEQ_MATHSEQ << _ITCLS0SEQ_MATHSEQ_POSITION ) |
			( ITC_USER_ITCLS0SEQ_DATASEQ << _ITCLS0SEQ_DATASEQ_POSITION ) |
			( ITC_USER_ITCLS0SEQ_CVDCAP << _ITCLS0SEQ_CVDCAP_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCLS0SEQbits.ACCCNT = ITC_USER_ITCLS0SEQ_ACCCNT;
			ITCLS0SEQbits.ACCEN = ITC_USER_ITCLS0SEQ_ACCEN;
			ITCLS0SEQbits.MATHSEQ = ITC_USER_ITCLS0SEQ_MATHSEQ;
			ITCLS0SEQbits.DATASEQ = ITC_USER_ITCLS0SEQ_DATASEQ;
			ITCLS0SEQbits.CVDCAP = ITC_USER_ITCLS0SEQ_CVDCAP;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCLS0TMRレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS0TMR = 
			( ITC_USER_ITCLS0TMR_TMRA << _ITCLS0TMR_TMRA_POSITION ) |
			( ITC_USER_ITCLS0TMR_TMRB << _ITCLS0TMR_TMRB_POSITION ) |
			( ITC_USER_ITCLS0TMR_TMRC << _ITCLS0TMR_TMRC_POSITION ) |
			( ITC_USER_ITCLS0TMR_TMRD << _ITCLS0TMR_TMRD_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCLS0TMRbits.TMRA = ITC_USER_ITCLS0TMR_TMRA;
			ITCLS0TMRbits.TMRB = ITC_USER_ITCLS0TMR_TMRB;
			ITCLS0TMRbits.TMRC = ITC_USER_ITCLS0TMR_TMRC;
			ITCLS0TMRbits.TMRD = ITC_USER_ITCLS0TMR_TMRD;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCLS1CONレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS1CON = 
			( ITC_USER_ITCLS1CON_RECCNT << _ITCLS1CON_RECCNT_POSITION ) |
			( ITC_USER_ITCLS1CON_SSRC << _ITCLS1CON_SSRC_POSITION ) |
			( ITC_USER_ITCLS1CON_TRGCLR << _ITCLS1CON_TRGCLR_POSITION ) |
			( ITC_USER_ITCLS1CON_SAMP << _ITCLS1CON_SAMP_POSITION ) |
			( ITC_USER_ITCLS1CON_TRGEN << _ITCLS1CON_TRGEN_POSITION ) |
			( ITC_USER_ITCLS1CON_SAMC << _ITCLS1CON_SAMC_POSITION ) |
			( ITC_USER_ITCLS1CON_MULCHEN << _ITCLS1CON_MULCHEN_POSITION ) |
			( ITC_USER_ITCLS1CON_DMAEN << _ITCLS1CON_DMAEN_POSITION ) |
			( ITC_USER_ITCLS1CON_CM << _ITCLS1CON_CM_POSITION ) |
			( ITC_USER_ITCLS1CON_WM << _ITCLS1CON_WM_POSITION ) |
			( ITC_USER_ITCLS1CON_MODE << _ITCLS1CON_MODE_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCLS1CONbits.RECCNT = ITC_USER_ITCLS1CON_RECCNT;
			ITCLS1CONbits.SSRC = ITC_USER_ITCLS1CON_SSRC;
			ITCLS1CONbits.TRGCLR = ITC_USER_ITCLS1CON_TRGCLR;
			ITCLS1CONbits.SAMP = ITC_USER_ITCLS1CON_SAMP;
			ITCLS1CONbits.TRGEN = ITC_USER_ITCLS1CON_TRGEN;
			ITCLS1CONbits.SAMC = ITC_USER_ITCLS1CON_SAMC;
			ITCLS1CONbits.MULCHEN = ITC_USER_ITCLS1CON_MULCHEN;
			ITCLS1CONbits.DMAEN = ITC_USER_ITCLS1CON_DMAEN;
			ITCLS1CONbits.CM = ITC_USER_ITCLS1CON_CM;
			ITCLS1CONbits.WM = ITC_USER_ITCLS1CON_WM;
			ITCLS1CONbits.MODE = ITC_USER_ITCLS1CON_MODE;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCLS1STATレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS1STAT = 
			( ITC_USER_ITCLS1STAT_NEXT << _ITCLS1STAT_NEXT_POSITION ) |
			( ITC_USER_ITCLS1STAT_INT << _ITCLS1STAT_INT_POSITION ) |
			( ITC_USER_ITCLS1STAT_BUSY << _ITCLS1STAT_BUSY_POSITION ) |
			( ITC_USER_ITCLS1STAT_TACT << _ITCLS1STAT_TACT_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCLS1STATbits.NEXT = ITC_USER_ITCLS1STAT_NEXT;
			ITCLS1STATbits.INT = ITC_USER_ITCLS1STAT_INT;
			ITCLS1STATbits.BUSY = ITC_USER_ITCLS1STAT_BUSY;
			ITCLS1STATbits.TACT = ITC_USER_ITCLS1STAT_TACT;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCLS1CMPHIレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS1CMPHI = ITC_USER_ITCLS1CMPHI;
	/*-----------------------------------------------------------------------*/
	/* ITCLS1CMPLOレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS1CMPLO = ITC_USER_ITCLS1CMPLO;
	/*-----------------------------------------------------------------------*/
	/* ITCLS1MULレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS1MUL = 
			( ITC_USER_ITCLS1MUL_MUL0 << _ITCLS1MUL_MUL0_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL1 << _ITCLS1MUL_MUL1_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL2 << _ITCLS1MUL_MUL2_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL3 << _ITCLS1MUL_MUL3_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL4 << _ITCLS1MUL_MUL4_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL5 << _ITCLS1MUL_MUL5_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL6 << _ITCLS1MUL_MUL6_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL7 << _ITCLS1MUL_MUL7_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL8 << _ITCLS1MUL_MUL8_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL9 << _ITCLS1MUL_MUL9_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL10 << _ITCLS1MUL_MUL10_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL11 << _ITCLS1MUL_MUL11_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL12 << _ITCLS1MUL_MUL12_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL13 << _ITCLS1MUL_MUL13_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL14 << _ITCLS1MUL_MUL14_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL15 << _ITCLS1MUL_MUL15_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL16 << _ITCLS1MUL_MUL16_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL17 << _ITCLS1MUL_MUL17_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL18 << _ITCLS1MUL_MUL18_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL19 << _ITCLS1MUL_MUL19_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL20 << _ITCLS1MUL_MUL20_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL21 << _ITCLS1MUL_MUL21_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL22 << _ITCLS1MUL_MUL22_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL23 << _ITCLS1MUL_MUL23_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL24 << _ITCLS1MUL_MUL24_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL25 << _ITCLS1MUL_MUL25_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL26 << _ITCLS1MUL_MUL26_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL27 << _ITCLS1MUL_MUL27_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL28 << _ITCLS1MUL_MUL28_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL29 << _ITCLS1MUL_MUL29_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL30 << _ITCLS1MUL_MUL30_POSITION ) |
			( ITC_USER_ITCLS1MUL_MUL31 << _ITCLS1MUL_MUL31_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCLS1MULbits.MUL0 = ITC_USER_ITCLS1MUL_MUL0;
			ITCLS1MULbits.MUL1 = ITC_USER_ITCLS1MUL_MUL1;
			ITCLS1MULbits.MUL2 = ITC_USER_ITCLS1MUL_MUL2;
			ITCLS1MULbits.MUL3 = ITC_USER_ITCLS1MUL_MUL3;
			ITCLS1MULbits.MUL4 = ITC_USER_ITCLS1MUL_MUL4;
			ITCLS1MULbits.MUL5 = ITC_USER_ITCLS1MUL_MUL5;
			ITCLS1MULbits.MUL6 = ITC_USER_ITCLS1MUL_MUL6;
			ITCLS1MULbits.MUL7 = ITC_USER_ITCLS1MUL_MUL7;
			ITCLS1MULbits.MUL8 = ITC_USER_ITCLS1MUL_MUL8;
			ITCLS1MULbits.MUL9 = ITC_USER_ITCLS1MUL_MUL9;
			ITCLS1MULbits.MUL10 = ITC_USER_ITCLS1MUL_MUL10;
			ITCLS1MULbits.MUL11 = ITC_USER_ITCLS1MUL_MUL11;
			ITCLS1MULbits.MUL12 = ITC_USER_ITCLS1MUL_MUL12;
			ITCLS1MULbits.MUL13 = ITC_USER_ITCLS1MUL_MUL13;
			ITCLS1MULbits.MUL14 = ITC_USER_ITCLS1MUL_MUL14;
			ITCLS1MULbits.MUL15 = ITC_USER_ITCLS1MUL_MUL15;
			ITCLS1MULbits.MUL16 = ITC_USER_ITCLS1MUL_MUL16;
			ITCLS1MULbits.MUL17 = ITC_USER_ITCLS1MUL_MUL17;
			ITCLS1MULbits.MUL18 = ITC_USER_ITCLS1MUL_MUL18;
			ITCLS1MULbits.MUL19 = ITC_USER_ITCLS1MUL_MUL19;
			ITCLS1MULbits.MUL20 = ITC_USER_ITCLS1MUL_MUL20;
			ITCLS1MULbits.MUL21 = ITC_USER_ITCLS1MUL_MUL21;
			ITCLS1MULbits.MUL22 = ITC_USER_ITCLS1MUL_MUL22;
			ITCLS1MULbits.MUL23 = ITC_USER_ITCLS1MUL_MUL23;
			ITCLS1MULbits.MUL24 = ITC_USER_ITCLS1MUL_MUL24;
			ITCLS1MULbits.MUL25 = ITC_USER_ITCLS1MUL_MUL25;
			ITCLS1MULbits.MUL26 = ITC_USER_ITCLS1MUL_MUL26;
			ITCLS1MULbits.MUL27 = ITC_USER_ITCLS1MUL_MUL27;
			ITCLS1MULbits.MUL28 = ITC_USER_ITCLS1MUL_MUL28;
			ITCLS1MULbits.MUL29 = ITC_USER_ITCLS1MUL_MUL29;
			ITCLS1MULbits.MUL30 = ITC_USER_ITCLS1MUL_MUL30;
			ITCLS1MULbits.MUL31 = ITC_USER_ITCLS1MUL_MUL31;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCLS1SEQレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS1SEQ = 
			( ITC_USER_ITCLS1SEQ_ACCCNT << _ITCLS1SEQ_ACCCNT_POSITION ) |
			( ITC_USER_ITCLS1SEQ_ACCEN << _ITCLS1SEQ_ACCEN_POSITION ) |
			( ITC_USER_ITCLS1SEQ_MATHSEQ << _ITCLS1SEQ_MATHSEQ_POSITION ) |
			( ITC_USER_ITCLS1SEQ_DATASEQ << _ITCLS1SEQ_DATASEQ_POSITION ) |
			( ITC_USER_ITCLS1SEQ_CVDCAP << _ITCLS1SEQ_CVDCAP_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCLS1SEQbits.ACCCNT = ITC_USER_ITCLS1SEQ_ACCCNT;
			ITCLS1SEQbits.ACCEN = ITC_USER_ITCLS1SEQ_ACCEN;
			ITCLS1SEQbits.MATHSEQ = ITC_USER_ITCLS1SEQ_MATHSEQ;
			ITCLS1SEQbits.DATASEQ = ITC_USER_ITCLS1SEQ_DATASEQ;
			ITCLS1SEQbits.CVDCAP = ITC_USER_ITCLS1SEQ_CVDCAP;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCLS1TMRレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS1TMR = 
			( ITC_USER_ITCLS1TMR_TMRA << _ITCLS1TMR_TMRA_POSITION ) |
			( ITC_USER_ITCLS1TMR_TMRB << _ITCLS1TMR_TMRB_POSITION ) |
			( ITC_USER_ITCLS1TMR_TMRC << _ITCLS1TMR_TMRC_POSITION ) |
			( ITC_USER_ITCLS1TMR_TMRD << _ITCLS1TMR_TMRD_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCLS1TMRbits.TMRA = ITC_USER_ITCLS1TMR_TMRA;
			ITCLS1TMRbits.TMRB = ITC_USER_ITCLS1TMR_TMRB;
			ITCLS1TMRbits.TMRC = ITC_USER_ITCLS1TMR_TMRC;
			ITCLS1TMRbits.TMRD = ITC_USER_ITCLS1TMR_TMRD;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCLS2CONレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS2CON = 
			( ITC_USER_ITCLS2CON_RECCNT << _ITCLS2CON_RECCNT_POSITION ) |
			( ITC_USER_ITCLS2CON_SSRC << _ITCLS2CON_SSRC_POSITION ) |
			( ITC_USER_ITCLS2CON_TRGCLR << _ITCLS2CON_TRGCLR_POSITION ) |
			( ITC_USER_ITCLS2CON_SAMP << _ITCLS2CON_SAMP_POSITION ) |
			( ITC_USER_ITCLS2CON_TRGEN << _ITCLS2CON_TRGEN_POSITION ) |
			( ITC_USER_ITCLS2CON_SAMC << _ITCLS2CON_SAMC_POSITION ) |
			( ITC_USER_ITCLS2CON_MULCHEN << _ITCLS2CON_MULCHEN_POSITION ) |
			( ITC_USER_ITCLS2CON_DMAEN << _ITCLS2CON_DMAEN_POSITION ) |
			( ITC_USER_ITCLS2CON_CM << _ITCLS2CON_CM_POSITION ) |
			( ITC_USER_ITCLS2CON_WM << _ITCLS2CON_WM_POSITION ) |
			( ITC_USER_ITCLS2CON_MODE << _ITCLS2CON_MODE_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCLS2CONbits.RECCNT = ITC_USER_ITCLS2CON_RECCNT;
			ITCLS2CONbits.SSRC = ITC_USER_ITCLS2CON_SSRC;
			ITCLS2CONbits.TRGCLR = ITC_USER_ITCLS2CON_TRGCLR;
			ITCLS2CONbits.SAMP = ITC_USER_ITCLS2CON_SAMP;
			ITCLS2CONbits.TRGEN = ITC_USER_ITCLS2CON_TRGEN;
			ITCLS2CONbits.SAMC = ITC_USER_ITCLS2CON_SAMC;
			ITCLS2CONbits.MULCHEN = ITC_USER_ITCLS2CON_MULCHEN;
			ITCLS2CONbits.DMAEN = ITC_USER_ITCLS2CON_DMAEN;
			ITCLS2CONbits.CM = ITC_USER_ITCLS2CON_CM;
			ITCLS2CONbits.WM = ITC_USER_ITCLS2CON_WM;
			ITCLS2CONbits.MODE = ITC_USER_ITCLS2CON_MODE;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCLS2STATレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS2STAT = 
			( ITC_USER_ITCLS2STAT_NEXT << _ITCLS2STAT_NEXT_POSITION ) |
			( ITC_USER_ITCLS2STAT_INT << _ITCLS2STAT_INT_POSITION ) |
			( ITC_USER_ITCLS2STAT_BUSY << _ITCLS2STAT_BUSY_POSITION ) |
			( ITC_USER_ITCLS2STAT_TACT << _ITCLS2STAT_TACT_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCLS2STATbits.NEXT = ITC_USER_ITCLS2STAT_NEXT;
			ITCLS2STATbits.INT = ITC_USER_ITCLS2STAT_INT;
			ITCLS2STATbits.BUSY = ITC_USER_ITCLS2STAT_BUSY;
			ITCLS2STATbits.TACT = ITC_USER_ITCLS2STAT_TACT;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCLS2CMPHIレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS2CMPHI = ITC_USER_ITCLS2CMPHI;
	/*-----------------------------------------------------------------------*/
	/* ITCLS2CMPLOレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS2CMPLO = ITC_USER_ITCLS2CMPLO;
	/*-----------------------------------------------------------------------*/
	/* ITCLS2MULレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS2MUL = 
			( ITC_USER_ITCLS2MUL_MUL0 << _ITCLS2MUL_MUL0_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL1 << _ITCLS2MUL_MUL1_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL2 << _ITCLS2MUL_MUL2_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL3 << _ITCLS2MUL_MUL3_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL4 << _ITCLS2MUL_MUL4_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL5 << _ITCLS2MUL_MUL5_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL6 << _ITCLS2MUL_MUL6_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL7 << _ITCLS2MUL_MUL7_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL8 << _ITCLS2MUL_MUL8_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL9 << _ITCLS2MUL_MUL9_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL10 << _ITCLS2MUL_MUL10_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL11 << _ITCLS2MUL_MUL11_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL12 << _ITCLS2MUL_MUL12_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL13 << _ITCLS2MUL_MUL13_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL14 << _ITCLS2MUL_MUL14_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL15 << _ITCLS2MUL_MUL15_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL16 << _ITCLS2MUL_MUL16_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL17 << _ITCLS2MUL_MUL17_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL18 << _ITCLS2MUL_MUL18_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL19 << _ITCLS2MUL_MUL19_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL20 << _ITCLS2MUL_MUL20_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL21 << _ITCLS2MUL_MUL21_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL22 << _ITCLS2MUL_MUL22_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL23 << _ITCLS2MUL_MUL23_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL24 << _ITCLS2MUL_MUL24_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL25 << _ITCLS2MUL_MUL25_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL26 << _ITCLS2MUL_MUL26_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL27 << _ITCLS2MUL_MUL27_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL28 << _ITCLS2MUL_MUL28_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL29 << _ITCLS2MUL_MUL29_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL30 << _ITCLS2MUL_MUL30_POSITION ) |
			( ITC_USER_ITCLS2MUL_MUL31 << _ITCLS2MUL_MUL31_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCLS2MULbits.MUL0 = ITC_USER_ITCLS2MUL_MUL0;
			ITCLS2MULbits.MUL1 = ITC_USER_ITCLS2MUL_MUL1;
			ITCLS2MULbits.MUL2 = ITC_USER_ITCLS2MUL_MUL2;
			ITCLS2MULbits.MUL3 = ITC_USER_ITCLS2MUL_MUL3;
			ITCLS2MULbits.MUL4 = ITC_USER_ITCLS2MUL_MUL4;
			ITCLS2MULbits.MUL5 = ITC_USER_ITCLS2MUL_MUL5;
			ITCLS2MULbits.MUL6 = ITC_USER_ITCLS2MUL_MUL6;
			ITCLS2MULbits.MUL7 = ITC_USER_ITCLS2MUL_MUL7;
			ITCLS2MULbits.MUL8 = ITC_USER_ITCLS2MUL_MUL8;
			ITCLS2MULbits.MUL9 = ITC_USER_ITCLS2MUL_MUL9;
			ITCLS2MULbits.MUL10 = ITC_USER_ITCLS2MUL_MUL10;
			ITCLS2MULbits.MUL11 = ITC_USER_ITCLS2MUL_MUL11;
			ITCLS2MULbits.MUL12 = ITC_USER_ITCLS2MUL_MUL12;
			ITCLS2MULbits.MUL13 = ITC_USER_ITCLS2MUL_MUL13;
			ITCLS2MULbits.MUL14 = ITC_USER_ITCLS2MUL_MUL14;
			ITCLS2MULbits.MUL15 = ITC_USER_ITCLS2MUL_MUL15;
			ITCLS2MULbits.MUL16 = ITC_USER_ITCLS2MUL_MUL16;
			ITCLS2MULbits.MUL17 = ITC_USER_ITCLS2MUL_MUL17;
			ITCLS2MULbits.MUL18 = ITC_USER_ITCLS2MUL_MUL18;
			ITCLS2MULbits.MUL19 = ITC_USER_ITCLS2MUL_MUL19;
			ITCLS2MULbits.MUL20 = ITC_USER_ITCLS2MUL_MUL20;
			ITCLS2MULbits.MUL21 = ITC_USER_ITCLS2MUL_MUL21;
			ITCLS2MULbits.MUL22 = ITC_USER_ITCLS2MUL_MUL22;
			ITCLS2MULbits.MUL23 = ITC_USER_ITCLS2MUL_MUL23;
			ITCLS2MULbits.MUL24 = ITC_USER_ITCLS2MUL_MUL24;
			ITCLS2MULbits.MUL25 = ITC_USER_ITCLS2MUL_MUL25;
			ITCLS2MULbits.MUL26 = ITC_USER_ITCLS2MUL_MUL26;
			ITCLS2MULbits.MUL27 = ITC_USER_ITCLS2MUL_MUL27;
			ITCLS2MULbits.MUL28 = ITC_USER_ITCLS2MUL_MUL28;
			ITCLS2MULbits.MUL29 = ITC_USER_ITCLS2MUL_MUL29;
			ITCLS2MULbits.MUL30 = ITC_USER_ITCLS2MUL_MUL30;
			ITCLS2MULbits.MUL31 = ITC_USER_ITCLS2MUL_MUL31;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCLS2SEQレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS2SEQ = 
			( ITC_USER_ITCLS2SEQ_ACCCNT << _ITCLS2SEQ_ACCCNT_POSITION ) |
			( ITC_USER_ITCLS2SEQ_ACCEN << _ITCLS2SEQ_ACCEN_POSITION ) |
			( ITC_USER_ITCLS2SEQ_MATHSEQ << _ITCLS2SEQ_MATHSEQ_POSITION ) |
			( ITC_USER_ITCLS2SEQ_DATASEQ << _ITCLS2SEQ_DATASEQ_POSITION ) |
			( ITC_USER_ITCLS2SEQ_CVDCAP << _ITCLS2SEQ_CVDCAP_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCLS2SEQbits.ACCCNT = ITC_USER_ITCLS2SEQ_ACCCNT;
			ITCLS2SEQbits.ACCEN = ITC_USER_ITCLS2SEQ_ACCEN;
			ITCLS2SEQbits.MATHSEQ = ITC_USER_ITCLS2SEQ_MATHSEQ;
			ITCLS2SEQbits.DATASEQ = ITC_USER_ITCLS2SEQ_DATASEQ;
			ITCLS2SEQbits.CVDCAP = ITC_USER_ITCLS2SEQ_CVDCAP;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCLS2TMRレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCLS2TMR = 
			( ITC_USER_ITCLS2TMR_TMRA << _ITCLS2TMR_TMRA_POSITION ) |
			( ITC_USER_ITCLS2TMR_TMRB << _ITCLS2TMR_TMRB_POSITION ) |
			( ITC_USER_ITCLS2TMR_TMRC << _ITCLS2TMR_TMRC_POSITION ) |
			( ITC_USER_ITCLS2TMR_TMRD << _ITCLS2TMR_TMRD_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCLS2TMRbits.TMRA = ITC_USER_ITCLS2TMR_TMRA;
			ITCLS2TMRbits.TMRB = ITC_USER_ITCLS2TMR_TMRB;
			ITCLS2TMRbits.TMRC = ITC_USER_ITCLS2TMR_TMRC;
			ITCLS2TMRbits.TMRD = ITC_USER_ITCLS2TMR_TMRD;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCREC0レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCREC0 = 
			( ITC_USER_ITCREC0_PIN0 << _ITCREC0_PIN0_POSITION ) |
			( ITC_USER_ITCREC0_ACCDONE0 << _ITCREC0_ACCDONE0_POSITION ) |
			( ITC_USER_ITCREC0_GRDA0 << _ITCREC0_GRDA0_POSITION ) |
			( ITC_USER_ITCREC0_GRDB0 << _ITCREC0_GRDB0_POSITION ) |
			( ITC_USER_ITCREC0_PIN1 << _ITCREC0_PIN1_POSITION ) |
			( ITC_USER_ITCREC0_ACCDONE1 << _ITCREC0_ACCDONE1_POSITION ) |
			( ITC_USER_ITCREC0_GRDA1 << _ITCREC0_GRDA1_POSITION ) |
			( ITC_USER_ITCREC0_GRDB1 << _ITCREC0_GRDB1_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCREC0bits.PIN0 = ITC_USER_ITCREC0_PIN0;
			ITCREC0bits.ACCDONE0 = ITC_USER_ITCREC0_ACCDONE0;
			ITCREC0bits.GRDA0 = ITC_USER_ITCREC0_GRDA0;
			ITCREC0bits.GRDB0 = ITC_USER_ITCREC0_GRDB0;
			ITCREC0bits.PIN1 = ITC_USER_ITCREC0_PIN1;
			ITCREC0bits.ACCDONE1 = ITC_USER_ITCREC0_ACCDONE1;
			ITCREC0bits.GRDA1 = ITC_USER_ITCREC0_GRDA1;
			ITCREC0bits.GRDB1 = ITC_USER_ITCREC0_GRDB1;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCREC1レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCREC1 = 
			( ITC_USER_ITCREC1_PIN2 << _ITCREC1_PIN2_POSITION ) |
			( ITC_USER_ITCREC1_ACCDONE2 << _ITCREC1_ACCDONE2_POSITION ) |
			( ITC_USER_ITCREC1_GRDA2 << _ITCREC1_GRDA2_POSITION ) |
			( ITC_USER_ITCREC1_GRDB2 << _ITCREC1_GRDB2_POSITION ) |
			( ITC_USER_ITCREC1_PIN3 << _ITCREC1_PIN3_POSITION ) |
			( ITC_USER_ITCREC1_ACCDONE3 << _ITCREC1_ACCDONE3_POSITION ) |
			( ITC_USER_ITCREC1_GRDA3 << _ITCREC1_GRDA3_POSITION ) |
			( ITC_USER_ITCREC1_GRDB3 << _ITCREC1_GRDB3_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCREC1bits.PIN2 = ITC_USER_ITCREC1_PIN2;
			ITCREC1bits.ACCDONE2 = ITC_USER_ITCREC1_ACCDONE2;
			ITCREC1bits.GRDA2 = ITC_USER_ITCREC1_GRDA2;
			ITCREC1bits.GRDB2 = ITC_USER_ITCREC1_GRDB2;
			ITCREC1bits.PIN3 = ITC_USER_ITCREC1_PIN3;
			ITCREC1bits.ACCDONE3 = ITC_USER_ITCREC1_ACCDONE3;
			ITCREC1bits.GRDA3 = ITC_USER_ITCREC1_GRDA3;
			ITCREC1bits.GRDB3 = ITC_USER_ITCREC1_GRDB3;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCREC2レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCREC2 = 
			( ITC_USER_ITCREC2_PIN4 << _ITCREC2_PIN4_POSITION ) |
			( ITC_USER_ITCREC2_ACCDONE4 << _ITCREC2_ACCDONE4_POSITION ) |
			( ITC_USER_ITCREC2_GRDA4 << _ITCREC2_GRDA4_POSITION ) |
			( ITC_USER_ITCREC2_GRDB4 << _ITCREC2_GRDB4_POSITION ) |
			( ITC_USER_ITCREC2_PIN5 << _ITCREC2_PIN5_POSITION ) |
			( ITC_USER_ITCREC2_ACCDONE5 << _ITCREC2_ACCDONE5_POSITION ) |
			( ITC_USER_ITCREC2_GRDA5 << _ITCREC2_GRDA5_POSITION ) |
			( ITC_USER_ITCREC2_GRDB5 << _ITCREC2_GRDB5_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCREC2bits.PIN4 = ITC_USER_ITCREC2_PIN4;
			ITCREC2bits.ACCDONE4 = ITC_USER_ITCREC2_ACCDONE4;
			ITCREC2bits.GRDA4 = ITC_USER_ITCREC2_GRDA4;
			ITCREC2bits.GRDB4 = ITC_USER_ITCREC2_GRDB4;
			ITCREC2bits.PIN5 = ITC_USER_ITCREC2_PIN5;
			ITCREC2bits.ACCDONE5 = ITC_USER_ITCREC2_ACCDONE5;
			ITCREC2bits.GRDA5 = ITC_USER_ITCREC2_GRDA5;
			ITCREC2bits.GRDB5 = ITC_USER_ITCREC2_GRDB5;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCREC3レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCREC3 = 
			( ITC_USER_ITCREC3_PIN6 << _ITCREC3_PIN6_POSITION ) |
			( ITC_USER_ITCREC3_ACCDONE6 << _ITCREC3_ACCDONE6_POSITION ) |
			( ITC_USER_ITCREC3_GRDA6 << _ITCREC3_GRDA6_POSITION ) |
			( ITC_USER_ITCREC3_GRDB6 << _ITCREC3_GRDB6_POSITION ) |
			( ITC_USER_ITCREC3_PIN7 << _ITCREC3_PIN7_POSITION ) |
			( ITC_USER_ITCREC3_ACCDONE7 << _ITCREC3_ACCDONE7_POSITION ) |
			( ITC_USER_ITCREC3_GRDA7 << _ITCREC3_GRDA7_POSITION ) |
			( ITC_USER_ITCREC3_GRDB7 << _ITCREC3_GRDB7_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCREC3bits.PIN6 = ITC_USER_ITCREC3_PIN6;
			ITCREC3bits.ACCDONE6 = ITC_USER_ITCREC3_ACCDONE6;
			ITCREC3bits.GRDA6 = ITC_USER_ITCREC3_GRDA6;
			ITCREC3bits.GRDB6 = ITC_USER_ITCREC3_GRDB6;
			ITCREC3bits.PIN7 = ITC_USER_ITCREC3_PIN7;
			ITCREC3bits.ACCDONE7 = ITC_USER_ITCREC3_ACCDONE7;
			ITCREC3bits.GRDA7 = ITC_USER_ITCREC3_GRDA7;
			ITCREC3bits.GRDB7 = ITC_USER_ITCREC3_GRDB7;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCREC4レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCREC4 = 
			( ITC_USER_ITCREC4_PIN8 << _ITCREC4_PIN8_POSITION ) |
			( ITC_USER_ITCREC4_ACCDONE8 << _ITCREC4_ACCDONE8_POSITION ) |
			( ITC_USER_ITCREC4_GRDA8 << _ITCREC4_GRDA8_POSITION ) |
			( ITC_USER_ITCREC4_GRDB8 << _ITCREC4_GRDB8_POSITION ) |
			( ITC_USER_ITCREC4_PIN9 << _ITCREC4_PIN9_POSITION ) |
			( ITC_USER_ITCREC4_ACCDONE9 << _ITCREC4_ACCDONE9_POSITION ) |
			( ITC_USER_ITCREC4_GRDA9 << _ITCREC4_GRDA9_POSITION ) |
			( ITC_USER_ITCREC4_GRDB9 << _ITCREC4_GRDB9_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCREC4bits.PIN8 = ITC_USER_ITCREC4_PIN8;
			ITCREC4bits.ACCDONE8 = ITC_USER_ITCREC4_ACCDONE8;
			ITCREC4bits.GRDA8 = ITC_USER_ITCREC4_GRDA8;
			ITCREC4bits.GRDB8 = ITC_USER_ITCREC4_GRDB8;
			ITCREC4bits.PIN9 = ITC_USER_ITCREC4_PIN9;
			ITCREC4bits.ACCDONE9 = ITC_USER_ITCREC4_ACCDONE9;
			ITCREC4bits.GRDA9 = ITC_USER_ITCREC4_GRDA9;
			ITCREC4bits.GRDB9 = ITC_USER_ITCREC4_GRDB9;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCREC5レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCREC5 = 
			( ITC_USER_ITCREC5_PIN10 << _ITCREC5_PIN10_POSITION ) |
			( ITC_USER_ITCREC5_ACCDONE10 << _ITCREC5_ACCDONE10_POSITION ) |
			( ITC_USER_ITCREC5_GRDA10 << _ITCREC5_GRDA10_POSITION ) |
			( ITC_USER_ITCREC5_GRDB10 << _ITCREC5_GRDB10_POSITION ) |
			( ITC_USER_ITCREC5_PIN11 << _ITCREC5_PIN11_POSITION ) |
			( ITC_USER_ITCREC5_ACCDONE11 << _ITCREC5_ACCDONE11_POSITION ) |
			( ITC_USER_ITCREC5_GRDA11 << _ITCREC5_GRDA11_POSITION ) |
			( ITC_USER_ITCREC5_GRDB11 << _ITCREC5_GRDB11_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCREC5bits.PIN10 = ITC_USER_ITCREC5_PIN10;
			ITCREC5bits.ACCDONE10 = ITC_USER_ITCREC5_ACCDONE10;
			ITCREC5bits.GRDA10 = ITC_USER_ITCREC5_GRDA10;
			ITCREC5bits.GRDB10 = ITC_USER_ITCREC5_GRDB10;
			ITCREC5bits.PIN11 = ITC_USER_ITCREC5_PIN11;
			ITCREC5bits.ACCDONE11 = ITC_USER_ITCREC5_ACCDONE11;
			ITCREC5bits.GRDA11 = ITC_USER_ITCREC5_GRDA11;
			ITCREC5bits.GRDB11 = ITC_USER_ITCREC5_GRDB11;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCREC6レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCREC6 = 
			( ITC_USER_ITCREC6_PIN12 << _ITCREC6_PIN12_POSITION ) |
			( ITC_USER_ITCREC6_ACCDONE12 << _ITCREC6_ACCDONE12_POSITION ) |
			( ITC_USER_ITCREC6_GRDA12 << _ITCREC6_GRDA12_POSITION ) |
			( ITC_USER_ITCREC6_GRDB12 << _ITCREC6_GRDB12_POSITION ) |
			( ITC_USER_ITCREC6_PIN13 << _ITCREC6_PIN13_POSITION ) |
			( ITC_USER_ITCREC6_ACCDONE13 << _ITCREC6_ACCDONE13_POSITION ) |
			( ITC_USER_ITCREC6_GRDA13 << _ITCREC6_GRDA13_POSITION ) |
			( ITC_USER_ITCREC6_GRDB13 << _ITCREC6_GRDB13_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCREC6bits.PIN12 = ITC_USER_ITCREC6_PIN12;
			ITCREC6bits.ACCDONE12 = ITC_USER_ITCREC6_ACCDONE12;
			ITCREC6bits.GRDA12 = ITC_USER_ITCREC6_GRDA12;
			ITCREC6bits.GRDB12 = ITC_USER_ITCREC6_GRDB12;
			ITCREC6bits.PIN13 = ITC_USER_ITCREC6_PIN13;
			ITCREC6bits.ACCDONE13 = ITC_USER_ITCREC6_ACCDONE13;
			ITCREC6bits.GRDA13 = ITC_USER_ITCREC6_GRDA13;
			ITCREC6bits.GRDB13 = ITC_USER_ITCREC6_GRDB13;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCREC7レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCREC7 = 
			( ITC_USER_ITCREC7_PIN14 << _ITCREC7_PIN14_POSITION ) |
			( ITC_USER_ITCREC7_ACCDONE14 << _ITCREC7_ACCDONE14_POSITION ) |
			( ITC_USER_ITCREC7_GRDA14 << _ITCREC7_GRDA14_POSITION ) |
			( ITC_USER_ITCREC7_GRDB14 << _ITCREC7_GRDB14_POSITION ) |
			( ITC_USER_ITCREC7_PIN15 << _ITCREC7_PIN15_POSITION ) |
			( ITC_USER_ITCREC7_ACCDONE15 << _ITCREC7_ACCDONE15_POSITION ) |
			( ITC_USER_ITCREC7_GRDA15 << _ITCREC7_GRDA15_POSITION ) |
			( ITC_USER_ITCREC7_GRDB15 << _ITCREC7_GRDB15_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCREC7bits.PIN14 = ITC_USER_ITCREC7_PIN14;
			ITCREC7bits.ACCDONE14 = ITC_USER_ITCREC7_ACCDONE14;
			ITCREC7bits.GRDA14 = ITC_USER_ITCREC7_GRDA14;
			ITCREC7bits.GRDB14 = ITC_USER_ITCREC7_GRDB14;
			ITCREC7bits.PIN15 = ITC_USER_ITCREC7_PIN15;
			ITCREC7bits.ACCDONE15 = ITC_USER_ITCREC7_ACCDONE15;
			ITCREC7bits.GRDA15 = ITC_USER_ITCREC7_GRDA15;
			ITCREC7bits.GRDB15 = ITC_USER_ITCREC7_GRDB15;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCREC8レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCREC8 = 
			( ITC_USER_ITCREC8_PIN16 << _ITCREC8_PIN16_POSITION ) |
			( ITC_USER_ITCREC8_ACCDONE16 << _ITCREC8_ACCDONE16_POSITION ) |
			( ITC_USER_ITCREC8_GRDA16 << _ITCREC8_GRDA16_POSITION ) |
			( ITC_USER_ITCREC8_GRDB16 << _ITCREC8_GRDB16_POSITION ) |
			( ITC_USER_ITCREC8_PIN17 << _ITCREC8_PIN17_POSITION ) |
			( ITC_USER_ITCREC8_ACCDONE17 << _ITCREC8_ACCDONE17_POSITION ) |
			( ITC_USER_ITCREC8_GRDA17 << _ITCREC8_GRDA17_POSITION ) |
			( ITC_USER_ITCREC8_GRDB17 << _ITCREC8_GRDB17_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCREC8bits.PIN16 = ITC_USER_ITCREC8_PIN16;
			ITCREC8bits.ACCDONE16 = ITC_USER_ITCREC8_ACCDONE16;
			ITCREC8bits.GRDA16 = ITC_USER_ITCREC8_GRDA16;
			ITCREC8bits.GRDB16 = ITC_USER_ITCREC8_GRDB16;
			ITCREC8bits.PIN17 = ITC_USER_ITCREC8_PIN17;
			ITCREC8bits.ACCDONE17 = ITC_USER_ITCREC8_ACCDONE17;
			ITCREC8bits.GRDA17 = ITC_USER_ITCREC8_GRDA17;
			ITCREC8bits.GRDB17 = ITC_USER_ITCREC8_GRDB17;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCREC9レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCREC9 = 
			( ITC_USER_ITCREC9_PIN18 << _ITCREC9_PIN18_POSITION ) |
			( ITC_USER_ITCREC9_ACCDONE18 << _ITCREC9_ACCDONE18_POSITION ) |
			( ITC_USER_ITCREC9_GRDA18 << _ITCREC9_GRDA18_POSITION ) |
			( ITC_USER_ITCREC9_GRDB18 << _ITCREC9_GRDB18_POSITION ) |
			( ITC_USER_ITCREC9_PIN19 << _ITCREC9_PIN19_POSITION ) |
			( ITC_USER_ITCREC9_ACCDONE19 << _ITCREC9_ACCDONE19_POSITION ) |
			( ITC_USER_ITCREC9_GRDA19 << _ITCREC9_GRDA19_POSITION ) |
			( ITC_USER_ITCREC9_GRDB19 << _ITCREC9_GRDB19_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCREC9bits.PIN18 = ITC_USER_ITCREC9_PIN18;
			ITCREC9bits.ACCDONE18 = ITC_USER_ITCREC9_ACCDONE18;
			ITCREC9bits.GRDA18 = ITC_USER_ITCREC9_GRDA18;
			ITCREC9bits.GRDB18 = ITC_USER_ITCREC9_GRDB18;
			ITCREC9bits.PIN19 = ITC_USER_ITCREC9_PIN19;
			ITCREC9bits.ACCDONE19 = ITC_USER_ITCREC9_ACCDONE19;
			ITCREC9bits.GRDA19 = ITC_USER_ITCREC9_GRDA19;
			ITCREC9bits.GRDB19 = ITC_USER_ITCREC9_GRDB19;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCREC10レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCREC10 = 
			( ITC_USER_ITCREC10_PIN20 << _ITCREC10_PIN20_POSITION ) |
			( ITC_USER_ITCREC10_ACCDONE20 << _ITCREC10_ACCDONE20_POSITION ) |
			( ITC_USER_ITCREC10_GRDA20 << _ITCREC10_GRDA20_POSITION ) |
			( ITC_USER_ITCREC10_GRDB20 << _ITCREC10_GRDB20_POSITION ) |
			( ITC_USER_ITCREC10_PIN21 << _ITCREC10_PIN21_POSITION ) |
			( ITC_USER_ITCREC10_ACCDONE21 << _ITCREC10_ACCDONE21_POSITION ) |
			( ITC_USER_ITCREC10_GRDA21 << _ITCREC10_GRDA21_POSITION ) |
			( ITC_USER_ITCREC10_GRDB21 << _ITCREC10_GRDB21_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCREC10bits.PIN20 = ITC_USER_ITCREC10_PIN20;
			ITCREC10bits.ACCDONE20 = ITC_USER_ITCREC10_ACCDONE20;
			ITCREC10bits.GRDA20 = ITC_USER_ITCREC10_GRDA20;
			ITCREC10bits.GRDB20 = ITC_USER_ITCREC10_GRDB20;
			ITCREC10bits.PIN21 = ITC_USER_ITCREC10_PIN21;
			ITCREC10bits.ACCDONE21 = ITC_USER_ITCREC10_ACCDONE21;
			ITCREC10bits.GRDA21 = ITC_USER_ITCREC10_GRDA21;
			ITCREC10bits.GRDB21 = ITC_USER_ITCREC10_GRDB21;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCREC11レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCREC11 = 
			( ITC_USER_ITCREC11_PIN22 << _ITCREC11_PIN22_POSITION ) |
			( ITC_USER_ITCREC11_ACCDONE22 << _ITCREC11_ACCDONE22_POSITION ) |
			( ITC_USER_ITCREC11_GRDA22 << _ITCREC11_GRDA22_POSITION ) |
			( ITC_USER_ITCREC11_GRDB22 << _ITCREC11_GRDB22_POSITION ) |
			( ITC_USER_ITCREC11_PIN23 << _ITCREC11_PIN23_POSITION ) |
			( ITC_USER_ITCREC11_ACCDONE23 << _ITCREC11_ACCDONE23_POSITION ) |
			( ITC_USER_ITCREC11_GRDA23 << _ITCREC11_GRDA23_POSITION ) |
			( ITC_USER_ITCREC11_GRDB23 << _ITCREC11_GRDB23_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCREC11bits.PIN22 = ITC_USER_ITCREC11_PIN22;
			ITCREC11bits.ACCDONE22 = ITC_USER_ITCREC11_ACCDONE22;
			ITCREC11bits.GRDA22 = ITC_USER_ITCREC11_GRDA22;
			ITCREC11bits.GRDB22 = ITC_USER_ITCREC11_GRDB22;
			ITCREC11bits.PIN23 = ITC_USER_ITCREC11_PIN23;
			ITCREC11bits.ACCDONE23 = ITC_USER_ITCREC11_ACCDONE23;
			ITCREC11bits.GRDA23 = ITC_USER_ITCREC11_GRDA23;
			ITCREC11bits.GRDB23 = ITC_USER_ITCREC11_GRDB23;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCREC12レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCREC12 = 
			( ITC_USER_ITCREC12_PIN24 << _ITCREC12_PIN24_POSITION ) |
			( ITC_USER_ITCREC12_ACCDONE24 << _ITCREC12_ACCDONE24_POSITION ) |
			( ITC_USER_ITCREC12_GRDA24 << _ITCREC12_GRDA24_POSITION ) |
			( ITC_USER_ITCREC12_GRDB24 << _ITCREC12_GRDB24_POSITION ) |
			( ITC_USER_ITCREC12_PIN25 << _ITCREC12_PIN25_POSITION ) |
			( ITC_USER_ITCREC12_ACCDONE25 << _ITCREC12_ACCDONE25_POSITION ) |
			( ITC_USER_ITCREC12_GRDA25 << _ITCREC12_GRDA25_POSITION ) |
			( ITC_USER_ITCREC12_GRDB25 << _ITCREC12_GRDB25_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCREC12bits.PIN24 = ITC_USER_ITCREC12_PIN24;
			ITCREC12bits.ACCDONE24 = ITC_USER_ITCREC12_ACCDONE24;
			ITCREC12bits.GRDA24 = ITC_USER_ITCREC12_GRDA24;
			ITCREC12bits.GRDB24 = ITC_USER_ITCREC12_GRDB24;
			ITCREC12bits.PIN25 = ITC_USER_ITCREC12_PIN25;
			ITCREC12bits.ACCDONE25 = ITC_USER_ITCREC12_ACCDONE25;
			ITCREC12bits.GRDA25 = ITC_USER_ITCREC12_GRDA25;
			ITCREC12bits.GRDB25 = ITC_USER_ITCREC12_GRDB25;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCREC13レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCREC13 = 
			( ITC_USER_ITCREC13_PIN26 << _ITCREC13_PIN26_POSITION ) |
			( ITC_USER_ITCREC13_ACCDONE26 << _ITCREC13_ACCDONE26_POSITION ) |
			( ITC_USER_ITCREC13_GRDA26 << _ITCREC13_GRDA26_POSITION ) |
			( ITC_USER_ITCREC13_GRDB26 << _ITCREC13_GRDB26_POSITION ) |
			( ITC_USER_ITCREC13_PIN27 << _ITCREC13_PIN27_POSITION ) |
			( ITC_USER_ITCREC13_ACCDONE27 << _ITCREC13_ACCDONE27_POSITION ) |
			( ITC_USER_ITCREC13_GRDA27 << _ITCREC13_GRDA27_POSITION ) |
			( ITC_USER_ITCREC13_GRDB27 << _ITCREC13_GRDB27_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCREC13bits.PIN26 = ITC_USER_ITCREC13_PIN26;
			ITCREC13bits.ACCDONE26 = ITC_USER_ITCREC13_ACCDONE26;
			ITCREC13bits.GRDA26 = ITC_USER_ITCREC13_GRDA26;
			ITCREC13bits.GRDB26 = ITC_USER_ITCREC13_GRDB26;
			ITCREC13bits.PIN27 = ITC_USER_ITCREC13_PIN27;
			ITCREC13bits.ACCDONE27 = ITC_USER_ITCREC13_ACCDONE27;
			ITCREC13bits.GRDA27 = ITC_USER_ITCREC13_GRDA27;
			ITCREC13bits.GRDB27 = ITC_USER_ITCREC13_GRDB27;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCREC14レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCREC14 = 
			( ITC_USER_ITCREC14_PIN28 << _ITCREC14_PIN28_POSITION ) |
			( ITC_USER_ITCREC14_ACCDONE28 << _ITCREC14_ACCDONE28_POSITION ) |
			( ITC_USER_ITCREC14_GRDA28 << _ITCREC14_GRDA28_POSITION ) |
			( ITC_USER_ITCREC14_GRDB28 << _ITCREC14_GRDB28_POSITION ) |
			( ITC_USER_ITCREC14_PIN29 << _ITCREC14_PIN29_POSITION ) |
			( ITC_USER_ITCREC14_ACCDONE29 << _ITCREC14_ACCDONE29_POSITION ) |
			( ITC_USER_ITCREC14_GRDA29 << _ITCREC14_GRDA29_POSITION ) |
			( ITC_USER_ITCREC14_GRDB29 << _ITCREC14_GRDB29_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCREC14bits.PIN28 = ITC_USER_ITCREC14_PIN28;
			ITCREC14bits.ACCDONE28 = ITC_USER_ITCREC14_ACCDONE28;
			ITCREC14bits.GRDA28 = ITC_USER_ITCREC14_GRDA28;
			ITCREC14bits.GRDB28 = ITC_USER_ITCREC14_GRDB28;
			ITCREC14bits.PIN29 = ITC_USER_ITCREC14_PIN29;
			ITCREC14bits.ACCDONE29 = ITC_USER_ITCREC14_ACCDONE29;
			ITCREC14bits.GRDA29 = ITC_USER_ITCREC14_GRDA29;
			ITCREC14bits.GRDB29 = ITC_USER_ITCREC14_GRDB29;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCREC15レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCREC15 = 
			( ITC_USER_ITCREC15_PIN30 << _ITCREC15_PIN30_POSITION ) |
			( ITC_USER_ITCREC15_ACCDONE30 << _ITCREC15_ACCDONE30_POSITION ) |
			( ITC_USER_ITCREC15_GRDA30 << _ITCREC15_GRDA30_POSITION ) |
			( ITC_USER_ITCREC15_GRDB30 << _ITCREC15_GRDB30_POSITION ) |
			( ITC_USER_ITCREC15_PIN31 << _ITCREC15_PIN31_POSITION ) |
			( ITC_USER_ITCREC15_ACCDONE31 << _ITCREC15_ACCDONE31_POSITION ) |
			( ITC_USER_ITCREC15_GRDA31 << _ITCREC15_GRDA31_POSITION ) |
			( ITC_USER_ITCREC15_GRDB31 << _ITCREC15_GRDB31_POSITION ) ;
		#ifdef DEF_BITNAME
			ITCREC15bits.PIN30 = ITC_USER_ITCREC15_PIN30;
			ITCREC15bits.ACCDONE30 = ITC_USER_ITCREC15_ACCDONE30;
			ITCREC15bits.GRDA30 = ITC_USER_ITCREC15_GRDA30;
			ITCREC15bits.GRDB30 = ITC_USER_ITCREC15_GRDB30;
			ITCREC15bits.PIN31 = ITC_USER_ITCREC15_PIN31;
			ITCREC15bits.ACCDONE31 = ITC_USER_ITCREC15_ACCDONE31;
			ITCREC15bits.GRDA31 = ITC_USER_ITCREC15_GRDA31;
			ITCREC15bits.GRDB31 = ITC_USER_ITCREC15_GRDB31;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* ITCRES0レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES0 = ITC_USER_ITCRES0;
	/*-----------------------------------------------------------------------*/
	/* ITCRES1レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES1 = ITC_USER_ITCRES1;
	/*-----------------------------------------------------------------------*/
	/* ITCRES2レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES2 = ITC_USER_ITCRES2;
	/*-----------------------------------------------------------------------*/
	/* ITCRES3レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES3 = ITC_USER_ITCRES3;
	/*-----------------------------------------------------------------------*/
	/* ITCRES4レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES4 = ITC_USER_ITCRES4;
	/*-----------------------------------------------------------------------*/
	/* ITCRES5レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES5 = ITC_USER_ITCRES5;
	/*-----------------------------------------------------------------------*/
	/* ITCRES6レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES6 = ITC_USER_ITCRES6;
	/*-----------------------------------------------------------------------*/
	/* ITCRES7レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES7 = ITC_USER_ITCRES7;
	/*-----------------------------------------------------------------------*/
	/* ITCRES8レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES8 = ITC_USER_ITCRES8;
	/*-----------------------------------------------------------------------*/
	/* ITCRES9レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES9 = ITC_USER_ITCRES9;
	/*-----------------------------------------------------------------------*/
	/* ITCRES10レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES10 = ITC_USER_ITCRES10;
	/*-----------------------------------------------------------------------*/
	/* ITCRES11レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES11 = ITC_USER_ITCRES11;
	/*-----------------------------------------------------------------------*/
	/* ITCRES12レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES12 = ITC_USER_ITCRES12;
	/*-----------------------------------------------------------------------*/
	/* ITCRES13レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES13 = ITC_USER_ITCRES13;
	/*-----------------------------------------------------------------------*/
	/* ITCRES14レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES14 = ITC_USER_ITCRES14;
	/*-----------------------------------------------------------------------*/
	/* ITCRES15レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES15 = ITC_USER_ITCRES15;
	/*-----------------------------------------------------------------------*/
	/* ITCRES16レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES16 = ITC_USER_ITCRES16;
	/*-----------------------------------------------------------------------*/
	/* ITCRES17レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES17 = ITC_USER_ITCRES17;
	/*-----------------------------------------------------------------------*/
	/* ITCRES18レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES18 = ITC_USER_ITCRES18;
	/*-----------------------------------------------------------------------*/
	/* ITCRES19レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES19 = ITC_USER_ITCRES19;
	/*-----------------------------------------------------------------------*/
	/* ITCRES20レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES20 = ITC_USER_ITCRES20;
	/*-----------------------------------------------------------------------*/
	/* ITCRES21レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES21 = ITC_USER_ITCRES21;
	/*-----------------------------------------------------------------------*/
	/* ITCRES22レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES22 = ITC_USER_ITCRES22;
	/*-----------------------------------------------------------------------*/
	/* ITCRES23レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES23 = ITC_USER_ITCRES23;
	/*-----------------------------------------------------------------------*/
	/* ITCRES24レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES24 = ITC_USER_ITCRES24;
	/*-----------------------------------------------------------------------*/
	/* ITCRES25レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES25 = ITC_USER_ITCRES25;
	/*-----------------------------------------------------------------------*/
	/* ITCRES26レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES26 = ITC_USER_ITCRES26;
	/*-----------------------------------------------------------------------*/
	/* ITCRES27レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES27 = ITC_USER_ITCRES27;
	/*-----------------------------------------------------------------------*/
	/* ITCRES28レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES28 = ITC_USER_ITCRES28;
	/*-----------------------------------------------------------------------*/
	/* ITCRES29レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES29 = ITC_USER_ITCRES29;
	/*-----------------------------------------------------------------------*/
	/* ITCRES30レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES30 = ITC_USER_ITCRES30;
	/*-----------------------------------------------------------------------*/
	/* ITCRES31レジスタ */
	/*-----------------------------------------------------------------------*/
		ITCRES31 = ITC_USER_ITCRES31;
	/*-----------------------------------------------------------------------*/
	/* ITCCURRESレジスタ */
	/*-----------------------------------------------------------------------*/
		ITCCURRES = ITC_USER_ITCCURRES;
#endif
}