/*----------------------------------------------------------------------------*/
/**
* @file		PAC_Driver.c
* @brief	Peripheral Access Controlに関するドライバ関数
* @date		24/07/16
* @details	
* @note		
*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*インクルードファイル*/
/*----------------------------------------------------------------------------*/
#include <xc.h>
#include "BoardSupportPackage.h"
#include "init_fix.h"
#include "typedef.h"
#include "pac_user.h"
/*----------------------------------------------------------------------------*/
/*定数定義*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*変数定義*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*プロトタイプ宣言*/
/*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_PAC_Set_Register(void)
* @brief     PACレジスタをセットします
* @param
* @return
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_PAC_Set_Register(void)
{
   /*-----------------------------------------------------------------------*/
	/* PACCON1レジスタ */
	/*-----------------------------------------------------------------------*/
		PACCON1 = 
			( PAC_USER_PACCON1_IVTBASELK << _PACCON1_IVTBASELK_POSITION ) |
			( PAC_USER_PACCON1_IVTCREGLK << _PACCON1_IVTCREGLK_POSITION ) |
			( PAC_USER_PACCON1_BMXIRAMLLK << _PACCON1_BMXIRAMLLK_POSITION ) |
			( PAC_USER_PACCON1_BMXIRAMHLK << _PACCON1_BMXIRAMHLK_POSITION ) |
			( PAC_USER_PACCON1_PCLKCONLK << _PACCON1_PCLKCONLK_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON1LK << _PACCON1_IOIMCON1LK_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON2LK << _PACCON1_IOIMCON2LK_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON3LK << _PACCON1_IOIMCON3LK_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON4LK << _PACCON1_IOIMCON4LK_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON5LK << _PACCON1_IOIMCON5LK_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON6LK << _PACCON1_IOIMCON6LK_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON7LK << _PACCON1_IOIMCON7LK_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON8LK << _PACCON1_IOIMCON8LK_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON9LK << _PACCON1_IOIMCON9LK_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON10LK << _PACCON1_IOIMCON10LK_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON11LK << _PACCON1_IOIMCON11LK_POSITION ) |
			( PAC_USER_PACCON1_IVTBASEWR << _PACCON1_IVTBASEWR_POSITION ) |
			( PAC_USER_PACCON1_IVTCREGWR << _PACCON1_IVTCREGWR_POSITION ) |
			( PAC_USER_PACCON1_BMXIRAMLWR << _PACCON1_BMXIRAMLWR_POSITION ) |
			( PAC_USER_PACCON1_BMXIRAMHWR << _PACCON1_BMXIRAMHWR_POSITION ) |
			( PAC_USER_PACCON1_PCLKCONWR << _PACCON1_PCLKCONWR_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON1WR << _PACCON1_IOIMCON1WR_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON2WR << _PACCON1_IOIMCON2WR_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON3WR << _PACCON1_IOIMCON3WR_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON4WR << _PACCON1_IOIMCON4WR_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON5WR << _PACCON1_IOIMCON5WR_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON6WR << _PACCON1_IOIMCON6WR_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON7WR << _PACCON1_IOIMCON7WR_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON8WR << _PACCON1_IOIMCON8WR_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON9WR << _PACCON1_IOIMCON9WR_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON10WR << _PACCON1_IOIMCON10WR_POSITION ) |
			( PAC_USER_PACCON1_IOIMCON11WR << _PACCON1_IOIMCON11WR_POSITION ) ;
		#ifdef DEF_BITNAME
			PACCON1bits.IVTBASELK = PAC_USER_PACCON1_IVTBASELK;
			PACCON1bits.IVTCREGLK = PAC_USER_PACCON1_IVTCREGLK;
			PACCON1bits.BMXIRAMLLK = PAC_USER_PACCON1_BMXIRAMLLK;
			PACCON1bits.BMXIRAMHLK = PAC_USER_PACCON1_BMXIRAMHLK;
			PACCON1bits.PCLKCONLK = PAC_USER_PACCON1_PCLKCONLK;
			PACCON1bits.IOIMCON1LK = PAC_USER_PACCON1_IOIMCON1LK;
			PACCON1bits.IOIMCON2LK = PAC_USER_PACCON1_IOIMCON2LK;
			PACCON1bits.IOIMCON3LK = PAC_USER_PACCON1_IOIMCON3LK;
			PACCON1bits.IOIMCON4LK = PAC_USER_PACCON1_IOIMCON4LK;
			PACCON1bits.IOIMCON5LK = PAC_USER_PACCON1_IOIMCON5LK;
			PACCON1bits.IOIMCON6LK = PAC_USER_PACCON1_IOIMCON6LK;
			PACCON1bits.IOIMCON7LK = PAC_USER_PACCON1_IOIMCON7LK;
			PACCON1bits.IOIMCON8LK = PAC_USER_PACCON1_IOIMCON8LK;
			PACCON1bits.IOIMCON9LK = PAC_USER_PACCON1_IOIMCON9LK;
			PACCON1bits.IOIMCON10LK = PAC_USER_PACCON1_IOIMCON10LK;
			PACCON1bits.IOIMCON11LK = PAC_USER_PACCON1_IOIMCON11LK;
			PACCON1bits.IVTBASEWR = PAC_USER_PACCON1_IVTBASEWR;
			PACCON1bits.IVTCREGWR = PAC_USER_PACCON1_IVTCREGWR;
			PACCON1bits.BMXIRAMLWR = PAC_USER_PACCON1_BMXIRAMLWR;
			PACCON1bits.BMXIRAMHWR = PAC_USER_PACCON1_BMXIRAMHWR;
			PACCON1bits.PCLKCONWR = PAC_USER_PACCON1_PCLKCONWR;
			PACCON1bits.IOIMCON1WR = PAC_USER_PACCON1_IOIMCON1WR;
			PACCON1bits.IOIMCON2WR = PAC_USER_PACCON1_IOIMCON2WR;
			PACCON1bits.IOIMCON3WR = PAC_USER_PACCON1_IOIMCON3WR;
			PACCON1bits.IOIMCON4WR = PAC_USER_PACCON1_IOIMCON4WR;
			PACCON1bits.IOIMCON5WR = PAC_USER_PACCON1_IOIMCON5WR;
			PACCON1bits.IOIMCON6WR = PAC_USER_PACCON1_IOIMCON6WR;
			PACCON1bits.IOIMCON7WR = PAC_USER_PACCON1_IOIMCON7WR;
			PACCON1bits.IOIMCON8WR = PAC_USER_PACCON1_IOIMCON8WR;
			PACCON1bits.IOIMCON9WR = PAC_USER_PACCON1_IOIMCON9WR;
			PACCON1bits.IOIMCON10WR = PAC_USER_PACCON1_IOIMCON10WR;
			PACCON1bits.IOIMCON11WR = PAC_USER_PACCON1_IOIMCON11WR;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PACCON2レジスタ */
	/*-----------------------------------------------------------------------*/
		PACCON2 = 
			( PAC_USER_PACCON2_IOIMCON12LK << _PACCON2_IOIMCON12LK_POSITION ) |
			( PAC_USER_PACCON2_IOIMCON13LK << _PACCON2_IOIMCON13LK_POSITION ) |
			( PAC_USER_PACCON2_IOIMCON14LK << _PACCON2_IOIMCON14LK_POSITION ) |
			( PAC_USER_PACCON2_IOIMCON15LK << _PACCON2_IOIMCON15LK_POSITION ) |
			( PAC_USER_PACCON2_IOIMCON16LK << _PACCON2_IOIMCON16LK_POSITION ) |
			( PAC_USER_PACCON2_NVMCONLK << _PACCON2_NVMCONLK_POSITION ) |
			( PAC_USER_PACCON2_OSCCTRLLK << _PACCON2_OSCCTRLLK_POSITION ) |
			( PAC_USER_PACCON2_CM1CONLK << _PACCON2_CM1CONLK_POSITION ) |
			( PAC_USER_PACCON2_CM1RANGELK << _PACCON2_CM1RANGELK_POSITION ) |
			( PAC_USER_PACCON2_CM2CONLK << _PACCON2_CM2CONLK_POSITION ) |
			( PAC_USER_PACCON2_CM2RANGELK << _PACCON2_CM2RANGELK_POSITION ) |
			( PAC_USER_PACCON2_CM3CONLK << _PACCON2_CM3CONLK_POSITION ) |
			( PAC_USER_PACCON2_CM3RANGELK << _PACCON2_CM3RANGELK_POSITION ) |
			( PAC_USER_PACCON2_CM4CONLK << _PACCON2_CM4CONLK_POSITION ) |
			( PAC_USER_PACCON2_CM4RANGELK << _PACCON2_CM4RANGELK_POSITION ) |
			( PAC_USER_PACCON2_WDTCONLK << _PACCON2_WDTCONLK_POSITION ) |
			( PAC_USER_PACCON2_IOIMCON12WR << _PACCON2_IOIMCON12WR_POSITION ) |
			( PAC_USER_PACCON2_IOIMCON13WR << _PACCON2_IOIMCON13WR_POSITION ) |
			( PAC_USER_PACCON2_IOIMCON14WR << _PACCON2_IOIMCON14WR_POSITION ) |
			( PAC_USER_PACCON2_IOIMCON15WR << _PACCON2_IOIMCON15WR_POSITION ) |
			( PAC_USER_PACCON2_IOIMCON16WR << _PACCON2_IOIMCON16WR_POSITION ) |
			( PAC_USER_PACCON2_NVMCONWR << _PACCON2_NVMCONWR_POSITION ) |
			( PAC_USER_PACCON2_OSCCTRLWR << _PACCON2_OSCCTRLWR_POSITION ) |
			( PAC_USER_PACCON2_CM1CONWR << _PACCON2_CM1CONWR_POSITION ) |
			( PAC_USER_PACCON2_CM1RANGEWR << _PACCON2_CM1RANGEWR_POSITION ) |
			( PAC_USER_PACCON2_CM2CONWR << _PACCON2_CM2CONWR_POSITION ) |
			( PAC_USER_PACCON2_CM2RANGEWR << _PACCON2_CM2RANGEWR_POSITION ) |
			( PAC_USER_PACCON2_CM3CONWR << _PACCON2_CM3CONWR_POSITION ) |
			( PAC_USER_PACCON2_CM3RANGEWR << _PACCON2_CM3RANGEWR_POSITION ) |
			( PAC_USER_PACCON2_CM4CONWR << _PACCON2_CM4CONWR_POSITION ) |
			( PAC_USER_PACCON2_CM4RANGEWR << _PACCON2_CM4RANGEWR_POSITION ) |
			( PAC_USER_PACCON2_WDTCONWR << _PACCON2_WDTCONWR_POSITION ) ;
		#ifdef DEF_BITNAME
			PACCON2bits.IOIMCON12LK = PAC_USER_PACCON2_IOIMCON12LK;
			PACCON2bits.IOIMCON13LK = PAC_USER_PACCON2_IOIMCON13LK;
			PACCON2bits.IOIMCON14LK = PAC_USER_PACCON2_IOIMCON14LK;
			PACCON2bits.IOIMCON15LK = PAC_USER_PACCON2_IOIMCON15LK;
			PACCON2bits.IOIMCON16LK = PAC_USER_PACCON2_IOIMCON16LK;
			PACCON2bits.NVMCONLK = PAC_USER_PACCON2_NVMCONLK;
			PACCON2bits.OSCCTRLLK = PAC_USER_PACCON2_OSCCTRLLK;
			PACCON2bits.CM1CONLK = PAC_USER_PACCON2_CM1CONLK;
			PACCON2bits.CM1RANGELK = PAC_USER_PACCON2_CM1RANGELK;
			PACCON2bits.CM2CONLK = PAC_USER_PACCON2_CM2CONLK;
			PACCON2bits.CM2RANGELK = PAC_USER_PACCON2_CM2RANGELK;
			PACCON2bits.CM3CONLK = PAC_USER_PACCON2_CM3CONLK;
			PACCON2bits.CM3RANGELK = PAC_USER_PACCON2_CM3RANGELK;
			PACCON2bits.CM4CONLK = PAC_USER_PACCON2_CM4CONLK;
			PACCON2bits.CM4RANGELK = PAC_USER_PACCON2_CM4RANGELK;
			PACCON2bits.WDTCONLK = PAC_USER_PACCON2_WDTCONLK;
			PACCON2bits.IOIMCON12WR = PAC_USER_PACCON2_IOIMCON12WR;
			PACCON2bits.IOIMCON13WR = PAC_USER_PACCON2_IOIMCON13WR;
			PACCON2bits.IOIMCON14WR = PAC_USER_PACCON2_IOIMCON14WR;
			PACCON2bits.IOIMCON15WR = PAC_USER_PACCON2_IOIMCON15WR;
			PACCON2bits.IOIMCON16WR = PAC_USER_PACCON2_IOIMCON16WR;
			PACCON2bits.NVMCONWR = PAC_USER_PACCON2_NVMCONWR;
			PACCON2bits.OSCCTRLWR = PAC_USER_PACCON2_OSCCTRLWR;
			PACCON2bits.CM1CONWR = PAC_USER_PACCON2_CM1CONWR;
			PACCON2bits.CM1RANGEWR = PAC_USER_PACCON2_CM1RANGEWR;
			PACCON2bits.CM2CONWR = PAC_USER_PACCON2_CM2CONWR;
			PACCON2bits.CM2RANGEWR = PAC_USER_PACCON2_CM2RANGEWR;
			PACCON2bits.CM3CONWR = PAC_USER_PACCON2_CM3CONWR;
			PACCON2bits.CM3RANGEWR = PAC_USER_PACCON2_CM3RANGEWR;
			PACCON2bits.CM4CONWR = PAC_USER_PACCON2_CM4CONWR;
			PACCON2bits.CM4RANGEWR = PAC_USER_PACCON2_CM4RANGEWR;
			PACCON2bits.WDTCONWR = PAC_USER_PACCON2_WDTCONWR;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PACCON3レジスタ */
	/*-----------------------------------------------------------------------*/
		PACCON3 = 
			( PAC_USER_PACCON3_RPCONLK << _PACCON3_RPCONLK_POSITION ) |
			( PAC_USER_PACCON3_PMDLK << _PACCON3_PMDLK_POSITION ) |
			( PAC_USER_PACCON3_MBISTCONLK << _PACCON3_MBISTCONLK_POSITION ) |
			( PAC_USER_PACCON3_APCLKCONLK << _PACCON3_APCLKCONLK_POSITION ) |
			( PAC_USER_PACCON3_OPAMP1LK << _PACCON3_OPAMP1LK_POSITION ) |
			( PAC_USER_PACCON3_OPAMP2LK << _PACCON3_OPAMP2LK_POSITION ) |
			( PAC_USER_PACCON3_OPAMP3LK << _PACCON3_OPAMP3LK_POSITION ) |
			( PAC_USER_PACCON3_IBIASCONLK << _PACCON3_IBIASCONLK_POSITION ) |
			( PAC_USER_PACCON3_RPCONWR << _PACCON3_RPCONWR_POSITION ) |
			( PAC_USER_PACCON3_PMDWR << _PACCON3_PMDWR_POSITION ) |
			( PAC_USER_PACCON3_MBISTCONWR << _PACCON3_MBISTCONWR_POSITION ) |
			( PAC_USER_PACCON3_APCLKCONWR << _PACCON3_APCLKCONWR_POSITION ) |
			( PAC_USER_PACCON3_OPAMP1WR << _PACCON3_OPAMP1WR_POSITION ) |
			( PAC_USER_PACCON3_OPAMP2WR << _PACCON3_OPAMP2WR_POSITION ) |
			( PAC_USER_PACCON3_OPAMP3WR << _PACCON3_OPAMP3WR_POSITION ) |
			( PAC_USER_PACCON3_IBIASCONWR << _PACCON3_IBIASCONWR_POSITION ) ;
		#ifdef DEF_BITNAME
			PACCON3bits.RPCONLK = PAC_USER_PACCON3_RPCONLK;
			PACCON3bits.PMDLK = PAC_USER_PACCON3_PMDLK;
			PACCON3bits.MBISTCONLK = PAC_USER_PACCON3_MBISTCONLK;
			PACCON3bits.APCLKCONLK = PAC_USER_PACCON3_APCLKCONLK;
			PACCON3bits.OPAMP1LK = PAC_USER_PACCON3_OPAMP1LK;
			PACCON3bits.OPAMP2LK = PAC_USER_PACCON3_OPAMP2LK;
			PACCON3bits.OPAMP3LK = PAC_USER_PACCON3_OPAMP3LK;
			PACCON3bits.IBIASCONLK = PAC_USER_PACCON3_IBIASCONLK;
			PACCON3bits.RPCONWR = PAC_USER_PACCON3_RPCONWR;
			PACCON3bits.PMDWR = PAC_USER_PACCON3_PMDWR;
			PACCON3bits.MBISTCONWR = PAC_USER_PACCON3_MBISTCONWR;
			PACCON3bits.APCLKCONWR = PAC_USER_PACCON3_APCLKCONWR;
			PACCON3bits.OPAMP1WR = PAC_USER_PACCON3_OPAMP1WR;
			PACCON3bits.OPAMP2WR = PAC_USER_PACCON3_OPAMP2WR;
			PACCON3bits.OPAMP3WR = PAC_USER_PACCON3_OPAMP3WR;
			PACCON3bits.IBIASCONWR = PAC_USER_PACCON3_IBIASCONWR;
		#endif 

}
