/*----------------------------------------------------------------------------*/
/**
* @file		Security_Driver.c
* @brief	Securityに関するドライバ関数
* @date		24/07/16
* @details	
* @note		
*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*インクルードファイル*/
/*----------------------------------------------------------------------------*/
#include <xc.h>
#include "BoardSupportPackage.h"
#include "init_fix.h"
#include "typedef.h"
#include "security_user.h"
/*----------------------------------------------------------------------------*/
/*定数定義*/
/*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*/
/*変数定義*/
/*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*/
/*プロトタイプ宣言*/
/*----------------------------------------------------------------------------*/


/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_Security_Set_Register(void)
* @brief     Securityレジスタの設定をします
* @param
* @return
* @detail     
*/
/*----------------------------------------------------------------------------*/
void vdg_Security_Set_Register(void)
{
	
	/*-----------------------------------------------------------------------*/
	/* UCPROTレジスタ */
	/*-----------------------------------------------------------------------*/
		UCPROT = 
			( SECURITY_USER_UCPROT_EPUCB << _UCPROT_EPUCB_POSITION ) |
			( SECURITY_USER_UCPROT_WPUCB << _UCPROT_WPUCB_POSITION ) |
			( SECURITY_USER_UCPROT_WPUCA << _UCPROT_WPUCA_POSITION ) |
			( SECURITY_USER_UCPROT_WPUCAI << _UCPROT_WPUCAI_POSITION ) ;
		#ifdef DEF_BITNAME
			UCPROTbits.EPUCB = SECURITY_USER_UCPROT_EPUCB;
			UCPROTbits.WPUCB = SECURITY_USER_UCPROT_WPUCB;
			UCPROTbits.WPUCA = SECURITY_USER_UCPROT_WPUCA;
			UCPROTbits.WPUCAI = SECURITY_USER_UCPROT_WPUCAI;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* IRTCTRLレジスタ */
	/*-----------------------------------------------------------------------*/
		IRTCTRL = 
			( SECURITY_USER_IRTCTRL_EAA << _IRTCTRL_EAA_POSITION ) |
			( SECURITY_USER_IRTCTRL_DBG << _IRTCTRL_DBG_POSITION ) |
			( SECURITY_USER_IRTCTRL_DONE << _IRTCTRL_DONE_POSITION ) |
			( SECURITY_USER_IRTCTRL_PLCK << _IRTCTRL_PLCK_POSITION ) |
			( SECURITY_USER_IRTCTRL_IACT << _IRTCTRL_IACT_POSITION ) ;
		#ifdef DEF_BITNAME
			IRTCTRLbits.EAA = SECURITY_USER_IRTCTRL_EAA;
			IRTCTRLbits.DBG = SECURITY_USER_IRTCTRL_DBG;
			IRTCTRLbits.DONE = SECURITY_USER_IRTCTRL_DONE;
			IRTCTRLbits.PLCK = SECURITY_USER_IRTCTRL_PLCK;
			IRTCTRLbits.IACT = SECURITY_USER_IRTCTRL_IACT;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* IRTSTATレジスタ */
	/*-----------------------------------------------------------------------*/
		IRTSTAT = SECURITY_USER_IRTSTAT;
	
	/*-----------------------------------------------------------------------*/
	/* PR0CTRLレジスタ */
	/*-----------------------------------------------------------------------*/
		PR0CTRL = 
			( SECURITY_USER_PR0CTRL_RDIS << _PR0CTRL_RDIS_POSITION ) |
			( SECURITY_USER_PR0CTRL_ERAO << _PR0CTRL_ERAO_POSITION ) |
			( SECURITY_USER_PR0CTRL_EX << _PR0CTRL_EX_POSITION ) |
			( SECURITY_USER_PR0CTRL_RD << _PR0CTRL_RD_POSITION ) |
			( SECURITY_USER_PR0CTRL_WR << _PR0CTRL_WR_POSITION ) |
			( SECURITY_USER_PR0CTRL_CRC << _PR0CTRL_CRC_POSITION ) |
			( SECURITY_USER_PR0CTRL_RTYPE << _PR0CTRL_RTYPE_POSITION ) |
			( SECURITY_USER_PR0CTRL_PSEL << _PR0CTRL_PSEL_POSITION ) ;
		#ifdef DEF_BITNAME
			PR0CTRLbits.RDIS = SECURITY_USER_PR0CTRL_RDIS;
			PR0CTRLbits.ERAO = SECURITY_USER_PR0CTRL_ERAO;
			PR0CTRLbits.EX = SECURITY_USER_PR0CTRL_EX;
			PR0CTRLbits.RD = SECURITY_USER_PR0CTRL_RD;
			PR0CTRLbits.WR = SECURITY_USER_PR0CTRL_WR;
			PR0CTRLbits.CRC = SECURITY_USER_PR0CTRL_CRC;
			PR0CTRLbits.RTYPE = SECURITY_USER_PR0CTRL_RTYPE;
			PR0CTRLbits.PSEL = SECURITY_USER_PR0CTRL_PSEL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PR0STレジスタ */
	/*-----------------------------------------------------------------------*/
		PR0ST = SECURITY_USER_PR0ST;
	/*-----------------------------------------------------------------------*/
	/* PR0ENDレジスタ */
	/*-----------------------------------------------------------------------*/
		PR0END = SECURITY_USER_PR0END;
	/*-----------------------------------------------------------------------*/
	/* PR0LOCKレジスタ */
	/*-----------------------------------------------------------------------*/
		PR0LOCK = 
			( SECURITY_USER_PR0LOCK_LOCK << _PR0LOCK_LOCK_POSITION ) |
			( SECURITY_USER_PR0LOCK_KEY << _PR0LOCK_KEY_POSITION ) ;
		#ifdef DEF_BITNAME
			PR0LOCKbits.LOCK = SECURITY_USER_PR0LOCK_LOCK;
			PR0LOCKbits.KEY = SECURITY_USER_PR0LOCK_KEY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PR1CTRLレジスタ */
	/*-----------------------------------------------------------------------*/
		PR1CTRL = 
			( SECURITY_USER_PR1CTRL_RDIS << _PR1CTRL_RDIS_POSITION ) |
			( SECURITY_USER_PR1CTRL_ERAO << _PR1CTRL_ERAO_POSITION ) |
			( SECURITY_USER_PR1CTRL_EX << _PR1CTRL_EX_POSITION ) |
			( SECURITY_USER_PR1CTRL_RD << _PR1CTRL_RD_POSITION ) |
			( SECURITY_USER_PR1CTRL_WR << _PR1CTRL_WR_POSITION ) |
			( SECURITY_USER_PR1CTRL_CRC << _PR1CTRL_CRC_POSITION ) |
			( SECURITY_USER_PR1CTRL_RTYPE << _PR1CTRL_RTYPE_POSITION ) |
			( SECURITY_USER_PR1CTRL_PSEL << _PR1CTRL_PSEL_POSITION ) ;
		#ifdef DEF_BITNAME
			PR1CTRLbits.RDIS = SECURITY_USER_PR1CTRL_RDIS;
			PR1CTRLbits.ERAO = SECURITY_USER_PR1CTRL_ERAO;
			PR1CTRLbits.EX = SECURITY_USER_PR1CTRL_EX;
			PR1CTRLbits.RD = SECURITY_USER_PR1CTRL_RD;
			PR1CTRLbits.WR = SECURITY_USER_PR1CTRL_WR;
			PR1CTRLbits.CRC = SECURITY_USER_PR1CTRL_CRC;
			PR1CTRLbits.RTYPE = SECURITY_USER_PR1CTRL_RTYPE;
			PR1CTRLbits.PSEL = SECURITY_USER_PR1CTRL_PSEL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PR1STレジスタ */
	/*-----------------------------------------------------------------------*/
		PR1ST = SECURITY_USER_PR1ST;
	/*-----------------------------------------------------------------------*/
	/* PR1ENDレジスタ */
	/*-----------------------------------------------------------------------*/
		PR1END = SECURITY_USER_PR1END;

	/*-----------------------------------------------------------------------*/
	/* PR1LOCKレジスタ */
	/*-----------------------------------------------------------------------*/
		PR1LOCK = 
			( SECURITY_USER_PR1LOCK_LOCK << _PR1LOCK_LOCK_POSITION ) |
			( SECURITY_USER_PR1LOCK_KEY << _PR1LOCK_KEY_POSITION ) ;
		#ifdef DEF_BITNAME
			PR1LOCKbits.LOCK = SECURITY_USER_PR1LOCK_LOCK;
			PR1LOCKbits.KEY = SECURITY_USER_PR1LOCK_KEY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PR2CTRLレジスタ */
	/*-----------------------------------------------------------------------*/
		PR2CTRL = 
			( SECURITY_USER_PR2CTRL_RDIS << _PR2CTRL_RDIS_POSITION ) |
			( SECURITY_USER_PR2CTRL_ERAO << _PR2CTRL_ERAO_POSITION ) |
			( SECURITY_USER_PR2CTRL_EX << _PR2CTRL_EX_POSITION ) |
			( SECURITY_USER_PR2CTRL_RD << _PR2CTRL_RD_POSITION ) |
			( SECURITY_USER_PR2CTRL_WR << _PR2CTRL_WR_POSITION ) |
			( SECURITY_USER_PR2CTRL_CRC << _PR2CTRL_CRC_POSITION ) |
			( SECURITY_USER_PR2CTRL_RTYPE << _PR2CTRL_RTYPE_POSITION ) |
			( SECURITY_USER_PR2CTRL_PSEL << _PR2CTRL_PSEL_POSITION ) ;
		#ifdef DEF_BITNAME
			PR2CTRLbits.RDIS = SECURITY_USER_PR2CTRL_RDIS;
			PR2CTRLbits.ERAO = SECURITY_USER_PR2CTRL_ERAO;
			PR2CTRLbits.EX = SECURITY_USER_PR2CTRL_EX;
			PR2CTRLbits.RD = SECURITY_USER_PR2CTRL_RD;
			PR2CTRLbits.WR = SECURITY_USER_PR2CTRL_WR;
			PR2CTRLbits.CRC = SECURITY_USER_PR2CTRL_CRC;
			PR2CTRLbits.RTYPE = SECURITY_USER_PR2CTRL_RTYPE;
			PR2CTRLbits.PSEL = SECURITY_USER_PR2CTRL_PSEL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PR2STレジスタ */
	/*-----------------------------------------------------------------------*/
		PR2ST = SECURITY_USER_PR2ST;
	/*-----------------------------------------------------------------------*/
	/* PR2ENDレジスタ */
	/*-----------------------------------------------------------------------*/
		PR2END = SECURITY_USER_PR2END;

	/*-----------------------------------------------------------------------*/
	/* PR2LOCKレジスタ */
	/*-----------------------------------------------------------------------*/
		PR2LOCK = 
			( SECURITY_USER_PR2LOCK_LOCK << _PR2LOCK_LOCK_POSITION ) |
			( SECURITY_USER_PR2LOCK_KEY << _PR2LOCK_KEY_POSITION ) ;
		#ifdef DEF_BITNAME
			PR2LOCKbits.LOCK = SECURITY_USER_PR2LOCK_LOCK;
			PR2LOCKbits.KEY = SECURITY_USER_PR2LOCK_KEY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PR3CTRLレジスタ */
	/*-----------------------------------------------------------------------*/
		PR3CTRL = 
			( SECURITY_USER_PR3CTRL_RDIS << _PR3CTRL_RDIS_POSITION ) |
			( SECURITY_USER_PR3CTRL_ERAO << _PR3CTRL_ERAO_POSITION ) |
			( SECURITY_USER_PR3CTRL_EX << _PR3CTRL_EX_POSITION ) |
			( SECURITY_USER_PR3CTRL_RD << _PR3CTRL_RD_POSITION ) |
			( SECURITY_USER_PR3CTRL_WR << _PR3CTRL_WR_POSITION ) |
			( SECURITY_USER_PR3CTRL_CRC << _PR3CTRL_CRC_POSITION ) |
			( SECURITY_USER_PR3CTRL_RTYPE << _PR3CTRL_RTYPE_POSITION ) |
			( SECURITY_USER_PR3CTRL_PSEL << _PR3CTRL_PSEL_POSITION ) ;
		#ifdef DEF_BITNAME
			PR3CTRLbits.RDIS = SECURITY_USER_PR3CTRL_RDIS;
			PR3CTRLbits.ERAO = SECURITY_USER_PR3CTRL_ERAO;
			PR3CTRLbits.EX = SECURITY_USER_PR3CTRL_EX;
			PR3CTRLbits.RD = SECURITY_USER_PR3CTRL_RD;
			PR3CTRLbits.WR = SECURITY_USER_PR3CTRL_WR;
			PR3CTRLbits.CRC = SECURITY_USER_PR3CTRL_CRC;
			PR3CTRLbits.RTYPE = SECURITY_USER_PR3CTRL_RTYPE;
			PR3CTRLbits.PSEL = SECURITY_USER_PR3CTRL_PSEL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PR3STレジスタ */
	/*-----------------------------------------------------------------------*/
		PR3ST =  SECURITY_USER_PR3ST;
	/*-----------------------------------------------------------------------*/
	/* PR3ENDレジスタ */
	/*-----------------------------------------------------------------------*/
		PR3END = SECURITY_USER_PR3END;
	/*-----------------------------------------------------------------------*/
	/* PR3LOCKレジスタ */
	/*-----------------------------------------------------------------------*/
		PR3LOCK = 
			( SECURITY_USER_PR3LOCK_LOCK << _PR3LOCK_LOCK_POSITION ) |
			( SECURITY_USER_PR3LOCK_KEY << _PR3LOCK_KEY_POSITION ) ;
		#ifdef DEF_BITNAME
			PR3LOCKbits.LOCK = SECURITY_USER_PR3LOCK_LOCK;
			PR3LOCKbits.KEY = SECURITY_USER_PR3LOCK_KEY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PR4CTRLレジスタ */
	/*-----------------------------------------------------------------------*/
		PR4CTRL = 
			( SECURITY_USER_PR4CTRL_RDIS << _PR4CTRL_RDIS_POSITION ) |
			( SECURITY_USER_PR4CTRL_ERAO << _PR4CTRL_ERAO_POSITION ) |
			( SECURITY_USER_PR4CTRL_EX << _PR4CTRL_EX_POSITION ) |
			( SECURITY_USER_PR4CTRL_RD << _PR4CTRL_RD_POSITION ) |
			( SECURITY_USER_PR4CTRL_WR << _PR4CTRL_WR_POSITION ) |
			( SECURITY_USER_PR4CTRL_CRC << _PR4CTRL_CRC_POSITION ) |
			( SECURITY_USER_PR4CTRL_RTYPE << _PR4CTRL_RTYPE_POSITION ) |
			( SECURITY_USER_PR4CTRL_PSEL << _PR4CTRL_PSEL_POSITION ) ;
		#ifdef DEF_BITNAME
			PR4CTRLbits.RDIS = SECURITY_USER_PR4CTRL_RDIS;
			PR4CTRLbits.ERAO = SECURITY_USER_PR4CTRL_ERAO;
			PR4CTRLbits.EX = SECURITY_USER_PR4CTRL_EX;
			PR4CTRLbits.RD = SECURITY_USER_PR4CTRL_RD;
			PR4CTRLbits.WR = SECURITY_USER_PR4CTRL_WR;
			PR4CTRLbits.CRC = SECURITY_USER_PR4CTRL_CRC;
			PR4CTRLbits.RTYPE = SECURITY_USER_PR4CTRL_RTYPE;
			PR4CTRLbits.PSEL = SECURITY_USER_PR4CTRL_PSEL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PR4STレジスタ */
	/*-----------------------------------------------------------------------*/
		PR4ST = SECURITY_USER_PR4ST;

	/*-----------------------------------------------------------------------*/
	/* PR4ENDレジスタ */
	/*-----------------------------------------------------------------------*/
		PR4END =  SECURITY_USER_PR4END;
	/*-----------------------------------------------------------------------*/
	/* PR4LOCKレジスタ */
	/*-----------------------------------------------------------------------*/
		PR4LOCK = 
			( SECURITY_USER_PR4LOCK_LOCK << _PR4LOCK_LOCK_POSITION ) |
			( SECURITY_USER_PR4LOCK_KEY << _PR4LOCK_KEY_POSITION ) ;
		#ifdef DEF_BITNAME
			PR4LOCKbits.LOCK = SECURITY_USER_PR4LOCK_LOCK;
			PR4LOCKbits.KEY = SECURITY_USER_PR4LOCK_KEY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PR5CTRLレジスタ */
	/*-----------------------------------------------------------------------*/
		PR5CTRL = 
			( SECURITY_USER_PR5CTRL_RDIS << _PR5CTRL_RDIS_POSITION ) |
			( SECURITY_USER_PR5CTRL_ERAO << _PR5CTRL_ERAO_POSITION ) |
			( SECURITY_USER_PR5CTRL_EX << _PR5CTRL_EX_POSITION ) |
			( SECURITY_USER_PR5CTRL_RD << _PR5CTRL_RD_POSITION ) |
			( SECURITY_USER_PR5CTRL_WR << _PR5CTRL_WR_POSITION ) |
			( SECURITY_USER_PR5CTRL_CRC << _PR5CTRL_CRC_POSITION ) |
			( SECURITY_USER_PR5CTRL_RTYPE << _PR5CTRL_RTYPE_POSITION ) |
			( SECURITY_USER_PR5CTRL_PSEL << _PR5CTRL_PSEL_POSITION ) ;
		#ifdef DEF_BITNAME
			PR5CTRLbits.RDIS = SECURITY_USER_PR5CTRL_RDIS;
			PR5CTRLbits.ERAO = SECURITY_USER_PR5CTRL_ERAO;
			PR5CTRLbits.EX = SECURITY_USER_PR5CTRL_EX;
			PR5CTRLbits.RD = SECURITY_USER_PR5CTRL_RD;
			PR5CTRLbits.WR = SECURITY_USER_PR5CTRL_WR;
			PR5CTRLbits.CRC = SECURITY_USER_PR5CTRL_CRC;
			PR5CTRLbits.RTYPE = SECURITY_USER_PR5CTRL_RTYPE;
			PR5CTRLbits.PSEL = SECURITY_USER_PR5CTRL_PSEL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PR5STレジスタ */
	/*-----------------------------------------------------------------------*/
		PR5ST =  SECURITY_USER_PR5ST;
	/*-----------------------------------------------------------------------*/
	/* PR5ENDレジスタ */
	/*-----------------------------------------------------------------------*/
		PR5END = SECURITY_USER_PR5END;

	/*-----------------------------------------------------------------------*/
	/* PR5LOCKレジスタ */
	/*-----------------------------------------------------------------------*/
		PR5LOCK = 
			( SECURITY_USER_PR5LOCK_LOCK << _PR5LOCK_LOCK_POSITION ) |
			( SECURITY_USER_PR5LOCK_KEY << _PR5LOCK_KEY_POSITION ) ;
		#ifdef DEF_BITNAME
			PR5LOCKbits.LOCK = SECURITY_USER_PR5LOCK_LOCK;
			PR5LOCKbits.KEY = SECURITY_USER_PR5LOCK_KEY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PR6CTRLレジスタ */
	/*-----------------------------------------------------------------------*/
		PR6CTRL = 
			( SECURITY_USER_PR6CTRL_RDIS << _PR6CTRL_RDIS_POSITION ) |
			( SECURITY_USER_PR6CTRL_ERAO << _PR6CTRL_ERAO_POSITION ) |
			( SECURITY_USER_PR6CTRL_EX << _PR6CTRL_EX_POSITION ) |
			( SECURITY_USER_PR6CTRL_RD << _PR6CTRL_RD_POSITION ) |
			( SECURITY_USER_PR6CTRL_WR << _PR6CTRL_WR_POSITION ) |
			( SECURITY_USER_PR6CTRL_CRC << _PR6CTRL_CRC_POSITION ) |
			( SECURITY_USER_PR6CTRL_RTYPE << _PR6CTRL_RTYPE_POSITION ) |
			( SECURITY_USER_PR6CTRL_PSEL << _PR6CTRL_PSEL_POSITION ) ;
		#ifdef DEF_BITNAME
			PR6CTRLbits.RDIS = SECURITY_USER_PR6CTRL_RDIS;
			PR6CTRLbits.ERAO = SECURITY_USER_PR6CTRL_ERAO;
			PR6CTRLbits.EX = SECURITY_USER_PR6CTRL_EX;
			PR6CTRLbits.RD = SECURITY_USER_PR6CTRL_RD;
			PR6CTRLbits.WR = SECURITY_USER_PR6CTRL_WR;
			PR6CTRLbits.CRC = SECURITY_USER_PR6CTRL_CRC;
			PR6CTRLbits.RTYPE = SECURITY_USER_PR6CTRL_RTYPE;
			PR6CTRLbits.PSEL = SECURITY_USER_PR6CTRL_PSEL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PR6STレジスタ */
	/*-----------------------------------------------------------------------*/
		PR6ST =  SECURITY_USER_PR6ST;
	/*-----------------------------------------------------------------------*/
	/* PR6ENDレジスタ */
	/*-----------------------------------------------------------------------*/
		PR6END = SECURITY_USER_PR6END;
	/*-----------------------------------------------------------------------*/
	/* PR6LOCKレジスタ */
	/*-----------------------------------------------------------------------*/
		PR6LOCK = 
			( SECURITY_USER_PR6LOCK_LOCK << _PR6LOCK_LOCK_POSITION ) |
			( SECURITY_USER_PR6LOCK_KEY << _PR6LOCK_KEY_POSITION ) ;
		#ifdef DEF_BITNAME
			PR6LOCKbits.LOCK = SECURITY_USER_PR6LOCK_LOCK;
			PR6LOCKbits.KEY = SECURITY_USER_PR6LOCK_KEY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PR7CTRLレジスタ */
	/*-----------------------------------------------------------------------*/
		PR7CTRL = 
			( SECURITY_USER_PR7CTRL_RDIS << _PR7CTRL_RDIS_POSITION ) |
			( SECURITY_USER_PR7CTRL_ERAO << _PR7CTRL_ERAO_POSITION ) |
			( SECURITY_USER_PR7CTRL_EX << _PR7CTRL_EX_POSITION ) |
			( SECURITY_USER_PR7CTRL_RD << _PR7CTRL_RD_POSITION ) |
			( SECURITY_USER_PR7CTRL_WR << _PR7CTRL_WR_POSITION ) |
			( SECURITY_USER_PR7CTRL_CRC << _PR7CTRL_CRC_POSITION ) |
			( SECURITY_USER_PR7CTRL_RTYPE << _PR7CTRL_RTYPE_POSITION ) |
			( SECURITY_USER_PR7CTRL_PSEL << _PR7CTRL_PSEL_POSITION ) ;
		#ifdef DEF_BITNAME
			PR7CTRLbits.RDIS = SECURITY_USER_PR7CTRL_RDIS;
			PR7CTRLbits.ERAO = SECURITY_USER_PR7CTRL_ERAO;
			PR7CTRLbits.EX = SECURITY_USER_PR7CTRL_EX;
			PR7CTRLbits.RD = SECURITY_USER_PR7CTRL_RD;
			PR7CTRLbits.WR = SECURITY_USER_PR7CTRL_WR;
			PR7CTRLbits.CRC = SECURITY_USER_PR7CTRL_CRC;
			PR7CTRLbits.RTYPE = SECURITY_USER_PR7CTRL_RTYPE;
			PR7CTRLbits.PSEL = SECURITY_USER_PR7CTRL_PSEL;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PR7STレジスタ */
	/*-----------------------------------------------------------------------*/
		PR7ST = SECURITY_USER_PR7ST;
	/*-----------------------------------------------------------------------*/
	/* PR7ENDレジスタ */
	/*-----------------------------------------------------------------------*/
		PR7END = SECURITY_USER_PR7END;
	/*-----------------------------------------------------------------------*/
	/* PR7LOCKレジスタ */
	/*-----------------------------------------------------------------------*/
		PR7LOCK = 
			( SECURITY_USER_PR7LOCK_LOCK << _PR7LOCK_LOCK_POSITION ) |
			( SECURITY_USER_PR7LOCK_KEY << _PR7LOCK_KEY_POSITION ) ;
		#ifdef DEF_BITNAME
			PR7LOCKbits.LOCK = SECURITY_USER_PR7LOCK_LOCK;
			PR7LOCKbits.KEY = SECURITY_USER_PR7LOCK_KEY;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PACCON1レジスタ */
	/*-----------------------------------------------------------------------*/
		PACCON1 = 
			( SECURITY_USER_PACCON1_IVTBASELK << _PACCON1_IVTBASELK_POSITION ) |
			( SECURITY_USER_PACCON1_IVTCREGLK << _PACCON1_IVTCREGLK_POSITION ) |
			( SECURITY_USER_PACCON1_BMXIRAMLLK << _PACCON1_BMXIRAMLLK_POSITION ) |
			( SECURITY_USER_PACCON1_BMXIRAMHLK << _PACCON1_BMXIRAMHLK_POSITION ) |
			( SECURITY_USER_PACCON1_PCLKCONLK << _PACCON1_PCLKCONLK_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON1LK << _PACCON1_IOIMCON1LK_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON2LK << _PACCON1_IOIMCON2LK_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON3LK << _PACCON1_IOIMCON3LK_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON4LK << _PACCON1_IOIMCON4LK_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON5LK << _PACCON1_IOIMCON5LK_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON6LK << _PACCON1_IOIMCON6LK_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON7LK << _PACCON1_IOIMCON7LK_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON8LK << _PACCON1_IOIMCON8LK_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON9LK << _PACCON1_IOIMCON9LK_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON10LK << _PACCON1_IOIMCON10LK_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON11LK << _PACCON1_IOIMCON11LK_POSITION ) |
			( SECURITY_USER_PACCON1_IVTBASEWR << _PACCON1_IVTBASEWR_POSITION ) |
			( SECURITY_USER_PACCON1_IVTCREGWR << _PACCON1_IVTCREGWR_POSITION ) |
			( SECURITY_USER_PACCON1_BMXIRAMLWR << _PACCON1_BMXIRAMLWR_POSITION ) |
			( SECURITY_USER_PACCON1_BMXIRAMHWR << _PACCON1_BMXIRAMHWR_POSITION ) |
			( SECURITY_USER_PACCON1_PCLKCONWR << _PACCON1_PCLKCONWR_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON1WR << _PACCON1_IOIMCON1WR_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON2WR << _PACCON1_IOIMCON2WR_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON3WR << _PACCON1_IOIMCON3WR_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON4WR << _PACCON1_IOIMCON4WR_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON5WR << _PACCON1_IOIMCON5WR_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON6WR << _PACCON1_IOIMCON6WR_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON7WR << _PACCON1_IOIMCON7WR_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON8WR << _PACCON1_IOIMCON8WR_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON9WR << _PACCON1_IOIMCON9WR_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON10WR << _PACCON1_IOIMCON10WR_POSITION ) |
			( SECURITY_USER_PACCON1_IOIMCON11WR << _PACCON1_IOIMCON11WR_POSITION ) ;
		#ifdef DEF_BITNAME
			PACCON1bits.IVTBASELK = SECURITY_USER_PACCON1_IVTBASELK;
			PACCON1bits.IVTCREGLK = SECURITY_USER_PACCON1_IVTCREGLK;
			PACCON1bits.BMXIRAMLLK = SECURITY_USER_PACCON1_BMXIRAMLLK;
			PACCON1bits.BMXIRAMHLK = SECURITY_USER_PACCON1_BMXIRAMHLK;
			PACCON1bits.PCLKCONLK = SECURITY_USER_PACCON1_PCLKCONLK;
			PACCON1bits.IOIMCON1LK = SECURITY_USER_PACCON1_IOIMCON1LK;
			PACCON1bits.IOIMCON2LK = SECURITY_USER_PACCON1_IOIMCON2LK;
			PACCON1bits.IOIMCON3LK = SECURITY_USER_PACCON1_IOIMCON3LK;
			PACCON1bits.IOIMCON4LK = SECURITY_USER_PACCON1_IOIMCON4LK;
			PACCON1bits.IOIMCON5LK = SECURITY_USER_PACCON1_IOIMCON5LK;
			PACCON1bits.IOIMCON6LK = SECURITY_USER_PACCON1_IOIMCON6LK;
			PACCON1bits.IOIMCON7LK = SECURITY_USER_PACCON1_IOIMCON7LK;
			PACCON1bits.IOIMCON8LK = SECURITY_USER_PACCON1_IOIMCON8LK;
			PACCON1bits.IOIMCON9LK = SECURITY_USER_PACCON1_IOIMCON9LK;
			PACCON1bits.IOIMCON10LK = SECURITY_USER_PACCON1_IOIMCON10LK;
			PACCON1bits.IOIMCON11LK = SECURITY_USER_PACCON1_IOIMCON11LK;
			PACCON1bits.IVTBASEWR = SECURITY_USER_PACCON1_IVTBASEWR;
			PACCON1bits.IVTCREGWR = SECURITY_USER_PACCON1_IVTCREGWR;
			PACCON1bits.BMXIRAMLWR = SECURITY_USER_PACCON1_BMXIRAMLWR;
			PACCON1bits.BMXIRAMHWR = SECURITY_USER_PACCON1_BMXIRAMHWR;
			PACCON1bits.PCLKCONWR = SECURITY_USER_PACCON1_PCLKCONWR;
			PACCON1bits.IOIMCON1WR = SECURITY_USER_PACCON1_IOIMCON1WR;
			PACCON1bits.IOIMCON2WR = SECURITY_USER_PACCON1_IOIMCON2WR;
			PACCON1bits.IOIMCON3WR = SECURITY_USER_PACCON1_IOIMCON3WR;
			PACCON1bits.IOIMCON4WR = SECURITY_USER_PACCON1_IOIMCON4WR;
			PACCON1bits.IOIMCON5WR = SECURITY_USER_PACCON1_IOIMCON5WR;
			PACCON1bits.IOIMCON6WR = SECURITY_USER_PACCON1_IOIMCON6WR;
			PACCON1bits.IOIMCON7WR = SECURITY_USER_PACCON1_IOIMCON7WR;
			PACCON1bits.IOIMCON8WR = SECURITY_USER_PACCON1_IOIMCON8WR;
			PACCON1bits.IOIMCON9WR = SECURITY_USER_PACCON1_IOIMCON9WR;
			PACCON1bits.IOIMCON10WR = SECURITY_USER_PACCON1_IOIMCON10WR;
			PACCON1bits.IOIMCON11WR = SECURITY_USER_PACCON1_IOIMCON11WR;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PACCON2レジスタ */
	/*-----------------------------------------------------------------------*/
		PACCON2 = 
			( SECURITY_USER_PACCON2_IOIMCON12LK << _PACCON2_IOIMCON12LK_POSITION ) |
			( SECURITY_USER_PACCON2_IOIMCON13LK << _PACCON2_IOIMCON13LK_POSITION ) |
			( SECURITY_USER_PACCON2_IOIMCON14LK << _PACCON2_IOIMCON14LK_POSITION ) |
			( SECURITY_USER_PACCON2_IOIMCON15LK << _PACCON2_IOIMCON15LK_POSITION ) |
			( SECURITY_USER_PACCON2_IOIMCON16LK << _PACCON2_IOIMCON16LK_POSITION ) |
			( SECURITY_USER_PACCON2_NVMCONLK << _PACCON2_NVMCONLK_POSITION ) |
			( SECURITY_USER_PACCON2_OSCCTRLLK << _PACCON2_OSCCTRLLK_POSITION ) |
			( SECURITY_USER_PACCON2_CM1CONLK << _PACCON2_CM1CONLK_POSITION ) |
			( SECURITY_USER_PACCON2_CM1RANGELK << _PACCON2_CM1RANGELK_POSITION ) |
			( SECURITY_USER_PACCON2_CM2CONLK << _PACCON2_CM2CONLK_POSITION ) |
			( SECURITY_USER_PACCON2_CM2RANGELK << _PACCON2_CM2RANGELK_POSITION ) |
			( SECURITY_USER_PACCON2_CM3CONLK << _PACCON2_CM3CONLK_POSITION ) |
			( SECURITY_USER_PACCON2_CM3RANGELK << _PACCON2_CM3RANGELK_POSITION ) |
			( SECURITY_USER_PACCON2_CM4CONLK << _PACCON2_CM4CONLK_POSITION ) |
			( SECURITY_USER_PACCON2_CM4RANGELK << _PACCON2_CM4RANGELK_POSITION ) |
			( SECURITY_USER_PACCON2_WDTCONLK << _PACCON2_WDTCONLK_POSITION ) |
			( SECURITY_USER_PACCON2_IOIMCON12WR << _PACCON2_IOIMCON12WR_POSITION ) |
			( SECURITY_USER_PACCON2_IOIMCON13WR << _PACCON2_IOIMCON13WR_POSITION ) |
			( SECURITY_USER_PACCON2_IOIMCON14WR << _PACCON2_IOIMCON14WR_POSITION ) |
			( SECURITY_USER_PACCON2_IOIMCON15WR << _PACCON2_IOIMCON15WR_POSITION ) |
			( SECURITY_USER_PACCON2_IOIMCON16WR << _PACCON2_IOIMCON16WR_POSITION ) |
			( SECURITY_USER_PACCON2_NVMCONWR << _PACCON2_NVMCONWR_POSITION ) |
			( SECURITY_USER_PACCON2_OSCCTRLWR << _PACCON2_OSCCTRLWR_POSITION ) |
			( SECURITY_USER_PACCON2_CM1CONWR << _PACCON2_CM1CONWR_POSITION ) |
			( SECURITY_USER_PACCON2_CM1RANGEWR << _PACCON2_CM1RANGEWR_POSITION ) |
			( SECURITY_USER_PACCON2_CM2CONWR << _PACCON2_CM2CONWR_POSITION ) |
			( SECURITY_USER_PACCON2_CM2RANGEWR << _PACCON2_CM2RANGEWR_POSITION ) |
			( SECURITY_USER_PACCON2_CM3CONWR << _PACCON2_CM3CONWR_POSITION ) |
			( SECURITY_USER_PACCON2_CM3RANGEWR << _PACCON2_CM3RANGEWR_POSITION ) |
			( SECURITY_USER_PACCON2_CM4CONWR << _PACCON2_CM4CONWR_POSITION ) |
			( SECURITY_USER_PACCON2_CM4RANGEWR << _PACCON2_CM4RANGEWR_POSITION ) |
			( SECURITY_USER_PACCON2_WDTCONWR << _PACCON2_WDTCONWR_POSITION ) ;
		#ifdef DEF_BITNAME
			PACCON2bits.IOIMCON12LK = SECURITY_USER_PACCON2_IOIMCON12LK;
			PACCON2bits.IOIMCON13LK = SECURITY_USER_PACCON2_IOIMCON13LK;
			PACCON2bits.IOIMCON14LK = SECURITY_USER_PACCON2_IOIMCON14LK;
			PACCON2bits.IOIMCON15LK = SECURITY_USER_PACCON2_IOIMCON15LK;
			PACCON2bits.IOIMCON16LK = SECURITY_USER_PACCON2_IOIMCON16LK;
			PACCON2bits.NVMCONLK = SECURITY_USER_PACCON2_NVMCONLK;
			PACCON2bits.OSCCTRLLK = SECURITY_USER_PACCON2_OSCCTRLLK;
			PACCON2bits.CM1CONLK = SECURITY_USER_PACCON2_CM1CONLK;
			PACCON2bits.CM1RANGELK = SECURITY_USER_PACCON2_CM1RANGELK;
			PACCON2bits.CM2CONLK = SECURITY_USER_PACCON2_CM2CONLK;
			PACCON2bits.CM2RANGELK = SECURITY_USER_PACCON2_CM2RANGELK;
			PACCON2bits.CM3CONLK = SECURITY_USER_PACCON2_CM3CONLK;
			PACCON2bits.CM3RANGELK = SECURITY_USER_PACCON2_CM3RANGELK;
			PACCON2bits.CM4CONLK = SECURITY_USER_PACCON2_CM4CONLK;
			PACCON2bits.CM4RANGELK = SECURITY_USER_PACCON2_CM4RANGELK;
			PACCON2bits.WDTCONLK = SECURITY_USER_PACCON2_WDTCONLK;
			PACCON2bits.IOIMCON12WR = SECURITY_USER_PACCON2_IOIMCON12WR;
			PACCON2bits.IOIMCON13WR = SECURITY_USER_PACCON2_IOIMCON13WR;
			PACCON2bits.IOIMCON14WR = SECURITY_USER_PACCON2_IOIMCON14WR;
			PACCON2bits.IOIMCON15WR = SECURITY_USER_PACCON2_IOIMCON15WR;
			PACCON2bits.IOIMCON16WR = SECURITY_USER_PACCON2_IOIMCON16WR;
			PACCON2bits.NVMCONWR = SECURITY_USER_PACCON2_NVMCONWR;
			PACCON2bits.OSCCTRLWR = SECURITY_USER_PACCON2_OSCCTRLWR;
			PACCON2bits.CM1CONWR = SECURITY_USER_PACCON2_CM1CONWR;
			PACCON2bits.CM1RANGEWR = SECURITY_USER_PACCON2_CM1RANGEWR;
			PACCON2bits.CM2CONWR = SECURITY_USER_PACCON2_CM2CONWR;
			PACCON2bits.CM2RANGEWR = SECURITY_USER_PACCON2_CM2RANGEWR;
			PACCON2bits.CM3CONWR = SECURITY_USER_PACCON2_CM3CONWR;
			PACCON2bits.CM3RANGEWR = SECURITY_USER_PACCON2_CM3RANGEWR;
			PACCON2bits.CM4CONWR = SECURITY_USER_PACCON2_CM4CONWR;
			PACCON2bits.CM4RANGEWR = SECURITY_USER_PACCON2_CM4RANGEWR;
			PACCON2bits.WDTCONWR = SECURITY_USER_PACCON2_WDTCONWR;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* PACCON3レジスタ */
	/*-----------------------------------------------------------------------*/
		PACCON3 = 
			( SECURITY_USER_PACCON3_RPCONLK << _PACCON3_RPCONLK_POSITION ) |
			( SECURITY_USER_PACCON3_PMDLK << _PACCON3_PMDLK_POSITION ) |
			( SECURITY_USER_PACCON3_MBISTCONLK << _PACCON3_MBISTCONLK_POSITION ) |
			( SECURITY_USER_PACCON3_APCLKCONLK << _PACCON3_APCLKCONLK_POSITION ) |
			( SECURITY_USER_PACCON3_OPAMP1LK << _PACCON3_OPAMP1LK_POSITION ) |
			( SECURITY_USER_PACCON3_OPAMP2LK << _PACCON3_OPAMP2LK_POSITION ) |
			( SECURITY_USER_PACCON3_OPAMP3LK << _PACCON3_OPAMP3LK_POSITION ) |
			( SECURITY_USER_PACCON3_IBIASCONLK << _PACCON3_IBIASCONLK_POSITION ) |
			( SECURITY_USER_PACCON3_RPCONWR << _PACCON3_RPCONWR_POSITION ) |
			( SECURITY_USER_PACCON3_PMDWR << _PACCON3_PMDWR_POSITION ) |
			( SECURITY_USER_PACCON3_MBISTCONWR << _PACCON3_MBISTCONWR_POSITION ) |
			( SECURITY_USER_PACCON3_APCLKCONWR << _PACCON3_APCLKCONWR_POSITION ) |
			( SECURITY_USER_PACCON3_OPAMP1WR << _PACCON3_OPAMP1WR_POSITION ) |
			( SECURITY_USER_PACCON3_OPAMP2WR << _PACCON3_OPAMP2WR_POSITION ) |
			( SECURITY_USER_PACCON3_OPAMP3WR << _PACCON3_OPAMP3WR_POSITION ) |
			( SECURITY_USER_PACCON3_IBIASCONWR << _PACCON3_IBIASCONWR_POSITION ) ;
		#ifdef DEF_BITNAME
			PACCON3bits.RPCONLK = SECURITY_USER_PACCON3_RPCONLK;
			PACCON3bits.PMDLK = SECURITY_USER_PACCON3_PMDLK;
			PACCON3bits.MBISTCONLK = SECURITY_USER_PACCON3_MBISTCONLK;
			PACCON3bits.APCLKCONLK = SECURITY_USER_PACCON3_APCLKCONLK;
			PACCON3bits.OPAMP1LK = SECURITY_USER_PACCON3_OPAMP1LK;
			PACCON3bits.OPAMP2LK = SECURITY_USER_PACCON3_OPAMP2LK;
			PACCON3bits.OPAMP3LK = SECURITY_USER_PACCON3_OPAMP3LK;
			PACCON3bits.IBIASCONLK = SECURITY_USER_PACCON3_IBIASCONLK;
			PACCON3bits.RPCONWR = SECURITY_USER_PACCON3_RPCONWR;
			PACCON3bits.PMDWR = SECURITY_USER_PACCON3_PMDWR;
			PACCON3bits.MBISTCONWR = SECURITY_USER_PACCON3_MBISTCONWR;
			PACCON3bits.APCLKCONWR = SECURITY_USER_PACCON3_APCLKCONWR;
			PACCON3bits.OPAMP1WR = SECURITY_USER_PACCON3_OPAMP1WR;
			PACCON3bits.OPAMP2WR = SECURITY_USER_PACCON3_OPAMP2WR;
			PACCON3bits.OPAMP3WR = SECURITY_USER_PACCON3_OPAMP3WR;
			PACCON3bits.IBIASCONWR = SECURITY_USER_PACCON3_IBIASCONWR;
		#endif 
}		

