/*----------------------------------------------------------------------------*/
/**
* @file		SM_Driver.c
* @brief	SMモジュールに関するドライバ関数
* @date		25/5/4
* @details	
* @note		
*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*インクルードファイル*/
/*----------------------------------------------------------------------------*/
#include <xc.h>
#include "BoardSupportPackage.h"
#include "init_fix.h"
#include "typedef.h"
#include "sm_user.h"
/*----------------------------------------------------------------------------*/
/*定数定義*/
/*----------------------------------------------------------------------------*/


/*----------------------------------------------------------------------------*/
/*
* @fn        vdg_SM_Set_Register(void)
* @brief     SMのレジスタを初期化します 
* @param
* @return
* @detail
*/
/*----------------------------------------------------------------------------*/
void vdg_SM_Set_Register(void)
{
	
	/*-----------------------------------------------------------------------*/
	/* SDATACMD0レジスタ */
	/*-----------------------------------------------------------------------*/
		SDATACMD0 = 
			( SM_USER_SDATACMD0_PC0 << _SDATACMD0_PC0_POSITION ) |
			( SM_USER_SDATACMD0_PCA << _SDATACMD0_PCA_POSITION ) |
			( SM_USER_SDATACMD0_PCB << _SDATACMD0_PCB_POSITION ) |
			( SM_USER_SDATACMD0_PCC << _SDATACMD0_PCC_POSITION ) |
			( SM_USER_SDATACMD0_BAL << _SDATACMD0_BAL_POSITION ) |
			( SM_USER_SDATACMD0_CONV << _SDATACMD0_CONV_POSITION ) |
			( SM_USER_SDATACMD0_DISCHRG << _SDATACMD0_DISCHRG_POSITION ) |
			( SM_USER_SDATACMD0_CHRG << _SDATACMD0_CHRG_POSITION ) |
			( SM_USER_SDATACMD0_SECOND << _SDATACMD0_SECOND_POSITION ) |
			( SM_USER_SDATACMD0_MSTART << _SDATACMD0_MSTART_POSITION ) |
			( SM_USER_SDATACMD0_DMASTP << _SDATACMD0_DMASTP_POSITION ) |
			( SM_USER_SDATACMD0_LOOP << _SDATACMD0_LOOP_POSITION ) |
			( SM_USER_SDATACMD0_END << _SDATACMD0_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SDATACMD0bits.PC0 = SM_USER_SDATACMD0_PC0;
			SDATACMD0bits.PCA = SM_USER_SDATACMD0_PCA;
			SDATACMD0bits.PCB = SM_USER_SDATACMD0_PCB;
			SDATACMD0bits.PCC = SM_USER_SDATACMD0_PCC;
			SDATACMD0bits.BAL = SM_USER_SDATACMD0_BAL;
			SDATACMD0bits.CONV = SM_USER_SDATACMD0_CONV;
			SDATACMD0bits.DISCHRG = SM_USER_SDATACMD0_DISCHRG;
			SDATACMD0bits.CHRG = SM_USER_SDATACMD0_CHRG;
			SDATACMD0bits.SECOND = SM_USER_SDATACMD0_SECOND;
			SDATACMD0bits.MSTART = SM_USER_SDATACMD0_MSTART;
			SDATACMD0bits.DMASTP = SM_USER_SDATACMD0_DMASTP;
			SDATACMD0bits.LOOP = SM_USER_SDATACMD0_LOOP;
			SDATACMD0bits.END = SM_USER_SDATACMD0_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SDATACMD1レジスタ */
	/*-----------------------------------------------------------------------*/
		SDATACMD1 = 
			( SM_USER_SDATACMD1_PC0 << _SDATACMD1_PC0_POSITION ) |
			( SM_USER_SDATACMD1_PCA << _SDATACMD1_PCA_POSITION ) |
			( SM_USER_SDATACMD1_PCB << _SDATACMD1_PCB_POSITION ) |
			( SM_USER_SDATACMD1_PCC << _SDATACMD1_PCC_POSITION ) |
			( SM_USER_SDATACMD1_BAL << _SDATACMD1_BAL_POSITION ) |
			( SM_USER_SDATACMD1_CONV << _SDATACMD1_CONV_POSITION ) |
			( SM_USER_SDATACMD1_DISCHRG << _SDATACMD1_DISCHRG_POSITION ) |
			( SM_USER_SDATACMD1_CHRG << _SDATACMD1_CHRG_POSITION ) |
			( SM_USER_SDATACMD1_SECOND << _SDATACMD1_SECOND_POSITION ) |
			( SM_USER_SDATACMD1_MSTART << _SDATACMD1_MSTART_POSITION ) |
			( SM_USER_SDATACMD1_DMASTP << _SDATACMD1_DMASTP_POSITION ) |
			( SM_USER_SDATACMD1_LOOP << _SDATACMD1_LOOP_POSITION ) |
			( SM_USER_SDATACMD1_END << _SDATACMD1_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SDATACMD1bits.PC0 = SM_USER_SDATACMD1_PC0;
			SDATACMD1bits.PCA = SM_USER_SDATACMD1_PCA;
			SDATACMD1bits.PCB = SM_USER_SDATACMD1_PCB;
			SDATACMD1bits.PCC = SM_USER_SDATACMD1_PCC;
			SDATACMD1bits.BAL = SM_USER_SDATACMD1_BAL;
			SDATACMD1bits.CONV = SM_USER_SDATACMD1_CONV;
			SDATACMD1bits.DISCHRG = SM_USER_SDATACMD1_DISCHRG;
			SDATACMD1bits.CHRG = SM_USER_SDATACMD1_CHRG;
			SDATACMD1bits.SECOND = SM_USER_SDATACMD1_SECOND;
			SDATACMD1bits.MSTART = SM_USER_SDATACMD1_MSTART;
			SDATACMD1bits.DMASTP = SM_USER_SDATACMD1_DMASTP;
			SDATACMD1bits.LOOP = SM_USER_SDATACMD1_LOOP;
			SDATACMD1bits.END = SM_USER_SDATACMD1_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SDATACMD2レジスタ */
	/*-----------------------------------------------------------------------*/
		SDATACMD2 = 
			( SM_USER_SDATACMD2_PC0 << _SDATACMD2_PC0_POSITION ) |
			( SM_USER_SDATACMD2_PCA << _SDATACMD2_PCA_POSITION ) |
			( SM_USER_SDATACMD2_PCB << _SDATACMD2_PCB_POSITION ) |
			( SM_USER_SDATACMD2_PCC << _SDATACMD2_PCC_POSITION ) |
			( SM_USER_SDATACMD2_BAL << _SDATACMD2_BAL_POSITION ) |
			( SM_USER_SDATACMD2_CONV << _SDATACMD2_CONV_POSITION ) |
			( SM_USER_SDATACMD2_DISCHRG << _SDATACMD2_DISCHRG_POSITION ) |
			( SM_USER_SDATACMD2_CHRG << _SDATACMD2_CHRG_POSITION ) |
			( SM_USER_SDATACMD2_SECOND << _SDATACMD2_SECOND_POSITION ) |
			( SM_USER_SDATACMD2_MSTART << _SDATACMD2_MSTART_POSITION ) |
			( SM_USER_SDATACMD2_DMASTP << _SDATACMD2_DMASTP_POSITION ) |
			( SM_USER_SDATACMD2_LOOP << _SDATACMD2_LOOP_POSITION ) |
			( SM_USER_SDATACMD2_END << _SDATACMD2_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SDATACMD2bits.PC0 = SM_USER_SDATACMD2_PC0;
			SDATACMD2bits.PCA = SM_USER_SDATACMD2_PCA;
			SDATACMD2bits.PCB = SM_USER_SDATACMD2_PCB;
			SDATACMD2bits.PCC = SM_USER_SDATACMD2_PCC;
			SDATACMD2bits.BAL = SM_USER_SDATACMD2_BAL;
			SDATACMD2bits.CONV = SM_USER_SDATACMD2_CONV;
			SDATACMD2bits.DISCHRG = SM_USER_SDATACMD2_DISCHRG;
			SDATACMD2bits.CHRG = SM_USER_SDATACMD2_CHRG;
			SDATACMD2bits.SECOND = SM_USER_SDATACMD2_SECOND;
			SDATACMD2bits.MSTART = SM_USER_SDATACMD2_MSTART;
			SDATACMD2bits.DMASTP = SM_USER_SDATACMD2_DMASTP;
			SDATACMD2bits.LOOP = SM_USER_SDATACMD2_LOOP;
			SDATACMD2bits.END = SM_USER_SDATACMD2_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SDATACMD3レジスタ */
	/*-----------------------------------------------------------------------*/
		SDATACMD3 = 
			( SM_USER_SDATACMD3_PC0 << _SDATACMD3_PC0_POSITION ) |
			( SM_USER_SDATACMD3_PCA << _SDATACMD3_PCA_POSITION ) |
			( SM_USER_SDATACMD3_PCB << _SDATACMD3_PCB_POSITION ) |
			( SM_USER_SDATACMD3_PCC << _SDATACMD3_PCC_POSITION ) |
			( SM_USER_SDATACMD3_BAL << _SDATACMD3_BAL_POSITION ) |
			( SM_USER_SDATACMD3_CONV << _SDATACMD3_CONV_POSITION ) |
			( SM_USER_SDATACMD3_DISCHRG << _SDATACMD3_DISCHRG_POSITION ) |
			( SM_USER_SDATACMD3_CHRG << _SDATACMD3_CHRG_POSITION ) |
			( SM_USER_SDATACMD3_SECOND << _SDATACMD3_SECOND_POSITION ) |
			( SM_USER_SDATACMD3_MSTART << _SDATACMD3_MSTART_POSITION ) |
			( SM_USER_SDATACMD3_DMASTP << _SDATACMD3_DMASTP_POSITION ) |
			( SM_USER_SDATACMD3_LOOP << _SDATACMD3_LOOP_POSITION ) |
			( SM_USER_SDATACMD3_END << _SDATACMD3_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SDATACMD3bits.PC0 = SM_USER_SDATACMD3_PC0;
			SDATACMD3bits.PCA = SM_USER_SDATACMD3_PCA;
			SDATACMD3bits.PCB = SM_USER_SDATACMD3_PCB;
			SDATACMD3bits.PCC = SM_USER_SDATACMD3_PCC;
			SDATACMD3bits.BAL = SM_USER_SDATACMD3_BAL;
			SDATACMD3bits.CONV = SM_USER_SDATACMD3_CONV;
			SDATACMD3bits.DISCHRG = SM_USER_SDATACMD3_DISCHRG;
			SDATACMD3bits.CHRG = SM_USER_SDATACMD3_CHRG;
			SDATACMD3bits.SECOND = SM_USER_SDATACMD3_SECOND;
			SDATACMD3bits.MSTART = SM_USER_SDATACMD3_MSTART;
			SDATACMD3bits.DMASTP = SM_USER_SDATACMD3_DMASTP;
			SDATACMD3bits.LOOP = SM_USER_SDATACMD3_LOOP;
			SDATACMD3bits.END = SM_USER_SDATACMD3_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SDATACMD4レジスタ */
	/*-----------------------------------------------------------------------*/
		SDATACMD4 = 
			( SM_USER_SDATACMD4_PC0 << _SDATACMD4_PC0_POSITION ) |
			( SM_USER_SDATACMD4_PCA << _SDATACMD4_PCA_POSITION ) |
			( SM_USER_SDATACMD4_PCB << _SDATACMD4_PCB_POSITION ) |
			( SM_USER_SDATACMD4_PCC << _SDATACMD4_PCC_POSITION ) |
			( SM_USER_SDATACMD4_BAL << _SDATACMD4_BAL_POSITION ) |
			( SM_USER_SDATACMD4_CONV << _SDATACMD4_CONV_POSITION ) |
			( SM_USER_SDATACMD4_DISCHRG << _SDATACMD4_DISCHRG_POSITION ) |
			( SM_USER_SDATACMD4_CHRG << _SDATACMD4_CHRG_POSITION ) |
			( SM_USER_SDATACMD4_SECOND << _SDATACMD4_SECOND_POSITION ) |
			( SM_USER_SDATACMD4_MSTART << _SDATACMD4_MSTART_POSITION ) |
			( SM_USER_SDATACMD4_DMASTP << _SDATACMD4_DMASTP_POSITION ) |
			( SM_USER_SDATACMD4_LOOP << _SDATACMD4_LOOP_POSITION ) |
			( SM_USER_SDATACMD4_END << _SDATACMD4_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SDATACMD4bits.PC0 = SM_USER_SDATACMD4_PC0;
			SDATACMD4bits.PCA = SM_USER_SDATACMD4_PCA;
			SDATACMD4bits.PCB = SM_USER_SDATACMD4_PCB;
			SDATACMD4bits.PCC = SM_USER_SDATACMD4_PCC;
			SDATACMD4bits.BAL = SM_USER_SDATACMD4_BAL;
			SDATACMD4bits.CONV = SM_USER_SDATACMD4_CONV;
			SDATACMD4bits.DISCHRG = SM_USER_SDATACMD4_DISCHRG;
			SDATACMD4bits.CHRG = SM_USER_SDATACMD4_CHRG;
			SDATACMD4bits.SECOND = SM_USER_SDATACMD4_SECOND;
			SDATACMD4bits.MSTART = SM_USER_SDATACMD4_MSTART;
			SDATACMD4bits.DMASTP = SM_USER_SDATACMD4_DMASTP;
			SDATACMD4bits.LOOP = SM_USER_SDATACMD4_LOOP;
			SDATACMD4bits.END = SM_USER_SDATACMD4_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SDATACMD5レジスタ */
	/*-----------------------------------------------------------------------*/
		SDATACMD5 = 
			( SM_USER_SDATACMD5_PC0 << _SDATACMD5_PC0_POSITION ) |
			( SM_USER_SDATACMD5_PCA << _SDATACMD5_PCA_POSITION ) |
			( SM_USER_SDATACMD5_PCB << _SDATACMD5_PCB_POSITION ) |
			( SM_USER_SDATACMD5_PCC << _SDATACMD5_PCC_POSITION ) |
			( SM_USER_SDATACMD5_BAL << _SDATACMD5_BAL_POSITION ) |
			( SM_USER_SDATACMD5_CONV << _SDATACMD5_CONV_POSITION ) |
			( SM_USER_SDATACMD5_DISCHRG << _SDATACMD5_DISCHRG_POSITION ) |
			( SM_USER_SDATACMD5_CHRG << _SDATACMD5_CHRG_POSITION ) |
			( SM_USER_SDATACMD5_SECOND << _SDATACMD5_SECOND_POSITION ) |
			( SM_USER_SDATACMD5_MSTART << _SDATACMD5_MSTART_POSITION ) |
			( SM_USER_SDATACMD5_DMASTP << _SDATACMD5_DMASTP_POSITION ) |
			( SM_USER_SDATACMD5_LOOP << _SDATACMD5_LOOP_POSITION ) |
			( SM_USER_SDATACMD5_END << _SDATACMD5_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SDATACMD5bits.PC0 = SM_USER_SDATACMD5_PC0;
			SDATACMD5bits.PCA = SM_USER_SDATACMD5_PCA;
			SDATACMD5bits.PCB = SM_USER_SDATACMD5_PCB;
			SDATACMD5bits.PCC = SM_USER_SDATACMD5_PCC;
			SDATACMD5bits.BAL = SM_USER_SDATACMD5_BAL;
			SDATACMD5bits.CONV = SM_USER_SDATACMD5_CONV;
			SDATACMD5bits.DISCHRG = SM_USER_SDATACMD5_DISCHRG;
			SDATACMD5bits.CHRG = SM_USER_SDATACMD5_CHRG;
			SDATACMD5bits.SECOND = SM_USER_SDATACMD5_SECOND;
			SDATACMD5bits.MSTART = SM_USER_SDATACMD5_MSTART;
			SDATACMD5bits.DMASTP = SM_USER_SDATACMD5_DMASTP;
			SDATACMD5bits.LOOP = SM_USER_SDATACMD5_LOOP;
			SDATACMD5bits.END = SM_USER_SDATACMD5_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SDATACMD6レジスタ */
	/*-----------------------------------------------------------------------*/
		SDATACMD6 = 
			( SM_USER_SDATACMD6_PC0 << _SDATACMD6_PC0_POSITION ) |
			( SM_USER_SDATACMD6_PCA << _SDATACMD6_PCA_POSITION ) |
			( SM_USER_SDATACMD6_PCB << _SDATACMD6_PCB_POSITION ) |
			( SM_USER_SDATACMD6_PCC << _SDATACMD6_PCC_POSITION ) |
			( SM_USER_SDATACMD6_BAL << _SDATACMD6_BAL_POSITION ) |
			( SM_USER_SDATACMD6_CONV << _SDATACMD6_CONV_POSITION ) |
			( SM_USER_SDATACMD6_DISCHRG << _SDATACMD6_DISCHRG_POSITION ) |
			( SM_USER_SDATACMD6_CHRG << _SDATACMD6_CHRG_POSITION ) |
			( SM_USER_SDATACMD6_SECOND << _SDATACMD6_SECOND_POSITION ) |
			( SM_USER_SDATACMD6_MSTART << _SDATACMD6_MSTART_POSITION ) |
			( SM_USER_SDATACMD6_DMASTP << _SDATACMD6_DMASTP_POSITION ) |
			( SM_USER_SDATACMD6_LOOP << _SDATACMD6_LOOP_POSITION ) |
			( SM_USER_SDATACMD6_END << _SDATACMD6_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SDATACMD6bits.PC0 = SM_USER_SDATACMD6_PC0;
			SDATACMD6bits.PCA = SM_USER_SDATACMD6_PCA;
			SDATACMD6bits.PCB = SM_USER_SDATACMD6_PCB;
			SDATACMD6bits.PCC = SM_USER_SDATACMD6_PCC;
			SDATACMD6bits.BAL = SM_USER_SDATACMD6_BAL;
			SDATACMD6bits.CONV = SM_USER_SDATACMD6_CONV;
			SDATACMD6bits.DISCHRG = SM_USER_SDATACMD6_DISCHRG;
			SDATACMD6bits.CHRG = SM_USER_SDATACMD6_CHRG;
			SDATACMD6bits.SECOND = SM_USER_SDATACMD6_SECOND;
			SDATACMD6bits.MSTART = SM_USER_SDATACMD6_MSTART;
			SDATACMD6bits.DMASTP = SM_USER_SDATACMD6_DMASTP;
			SDATACMD6bits.LOOP = SM_USER_SDATACMD6_LOOP;
			SDATACMD6bits.END = SM_USER_SDATACMD6_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SDATACMD7レジスタ */
	/*-----------------------------------------------------------------------*/
		SDATACMD7 = 
			( SM_USER_SDATACMD7_PC0 << _SDATACMD7_PC0_POSITION ) |
			( SM_USER_SDATACMD7_PCA << _SDATACMD7_PCA_POSITION ) |
			( SM_USER_SDATACMD7_PCB << _SDATACMD7_PCB_POSITION ) |
			( SM_USER_SDATACMD7_PCC << _SDATACMD7_PCC_POSITION ) |
			( SM_USER_SDATACMD7_BAL << _SDATACMD7_BAL_POSITION ) |
			( SM_USER_SDATACMD7_CONV << _SDATACMD7_CONV_POSITION ) |
			( SM_USER_SDATACMD7_DISCHRG << _SDATACMD7_DISCHRG_POSITION ) |
			( SM_USER_SDATACMD7_CHRG << _SDATACMD7_CHRG_POSITION ) |
			( SM_USER_SDATACMD7_SECOND << _SDATACMD7_SECOND_POSITION ) |
			( SM_USER_SDATACMD7_MSTART << _SDATACMD7_MSTART_POSITION ) |
			( SM_USER_SDATACMD7_DMASTP << _SDATACMD7_DMASTP_POSITION ) |
			( SM_USER_SDATACMD7_LOOP << _SDATACMD7_LOOP_POSITION ) |
			( SM_USER_SDATACMD7_END << _SDATACMD7_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SDATACMD7bits.PC0 = SM_USER_SDATACMD7_PC0;
			SDATACMD7bits.PCA = SM_USER_SDATACMD7_PCA;
			SDATACMD7bits.PCB = SM_USER_SDATACMD7_PCB;
			SDATACMD7bits.PCC = SM_USER_SDATACMD7_PCC;
			SDATACMD7bits.BAL = SM_USER_SDATACMD7_BAL;
			SDATACMD7bits.CONV = SM_USER_SDATACMD7_CONV;
			SDATACMD7bits.DISCHRG = SM_USER_SDATACMD7_DISCHRG;
			SDATACMD7bits.CHRG = SM_USER_SDATACMD7_CHRG;
			SDATACMD7bits.SECOND = SM_USER_SDATACMD7_SECOND;
			SDATACMD7bits.MSTART = SM_USER_SDATACMD7_MSTART;
			SDATACMD7bits.DMASTP = SM_USER_SDATACMD7_DMASTP;
			SDATACMD7bits.LOOP = SM_USER_SDATACMD7_LOOP;
			SDATACMD7bits.END = SM_USER_SDATACMD7_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SDATACMD8レジスタ */
	/*-----------------------------------------------------------------------*/
		SDATACMD8 = 
			( SM_USER_SDATACMD8_PC0 << _SDATACMD8_PC0_POSITION ) |
			( SM_USER_SDATACMD8_PCA << _SDATACMD8_PCA_POSITION ) |
			( SM_USER_SDATACMD8_PCB << _SDATACMD8_PCB_POSITION ) |
			( SM_USER_SDATACMD8_PCC << _SDATACMD8_PCC_POSITION ) |
			( SM_USER_SDATACMD8_BAL << _SDATACMD8_BAL_POSITION ) |
			( SM_USER_SDATACMD8_CONV << _SDATACMD8_CONV_POSITION ) |
			( SM_USER_SDATACMD8_DISCHRG << _SDATACMD8_DISCHRG_POSITION ) |
			( SM_USER_SDATACMD8_CHRG << _SDATACMD8_CHRG_POSITION ) |
			( SM_USER_SDATACMD8_SECOND << _SDATACMD8_SECOND_POSITION ) |
			( SM_USER_SDATACMD8_MSTART << _SDATACMD8_MSTART_POSITION ) |
			( SM_USER_SDATACMD8_DMASTP << _SDATACMD8_DMASTP_POSITION ) |
			( SM_USER_SDATACMD8_LOOP << _SDATACMD8_LOOP_POSITION ) |
			( SM_USER_SDATACMD8_END << _SDATACMD8_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SDATACMD8bits.PC0 = SM_USER_SDATACMD8_PC0;
			SDATACMD8bits.PCA = SM_USER_SDATACMD8_PCA;
			SDATACMD8bits.PCB = SM_USER_SDATACMD8_PCB;
			SDATACMD8bits.PCC = SM_USER_SDATACMD8_PCC;
			SDATACMD8bits.BAL = SM_USER_SDATACMD8_BAL;
			SDATACMD8bits.CONV = SM_USER_SDATACMD8_CONV;
			SDATACMD8bits.DISCHRG = SM_USER_SDATACMD8_DISCHRG;
			SDATACMD8bits.CHRG = SM_USER_SDATACMD8_CHRG;
			SDATACMD8bits.SECOND = SM_USER_SDATACMD8_SECOND;
			SDATACMD8bits.MSTART = SM_USER_SDATACMD8_MSTART;
			SDATACMD8bits.DMASTP = SM_USER_SDATACMD8_DMASTP;
			SDATACMD8bits.LOOP = SM_USER_SDATACMD8_LOOP;
			SDATACMD8bits.END = SM_USER_SDATACMD8_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SDATACMD9レジスタ */
	/*-----------------------------------------------------------------------*/
		SDATACMD9 = 
			( SM_USER_SDATACMD9_PC0 << _SDATACMD9_PC0_POSITION ) |
			( SM_USER_SDATACMD9_PCA << _SDATACMD9_PCA_POSITION ) |
			( SM_USER_SDATACMD9_PCB << _SDATACMD9_PCB_POSITION ) |
			( SM_USER_SDATACMD9_PCC << _SDATACMD9_PCC_POSITION ) |
			( SM_USER_SDATACMD9_BAL << _SDATACMD9_BAL_POSITION ) |
			( SM_USER_SDATACMD9_CONV << _SDATACMD9_CONV_POSITION ) |
			( SM_USER_SDATACMD9_DISCHRG << _SDATACMD9_DISCHRG_POSITION ) |
			( SM_USER_SDATACMD9_CHRG << _SDATACMD9_CHRG_POSITION ) |
			( SM_USER_SDATACMD9_SECOND << _SDATACMD9_SECOND_POSITION ) |
			( SM_USER_SDATACMD9_MSTART << _SDATACMD9_MSTART_POSITION ) |
			( SM_USER_SDATACMD9_DMASTP << _SDATACMD9_DMASTP_POSITION ) |
			( SM_USER_SDATACMD9_LOOP << _SDATACMD9_LOOP_POSITION ) |
			( SM_USER_SDATACMD9_END << _SDATACMD9_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SDATACMD9bits.PC0 = SM_USER_SDATACMD9_PC0;
			SDATACMD9bits.PCA = SM_USER_SDATACMD9_PCA;
			SDATACMD9bits.PCB = SM_USER_SDATACMD9_PCB;
			SDATACMD9bits.PCC = SM_USER_SDATACMD9_PCC;
			SDATACMD9bits.BAL = SM_USER_SDATACMD9_BAL;
			SDATACMD9bits.CONV = SM_USER_SDATACMD9_CONV;
			SDATACMD9bits.DISCHRG = SM_USER_SDATACMD9_DISCHRG;
			SDATACMD9bits.CHRG = SM_USER_SDATACMD9_CHRG;
			SDATACMD9bits.SECOND = SM_USER_SDATACMD9_SECOND;
			SDATACMD9bits.MSTART = SM_USER_SDATACMD9_MSTART;
			SDATACMD9bits.DMASTP = SM_USER_SDATACMD9_DMASTP;
			SDATACMD9bits.LOOP = SM_USER_SDATACMD9_LOOP;
			SDATACMD9bits.END = SM_USER_SDATACMD9_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SDATACMD10レジスタ */
	/*-----------------------------------------------------------------------*/
		SDATACMD10 = 
			( SM_USER_SDATACMD10_PC0 << _SDATACMD10_PC0_POSITION ) |
			( SM_USER_SDATACMD10_PCA << _SDATACMD10_PCA_POSITION ) |
			( SM_USER_SDATACMD10_PCB << _SDATACMD10_PCB_POSITION ) |
			( SM_USER_SDATACMD10_PCC << _SDATACMD10_PCC_POSITION ) |
			( SM_USER_SDATACMD10_BAL << _SDATACMD10_BAL_POSITION ) |
			( SM_USER_SDATACMD10_CONV << _SDATACMD10_CONV_POSITION ) |
			( SM_USER_SDATACMD10_DISCHRG << _SDATACMD10_DISCHRG_POSITION ) |
			( SM_USER_SDATACMD10_CHRG << _SDATACMD10_CHRG_POSITION ) |
			( SM_USER_SDATACMD10_SECOND << _SDATACMD10_SECOND_POSITION ) |
			( SM_USER_SDATACMD10_MSTART << _SDATACMD10_MSTART_POSITION ) |
			( SM_USER_SDATACMD10_DMASTP << _SDATACMD10_DMASTP_POSITION ) |
			( SM_USER_SDATACMD10_LOOP << _SDATACMD10_LOOP_POSITION ) |
			( SM_USER_SDATACMD10_END << _SDATACMD10_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SDATACMD10bits.PC0 = SM_USER_SDATACMD10_PC0;
			SDATACMD10bits.PCA = SM_USER_SDATACMD10_PCA;
			SDATACMD10bits.PCB = SM_USER_SDATACMD10_PCB;
			SDATACMD10bits.PCC = SM_USER_SDATACMD10_PCC;
			SDATACMD10bits.BAL = SM_USER_SDATACMD10_BAL;
			SDATACMD10bits.CONV = SM_USER_SDATACMD10_CONV;
			SDATACMD10bits.DISCHRG = SM_USER_SDATACMD10_DISCHRG;
			SDATACMD10bits.CHRG = SM_USER_SDATACMD10_CHRG;
			SDATACMD10bits.SECOND = SM_USER_SDATACMD10_SECOND;
			SDATACMD10bits.MSTART = SM_USER_SDATACMD10_MSTART;
			SDATACMD10bits.DMASTP = SM_USER_SDATACMD10_DMASTP;
			SDATACMD10bits.LOOP = SM_USER_SDATACMD10_LOOP;
			SDATACMD10bits.END = SM_USER_SDATACMD10_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SDATACMD11レジスタ */
	/*-----------------------------------------------------------------------*/
		SDATACMD11 = 
			( SM_USER_SDATACMD11_PC0 << _SDATACMD11_PC0_POSITION ) |
			( SM_USER_SDATACMD11_PCA << _SDATACMD11_PCA_POSITION ) |
			( SM_USER_SDATACMD11_PCB << _SDATACMD11_PCB_POSITION ) |
			( SM_USER_SDATACMD11_PCC << _SDATACMD11_PCC_POSITION ) |
			( SM_USER_SDATACMD11_BAL << _SDATACMD11_BAL_POSITION ) |
			( SM_USER_SDATACMD11_CONV << _SDATACMD11_CONV_POSITION ) |
			( SM_USER_SDATACMD11_DISCHRG << _SDATACMD11_DISCHRG_POSITION ) |
			( SM_USER_SDATACMD11_CHRG << _SDATACMD11_CHRG_POSITION ) |
			( SM_USER_SDATACMD11_SECOND << _SDATACMD11_SECOND_POSITION ) |
			( SM_USER_SDATACMD11_MSTART << _SDATACMD11_MSTART_POSITION ) |
			( SM_USER_SDATACMD11_DMASTP << _SDATACMD11_DMASTP_POSITION ) |
			( SM_USER_SDATACMD11_LOOP << _SDATACMD11_LOOP_POSITION ) |
			( SM_USER_SDATACMD11_END << _SDATACMD11_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SDATACMD11bits.PC0 = SM_USER_SDATACMD11_PC0;
			SDATACMD11bits.PCA = SM_USER_SDATACMD11_PCA;
			SDATACMD11bits.PCB = SM_USER_SDATACMD11_PCB;
			SDATACMD11bits.PCC = SM_USER_SDATACMD11_PCC;
			SDATACMD11bits.BAL = SM_USER_SDATACMD11_BAL;
			SDATACMD11bits.CONV = SM_USER_SDATACMD11_CONV;
			SDATACMD11bits.DISCHRG = SM_USER_SDATACMD11_DISCHRG;
			SDATACMD11bits.CHRG = SM_USER_SDATACMD11_CHRG;
			SDATACMD11bits.SECOND = SM_USER_SDATACMD11_SECOND;
			SDATACMD11bits.MSTART = SM_USER_SDATACMD11_MSTART;
			SDATACMD11bits.DMASTP = SM_USER_SDATACMD11_DMASTP;
			SDATACMD11bits.LOOP = SM_USER_SDATACMD11_LOOP;
			SDATACMD11bits.END = SM_USER_SDATACMD11_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SDATACMD12レジスタ */
	/*-----------------------------------------------------------------------*/
		SDATACMD12 = 
			( SM_USER_SDATACMD12_PC0 << _SDATACMD12_PC0_POSITION ) |
			( SM_USER_SDATACMD12_PCA << _SDATACMD12_PCA_POSITION ) |
			( SM_USER_SDATACMD12_PCB << _SDATACMD12_PCB_POSITION ) |
			( SM_USER_SDATACMD12_PCC << _SDATACMD12_PCC_POSITION ) |
			( SM_USER_SDATACMD12_BAL << _SDATACMD12_BAL_POSITION ) |
			( SM_USER_SDATACMD12_CONV << _SDATACMD12_CONV_POSITION ) |
			( SM_USER_SDATACMD12_DISCHRG << _SDATACMD12_DISCHRG_POSITION ) |
			( SM_USER_SDATACMD12_CHRG << _SDATACMD12_CHRG_POSITION ) |
			( SM_USER_SDATACMD12_SECOND << _SDATACMD12_SECOND_POSITION ) |
			( SM_USER_SDATACMD12_MSTART << _SDATACMD12_MSTART_POSITION ) |
			( SM_USER_SDATACMD12_DMASTP << _SDATACMD12_DMASTP_POSITION ) |
			( SM_USER_SDATACMD12_LOOP << _SDATACMD12_LOOP_POSITION ) |
			( SM_USER_SDATACMD12_END << _SDATACMD12_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SDATACMD12bits.PC0 = SM_USER_SDATACMD12_PC0;
			SDATACMD12bits.PCA = SM_USER_SDATACMD12_PCA;
			SDATACMD12bits.PCB = SM_USER_SDATACMD12_PCB;
			SDATACMD12bits.PCC = SM_USER_SDATACMD12_PCC;
			SDATACMD12bits.BAL = SM_USER_SDATACMD12_BAL;
			SDATACMD12bits.CONV = SM_USER_SDATACMD12_CONV;
			SDATACMD12bits.DISCHRG = SM_USER_SDATACMD12_DISCHRG;
			SDATACMD12bits.CHRG = SM_USER_SDATACMD12_CHRG;
			SDATACMD12bits.SECOND = SM_USER_SDATACMD12_SECOND;
			SDATACMD12bits.MSTART = SM_USER_SDATACMD12_MSTART;
			SDATACMD12bits.DMASTP = SM_USER_SDATACMD12_DMASTP;
			SDATACMD12bits.LOOP = SM_USER_SDATACMD12_LOOP;
			SDATACMD12bits.END = SM_USER_SDATACMD12_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SDATACMD13レジスタ */
	/*-----------------------------------------------------------------------*/
		SDATACMD13 = 
			( SM_USER_SDATACMD13_PC0 << _SDATACMD13_PC0_POSITION ) |
			( SM_USER_SDATACMD13_PCA << _SDATACMD13_PCA_POSITION ) |
			( SM_USER_SDATACMD13_PCB << _SDATACMD13_PCB_POSITION ) |
			( SM_USER_SDATACMD13_PCC << _SDATACMD13_PCC_POSITION ) |
			( SM_USER_SDATACMD13_BAL << _SDATACMD13_BAL_POSITION ) |
			( SM_USER_SDATACMD13_CONV << _SDATACMD13_CONV_POSITION ) |
			( SM_USER_SDATACMD13_DISCHRG << _SDATACMD13_DISCHRG_POSITION ) |
			( SM_USER_SDATACMD13_CHRG << _SDATACMD13_CHRG_POSITION ) |
			( SM_USER_SDATACMD13_SECOND << _SDATACMD13_SECOND_POSITION ) |
			( SM_USER_SDATACMD13_MSTART << _SDATACMD13_MSTART_POSITION ) |
			( SM_USER_SDATACMD13_DMASTP << _SDATACMD13_DMASTP_POSITION ) |
			( SM_USER_SDATACMD13_LOOP << _SDATACMD13_LOOP_POSITION ) |
			( SM_USER_SDATACMD13_END << _SDATACMD13_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SDATACMD13bits.PC0 = SM_USER_SDATACMD13_PC0;
			SDATACMD13bits.PCA = SM_USER_SDATACMD13_PCA;
			SDATACMD13bits.PCB = SM_USER_SDATACMD13_PCB;
			SDATACMD13bits.PCC = SM_USER_SDATACMD13_PCC;
			SDATACMD13bits.BAL = SM_USER_SDATACMD13_BAL;
			SDATACMD13bits.CONV = SM_USER_SDATACMD13_CONV;
			SDATACMD13bits.DISCHRG = SM_USER_SDATACMD13_DISCHRG;
			SDATACMD13bits.CHRG = SM_USER_SDATACMD13_CHRG;
			SDATACMD13bits.SECOND = SM_USER_SDATACMD13_SECOND;
			SDATACMD13bits.MSTART = SM_USER_SDATACMD13_MSTART;
			SDATACMD13bits.DMASTP = SM_USER_SDATACMD13_DMASTP;
			SDATACMD13bits.LOOP = SM_USER_SDATACMD13_LOOP;
			SDATACMD13bits.END = SM_USER_SDATACMD13_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SDATACMD14レジスタ */
	/*-----------------------------------------------------------------------*/
		SDATACMD14 = 
			( SM_USER_SDATACMD14_PC0 << _SDATACMD14_PC0_POSITION ) |
			( SM_USER_SDATACMD14_PCA << _SDATACMD14_PCA_POSITION ) |
			( SM_USER_SDATACMD14_PCB << _SDATACMD14_PCB_POSITION ) |
			( SM_USER_SDATACMD14_PCC << _SDATACMD14_PCC_POSITION ) |
			( SM_USER_SDATACMD14_BAL << _SDATACMD14_BAL_POSITION ) |
			( SM_USER_SDATACMD14_CONV << _SDATACMD14_CONV_POSITION ) |
			( SM_USER_SDATACMD14_DISCHRG << _SDATACMD14_DISCHRG_POSITION ) |
			( SM_USER_SDATACMD14_CHRG << _SDATACMD14_CHRG_POSITION ) |
			( SM_USER_SDATACMD14_SECOND << _SDATACMD14_SECOND_POSITION ) |
			( SM_USER_SDATACMD14_MSTART << _SDATACMD14_MSTART_POSITION ) |
			( SM_USER_SDATACMD14_DMASTP << _SDATACMD14_DMASTP_POSITION ) |
			( SM_USER_SDATACMD14_LOOP << _SDATACMD14_LOOP_POSITION ) |
			( SM_USER_SDATACMD14_END << _SDATACMD14_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SDATACMD14bits.PC0 = SM_USER_SDATACMD14_PC0;
			SDATACMD14bits.PCA = SM_USER_SDATACMD14_PCA;
			SDATACMD14bits.PCB = SM_USER_SDATACMD14_PCB;
			SDATACMD14bits.PCC = SM_USER_SDATACMD14_PCC;
			SDATACMD14bits.BAL = SM_USER_SDATACMD14_BAL;
			SDATACMD14bits.CONV = SM_USER_SDATACMD14_CONV;
			SDATACMD14bits.DISCHRG = SM_USER_SDATACMD14_DISCHRG;
			SDATACMD14bits.CHRG = SM_USER_SDATACMD14_CHRG;
			SDATACMD14bits.SECOND = SM_USER_SDATACMD14_SECOND;
			SDATACMD14bits.MSTART = SM_USER_SDATACMD14_MSTART;
			SDATACMD14bits.DMASTP = SM_USER_SDATACMD14_DMASTP;
			SDATACMD14bits.LOOP = SM_USER_SDATACMD14_LOOP;
			SDATACMD14bits.END = SM_USER_SDATACMD14_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SDATACMD15レジスタ */
	/*-----------------------------------------------------------------------*/
		SDATACMD15 = 
			( SM_USER_SDATACMD15_PC0 << _SDATACMD15_PC0_POSITION ) |
			( SM_USER_SDATACMD15_PCA << _SDATACMD15_PCA_POSITION ) |
			( SM_USER_SDATACMD15_PCB << _SDATACMD15_PCB_POSITION ) |
			( SM_USER_SDATACMD15_PCC << _SDATACMD15_PCC_POSITION ) |
			( SM_USER_SDATACMD15_BAL << _SDATACMD15_BAL_POSITION ) |
			( SM_USER_SDATACMD15_CONV << _SDATACMD15_CONV_POSITION ) |
			( SM_USER_SDATACMD15_DISCHRG << _SDATACMD15_DISCHRG_POSITION ) |
			( SM_USER_SDATACMD15_CHRG << _SDATACMD15_CHRG_POSITION ) |
			( SM_USER_SDATACMD15_SECOND << _SDATACMD15_SECOND_POSITION ) |
			( SM_USER_SDATACMD15_MSTART << _SDATACMD15_MSTART_POSITION ) |
			( SM_USER_SDATACMD15_DMASTP << _SDATACMD15_DMASTP_POSITION ) |
			( SM_USER_SDATACMD15_LOOP << _SDATACMD15_LOOP_POSITION ) |
			( SM_USER_SDATACMD15_END << _SDATACMD15_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SDATACMD15bits.PC0 = SM_USER_SDATACMD15_PC0;
			SDATACMD15bits.PCA = SM_USER_SDATACMD15_PCA;
			SDATACMD15bits.PCB = SM_USER_SDATACMD15_PCB;
			SDATACMD15bits.PCC = SM_USER_SDATACMD15_PCC;
			SDATACMD15bits.BAL = SM_USER_SDATACMD15_BAL;
			SDATACMD15bits.CONV = SM_USER_SDATACMD15_CONV;
			SDATACMD15bits.DISCHRG = SM_USER_SDATACMD15_DISCHRG;
			SDATACMD15bits.CHRG = SM_USER_SDATACMD15_CHRG;
			SDATACMD15bits.SECOND = SM_USER_SDATACMD15_SECOND;
			SDATACMD15bits.MSTART = SM_USER_SDATACMD15_MSTART;
			SDATACMD15bits.DMASTP = SM_USER_SDATACMD15_DMASTP;
			SDATACMD15bits.LOOP = SM_USER_SDATACMD15_LOOP;
			SDATACMD15bits.END = SM_USER_SDATACMD15_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SMATHCMD0レジスタ */
	/*-----------------------------------------------------------------------*/
		SMATHCMD0 = 
			( SM_USER_SMATHCMD0_AIN << _SMATHCMD0_AIN_POSITION ) |
			( SM_USER_SMATHCMD0_BIN << _SMATHCMD0_BIN_POSITION ) |
			( SM_USER_SMATHCMD0_F << _SMATHCMD0_F_POSITION ) |
			( SM_USER_SMATHCMD0_WM << _SMATHCMD0_WM_POSITION ) |
			( SM_USER_SMATHCMD0_WMOV << _SMATHCMD0_WMOV_POSITION ) |
			( SM_USER_SMATHCMD0_ACCB << _SMATHCMD0_ACCB_POSITION ) |
			( SM_USER_SMATHCMD0_ACCA << _SMATHCMD0_ACCA_POSITION ) |
			( SM_USER_SMATHCMD0_CMP << _SMATHCMD0_CMP_POSITION ) |
			( SM_USER_SMATHCMD0_END << _SMATHCMD0_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SMATHCMD0bits.AIN = SM_USER_SMATHCMD0_AIN;
			SMATHCMD0bits.BIN = SM_USER_SMATHCMD0_BIN;
			SMATHCMD0bits.F = SM_USER_SMATHCMD0_F;
			SMATHCMD0bits.WM = SM_USER_SMATHCMD0_WM;
			SMATHCMD0bits.WMOV = SM_USER_SMATHCMD0_WMOV;
			SMATHCMD0bits.ACCB = SM_USER_SMATHCMD0_ACCB;
			SMATHCMD0bits.ACCA = SM_USER_SMATHCMD0_ACCA;
			SMATHCMD0bits.CMP = SM_USER_SMATHCMD0_CMP;
			SMATHCMD0bits.END = SM_USER_SMATHCMD0_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SMATHCMD1レジスタ */
	/*-----------------------------------------------------------------------*/
		SMATHCMD1 = 
			( SM_USER_SMATHCMD1_AIN << _SMATHCMD1_AIN_POSITION ) |
			( SM_USER_SMATHCMD1_BIN << _SMATHCMD1_BIN_POSITION ) |
			( SM_USER_SMATHCMD1_F << _SMATHCMD1_F_POSITION ) |
			( SM_USER_SMATHCMD1_WM << _SMATHCMD1_WM_POSITION ) |
			( SM_USER_SMATHCMD1_WMOV << _SMATHCMD1_WMOV_POSITION ) |
			( SM_USER_SMATHCMD1_ACCB << _SMATHCMD1_ACCB_POSITION ) |
			( SM_USER_SMATHCMD1_ACCA << _SMATHCMD1_ACCA_POSITION ) |
			( SM_USER_SMATHCMD1_CMP << _SMATHCMD1_CMP_POSITION ) |
			( SM_USER_SMATHCMD1_END << _SMATHCMD1_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SMATHCMD1bits.AIN = SM_USER_SMATHCMD1_AIN;
			SMATHCMD1bits.BIN = SM_USER_SMATHCMD1_BIN;
			SMATHCMD1bits.F = SM_USER_SMATHCMD1_F;
			SMATHCMD1bits.WM = SM_USER_SMATHCMD1_WM;
			SMATHCMD1bits.WMOV = SM_USER_SMATHCMD1_WMOV;
			SMATHCMD1bits.ACCB = SM_USER_SMATHCMD1_ACCB;
			SMATHCMD1bits.ACCA = SM_USER_SMATHCMD1_ACCA;
			SMATHCMD1bits.CMP = SM_USER_SMATHCMD1_CMP;
			SMATHCMD1bits.END = SM_USER_SMATHCMD1_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SMATHCMD2レジスタ */
	/*-----------------------------------------------------------------------*/
		SMATHCMD2 = 
			( SM_USER_SMATHCMD2_AIN << _SMATHCMD2_AIN_POSITION ) |
			( SM_USER_SMATHCMD2_BIN << _SMATHCMD2_BIN_POSITION ) |
			( SM_USER_SMATHCMD2_F << _SMATHCMD2_F_POSITION ) |
			( SM_USER_SMATHCMD2_WM << _SMATHCMD2_WM_POSITION ) |
			( SM_USER_SMATHCMD2_WMOV << _SMATHCMD2_WMOV_POSITION ) |
			( SM_USER_SMATHCMD2_ACCB << _SMATHCMD2_ACCB_POSITION ) |
			( SM_USER_SMATHCMD2_ACCA << _SMATHCMD2_ACCA_POSITION ) |
			( SM_USER_SMATHCMD2_CMP << _SMATHCMD2_CMP_POSITION ) |
			( SM_USER_SMATHCMD2_END << _SMATHCMD2_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SMATHCMD2bits.AIN = SM_USER_SMATHCMD2_AIN;
			SMATHCMD2bits.BIN = SM_USER_SMATHCMD2_BIN;
			SMATHCMD2bits.F = SM_USER_SMATHCMD2_F;
			SMATHCMD2bits.WM = SM_USER_SMATHCMD2_WM;
			SMATHCMD2bits.WMOV = SM_USER_SMATHCMD2_WMOV;
			SMATHCMD2bits.ACCB = SM_USER_SMATHCMD2_ACCB;
			SMATHCMD2bits.ACCA = SM_USER_SMATHCMD2_ACCA;
			SMATHCMD2bits.CMP = SM_USER_SMATHCMD2_CMP;
			SMATHCMD2bits.END = SM_USER_SMATHCMD2_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SMATHCMD3レジスタ */
	/*-----------------------------------------------------------------------*/
		SMATHCMD3 = 
			( SM_USER_SMATHCMD3_AIN << _SMATHCMD3_AIN_POSITION ) |
			( SM_USER_SMATHCMD3_BIN << _SMATHCMD3_BIN_POSITION ) |
			( SM_USER_SMATHCMD3_F << _SMATHCMD3_F_POSITION ) |
			( SM_USER_SMATHCMD3_WM << _SMATHCMD3_WM_POSITION ) |
			( SM_USER_SMATHCMD3_WMOV << _SMATHCMD3_WMOV_POSITION ) |
			( SM_USER_SMATHCMD3_ACCB << _SMATHCMD3_ACCB_POSITION ) |
			( SM_USER_SMATHCMD3_ACCA << _SMATHCMD3_ACCA_POSITION ) |
			( SM_USER_SMATHCMD3_CMP << _SMATHCMD3_CMP_POSITION ) |
			( SM_USER_SMATHCMD3_END << _SMATHCMD3_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SMATHCMD3bits.AIN = SM_USER_SMATHCMD3_AIN;
			SMATHCMD3bits.BIN = SM_USER_SMATHCMD3_BIN;
			SMATHCMD3bits.F = SM_USER_SMATHCMD3_F;
			SMATHCMD3bits.WM = SM_USER_SMATHCMD3_WM;
			SMATHCMD3bits.WMOV = SM_USER_SMATHCMD3_WMOV;
			SMATHCMD3bits.ACCB = SM_USER_SMATHCMD3_ACCB;
			SMATHCMD3bits.ACCA = SM_USER_SMATHCMD3_ACCA;
			SMATHCMD3bits.CMP = SM_USER_SMATHCMD3_CMP;
			SMATHCMD3bits.END = SM_USER_SMATHCMD3_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SMATHCMD4レジスタ */
	/*-----------------------------------------------------------------------*/
		SMATHCMD4 = 
			( SM_USER_SMATHCMD4_AIN << _SMATHCMD4_AIN_POSITION ) |
			( SM_USER_SMATHCMD4_BIN << _SMATHCMD4_BIN_POSITION ) |
			( SM_USER_SMATHCMD4_F << _SMATHCMD4_F_POSITION ) |
			( SM_USER_SMATHCMD4_WM << _SMATHCMD4_WM_POSITION ) |
			( SM_USER_SMATHCMD4_WMOV << _SMATHCMD4_WMOV_POSITION ) |
			( SM_USER_SMATHCMD4_ACCB << _SMATHCMD4_ACCB_POSITION ) |
			( SM_USER_SMATHCMD4_ACCA << _SMATHCMD4_ACCA_POSITION ) |
			( SM_USER_SMATHCMD4_CMP << _SMATHCMD4_CMP_POSITION ) |
			( SM_USER_SMATHCMD4_END << _SMATHCMD4_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SMATHCMD4bits.AIN = SM_USER_SMATHCMD4_AIN;
			SMATHCMD4bits.BIN = SM_USER_SMATHCMD4_BIN;
			SMATHCMD4bits.F = SM_USER_SMATHCMD4_F;
			SMATHCMD4bits.WM = SM_USER_SMATHCMD4_WM;
			SMATHCMD4bits.WMOV = SM_USER_SMATHCMD4_WMOV;
			SMATHCMD4bits.ACCB = SM_USER_SMATHCMD4_ACCB;
			SMATHCMD4bits.ACCA = SM_USER_SMATHCMD4_ACCA;
			SMATHCMD4bits.CMP = SM_USER_SMATHCMD4_CMP;
			SMATHCMD4bits.END = SM_USER_SMATHCMD4_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SMATHCMD5レジスタ */
	/*-----------------------------------------------------------------------*/
		SMATHCMD5 = 
			( SM_USER_SMATHCMD5_AIN << _SMATHCMD5_AIN_POSITION ) |
			( SM_USER_SMATHCMD5_BIN << _SMATHCMD5_BIN_POSITION ) |
			( SM_USER_SMATHCMD5_F << _SMATHCMD5_F_POSITION ) |
			( SM_USER_SMATHCMD5_WM << _SMATHCMD5_WM_POSITION ) |
			( SM_USER_SMATHCMD5_WMOV << _SMATHCMD5_WMOV_POSITION ) |
			( SM_USER_SMATHCMD5_ACCB << _SMATHCMD5_ACCB_POSITION ) |
			( SM_USER_SMATHCMD5_ACCA << _SMATHCMD5_ACCA_POSITION ) |
			( SM_USER_SMATHCMD5_CMP << _SMATHCMD5_CMP_POSITION ) |
			( SM_USER_SMATHCMD5_END << _SMATHCMD5_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SMATHCMD5bits.AIN = SM_USER_SMATHCMD5_AIN;
			SMATHCMD5bits.BIN = SM_USER_SMATHCMD5_BIN;
			SMATHCMD5bits.F = SM_USER_SMATHCMD5_F;
			SMATHCMD5bits.WM = SM_USER_SMATHCMD5_WM;
			SMATHCMD5bits.WMOV = SM_USER_SMATHCMD5_WMOV;
			SMATHCMD5bits.ACCB = SM_USER_SMATHCMD5_ACCB;
			SMATHCMD5bits.ACCA = SM_USER_SMATHCMD5_ACCA;
			SMATHCMD5bits.CMP = SM_USER_SMATHCMD5_CMP;
			SMATHCMD5bits.END = SM_USER_SMATHCMD5_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SMATHCMD6レジスタ */
	/*-----------------------------------------------------------------------*/
		SMATHCMD6 = 
			( SM_USER_SMATHCMD6_AIN << _SMATHCMD6_AIN_POSITION ) |
			( SM_USER_SMATHCMD6_BIN << _SMATHCMD6_BIN_POSITION ) |
			( SM_USER_SMATHCMD6_F << _SMATHCMD6_F_POSITION ) |
			( SM_USER_SMATHCMD6_WM << _SMATHCMD6_WM_POSITION ) |
			( SM_USER_SMATHCMD6_WMOV << _SMATHCMD6_WMOV_POSITION ) |
			( SM_USER_SMATHCMD6_ACCB << _SMATHCMD6_ACCB_POSITION ) |
			( SM_USER_SMATHCMD6_ACCA << _SMATHCMD6_ACCA_POSITION ) |
			( SM_USER_SMATHCMD6_CMP << _SMATHCMD6_CMP_POSITION ) |
			( SM_USER_SMATHCMD6_END << _SMATHCMD6_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SMATHCMD6bits.AIN = SM_USER_SMATHCMD6_AIN;
			SMATHCMD6bits.BIN = SM_USER_SMATHCMD6_BIN;
			SMATHCMD6bits.F = SM_USER_SMATHCMD6_F;
			SMATHCMD6bits.WM = SM_USER_SMATHCMD6_WM;
			SMATHCMD6bits.WMOV = SM_USER_SMATHCMD6_WMOV;
			SMATHCMD6bits.ACCB = SM_USER_SMATHCMD6_ACCB;
			SMATHCMD6bits.ACCA = SM_USER_SMATHCMD6_ACCA;
			SMATHCMD6bits.CMP = SM_USER_SMATHCMD6_CMP;
			SMATHCMD6bits.END = SM_USER_SMATHCMD6_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SMATHCMD7レジスタ */
	/*-----------------------------------------------------------------------*/
		SMATHCMD7 = 
			( SM_USER_SMATHCMD7_AIN << _SMATHCMD7_AIN_POSITION ) |
			( SM_USER_SMATHCMD7_BIN << _SMATHCMD7_BIN_POSITION ) |
			( SM_USER_SMATHCMD7_F << _SMATHCMD7_F_POSITION ) |
			( SM_USER_SMATHCMD7_WM << _SMATHCMD7_WM_POSITION ) |
			( SM_USER_SMATHCMD7_WMOV << _SMATHCMD7_WMOV_POSITION ) |
			( SM_USER_SMATHCMD7_ACCB << _SMATHCMD7_ACCB_POSITION ) |
			( SM_USER_SMATHCMD7_ACCA << _SMATHCMD7_ACCA_POSITION ) |
			( SM_USER_SMATHCMD7_CMP << _SMATHCMD7_CMP_POSITION ) |
			( SM_USER_SMATHCMD7_END << _SMATHCMD7_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SMATHCMD7bits.AIN = SM_USER_SMATHCMD7_AIN;
			SMATHCMD7bits.BIN = SM_USER_SMATHCMD7_BIN;
			SMATHCMD7bits.F = SM_USER_SMATHCMD7_F;
			SMATHCMD7bits.WM = SM_USER_SMATHCMD7_WM;
			SMATHCMD7bits.WMOV = SM_USER_SMATHCMD7_WMOV;
			SMATHCMD7bits.ACCB = SM_USER_SMATHCMD7_ACCB;
			SMATHCMD7bits.ACCA = SM_USER_SMATHCMD7_ACCA;
			SMATHCMD7bits.CMP = SM_USER_SMATHCMD7_CMP;
			SMATHCMD7bits.END = SM_USER_SMATHCMD7_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SMATHCMD8レジスタ */
	/*-----------------------------------------------------------------------*/
		SMATHCMD8 = 
			( SM_USER_SMATHCMD8_AIN << _SMATHCMD8_AIN_POSITION ) |
			( SM_USER_SMATHCMD8_BIN << _SMATHCMD8_BIN_POSITION ) |
			( SM_USER_SMATHCMD8_F << _SMATHCMD8_F_POSITION ) |
			( SM_USER_SMATHCMD8_WM << _SMATHCMD8_WM_POSITION ) |
			( SM_USER_SMATHCMD8_WMOV << _SMATHCMD8_WMOV_POSITION ) |
			( SM_USER_SMATHCMD8_ACCB << _SMATHCMD8_ACCB_POSITION ) |
			( SM_USER_SMATHCMD8_ACCA << _SMATHCMD8_ACCA_POSITION ) |
			( SM_USER_SMATHCMD8_CMP << _SMATHCMD8_CMP_POSITION ) |
			( SM_USER_SMATHCMD8_END << _SMATHCMD8_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SMATHCMD8bits.AIN = SM_USER_SMATHCMD8_AIN;
			SMATHCMD8bits.BIN = SM_USER_SMATHCMD8_BIN;
			SMATHCMD8bits.F = SM_USER_SMATHCMD8_F;
			SMATHCMD8bits.WM = SM_USER_SMATHCMD8_WM;
			SMATHCMD8bits.WMOV = SM_USER_SMATHCMD8_WMOV;
			SMATHCMD8bits.ACCB = SM_USER_SMATHCMD8_ACCB;
			SMATHCMD8bits.ACCA = SM_USER_SMATHCMD8_ACCA;
			SMATHCMD8bits.CMP = SM_USER_SMATHCMD8_CMP;
			SMATHCMD8bits.END = SM_USER_SMATHCMD8_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SMATHCMD9レジスタ */
	/*-----------------------------------------------------------------------*/
		SMATHCMD9 = 
			( SM_USER_SMATHCMD9_AIN << _SMATHCMD9_AIN_POSITION ) |
			( SM_USER_SMATHCMD9_BIN << _SMATHCMD9_BIN_POSITION ) |
			( SM_USER_SMATHCMD9_F << _SMATHCMD9_F_POSITION ) |
			( SM_USER_SMATHCMD9_WM << _SMATHCMD9_WM_POSITION ) |
			( SM_USER_SMATHCMD9_WMOV << _SMATHCMD9_WMOV_POSITION ) |
			( SM_USER_SMATHCMD9_ACCB << _SMATHCMD9_ACCB_POSITION ) |
			( SM_USER_SMATHCMD9_ACCA << _SMATHCMD9_ACCA_POSITION ) |
			( SM_USER_SMATHCMD9_CMP << _SMATHCMD9_CMP_POSITION ) |
			( SM_USER_SMATHCMD9_END << _SMATHCMD9_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SMATHCMD9bits.AIN = SM_USER_SMATHCMD9_AIN;
			SMATHCMD9bits.BIN = SM_USER_SMATHCMD9_BIN;
			SMATHCMD9bits.F = SM_USER_SMATHCMD9_F;
			SMATHCMD9bits.WM = SM_USER_SMATHCMD9_WM;
			SMATHCMD9bits.WMOV = SM_USER_SMATHCMD9_WMOV;
			SMATHCMD9bits.ACCB = SM_USER_SMATHCMD9_ACCB;
			SMATHCMD9bits.ACCA = SM_USER_SMATHCMD9_ACCA;
			SMATHCMD9bits.CMP = SM_USER_SMATHCMD9_CMP;
			SMATHCMD9bits.END = SM_USER_SMATHCMD9_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SMATHCMD10レジスタ */
	/*-----------------------------------------------------------------------*/
		SMATHCMD10 = 
			( SM_USER_SMATHCMD10_AIN << _SMATHCMD10_AIN_POSITION ) |
			( SM_USER_SMATHCMD10_BIN << _SMATHCMD10_BIN_POSITION ) |
			( SM_USER_SMATHCMD10_F << _SMATHCMD10_F_POSITION ) |
			( SM_USER_SMATHCMD10_WM << _SMATHCMD10_WM_POSITION ) |
			( SM_USER_SMATHCMD10_WMOV << _SMATHCMD10_WMOV_POSITION ) |
			( SM_USER_SMATHCMD10_ACCB << _SMATHCMD10_ACCB_POSITION ) |
			( SM_USER_SMATHCMD10_ACCA << _SMATHCMD10_ACCA_POSITION ) |
			( SM_USER_SMATHCMD10_CMP << _SMATHCMD10_CMP_POSITION ) |
			( SM_USER_SMATHCMD10_END << _SMATHCMD10_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SMATHCMD10bits.AIN = SM_USER_SMATHCMD10_AIN;
			SMATHCMD10bits.BIN = SM_USER_SMATHCMD10_BIN;
			SMATHCMD10bits.F = SM_USER_SMATHCMD10_F;
			SMATHCMD10bits.WM = SM_USER_SMATHCMD10_WM;
			SMATHCMD10bits.WMOV = SM_USER_SMATHCMD10_WMOV;
			SMATHCMD10bits.ACCB = SM_USER_SMATHCMD10_ACCB;
			SMATHCMD10bits.ACCA = SM_USER_SMATHCMD10_ACCA;
			SMATHCMD10bits.CMP = SM_USER_SMATHCMD10_CMP;
			SMATHCMD10bits.END = SM_USER_SMATHCMD10_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SMATHCMD11レジスタ */
	/*-----------------------------------------------------------------------*/
		SMATHCMD11 = 
			( SM_USER_SMATHCMD11_AIN << _SMATHCMD11_AIN_POSITION ) |
			( SM_USER_SMATHCMD11_BIN << _SMATHCMD11_BIN_POSITION ) |
			( SM_USER_SMATHCMD11_F << _SMATHCMD11_F_POSITION ) |
			( SM_USER_SMATHCMD11_WM << _SMATHCMD11_WM_POSITION ) |
			( SM_USER_SMATHCMD11_WMOV << _SMATHCMD11_WMOV_POSITION ) |
			( SM_USER_SMATHCMD11_ACCB << _SMATHCMD11_ACCB_POSITION ) |
			( SM_USER_SMATHCMD11_ACCA << _SMATHCMD11_ACCA_POSITION ) |
			( SM_USER_SMATHCMD11_CMP << _SMATHCMD11_CMP_POSITION ) |
			( SM_USER_SMATHCMD11_END << _SMATHCMD11_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SMATHCMD11bits.AIN = SM_USER_SMATHCMD11_AIN;
			SMATHCMD11bits.BIN = SM_USER_SMATHCMD11_BIN;
			SMATHCMD11bits.F = SM_USER_SMATHCMD11_F;
			SMATHCMD11bits.WM = SM_USER_SMATHCMD11_WM;
			SMATHCMD11bits.WMOV = SM_USER_SMATHCMD11_WMOV;
			SMATHCMD11bits.ACCB = SM_USER_SMATHCMD11_ACCB;
			SMATHCMD11bits.ACCA = SM_USER_SMATHCMD11_ACCA;
			SMATHCMD11bits.CMP = SM_USER_SMATHCMD11_CMP;
			SMATHCMD11bits.END = SM_USER_SMATHCMD11_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SMATHCMD12レジスタ */
	/*-----------------------------------------------------------------------*/
		SMATHCMD12 = 
			( SM_USER_SMATHCMD12_AIN << _SMATHCMD12_AIN_POSITION ) |
			( SM_USER_SMATHCMD12_BIN << _SMATHCMD12_BIN_POSITION ) |
			( SM_USER_SMATHCMD12_F << _SMATHCMD12_F_POSITION ) |
			( SM_USER_SMATHCMD12_WM << _SMATHCMD12_WM_POSITION ) |
			( SM_USER_SMATHCMD12_WMOV << _SMATHCMD12_WMOV_POSITION ) |
			( SM_USER_SMATHCMD12_ACCB << _SMATHCMD12_ACCB_POSITION ) |
			( SM_USER_SMATHCMD12_ACCA << _SMATHCMD12_ACCA_POSITION ) |
			( SM_USER_SMATHCMD12_CMP << _SMATHCMD12_CMP_POSITION ) |
			( SM_USER_SMATHCMD12_END << _SMATHCMD12_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SMATHCMD12bits.AIN = SM_USER_SMATHCMD12_AIN;
			SMATHCMD12bits.BIN = SM_USER_SMATHCMD12_BIN;
			SMATHCMD12bits.F = SM_USER_SMATHCMD12_F;
			SMATHCMD12bits.WM = SM_USER_SMATHCMD12_WM;
			SMATHCMD12bits.WMOV = SM_USER_SMATHCMD12_WMOV;
			SMATHCMD12bits.ACCB = SM_USER_SMATHCMD12_ACCB;
			SMATHCMD12bits.ACCA = SM_USER_SMATHCMD12_ACCA;
			SMATHCMD12bits.CMP = SM_USER_SMATHCMD12_CMP;
			SMATHCMD12bits.END = SM_USER_SMATHCMD12_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SMATHCMD13レジスタ */
	/*-----------------------------------------------------------------------*/
		SMATHCMD13 = 
			( SM_USER_SMATHCMD13_AIN << _SMATHCMD13_AIN_POSITION ) |
			( SM_USER_SMATHCMD13_BIN << _SMATHCMD13_BIN_POSITION ) |
			( SM_USER_SMATHCMD13_F << _SMATHCMD13_F_POSITION ) |
			( SM_USER_SMATHCMD13_WM << _SMATHCMD13_WM_POSITION ) |
			( SM_USER_SMATHCMD13_WMOV << _SMATHCMD13_WMOV_POSITION ) |
			( SM_USER_SMATHCMD13_ACCB << _SMATHCMD13_ACCB_POSITION ) |
			( SM_USER_SMATHCMD13_ACCA << _SMATHCMD13_ACCA_POSITION ) |
			( SM_USER_SMATHCMD13_CMP << _SMATHCMD13_CMP_POSITION ) |
			( SM_USER_SMATHCMD13_END << _SMATHCMD13_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SMATHCMD13bits.AIN = SM_USER_SMATHCMD13_AIN;
			SMATHCMD13bits.BIN = SM_USER_SMATHCMD13_BIN;
			SMATHCMD13bits.F = SM_USER_SMATHCMD13_F;
			SMATHCMD13bits.WM = SM_USER_SMATHCMD13_WM;
			SMATHCMD13bits.WMOV = SM_USER_SMATHCMD13_WMOV;
			SMATHCMD13bits.ACCB = SM_USER_SMATHCMD13_ACCB;
			SMATHCMD13bits.ACCA = SM_USER_SMATHCMD13_ACCA;
			SMATHCMD13bits.CMP = SM_USER_SMATHCMD13_CMP;
			SMATHCMD13bits.END = SM_USER_SMATHCMD13_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SMATHCMD14レジスタ */
	/*-----------------------------------------------------------------------*/
		SMATHCMD14 = 
			( SM_USER_SMATHCMD14_AIN << _SMATHCMD14_AIN_POSITION ) |
			( SM_USER_SMATHCMD14_BIN << _SMATHCMD14_BIN_POSITION ) |
			( SM_USER_SMATHCMD14_F << _SMATHCMD14_F_POSITION ) |
			( SM_USER_SMATHCMD14_WM << _SMATHCMD14_WM_POSITION ) |
			( SM_USER_SMATHCMD14_WMOV << _SMATHCMD14_WMOV_POSITION ) |
			( SM_USER_SMATHCMD14_ACCB << _SMATHCMD14_ACCB_POSITION ) |
			( SM_USER_SMATHCMD14_ACCA << _SMATHCMD14_ACCA_POSITION ) |
			( SM_USER_SMATHCMD14_CMP << _SMATHCMD14_CMP_POSITION ) |
			( SM_USER_SMATHCMD14_END << _SMATHCMD14_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SMATHCMD14bits.AIN = SM_USER_SMATHCMD14_AIN;
			SMATHCMD14bits.BIN = SM_USER_SMATHCMD14_BIN;
			SMATHCMD14bits.F = SM_USER_SMATHCMD14_F;
			SMATHCMD14bits.WM = SM_USER_SMATHCMD14_WM;
			SMATHCMD14bits.WMOV = SM_USER_SMATHCMD14_WMOV;
			SMATHCMD14bits.ACCB = SM_USER_SMATHCMD14_ACCB;
			SMATHCMD14bits.ACCA = SM_USER_SMATHCMD14_ACCA;
			SMATHCMD14bits.CMP = SM_USER_SMATHCMD14_CMP;
			SMATHCMD14bits.END = SM_USER_SMATHCMD14_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SMATHCMD15レジスタ */
	/*-----------------------------------------------------------------------*/
		SMATHCMD15 = 
			( SM_USER_SMATHCMD15_AIN << _SMATHCMD15_AIN_POSITION ) |
			( SM_USER_SMATHCMD15_BIN << _SMATHCMD15_BIN_POSITION ) |
			( SM_USER_SMATHCMD15_F << _SMATHCMD15_F_POSITION ) |
			( SM_USER_SMATHCMD15_WM << _SMATHCMD15_WM_POSITION ) |
			( SM_USER_SMATHCMD15_WMOV << _SMATHCMD15_WMOV_POSITION ) |
			( SM_USER_SMATHCMD15_ACCB << _SMATHCMD15_ACCB_POSITION ) |
			( SM_USER_SMATHCMD15_ACCA << _SMATHCMD15_ACCA_POSITION ) |
			( SM_USER_SMATHCMD15_CMP << _SMATHCMD15_CMP_POSITION ) |
			( SM_USER_SMATHCMD15_END << _SMATHCMD15_END_POSITION ) ;
		#ifdef DEF_BITNAME
			SMATHCMD15bits.AIN = SM_USER_SMATHCMD15_AIN;
			SMATHCMD15bits.BIN = SM_USER_SMATHCMD15_BIN;
			SMATHCMD15bits.F = SM_USER_SMATHCMD15_F;
			SMATHCMD15bits.WM = SM_USER_SMATHCMD15_WM;
			SMATHCMD15bits.WMOV = SM_USER_SMATHCMD15_WMOV;
			SMATHCMD15bits.ACCB = SM_USER_SMATHCMD15_ACCB;
			SMATHCMD15bits.ACCA = SM_USER_SMATHCMD15_ACCA;
			SMATHCMD15bits.CMP = SM_USER_SMATHCMD15_CMP;
			SMATHCMD15bits.END = SM_USER_SMATHCMD15_END;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SDATAMAPレジスタ */
	/*-----------------------------------------------------------------------*/
		SDATAMAP = 
			( SM_USER_SDATAMAP_SPLIT0 << _SDATAMAP_SPLIT0_POSITION ) |
			( SM_USER_SDATAMAP_DATASEQ0 << _SDATAMAP_DATASEQ0_POSITION ) |
			( SM_USER_SDATAMAP_SPLIT1 << _SDATAMAP_SPLIT1_POSITION ) |
			( SM_USER_SDATAMAP_DATASEQ1 << _SDATAMAP_DATASEQ1_POSITION ) |
			( SM_USER_SDATAMAP_SPLIT2 << _SDATAMAP_SPLIT2_POSITION ) |
			( SM_USER_SDATAMAP_DATASEQ2 << _SDATAMAP_DATASEQ2_POSITION ) |
			( SM_USER_SDATAMAP_SPLIT3 << _SDATAMAP_SPLIT3_POSITION ) |
			( SM_USER_SDATAMAP_DATASEQ3 << _SDATAMAP_DATASEQ3_POSITION ) ;
		#ifdef DEF_BITNAME
			SDATAMAPbits.SPLIT0 = SM_USER_SDATAMAP_SPLIT0;
			SDATAMAPbits.DATASEQ0 = SM_USER_SDATAMAP_DATASEQ0;
			SDATAMAPbits.SPLIT1 = SM_USER_SDATAMAP_SPLIT1;
			SDATAMAPbits.DATASEQ1 = SM_USER_SDATAMAP_DATASEQ1;
			SDATAMAPbits.SPLIT2 = SM_USER_SDATAMAP_SPLIT2;
			SDATAMAPbits.DATASEQ2 = SM_USER_SDATAMAP_DATASEQ2;
			SDATAMAPbits.SPLIT3 = SM_USER_SDATAMAP_SPLIT3;
			SDATAMAPbits.DATASEQ3 = SM_USER_SDATAMAP_DATASEQ3;
		#endif 

	/*-----------------------------------------------------------------------*/
	/* SMATHMAPレジスタ */
	/*-----------------------------------------------------------------------*/
		SMATHMAP = 
			( SM_USER_SMATHMAP_SPLIT0 << _SMATHMAP_SPLIT0_POSITION ) |
			( SM_USER_SMATHMAP_CMP0 << _SMATHMAP_CMP0_POSITION ) |
			( SM_USER_SMATHMAP_ACC0 << _SMATHMAP_ACC0_POSITION ) |
			( SM_USER_SMATHMAP_SECOND0 << _SMATHMAP_SECOND0_POSITION ) |
			( SM_USER_SMATHMAP_MATHSEQ0 << _SMATHMAP_MATHSEQ0_POSITION ) |
			( SM_USER_SMATHMAP_SPLIT1 << _SMATHMAP_SPLIT1_POSITION ) |
			( SM_USER_SMATHMAP_CMP1 << _SMATHMAP_CMP1_POSITION ) |
			( SM_USER_SMATHMAP_ACC1 << _SMATHMAP_ACC1_POSITION ) |
			( SM_USER_SMATHMAP_SECOND1 << _SMATHMAP_SECOND1_POSITION ) |
			( SM_USER_SMATHMAP_MATHSEQ1 << _SMATHMAP_MATHSEQ1_POSITION ) |
			( SM_USER_SMATHMAP_SPLIT2 << _SMATHMAP_SPLIT2_POSITION ) |
			( SM_USER_SMATHMAP_CMP2 << _SMATHMAP_CMP2_POSITION ) |
			( SM_USER_SMATHMAP_ACC2 << _SMATHMAP_ACC2_POSITION ) |
			( SM_USER_SMATHMAP_SECOND2 << _SMATHMAP_SECOND2_POSITION ) |
			( SM_USER_SMATHMAP_MATHSEQ2 << _SMATHMAP_MATHSEQ2_POSITION ) |
			( SM_USER_SMATHMAP_SPLIT3 << _SMATHMAP_SPLIT3_POSITION ) |
			( SM_USER_SMATHMAP_CMP3 << _SMATHMAP_CMP3_POSITION ) |
			( SM_USER_SMATHMAP_ACC3 << _SMATHMAP_ACC3_POSITION ) |
			( SM_USER_SMATHMAP_SECOND3 << _SMATHMAP_SECOND3_POSITION ) |
			( SM_USER_SMATHMAP_MATHSEQ3 << _SMATHMAP_MATHSEQ3_POSITION ) ;
		#ifdef DEF_BITNAME
			SMATHMAPbits.SPLIT0 = SM_USER_SMATHMAP_SPLIT0;
			SMATHMAPbits.CMP0 = SM_USER_SMATHMAP_CMP0;
			SMATHMAPbits.ACC0 = SM_USER_SMATHMAP_ACC0;
			SMATHMAPbits.SECOND0 = SM_USER_SMATHMAP_SECOND0;
			SMATHMAPbits.MATHSEQ0 = SM_USER_SMATHMAP_MATHSEQ0;
			SMATHMAPbits.SPLIT1 = SM_USER_SMATHMAP_SPLIT1;
			SMATHMAPbits.CMP1 = SM_USER_SMATHMAP_CMP1;
			SMATHMAPbits.ACC1 = SM_USER_SMATHMAP_ACC1;
			SMATHMAPbits.SECOND1 = SM_USER_SMATHMAP_SECOND1;
			SMATHMAPbits.MATHSEQ1 = SM_USER_SMATHMAP_MATHSEQ1;
			SMATHMAPbits.SPLIT2 = SM_USER_SMATHMAP_SPLIT2;
			SMATHMAPbits.CMP2 = SM_USER_SMATHMAP_CMP2;
			SMATHMAPbits.ACC2 = SM_USER_SMATHMAP_ACC2;
			SMATHMAPbits.SECOND2 = SM_USER_SMATHMAP_SECOND2;
			SMATHMAPbits.MATHSEQ2 = SM_USER_SMATHMAP_MATHSEQ2;
			SMATHMAPbits.SPLIT3 = SM_USER_SMATHMAP_SPLIT3;
			SMATHMAPbits.CMP3 = SM_USER_SMATHMAP_CMP3;
			SMATHMAPbits.ACC3 = SM_USER_SMATHMAP_ACC3;
			SMATHMAPbits.SECOND3 = SM_USER_SMATHMAP_SECOND3;
			SMATHMAPbits.MATHSEQ3 = SM_USER_SMATHMAP_MATHSEQ3;
		#endif 

}

